# $MirOS: src/distrib/dbins/Makefile,v 1.1 2008/03/27 19:05:12 tg Exp $

CBIN=		dbins
BINDIR=		/bin
NOMAN=		Yes

LINKS+=		${BINDIR}/${CBIN} /bin/cat \
		${BINDIR}/${CBIN} /bin/chmod \
		${BINDIR}/${CBIN} /bin/chgrp \
		${BINDIR}/${CBIN} /sbin/chown \
		${BINDIR}/${CBIN} /usr/bin/chflags \
		${BINDIR}/${CBIN} /bin/cp \
		${BINDIR}/${CBIN} /bin/date \
		${BINDIR}/${CBIN} /bin/dd \
		${BINDIR}/${CBIN} /bin/df \
		${BINDIR}/${CBIN} /bin/echo \
		${BINDIR}/${CBIN} /bin/ed \
		${BINDIR}/${CBIN} /bin/expr \
		${BINDIR}/${CBIN} /bin/hostname \
		${BINDIR}/${CBIN} /bin/kill \
		${BINDIR}/${CBIN} /bin/ln \
		${BINDIR}/${CBIN} /bin/ls \
		${BINDIR}/${CBIN} /bin/cksum \
		${BINDIR}/${CBIN} /bin/sha1 \
		${BINDIR}/${CBIN} /bin/rmd160 \
		${BINDIR}/${CBIN} /bin/md5 \
		${BINDIR}/${CBIN} /bin/sum \
		${BINDIR}/${CBIN} /bin/mkdir \
		${BINDIR}/${CBIN} /bin/mksh \
		${BINDIR}/${CBIN} /bin/sh \
		${BINDIR}/${CBIN} /bin/mt \
		${BINDIR}/${CBIN} /bin/eject \
		${BINDIR}/${CBIN} /bin/mv \
		${BINDIR}/${CBIN} /bin/pax \
		${BINDIR}/${CBIN} /bin/cpio \
		${BINDIR}/${CBIN} /bin/tar \
		${BINDIR}/${CBIN} /bin/ps \
		${BINDIR}/${CBIN} /bin/pwd \
		${BINDIR}/${CBIN} /bin/rm \
		${BINDIR}/${CBIN} /bin/rmdir \
		${BINDIR}/${CBIN} /bin/sleep \
		${BINDIR}/${CBIN} /bin/stty \
		${BINDIR}/${CBIN} /bin/sync \
		${BINDIR}/${CBIN} /bin/systrace \
		${BINDIR}/${CBIN} /sbin/atactl \
		${BINDIR}/${CBIN} /sbin/badsect \
		${BINDIR}/${CBIN} /sbin/brconfig \
		${BINDIR}/${CBIN} /sbin/ccdconfig \
		${BINDIR}/${CBIN} /sbin/clri \
		${BINDIR}/${CBIN} /sbin/dhclient \
		${BINDIR}/${CBIN} /sbin/disklabel \
		${BINDIR}/${CBIN} /sbin/dmesg \
		${BINDIR}/${CBIN} /sbin/dump \
		${BINDIR}/${CBIN} /sbin/rdump \
		${BINDIR}/${CBIN} /sbin/dumpfs \
		${BINDIR}/${CBIN} /sbin/ffsinfo \
		${BINDIR}/${CBIN} /sbin/fsck \
		${BINDIR}/${CBIN} /sbin/fsck_ext2fs \
		${BINDIR}/${CBIN} /sbin/fsck_ffs \
		${BINDIR}/${CBIN} /sbin/fsck_msdos \
		${BINDIR}/${CBIN} /sbin/fsdb \
		${BINDIR}/${CBIN} /sbin/growfs \
		${BINDIR}/${CBIN} /sbin/ifconfig \
		${BINDIR}/${CBIN} /sbin/isakmpd \
		${BINDIR}/${CBIN} /sbin/kbd \
		${BINDIR}/${CBIN} /sbin/lmccontrol \
		${BINDIR}/${CBIN} /sbin/mknod \
		${BINDIR}/${CBIN} /sbin/mkfifo \
		${BINDIR}/${CBIN} /sbin/modload \
		${BINDIR}/${CBIN} /sbin/modunload \
		${BINDIR}/${CBIN} /sbin/mount \
		${BINDIR}/${CBIN} /sbin/mount_cd9660 \
		${BINDIR}/${CBIN} /sbin/mount_ext2fs \
		${BINDIR}/${CBIN} /sbin/mount_fdesc \
		${BINDIR}/${CBIN} /sbin/mount_ffs \
		${BINDIR}/${CBIN} /sbin/mount_kernfs \
		${BINDIR}/${CBIN} /sbin/mount_msdos \
		${BINDIR}/${CBIN} /sbin/mount_nfs \
		${BINDIR}/${CBIN} /sbin/mount_portal \
		${BINDIR}/${CBIN} /sbin/mount_procfs \
		${BINDIR}/${CBIN} /sbin/mountd \
		${BINDIR}/${CBIN} /sbin/ncheck_ffs \
		${BINDIR}/${CBIN} /sbin/ncheck \
		${BINDIR}/${CBIN} /sbin/newfs \
		${BINDIR}/${CBIN} /sbin/mount_mfs \
		${BINDIR}/${CBIN} /sbin/newfs_msdos \
		${BINDIR}/${CBIN} /sbin/nfsd \
		${BINDIR}/${CBIN} /sbin/nologin \
		${BINDIR}/${CBIN} /sbin/pfctl \
		${BINDIR}/${CBIN} /sbin/pflogd \
		${BINDIR}/${CBIN} /sbin/quotacheck \
		${BINDIR}/${CBIN} /sbin/raidctl \
		${BINDIR}/${CBIN} /sbin/reboot \
		${BINDIR}/${CBIN} /sbin/halt \
		${BINDIR}/${CBIN} /sbin/restore \
		${BINDIR}/${CBIN} /sbin/rrestore \
		${BINDIR}/${CBIN} /sbin/route \
		${BINDIR}/${CBIN} /sbin/routed \
		${BINDIR}/${CBIN} /sbin/rtquery \
		${BINDIR}/${CBIN} /sbin/rtsol \
		${BINDIR}/${CBIN} /sbin/savecore \
		${BINDIR}/${CBIN} /sbin/scan_ffs \
		${BINDIR}/${CBIN} /sbin/scsi \
		${BINDIR}/${CBIN} /sbin/slattach \
		${BINDIR}/${CBIN} /sbin/swapctl \
		${BINDIR}/${CBIN} /sbin/swapon \
		${BINDIR}/${CBIN} /sbin/sysctl \
		${BINDIR}/${CBIN} /sbin/ttyflags \
		${BINDIR}/${CBIN} /sbin/tunefs \
		${BINDIR}/${CBIN} /sbin/umount \
		${BINDIR}/${CBIN} /sbin/wicontrol \
		${BINDIR}/${CBIN} /sbin/wsconsctl \
		${BINDIR}/${CBIN} /usr/bin/compress \
		${BINDIR}/${CBIN} /usr/bin/uncompress \
		${BINDIR}/${CBIN} /usr/bin/zcat \
		${BINDIR}/${CBIN} /usr/bin/gzip \
		${BINDIR}/${CBIN} /usr/bin/gunzip \
		${BINDIR}/${CBIN} /usr/bin/gzcat \
		${BINDIR}/${CBIN} /usr/bin/encrypt \
		${BINDIR}/${CBIN} /usr/bin/ftp \
		${BINDIR}/${CBIN} /usr/sbin/chroot \
		${BINDIR}/${CBIN} /sbin/portmap \
		${BINDIR}/${CBIN} /usr/sbin/pwd_mkdb \
		${BINDIR}/${CBIN} /usr/sbin/vnconfig

.if ${MACHINE_ARCH} == "i386"
LINKS+=		${BINDIR}/${CBIN} /sbin/ancontrol \
		${BINDIR}/${CBIN} /sbin/fdisk \
		${BINDIR}/${CBIN} /sbin/iopctl \
		${BINDIR}/${CBIN} /sbin/mount_ntfs
.endif

CLEANFILES+=	${CBIN}.conf ${CBIN}.c ${CBIN}.cache ${CBIN}.mk

all: ${CBIN}

${CBIN}.mk ${CBIN}.cache ${CBIN}.c: ${CBIN}.conf
	crunchgen -E -D ${BSDSRCDIR} -L ${DESTDIR}/usr/lib \
	    -c ${CBIN}.c -e ${CBIN} -m ${CBIN}.mk ${.ALLSRC}

${CBIN}.conf: crunch.conf.${MACHINE_ARCH}
	cp $> $@

${CBIN}: ${CBIN}.mk ${CBIN}.cache ${CBIN}.c
	${MAKE} -f ${CBIN}.mk $@

clean: ${CBIN}.mk
	${MAKE} -f ${CBIN}.mk $@
	-rm -f ${CLEANFILES}

cleandir: clean
	-rm -f .depend

depend lint tags: ${CBIN}.mk
	${MAKE} -f ${CBIN}.mk $@

install:
	${INSTALL} ${INSTALL_COPY} ${INSTALL_STRIP} -o ${BINOWN} -g ${BINGRP} \
	    -m ${BINMODE} ${CBIN} ${DESTDIR}${BINDIR}/
.  if defined(LINKS) && !empty(LINKS)
.    for lnk file in ${LINKS}
	@l=${DESTDIR}${lnk}; \
	 t=${DESTDIR}${file}; \
	 echo $$t -\> $$l; \
	 rm -f $$t; ln $$l $$t || cp $$l $$t
.    endfor
.  endif
	-rm ${DESTDIR}${BINDIR}/${CBIN}

.include <bsd.prog.mk>
