#!/bin/mksh
# $MirOS: src/etc/monthly,v 1.11 2007/06/16 23:34:59 tg Exp $
# $OpenBSD: monthly,v 1.5 1998/02/02 23:08:57 millert Exp $

umask 022
export TZ=UTC PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/mpkg/bin
cd /

print RUNTIME=$(date +%J)

if [ -f /etc/monthly.local ];then
	echo ""
	echo "Running monthly.local:"
	. /etc/monthly.local
else
	echo "Nothing to do!"
fi

if [[ -e /var/log/wtmp ]]; then
	print
	print Doing login accounting for the time since last run
	print and rotating login accounting log file:
	ac -p | sort -nr +1
	[[ -e /var/log/wtmp.0 ]] && gzip -n9 /var/log/wtmp.0
	install -c -o root -g wheel -m 640 /dev/null /var/log/wtmp.1
	[[ -e /var/log/wtmp.0.gz ]] && mv /var/log/wtmp.0.gz /var/log/wtmp.1.gz
	mv /var/log/wtmp /var/log/wtmp.0
	mv /var/log/wtmp.1 /var/log/wtmp
	gzip -n9 /var/log/wtmp.0
fi
