.\" $MirOS: contrib/code/mpczar/mpczar/mpczar.1,v 1.7 2006/11/19 12:42:33 tg Exp $
.\"-
.\" Copyright (c) 2005, 2006
.\"	Thorsten Glaser <tg@mirbsd.de>
.\"
.\" Licensee is hereby permitted to deal in this work without restric-
.\" tion, including unlimited rights to use, publicly perform, modify,
.\" merge, distribute, sell, give away or sublicence, provided all co-
.\" pyright notices above, these terms and the disclaimer are retained
.\" in all redistributions or reproduced in accompanying documentation
.\" or other materials provided with binary redistributions.
.\"
.\" Advertising materials mentioning features or use of this work must
.\" display the following acknowledgement:
.\"	This product includes material provided by Thorsten Glaser.
.\"
.\" Licensor offers the work "AS IS" and WITHOUT WARRANTY of any kind,
.\" express, or implied, to the maximum extent permitted by applicable
.\" law, without malicious intent or gross negligence; in no event may
.\" licensor, an author or contributor be held liable for any indirect
.\" or other damage, or direct damage except proven a consequence of a
.\" direct error of said person and intended use of this work, loss or
.\" other issues arising in any way out of its use, even if advised of
.\" the possibility of such damage or existence of a defect.
.\"-
.Dd November 19, 2006
.Dt MPCZAR 1
.Os MirPorts\ Framework
.Sh NAME
.Nm mpczar
.Nd generate compressed normalised file archive
.Sh SYNOPSIS
.Nm
.Op Fl Cv
.Op Fl o Ar outfile
.Op Fl I Ar ignore ...
.Op Fl r Ar directory ...
.Op Ar
.Sh DESCRIPTION
The
.Nm
.Xr mksh 1
script takes a list of files from the command line,
adds all files found in any
.Ar directory
specified, removes all
.Ar ignore
entries found, sorts the list, creates a
.Xr cpio 1
archive in a normalised
format, compresses them using a helper programme
and writes the file to
.Ar outfile Ns .mcz
(or to standard output).
.Pp
The idea is that the archive generated is the same on
every system if the set of input files is the same, like
a mathematical function.
The input files are sorted, and any file information
about ownership, inodes and modification times is discarded.
.Pp
The options are as follows:
.Bl -tag -width "-r directory"
.It Fl C
Create an old-style portable
.Em cpio
archive instead of an
.Em sv4crc
.Pq default
archive.
Use this option only for distfiles which also must be usable
on systems that do not have MirOS cpio.
.It Fl I Ar ignore
Add
.Ar ignore
to the list of expressions to exclude using
.Xr fgrep 1 .
.It Fl o Ar outfile
Write archive to
.Ar outfile .
.It Fl r Ar directory
Add
.Ar directory
to the list of entries to recursively scan for
files which are candidates for the archive.
.It Fl v
Display a list of files saved to stderr.
.It Ar file
Add
.Ar file
to the archive.
.El
.Sh FILES
.Bl -tag -compact -width /usr/libexec/mpczar.z
.It /usr/libexec/mpczar.z
Compression helper mimicking a small
.Xr compress 1
using
.Xr zopen 3 .
.El
.Sh EXAMPLES
Compress all files of a newly checked-out
.Xr mksh 1
distribution:
.Bd -literal
$ cvs -qz9 -d anoncvs@anoncvs.mirbsd.org:/cvs co -Prmksh-R27 -dmksh src/bin/mksh
$ mpshar -o mksh27 -I CVS -r mksh
.Ed
.Sh DIAGNOSTICS
.Nm
returns 1 if
.Xr cpio 1
failed, 2 if compression failed, and 0 on success.
.Sh SEE ALSO
.Xr compress 1 ,
.Xr cpio 1 ,
.Xr fgrep 1 ,
.Xr uncompress 1 ,
.Xr zcat 1 ,
.Xr zopen 3
.Sh AUTHORS
.Nm
was written by
.An Thorsten Glaser Aq tg@66h.42h.de .
.Sh CAVEATS
File permissions are stored as-is in the archive and not normalised.
