#!/bin/sh
# $MirOS$
# $OpenBSD: DEINSTALL,v 1.3 2000/12/07 18:05:29 todd Exp $
#
# mksh de-installation

set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}

if grep -q ${PREFIX}/bin/mksh /etc/shells; then
    echo
    echo "+---------------"
    echo "| To completely deinstall the $1 package you need to edit"
    echo "| /etc/shells and remove this line:"
    echo "|"
    echo "|           ${PREFIX}/bin/mksh"
    echo "|"
    echo "+---------------"
    echo
fi

exit 0
