# $MirOS: ports/devel/p5-App-CLI/Makefile,v 1.1 2007/10/04 22:01:20 bsiegert Exp $

COMMENT=		require() modules from a variable
VERSION=		0.11
DISTNAME=		UNIVERSAL-require-${VERSION}
PKGNAME=		p5-Universal-require-${VERSION}-${DASH_VER}
CATEGORIES=		devel perl5
MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=UNIVERSAL/}
HOMEPAGE=		http://search.cpan.org/~mschwern/${DISTNAME}/

# like Perl (GPL/Artistic)
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	perl

.include <bsd.port.mk>
