.\" $MirOS: src/lib/libc/stdio/getline.3,v 1.1 2006/11/20 23:06:47 tg Exp $
.\"-
.\" Copyright (c) 2006, 2007
.\"	Thorsten Glaser <tg@mirbsd.de>
.\"
.\" Provided that these terms and disclaimer and all copyright notices
.\" are retained or reproduced in an accompanying document, permission
.\" is granted to deal in this work without restriction, including un-
.\" limited rights to use, publicly perform, distribute, sell, modify,
.\" merge, give away, or sublicence.
.\"
.\" This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
.\" the utmost extent permitted by applicable law, neither express nor
.\" implied; without malicious intent or gross negligence. In no event
.\" may a licensor, author or contributor be held liable for indirect,
.\" direct, other damage, loss, or other issues arising in any way out
.\" of dealing in the work, even if advised of the possibility of such
.\" damage or existence of a defect, except proven that it results out
.\" of said person's immediate fault when using the work as intended.
.\"-
.Dd November 20, 2006
.Dt GETLINE 3
.Os GNU
.Sh NAME
.Nm getline
.Nd get a line from a stream
.Sh SYNOPSIS
.Fd #define _GNU_SOURCE
.Fd #include <stdio.h>
.Ft ssize_t
.Fn getline "char **buf" "size_t *len" "FILE *stream"
.Sh DESCRIPTION
The
.Fn getline
function is a GNU extension and should not be used in new code.
It is only implemented in
.Mx
for compatibility reasons.
Thus, no description is provided, but feel free to send us a diff.
It basically does the same as
.Xr fgetln 3 ,
reallocating or resizing the
.Fa *buf
argument if necessary, and NUL-terminating the result.
.Sh HISTORY
The
.Fn getline
function was first introduced to BSD in
.Mx 10 .
