# $OpenBSD: Makefile,v 1.1.1.1 2003/05/13 10:41:50 avsm Exp $

COMMENT=			collection of useful CVS scripts

VSN=		0.2.0
DISTNAME=	cvsutils-${VSN}
CATEGORIES=     devel

HOMEPAGE=	http://www.red-bean.com/cvsutils/
MASTER_SITES=	${HOMEPAGE}/releases/

# GPL
PERMIT_PACKAGE_CDROM=	Yes 
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	gnu
NO_REGRESS=		Yes

.include <bsd.port.mk>
