# $MirOS: ports/devel/p5-ExtUtils-CBuilder/Makefile,v 1.3 2008/08/05 19:54:41 bsiegert Exp $
# $OpenBSD: Makefile,v 1.1.1.1 2004/05/21 22:09:56 msf Exp $

COMMENT=		compile and link C code for Perl modules

DISTNAME=		ExtUtils-CBuilder-0.24
PKGNAME=		p5-${DISTNAME}-${DASH_VER}
CATEGORIES=		devel perl5


# Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=ExtUtils/}

CONFIGURE_STYLE=	perl

PKG_ARCH=		*

.include <bsd.port.mk>
