# $MirOS: ports/archivers/bzip2/files/Makefile.bzip2recover,v 1.1 2005/05/21 12:54:56 bsiegert Exp $

SRCDIR=		${.CURDIR}/..

PROG=		bzip2recover
LDADD+=		-L${SRCDIR}/lib -lbz2
NOMAN=		Yes

.PATH:		${SRCDIR}

.if defined(DESTDIR) && !empty(DESTDIR) && defined(TRUEPREFIX)
PREFIX:=	${TRUEPREFIX}
.endif

.include <bsd.prog.mk>
