.\" $MirOS: src/lib/libc/stdlib/rpmatch.3,v 1.1 2007/05/22 16:13:51 tg Exp $
.\"-
.\" Copyright (c) 2007
.\"	Thorsten Glaser <tg@mirbsd.de>
.\"
.\" Provided that these terms and disclaimer and all copyright notices
.\" are retained or reproduced in an accompanying document, permission
.\" is granted to deal in this work without restriction, including un-
.\" limited rights to use, publicly perform, distribute, sell, modify,
.\" merge, give away, or sublicence.
.\"
.\" This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
.\" the utmost extent permitted by applicable law, neither express nor
.\" implied; without malicious intent or gross negligence. In no event
.\" may a licensor, author or contributor be held liable for indirect,
.\" direct, other damage, loss, or other issues arising in any way out
.\" of dealing in the work, even if advised of the possibility of such
.\" damage or existence of a defect, except proven that it results out
.\" of said person's immediate fault when using the work as intended.
.\"-
.Dd $Mdocdate$
.Dt RPMATCH 3
.Os GNU
.Sh NAME
.Nm rpmatch
.Nd check user input for confirmation
.Sh SYNOPSIS
.Fd #define _SVID_SOURCE
.Fd #include <stdlib.h>
.Ft int
.Fn rpmatch "const char *response"
.Sh DESCRIPTION
The
.Fn rpmatch
function is a GNU extension and should not be used in new code.
It is only implemented in
.Mx
for compatibility reasons.
It basically checks if the
.Fa response
string begins with
.Dq Y
or
.Dq y ,
returning 1, or
.Dq N
or
.Dq n ,
returning 0; returning -1 otherwise.
.Sh HISTORY
The
.Fn rpmatch
function was first introduced to BSD in
.Mx 10 .
