# $MirOS$
# $OpenBSD: Makefile,v 1.3 1997/09/21 11:51:22 deraadt Exp $

PROG=	tr
SRCS=	str.c tr.c

MSMODS=	ambstowcs

.include <bsd.own.mk>
.include "${BSDSRCDIR}/share/common/Makefile.inc"

.include <bsd.prog.mk>
