#!/bin/sh
# $MirOS: contrib/hosted/tg/deb/mksh/debian/mksh.prerm,v 1.9 2012/06/06 22:56:56 tg Exp $

set -e

# This maintainer script can be called the following ways:
#
# * prerm "remove"
# * old-prerm "upgrade" $new_version
# * conflictors-prerm "remove" "in-favour" $package $new_version
# * deconfigureds-prerm "deconfigure" "in-favour"
#	$package_being_installed $pbi_version ["removing"
#	$conflicting_package $cp_version]
# The package and dependencies are at least Half-Installed; dependencies
# have previously been configured and not removed.
#
# * new-prerm "failed-upgrade" $old_version
# Called when 'old-prerm "upgrade"' fails; new package not unpacked, all
# other constraints the same as above.

case $1 in
remove|deconfigure)
	update-alternatives --remove irc /usr/bin/sirc
	;;

upgrade|failed-upgrade)
	;;

*)
	echo >&2 "prerm called with unknown subcommand '$1'"
	exit 1
	;;
esac

exit 0
