#!/bin/sh
# $MirOS$
# $OpenBSD: INSTALL-server,v 1.8 2003/08/27 00:14:49 brad Exp $
#
# Pre/post-installation setup of MySQL

PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
DB_DIR=${DB_DIR}
ID=502

do_notice_existingdir()
{
  echo
  echo "+---------------"
  echo "| You appear to already have a MySQL database directory in $DB_DIR"
  echo "|"
  echo "| The database directory has been preserved. If you want to start"
  echo "| from the default database setup, you should perform these steps"
  echo "| as root:"
  echo "|"
  echo "|           rm -rf $DB_DIR"
  echo "|           $PREFIX/bin/mysql_install_db"
  echo "|"
  echo "+---------------"
  echo
}

do_database_install()
{
  $PREFIX/bin/mysql_install_db
}

# Verify/process the command
#
case $2 in 
    PRE-INSTALL)
	if [ -d $DB_DIR ]; then
	  do_notice_existingdir $1
	fi
	;;
    POST-INSTALL)
	if [ ! -d $DB_DIR ]; then
	  do_database_install
	fi
	;;
    *)
	echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
	exit 1
	;;  
esac

exit 0
