# $MirOS$
# From: @(#)Makefile	6.3 (Berkeley) 6/8/93
# $OpenBSD: Makefile,v 1.3 2004/02/01 14:22:44 jmc Exp $

VOLUME=	papers
DOC=	malloc
DIR=	papers/${DOC}
SRCS=	abs.ms intro.ms kernel.ms malloc.ms problems.ms alternatives.ms
SRCS+=	performance.ms implementation.ms conclusion.ms
MACROS=	-ms

.include <bsd.doc.mk>
