# $MirOS: src/lib/csu/sparc_elf/Makefile,v 1.2 2005/03/06 20:28:24 tg Exp $
# $NetBSD: Makefile,v 1.5 2001/07/17 18:25:12 mrg Exp $

# Uncomment the next line to enable the new .init fallthru
CPPFLAGS+=	-DHAVE_MD_DOT_INIT

.include "${.CURDIR}/../common_elf/Makefile.inc"
