@ignore
@c Set file name and title for man page.
@setfilename gpl
@settitle GNU General Public License
@c man begin COPYRIGHT
Copyright @copyright{} 1989, 1991 Free Software Foundation, Inc.
59 Temple Place - Suite 330, Boston, MA  02111-1307, USA

Everyone is permitted to copy and distribute verbatim copies
of the GNU GPL, but changing it is not allowed.
@c man end
@end ignore
@node Copying
@c man begin DESCRIPTION
@unnumbered GNU GENERAL PUBLIC LICENSE
See /usr/share/doc/legal/COPYING-2 for the full
text of the FSF propaganda.
@c man end
