#!/bin/mksh
# $MirOS: src/share/misc/licence.template,v 1.28 2008/11/14 15:33:44 tg Rel $
#-
# Copyright (c) 2010
#	Thorsten Glaser <tg@mirbsd.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un-
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person's immediate fault when using the work as intended.

buf=($(dd if="$1" count=1 2>&- | hexdump -ve '1/1 "0x%02X "'))
buf[0x94]=0
buf[0x95]=0
buf[0x96]=0
buf[0x97]=0
buf[0x98]=0
buf[0x99]=0
buf[0x9A]=0
buf[0x9B]=0
i=0
typeset -Z9 -Uui8 chksum=256
while (( i < 512 )); do
	(( chksum += buf[i++] ))
done
print ${chksum#8#}
