#!/bin/mksh
# $MirOS: src/sys/arch/i386/stand/bootxx_ustarfs/tarcksum,v 1.1 2010/01/10 01:28:50 tg Exp $
#-
# Copyright (c) 2010
#	Thorsten Glaser <tg@mirbsd.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un-
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person's immediate fault when using the work as intended.

function tarcksum {
	typeset buf i

	buf=($(dd if="$1" count=1 2>/dev/null | hexdump -ve '1/1 "0x%02X "'))
	buf[0x94]=0
	buf[0x95]=0
	buf[0x96]=0
	buf[0x97]=0
	buf[0x98]=0
	buf[0x99]=0
	buf[0x9A]=0
	buf[0x9B]=0
	i=0
	typeset -Z9 -Uui8 chksum=256
	while (( i < 512 )); do
		(( chksum += buf[i++] ))
	done
	print ${chksum#8#}
}

tarcksum "$1"
