#!/bin/sh
# $MirOS$

if test x"$1" = x"-"; then
	shift
	exec /usr/bin/env -i \
	    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/X11R6/bin TZ=UTC HOME=/ \
	    "$@"
fi
exec /usr/bin/env -i PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/X11R6/bin TZ=UTC \
    DISPLAY="$DISPLAY" HOME="${HOME:-/}" TERM="${TERM:-vt100}" USER="${USER}" \
    $(locale | fgrep LC_CTYPE) "$@"
