#!/bin/ksh
# $MirOS: src/scripts/tarmk,v 1.1 2005/03/06 16:08:16 tg Exp $
#-
# Copyright (c) 2004
#	Thorsten "mirabile" Glaser <tg@66h.42h.de>
#
# Licensee is hereby permitted to deal in this work without restric-
# tion, including unlimited rights to use, publicly perform, modify,
# merge, distribute, sell, give away or sublicence, provided all co-
# pyright notices above, these terms and the disclaimer are retained
# in all redistributions or reproduced in accompanying documentation
# or other materials provided with binary redistributions.
#
# Licensor hereby provides this work "AS IS" and WITHOUT WARRANTY of
# any kind, expressed or implied, to the maximum extent permitted by
# applicable law, but with the warranty of being written without ma-
# licious intent or gross negligence; in no event shall licensor, an
# author or contributor be held liable for any damage, direct, indi-
# rect or other, however caused, arising in any way out of the usage
# of this work, even if advised of the possibility of such damage.

rel="$1"
dst="$RELEASEDIR"
src="$DESTDIR"
cwd="$(readlink -nf .)"
mach="${MACHINE:-$(uname -m)}"
SHELL="${SHELL:-/bin/ksh}"
me="${0##*/}"

lists="$(for i in */mi; do basename "${i%/mi}"; done)"

if [[ -z $rel ]]; then
	print "Syntax: $me <release>"
	exit 1
fi

if [[ -z $src ]]; then
	print "Must set DESTDIR before calling $me!"
	exit 1
fi

if [[ -z $dst ]]; then
	print "Must set RELEASEDIR before calling $me!"
	exit 1
fi

if [[ -z $lists ]]; then
	print "Error, LISTS are empty!"
	exit 2
fi

print "Generating release tarballs for MirOS #${rel}"

cd "$src"
for set in $lists; do
	print -n "${set}..."
	( cd "$cwd"; $SHELL "${0%/*}/tarsets" "$set" -u ) \
	    | sed -n 's!^\.//*!!p' | cpio -oC512 -Hsv4cpio \
	    | gzip -n9 >"$dst/$set${rel}.ngz"
	print "done."
done
cd "$cwd"
