#!/bin/mksh
# $MirOS: src/scripts/tarsets,v 1.4 2005/12/17 05:46:23 tg Exp $

subdir="$(readlink -nf .)"
set="$1"
arch="${MACHINE:-$(uname -m)}"

cat "$subdir/$set/mi" "$subdir/$set/md.$arch" 2>/dev/null | sort $2
