# $MirOS$
# $OpenBSD: Makefile,v 1.1.1.1 2004/05/03 19:13:28 naddy Exp $

COMMENT=		command line shell and file manager

DISTNAME=		clex-3.18
CATEGORIES=		misc

HOMEPAGE=		http://www.clex.sk/


# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=		${HOMEPAGE:=download/}

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
