# $MirOS$

-include ../config-host.mak

BSDMAKE?=	make
MKSETENV=	/usr/bin/env MFLAGS= MAKEFLAGS= MAKE="$(BSDMAKE)"

all:
	cd lkm && exec $(MKSETENV) $(BSDMAKE) obj
	cd lkm && exec $(MKSETENV) $(BSDMAKE) depend
	cd lkm && exec $(MKSETENV) $(BSDMAKE)

clean:
	cd lkm && exec $(MKSETENV) $(BSDMAKE) clean

install:
	cd lkm && exec $(MKSETENV) $(BSDMAKE) install
