# $MirOS: src/distrib/common/Makefile.sparc,v 1.17 2010/01/10 21:09:54 tg Exp $
# $OpenBSD: Makefile.inc,v 1.14 2002/05/01 19:21:28 mickey Exp $

RAWLABEL=
RAMDISK=	FLOPPY
LISTS=		${TOPDIR}/common/list.sparc-fdd
IMAGESIZE=	3328
AOUT_BSDRD=	Yes

FLOPPYFILES=	bsd
BOOTXX_TAR=	(${MKSH} ${BOOTSH} -g ${FLOPPYGEOM} -T ${BOOT_TAR}; cat)

CDROM=		no
INST_FILES=	${FLOPPY}
