# $MirOS: src/distrib/common/Makefile.i386,v 1.6 2009/08/15 18:26:26 tg Exp $

BOOT=		${DESTDIR}/usr/mdec/boot.fd
IMAGESIZE=	2816

.if defined(SERIALSPEED)
FLOPPY?=	floppy${SERIALSPEED}.fs
FLOPPY_BOOTCFG=	sed 's/@SPEED@/${SERIALSPEED}/g' \
		    ${TOPDIR}/tools/boot.cfg.serial >${WRKDIR}/boot.cfg
.endif

CDROM=		no
INST_FILES=	${FLOPPY}
