# $MirOS: src/distrib/common/Makefile.sparc,v 1.19 2010/01/17 00:35:08 tg Exp $
# $OpenBSD: Makefile.inc,v 1.14 2002/05/01 19:21:28 mickey Exp $

RAWLABEL=
RAMDISK=	FLOPPY
IMAGESIZE=	3584
AOUT_BSDRD=	Yes

LISTADDS=	boot-fd dl-noman nfs no-huge pager-more ppp-off sparc

FLOPPYFILES=	bsd
BOOTXX_TAR=	(${MKSH} ${BOOTSH} -g ${FLOPPYGEOM} -T ${BOOT_TAR}; cat)

CDROM=		no
INST_FILES=	${FLOPPY}
