.\"	$MirOS$
.\"
.\" Copyright (c) 2006
.\"	Benny Siegert <bsiegert@gmx.de>
.\"
.\" Licensee is hereby permitted to deal in this work without restric-
.\" tion, including unlimited rights to use, publicly perform, modify,
.\" merge, distribute, sell, give away or sublicence, provided all co-
.\" pyright notices above, these terms and the disclaimer are retained
.\" in all redistributions or reproduced in accompanying documentation
.\" or other materials provided with binary redistributions.
.\"
.\" Licensor hereby provides this work "AS IS" and WITHOUT WARRANTY of
.\" any kind, expressed or implied, to the maximum extent permitted by
.\" applicable law, but with the warranty of being written without ma-
.\" licious intent or gross negligence; in no event shall licensor, an
.\" author or contributor be held liable for any damage, direct, indi-
.\" rect or other, however caused, arising in any way out of the usage
.\" of this work, even if advised of the possibility of such damage.
.\"-
.\"
.Dd August 8, 2006
.Dt PKG_UPGRADE 1
.Os
.Sh NAME
.Nm pkg_upgrade
.Nd upgrade an installed package in-place
.Sh SYNOPSIS
.Nm pkg_upgrade
.Op Fl afq
.Ar pkgname.cgz
.Sh DESCRIPTION
The
.Nm
command is used to upgrade an installed package in-place.
If no other version of the package is installed and
.Fl a
is not given,
.Nm
simply calls
.Xr pkg_add 1 .
Otherwise, the installed package is deleted and the new version is added,
keeping dependencies intact.
.Pp
The following command line options are supported:
.Bl -tag -width indent
.It Fl a
Ignore packages for which no older version is installed
.Pq auto .
.It Fl f
Also upgrade the package if the exact same version is already installed
.Pq force .
Useful if you rebuilt a package from source.
.It Fl q
Don't print less important messages
.Pq quiet .
.El
.Sh SEE ALSO
.Xr pkg_add 1 ,
.Xr pkg_create 1 ,
.Xr pkg_delete 1 ,
.Xr ports 7
.Sh AUTHORS
.Bl -tag -width indent -compact
.It "Benny Siegert"
idea, first version, this manpage
.It "Thorsten Glaser"
option handling, robustness fixes
.El
.Sh BUGS
.Nm
can easily render other packages unusable if you install a new version
of a shared library while the other package still uses the old one.
