#!/bin/sh
# $MirOS$
#
# xsane de-installation

# exit on errors, use a sane path and install prefix
#
set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}

do_notice()
{
    echo ""
    echo "+--------------------"
    echo "| If you used the "gimp" flavor of xsane make sure"
    echo "| to remove the xsane gimp-plugin link (if you created it)"
    echo "| by issuing the following command as root:"
    echo "|  --> rm ${PREFIX}/lib/gimp/1.2/plug-ins/xsane"
    echo "+--------------------"
    echo ""
}

# verify proper execution
#
if [ $# -ne 2 ]; then
    echo "Usage: `basename $0` distname DEINSTALL" >&2
    exit 1
fi

# verify/process the command
#
case $2 in
    DEINSTALL)
	do_notice
	;;
    *)
	echo "Usage: `basename $0` distname DEINSTALL" >&2
	exit 1
	;;
esac

exit 0
