.\"	$MirOS: src/usr.sbin/vnconfig/vnconfig.8,v 1.8 2014/03/29 11:36:06 tg Exp $
.\"	$OpenBSD: vnconfig.8,v 1.21 2004/09/10 15:37:53 pedro Exp $
.\"
.\" Copyright (c) 2006, 2009, 2014 Thorsten Glaser
.\" Copyright (c) 1993 University of Utah.
.\" Copyright (c) 1980, 1989, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the Systems Programming Group of the University of Utah Computer
.\" Science Department.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)vnconfig.8	8.1 (Berkeley) 6/5/93
.\"
.Dd $Mdocdate: March 29 2014 $
.Dt VNCONFIG 8
.Os
.Sh NAME
.Nm vnconfig
.Nd "configure vnode disks for file swapping or pseudo filesystems"
.Sh SYNOPSIS
.Nm
.Op Fl c
.Op Fl vkr
.Op Fl f Ar keyfile
.Ar rawdev
.Ar regular_file
.Nm
.Fl u
.Op Fl v
.Ar rawdev
.Nm
.Fl l
.Op Ar rawdev
.Nm
.Fl K Ar algorithm
.Fl f Ar keyfile
.Sh DESCRIPTION
The
.Nm
command configures vnode pseudo disk devices.
It will associate (or disassociate) the special file
.Ar rawdev
with the regular file
.Ar regular_file
allowing the latter to be accessed as though it were a disk.
Hence a regular file within the filesystem can be used for swapping
or can contain a filesystem that is mounted in the name space.
Both traditional devices,
.Pa vnd ,
and the cache-coherent devices,
.Pa svnd ,
are configured through
.Nm vnconfig .
.Pp
If you read the regular file while using
.Pa svnd ,
you need to mount the
.Pa svnd
with the mount option
.Ar sync
to ensure consistency in the buffer cache.
For normal operation this is not necessary.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Configures the device.
If successful, references to
.Ar rawdev
will access the contents of
.Ar regular_file .
This is the default operation.
.It Fl f Ar keyfile
Instead of an encryption key read from stdin, an ASN.1 octet string
will be decoded from the PEM format
.Ar keyfile .
This option implies
.Fl k .
.It Fl k
Associate an encryption key with the device.
All data will be encrypted using the Blowfish cipher before it is
written to the disk.
Encryption only works with
.Pa svnd ,
not with
.Pa vnd .
.It Fl K Ar algorithm
Generate a PEM format keyfile containing an encrypted ASN.1
octet string which can be used as keyfile for further invocations of
.Nm
.Fl kf .
This is incompatible with the
.Fl K Ar rounds / Fl S Ar saltfile
method invented in
.Ox 4.2 .
.Pp
If the
.Fl k
option is also used, the system will convert an old (plain password)
encryption key to a keyfile by first asking (twice) for the plaintext
password, then (twice) for the PEM passphrase with which to protect
the keyfile (consisting of an encoded version of the old plaintext
password).
This can be used to migrate old encrypted volumes using the
.Ox
blowfish (bf-cbc) format to the new keyfile-based scheme, which
supports changing the user (PEM) passphrase without needing to
re-encrypt the actual data.
.Pp
If the
.Fl k
option is not used,
.Nm
will create a keyfile consisting of 448 random bits (for use with
the new-style bf-cbc algorithm \*(en other algorithms will follow
and use different formats), ask (twice) for a PEM passphrase with
which the newly created keyfile is to be protected, which can be
changed by the user without needing to re-encrypt the actual data,
then save the keyfile just created to disc.
.Pp
The
.Ar algorithm
can be chosen from the default
.Xr openssltool 1
list; see below for an example.
.It Fl l
List the vnd devices and indicate which ones are in use.
If a specific
.Ar rawdev
is given, then only that one will be described.
.It Fl r
If the kernel supports it, don't write to the underlying file.
This is supported since
.Mx 7 .
.It Fl u
Unconfigures the device.
.It Fl v
Print messages to stdout describing actions taken.
.El
.Pp
If no action option is given,
.Fl c
is assumed.
.Sh FILES
.Bl -tag -width /etc/rvnd?? -compact
.It Pa /dev/{,r}{,s}vnd*
.El
.Sh EXAMPLES
Configure the vnode disk
.Pa svnd0
(all of its partitions become usable):
.Pp
.Dl # vnconfig svnd0 /tmp/diskimage
.Pp
Unconfigure the same device:
.Pp
.Dl # vnconfig -u svnd0
.Pp
Show a list of supported
.Em Cipher Types :
.Pp
.Dl $ openssl enc -
.Pp
Create an encrypted image and a keyfile:
.Bd -literal -offset indent
$ dd if=/dev/arandom of=/tmp/foo.ima bs=1048576 count=16
$ vnconfig -K AES-256-CBC -f /tmp/foo.skf
.Ed
.Pp
Use an encrypted image with a keyfile:
.Pp
.Dl # vnconfig -f /tmp/foo.skf svnd0 /tmp/foo.ima
.Sh SEE ALSO
.Xr openssl 1 ,
.Xr openssltool 1 ,
.Xr arc4random 3 ,
.Xr blowfish 3 ,
.Xr vnd 4 ,
.Xr mount 8 ,
.Xr swapon 8 ,
.Xr umount 8
.Sh HISTORY
Support for external keyfiles was added in
.Mx 9 .
.Sh BUGS
This command should really be named
.Nm vndconfig .
.Pp
Currently, only bf-cbc (Blowfish) encryption in an
.Ox
compatible format is available.
Support for AES (including VIA C3 hardware acceleration) is planned.
.Pp
Configuring a block device, such as
.Pa /dev/wd0e ,
as
.Ar regular_file
will result in very bad I/O performance due to the use of
synchronous (reliable) writes, even if the inner filesystem
is mounted async or with softupdates.
Character special devices cannot be used at all.
This is a bug inherited from
.Ox .
