# $MirOS: ports/devel/pear-Log/Makefile,v 1.3 2005/07/07 21:20:16 bsiegert Exp $
# $OpenBSD: Makefile,v 1.5 2004/02/29 00:08:50 avsm Exp $

COMMENT=			logging utilities for PHP

V=		1.8.4
DISTNAME=	Log-${V}
PKGNAME=	pear-${DISTNAME}-0
CATEGORIES=	devel pear

MASTER_SITES=	http://pear.php.net/get/
EXTRACT_SUFX=	.tgz

HOMEPAGE=	http://www.csh.rit.edu/~jon/projects/pear_log/

MODULES=	www/php/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
