# $MirOS: src/distrib/generic/Makefile.sparc,v 1.3 2006/07/05 23:14:28 tg Exp $

CLEANFILES+=	bsd.net{,.tmp}

all: bsd.net

install.md:
	cp bsd.net ${DESTDIR}/snapshot/bsd.net

bsd.net: bsd
	-rm -f $@.tmp
	gzip -d <bsd >$@.tmp
	elf2aout $@.tmp $@ -b
	-rm -f $@.tmp
