#!/bin/sh
# $MirOS: ports/shells/mksh/pkg/INSTALL,v 1.2 2008/03/02 15:41:17 tg Exp $

set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin; export PATH
PREFIX=${PKG_PREFIX:-/usr/local}

usage() {
	echo >&2 "usage: $0 distname { PRE-INSTALL | POST-INSTALL }"
	exit 1
}

test $# -eq 2 || usage

case $2 in
PRE-INSTALL)
	: nothing to pre-install for this port
	;;
POST-INSTALL)
	grep -q "^${PREFIX}/5bin/sh\$" /etc/shells || cat <<-EOF
		+-----------------------------------------------------------
		| For proper use of $1 you should notify the system that
		| ${PREFIX}/5bin/sh is a valid shell by adding it to the
		| file /etc/shells. If you are unfamiliar with this file
		| consult the shells(5) manual page.
		+-----------------------------------------------------------
	EOF
	grep -q "^${PREFIX}/5bin/jsh\$" /etc/shells || cat <<-EOF
		+-----------------------------------------------------------
		| For proper use of $1 you should notify the system that
		| ${PREFIX}/5bin/jsh is a valid shell by adding it to the
		| file /etc/shells. If you are unfamiliar with this file
		| consult the shells(5) manual page.
		+-----------------------------------------------------------
	EOF
	;;
*)
	usage
	;;
esac

exit 0
