.\" $MirOS: ports/misc/cksfv/files/cksfv.1,v 1.1.7.1 2005/03/18 15:50:25 tg Exp $
.\"-
.\" Copyright (c) 2004
.\"	Thorsten "mirabile" Glaser <tg@66h.42h.de>
.\"
.\" Licensee is hereby permitted to deal in this work without restric-
.\" tion, including unlimited rights to use, publicly perform, modify,
.\" merge, distribute, sell, give away or sublicence, provided all co-
.\" pyright notices above, these terms and the disclaimer are retained
.\" in all redistributions or reproduced in accompanying documentation
.\" or other materials provided with binary redistributions.
.\"
.\" All advertising materials mentioning features or use of this soft-
.\" ware must display the following acknowledgement:
.\"	This product includes material provided by Thorsten Glaser.
.\"
.\" Licensor offers the work "AS IS" and WITHOUT WARRANTY of any kind,
.\" express, or implied, to the maximum extent permitted by applicable
.\" law, without malicious intent or gross negligence; in no event may
.\" licensor, an author or contributor be held liable for any indirect
.\" or other damage, or direct damage except proven a consequence of a
.\" direct error of said person and intended use of this work, loss or
.\" other issues arising in any way out of its use, even if advised of
.\" the possibility of such damage or existence of a nontrivial bug.
.\"-
.Dd March 6, 2004
.Dt CKSFV 1
.Os
.Sh NAME
.Nm cksfv
.Nd verify crc32 checksums on anime and other files
.Sh SYNOPSIS
.Nm cksfv
.Op Fl iqv
.Op Fl C Ar directory
.Op Fl f Ar file.sfv
.Op Ar
.Sh DESCRIPTION
The
.Nm
utility creates a checksum of each file being processed, and
either writes the checksum to disc or compares it with a list
of valid filename/checksum pairs.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl i
Ignore case on filenames.
This is mainly a convenience option for broken filesystems.
Its use is deprecated.
.It Fl q
Be quiet, only printing errors.
.It Fl v
Be verbose, report matches too.
This is the default mode of operation.
.It Fl C Ar directory
Change to the directory before processing.
.It Fl f Ar file.sfv
Verify mode, compare checksums with these in
.Pa file.sfv .
.br
By default,
.Nm
generates checksums for the files listed on the command line.
.El
.Sh EXAMPLES
.Li $ cksfv -f naruto1\-5.sfv
.Pp
Verifies the checksums and existence of all files listed in
.Pa naruto1\-5.sfv
in the current directory.
.Pp
.Li $ cksfv -qiC naruto1\-5/ -f naruto1\-5.sfv
.Pp
Changes into the subdirectory
.Pa naruto1\-5
before processing, ignores file case and only reports errors.
.Pp
.Li $ cksfv * >../snapshot.sfv
.Pp
Generate an SFV checksum file of all files in the current directory.
.Sh SEE ALSO
The
.Nm
homepage at
.Pa http://www.fodder.org/cksfv/ .
.Pp
Other checksum programmes include
.Xr rmd160 1 ,
.Xr md5 1 ,
.Xr sha1 1 .
.Sh AUTHORS
.An Bryan Call Aq bc@fodder.org
wrote the
.Nm
utility.
.An Thorsten Glaser Aq tg@66h.42h.de
did the
.Mx
port and wrote this manual.
