# $MirOS: ports/devel/p5-App-CLI/Makefile,v 1.1 2007/10/04 22:01:20 bsiegert Exp $

COMMENT=		portably perform operations on file names
DISTNAME=		PathTools-3.25
PKGNAME=		p5-${DISTNAME}-${DASH_VER}
CATEGORIES=		devel perl5
MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=../../authors/id/K/KW/KWILLIAMS/}
HOMEPAGE=		http://search.cpan.org/~kwilliams/${DISTNAME}/

# like Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	perl

.include <bsd.port.mk>
