#!/bin/mksh
# $MirOS: CVSROOT/mklogci,v 1.15 2005/12/22 01:14:31 tg Exp $
#-
# Copyright (c) 2005
#	Thorsten "mirabile" Glaser <tg@mirbsd.de>
#
# Licensee is hereby permitted to deal in this work without restric-
# tion, including unlimited rights to use, publicly perform, modify,
# merge, distribute, sell, give away or sublicence, provided all co-
# pyright notices above, these terms and the disclaimer are retained
# in all redistributions or reproduced in accompanying documentation
# or other materials provided with binary redistributions.
#
# All advertising materials mentioning features or use of this soft-
# ware must display the following acknowledgement:
#	This product includes material provided by Thorsten Glaser.
#
# Licensor offers the work "AS IS" and WITHOUT WARRANTY of any kind,
# express, or implied, to the maximum extent permitted by applicable
# law, without malicious intent or gross negligence; in no event may
# licensor, an author or contributor be held liable for any indirect
# or other damage, or direct damage except proven a consequence of a
# direct error of said person and intended use of this work, loss or
# other issues arising in any way out of its use, even if advised of
# the possibility of such damage or existence of a nontrivial bug.
#-
# CVS helper to create log messages from cvs commits, rewritten from
# scratch. The design pattern is a perl script originally written by
# David Hampton and hacked by Greg A. Woods, OpenBSD and MirBSD.
#-
# Usage: mklogci commitid [-C root] [-f file] [-I uri] [-M module]
#		 [-m mailto] -p pathr [-R replyto] file ...
#	commitid	= GNU CVS 1.12.12 + MirOS mode %I, PGRP else
#	-C root		= CVSROOT (the %r argument)
#	-f logfile	= create ChangeLog file from commit messages
#	-I loguri	= reduce size of import mails, refer to URI
#	-M module	= set module name
#	-m mailto	= send commit messages to mailto
#	-p pathr	= the %p argument
#	-R replyto	= set Reply-To: replyto header

function die
{
	print -r Error: "$@"
	rm -f $repo/.tmp/cl.*.$id
	exit 1
}

function makeheader
{
	cat <<-EOF
		Commit ID:	$id
		CVSROOT:	$repo
		Module name:	$module
		Changes by:	${USER}@$hn	$(TZ=UTC date '+%Y/%m/%d %T' 2>/dev/null) UTC

	EOF
}

function writelog
{
	{
		cat "$@"
		print ________________________________________________________________________
		print
	} | $SHELL $repo/CVSROOT/genlog $logfile $repo/CVSROOT/history
}

function writemail
{
	sendmail -t |&
	print -pr -- To: $mailto
	print -pr -- Subject: CVS: $hn: $module
	if [[ -n $replyto ]]; then
		print -pr -- Mail-Followup-To: $replyto
		print -pr -- Reply-To: $replyto
	fi
	print -p
	exec 3>&p
	cat "$@" >&3
	exec 3>&-
}

function addnames
{
	local i

	dir=${dir##+(./)}
	dir=${dir%%+(/)}
	[[ -z $dir ]] && dir=.
	line=$(printf '\t%-15s:' "$dir")
	linadd=${add_names[0]}
	let i=1
	let linln=3
	while (( i <= ${#add_names[*]} )); do
		while (( ( linln + ${#linadd} ) < 58 )); do
			line="$line $linadd"
			let "linln += ${#linadd} + 1"
			if (( i < ${#add_names[*]} )); then
				linadd=${add_names[i++]}
			else
				linadd=
				let i++
				break
			fi
		done
		print -r -- "$line"
		line='			'
		let linln=3
	done
}

function addflist
{
	set -A add_names
	IFS= read dir
	[[ $dir = */ ]] || die addflist "($dir)" does not look like a directory
	while IFS= read fn; do
		if [[ $fn = */ ]]; then
			addnames
			dir=$fn
			set -A add_names
		else
			add_names[${#add_names[*]}]=$fn
		fi
	done
	addnames
}

SHELL=${SHELL:-/bin/mksh}
id=$1
[[ -z $id ]] && exit 255
shift

logfile=
loguri=
module=
mailto=
pathr=
replyto=

while getopts "C:f:I:M:m:p:R: :" flag; do
	case $flag {
	(C)	repo=$OPTARG ;;
	(f)	logfile=$OPTARG ;;
	(I)	loguri=$OPTARG ;;
	(M)	module=$OPTARG ;;
	(m)	mailto=$OPTARG ;;
	(p)	pathr=$OPTARG ;;
	(R)	replyto=$OPTARG ;;
	(\ )	let 'OPTIND -= 2'
		break ;;
	(*)	die check usage
	}
done
shift $((OPTIND - 1))

[[ -z $repo ]] && repo=$CVSROOT
[[ -n $logfile && ! -e $logfile ]] && die logfile "($logfile)" does not exist
[[ -z $pathr ]] && die give a path please
hn=$(hostname 2>/dev/null)
[[ $hn = *.* ]] || hn=$hn.$(domainname 2>/dev/null)
[[ $hn = *. ]] && hn=${hn}invalid
if [[ $pathr = */* ]]; then
	pathd=${pathr#*/}
else
	pathd=.
fi

diff=$repo/.tmp/cl.log.dif.$id
msgf=$repo/.tmp/cl.log.msg.$id
outf=$repo/.tmp/cl.log.out.$id
tmpf=$repo/.tmp/cl.log.tmp.$id
modf=$repo/.tmp/cl.module.$id
prefix=$repo/.tmp/cl.lst
set -A files
set -A fold
set -A fnew
let i=0

while (( $# > 0 )); do
	files[i]=$1
	fold[i]=$2
	fnew[i]=$3
	if [[ $i = 0 && $2 = -\ * && $3 = NONE ]]; then
		# cvs import or cvs add directory
		break
	else
		let ++i
		shift; shift; shift
	fi
done

[[ -z $module ]] && module=${pathr%%/*}
[[ -n $logfile && $logfile != */* ]] && logfile=$repo/$module/$logfile
if [[ -e $modf ]]; then
	[[ "$(<$modf)" = $module ]] || print \(multiple\) >$modf
else
	print $module >$modf
fi

# Check for newly created dir
if [[ ${fold[0]} = "- New directory" ]]; then
	makeheader >$tmpf
	print -r -- "${files[0]}" >>$tmpf
	print >>$tmpf
	cat >>$tmpf
	[[ -n $logfile ]] && writelog $tmpf
	[[ -n $mailto ]] && writemail $tmpf
	rm $repo/.tmp/cl.*.$id
	exit 0
fi

# Iterate over the message body
status=none
set -A changed_files
set -A added_files
set -A removed_files
set -A log_lines
while IFS= read -r line; do
	case $line {
	(Modified\ Files*)
		status=changed
		continue ;;
	(Added\ Files*)
		status=added
		continue ;;
	(Removed\ Files*)
		status=removed
		continue ;;
	(Log\ Message*)
		status=log
		continue ;;
	}

	# Delete leading/trailing whitespace
	[[ $status = log ]] || line=${line##*([	 ])}
	line=${line%%*([	 ])}

	case $status {
	(changed)
		for i in $line; do
			changed_files[${#changed_files[*]}]=$i
		done ;;
	(added)
		for i in $line; do
			added_files[${#added_files[*]}]=$i
		done ;;
	(removed)
		for i in $line; do
			removed_files[${#removed_files[*]}]=$i
		done ;;
	(log)
		log_lines[${#log_lines[*]}]=$line
		;;
	}

done

# Strip trailing blank lines from the log message; multiple blank
# lines are compressed into one, and leading blank lines are removed
[[ ${#log_lines[*]} -gt 0 ]] && \
    while [[ ${log_lines[${#log_lines[*]}-1]} = *([	 ]) ]]; do
	unset log_lines[${#log_lines[*]}-1]
done
let i=0
while (( i < ${#log_lines[*]} )); do
	[[ ${log_lines[i]} = *([	 ]) ]] || break
	let ++i
done
print -n >$msgf
sp=
[[ ${fold[0]} = "- Imported sources" ]] && sp='    '
while (( i < ${#log_lines[*]} )); do
	if [[ ${log_lines[i]} = *([	 ]) ]]; then
		let ++i
		[[ $isblank = 1 ]] && continue
		print >>$msgf
		isblank=1
	else
		print -r -- "$sp${log_lines[i++]}" >>$msgf
		isblank=0
	fi
done

# Check for an import command
if [[ ${fold[0]} = "- Imported sources" ]]; then
	makeheader >$tmpf
	print Log message: >>$tmpf
	ed -s $msgf <<-'EOF'
		%g/^    \(Status:\)$/s//\1/
		%g/^    \(Vendor Tag:\)/s//\1/
		%g/^    \(Release Tags:\)/s//\1/
		wq
	EOF
	if [[ -n $loguri ]]; then
		cat $tmpf >$outf
		sed -n '1,/Release Tags/p' <$msgf >>$outf
		cat >>$outf <<-EOF

			To reduce mail sizes, imports only send out the log message
			and tags; the (rather large) ChangeLog data can be found at
			|	${loguri}
			Please remember that it can take some time to synchronise.
		EOF
	else
		cat $tmpf $msgf >$outf
	fi
	[[ -n $logfile ]] && writelog $tmpf $msgf
	[[ -n $mailto ]] && writemail $outf
	rm $repo/.tmp/cl.*.$id
	exit 0
fi

[[ "$(<$repo/.tmp/cl.lastdir.$id)" = $repo/$pathr ]]
leave=$?

# Look for a log file which matches this log message
let i=0
lmsg=$(<$msgf)
while : ; do
	if [[ ! -e $prefix.msg.$i.$id ]]; then
		cp $msgf $prefix.msg.$i.$id
		break
	fi
	[[ $lmsg = "$(<$prefix.msg.$i.$id)" ]] && break
	let ++i
done

# Write information collected during this run
[[ ${#changed_files[*]} -gt 0 ]] && print -r -- "$pathd/" >>$prefix.chg.$i.$id
let j=0
while (( j < ${#changed_files[*]} )); do
	print -r -- "${changed_files[j++]}" >>$prefix.chg.$i.$id
done
[[ ${#added_files[*]} -gt 0 ]] && print -r -- "$pathd/" >>$prefix.add.$i.$id
let j=0
while (( j < ${#added_files[*]} )); do
	print -r -- "${added_files[j++]}" >>$prefix.add.$i.$id
done
[[ ${#removed_files[*]} -gt 0 ]] && print -r -- "$pathd/" >>$prefix.del.$i.$id
let j=0
while (( j < ${#removed_files[*]} )); do
	print -r -- "${removed_files[j++]}" >>$prefix.del.$i.$id
done

# Collect changeset diff information
let j=0
while (( j < ${#files[*]} )); do
	fn=$pathr/${files[j]}
	old=${fold[j]}
	[[ $old = NONE ]] && old=0
	new=${fnew[j]}
	[[ $new = NONE ]] && new=0
	print -r -- "cvs -R rdiff -ur$old -r$new $fn" >>$diff
	[[ -n $logfile ]] && print -r -- "$id	$fn" >>${logfile%/*}/idcache
	let ++j
done

# End here if this is not my last invocation
[[ $leave = 1 ]] && exit 0
module=$(<$modf)

# Prepare the final commit message
makeheader >$tmpf
let i=0
while [[ -e $prefix.msg.$i.$id ]]; do
	let j=0
	if [[ -s $prefix.chg.$i.$id ]]; then
		print Modified files: >>$tmpf
		addflist <$prefix.chg.$i.$id >>$tmpf
		let ++j
	fi
	if [[ -s $prefix.add.$i.$id ]]; then
		print Added files: >>$tmpf
		addflist <$prefix.add.$i.$id >>$tmpf
		let ++j
	fi
	if [[ -s $prefix.del.$i.$id ]]; then
		print Removed files: >>$tmpf
		addflist <$prefix.del.$i.$id >>$tmpf
		let ++j
	fi
	(( j > 0 )) && print >>$tmpf
	if [[ -s $prefix.msg.$i.$id ]]; then
		print Log message: >>$tmpf
		cat $prefix.msg.$i.$id >>$tmpf
		print >>$tmpf
	fi
	let ++i
done
if [[ -s $diff ]]; then
	print To generate a diff of this changeset, execute the \
	    following commands: >>$tmpf
	cat $diff >>$tmpf
fi

# And out with it
[[ -n $logfile ]] && writelog $tmpf
[[ -n $mailto ]] && writemail $tmpf
rm $repo/.tmp/cl.*.$id
exit 0
