#!/bin/mksh
# $MirOS: src/libexec/randshuffle/randshuffle,v 1.19 2007/06/09 15:22:10 tg Exp $
#-
# Copyright (c) 2006, 2007
#	Thorsten Glaser <tg@mirbsd.de>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un-
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# Advertising materials mentioning features or use of this work must
# display the following acknowledgement:
#	This product includes material provided by Thorsten Glaser.
#
# This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person's immediate fault when using the work as intended.

export PATH=/bin:/usr/bin:/sbin:/usr/sbin

[[ $1 = -f ]] && alias sleep=true

sleep $((RANDOM % 120 + 30))
(print -r "$$ $((RANDOM << 15 | RANDOM)) $PPID $SECONDS $TMOUT $KSH_VERSION"; \
 sysctl -a; ps -akwwx -o "$(ps -L)"; ps -aexwwo pid,args; ps -axwwo pid,args; \
 date) 2>&1 | cksum -ba sha256 >/dev/wrandom
sleep $((RANDOM % 9 + 9))
cat /var/db/host.random >/dev/urandom 2>&1
sleep $((RANDOM % 9 + 9))
umask 077
( ( dd if=/dev/prandom bs=64 count=1; \
    dd if=/dev/arandom bs=64 count=31; \
    dd if=/dev/urandom bs=64 count=32; \
  ) 2>/dev/wrandom | dd of=/var/db/host.random; \
    chown 0:0 /var/db/host.random; \
    chmod 600 /var/db/host.random) \
    >/dev/wrandom 2>&1
sleep $((RANDOM % 3 + 2))
print -n $$ $((RANDOM << 15 | RANDOM)) $SECONDS | cksum -ba suma >/dev/wrandom
sleep $((RANDOM % 1))
print "notice: system random seed rotated! $((RANDOM & 255))" | logger
exit 0
