#!/bin/mksh
# $MirOS: src/libexec/randshuffle/randshuffle,v 1.24 2010/10/01 17:27:06 tg Exp $
#-
# Copyright (c) 2006, 2007, 2008, 2010, 2014, 2016
#	mirabilos <m@mirbsd.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un-
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person's immediate fault when using the work as intended.

export PATH=/bin:/usr/bin:/sbin:/usr/sbin

if [[ $1 = -f ]]; then
	alias sleep=true
	shift
fi

set -A files
for file in "$@"; do
	[[ -e $file ]] && files[${#files[*]}]=$file
done
if (( ${#files[*]} )); then
	what=user
	x_p=4
	x_a=52
	x_u=8
else
	set -A files /var/db/host.random
	what=system
	x_p=1
	x_a=31
	x_u=32
fi

sleep $((RANDOM % 120 + 30))
(print -r "$$ $((RANDOM << 15 | RANDOM)) $PPID $SECONDS $TMOUT $KSH_VERSION"; \
 sysctl -a; ps -akwwx -o "$(ps -L)"; ps -aexwwo pid,args; ps -axwwo pid,args; \
 date) 2>&1 | \
    cksum -ba bafh -a sfv -a sha256 -a tiger -a whirlpool >/dev/wrandom
sleep $((RANDOM % 9 + 9))
cat "${files[@]}" >/dev/arandom 2>/dev/wrandom
sleep $((RANDOM % 9 + 9))
umask 077
for file in "${files[@]}"; do
	print $SECONDS $RANDOM "$file"
	(
		dd if=/dev/prandom bs=64 count=$x_p
		dd if=/dev/arandom bs=64 count=$x_a
		dd if=/dev/urandom bs=64 count=$x_u
	) | dd of="$file" conv=notrunc
	chown 0:0 "$file"
	chmod 600 "$file"
done >/dev/wrandom 2>&1
sleep $((RANDOM % 3 + 2))
print -n $what $$ $((RANDOM << 15 | RANDOM)) $SECONDS | \
    cksum -ba suma >/dev/wrandom
sleep $((RANDOM % 1 + 1))
print "notice: $what random seed rotated! $((RANDOM & 255))" | logger
print -n $RANDOM >/dev/wrandom
exit 0
