#!/bin/mksh
# $MirOS: src/libexec/randshuffle/randshuffle,v 1.13 2006/10/07 03:37:10 tg Exp $
#-
# Copyright (c) 2006
#	Thorsten Glaser <tg@mirbsd.de>
#
# Licensee is hereby permitted to deal in this work without restric-
# tion, including unlimited rights to use, publicly perform, modify,
# merge, distribute, sell, give away or sublicence, provided all co-
# pyright notices above, these terms and the disclaimer are retained
# in all redistributions or reproduced in accompanying documentation
# or other materials provided with binary redistributions.
#
# Advertising materials mentioning features or use of this work must
# display the following acknowledgement:
#	This product includes material provided by Thorsten Glaser.
#
# Licensor offers the work "AS IS" and WITHOUT WARRANTY of any kind,
# express, or implied, to the maximum extent permitted by applicable
# law, without malicious intent or gross negligence; in no event may
# licensor, an author or contributor be held liable for any indirect
# or other damage, or direct damage except proven a consequence of a
# direct error of said person and intended use of this work, loss or
# other issues arising in any way out of its use, even if advised of
# the possibility of such damage or existence of a defect.

export PATH=/bin:/usr/bin:/sbin:/usr/sbin

sleep $((RANDOM % 120 + 30))
( date; echo $RANDOM $PPID $SECONDS $TMOUT $$ $KSH_VERSION; ps ax ) 2>&1 | \
    cksum -ba sha512 >/dev/prandom
sleep $((RANDOM % 9 + 9))
cat /var/db/host.random >/dev/urandom 2>&1
sleep $((RANDOM % 9 + 9))
rm -f /var/db/host.random
umask 077
( dd if=/dev/prandom count=1; dd if=/dev/arandom count=4; dd if=/dev/urandom \
    count=3 ) >/var/db/host.random 2>/dev/prandom
chown 0:0 /var/db/host.random
chmod 0600 /var/db/host.random
sleep $((RANDOM % 3 + 3))
print "notice: system random seed rotated! $((RANDOM & 255))" | logger
sleep $((RANDOM % 9 + 9))
( TZ=UTC date; print $RANDOM $SECONDS ) 2>&1 | cksum -ba suma >/dev/prandom
exit 0
