# $MirOS$
# $OpenBSD: Makefile,v 1.15 2004/04/22 22:15:47 naddy Exp $

COMMENT=	"library to parse Uniform Resource Identifiers"
DISTNAME=	URI-1.35
PKGNAME=	p5-${DISTNAME}-0
CATEGORIES=	www perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=URI/}

# GPL/Artistic licence
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	perl

.include <bsd.port.mk>
