.\" $MirOS: X11/extras/xsel/xsel.1,v 1.1 2011/06/07 22:05:11 tg Exp $
.\"-
.\" Copyright (c) 2011 Thorsten Glaser <tg@mirbsd.org>
.\" xsel is:
.\" Copyright (C) 2001 Conrad Parker <conrad@vergenet.net>
.\" UTF-8 support by Sergey Kogan <kogan@sklad.bacon.ru>
.\"
.\" Permission to use, copy, modify, distribute, and sell this software and
.\" its documentation for any purpose is hereby granted without fee, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  No representations are made about the suitability of this
.\" software for any purpose.  It is provided "as is" without express or
.\" implied warranty.
.\"
.Dd $Mdocdate: June 7 2011 $
.Dt XSEL 1
.Os
.Sh NAME
.Nm xsel
.Nd manipulate the X selection
.Sh SYNOPSIS
.Nm
.Op Fl abcdfhiknopsVvx
.Op Fl l Ar logfile
.Op Fl t Ar timeout
.Sh DESCRIPTION
The
.Nm X
server maintains three selections, called
.Ic PRIMARY ,
.Ic SECONDARY
and
.Ic CLIPBOARD .
Normally, the
.Ic PRIMARY
selection is only accessible by manually highlighting
information and pasting with the middle mouse button, the
.Ic SECONDARY
selection is less frequently used by application programs, and the
.Ic CLIPBOARD
is only available to Copy/Cut/Paste commands of GUI applications.
.Nm XSel
is a command-line utility to manipulate the selections.
.Pp
By default,
.Nm XSel
operates on the
.Ic PRIMARY
selection.
It sets the selection to data read from standard input,
if standard output is a tty and standard input is not;
otherwise, it prints the current content of the selection.
If both input and output mode are selected, the previous
content of the selection is output, then the data read from
standard input is stored as the new content of the selection.
.Pp
The options are as follows:
.Bl -tag -width XlXlogfile
.It Fl a
Append input to the selection instead of replacing it.
.It Fl b
Operate on the
.Ic CLIPBOARD
selection.
.It Fl c
Clear the selection.
.It Fl d
Request that the selection be cleared and
the application owning it delete its contents.
.It Fl f
Follow input and append it to the selection as it grows.
.It Fl h
Display the usage and exit.
.It Fl i
Store input into the selection.
.It Fl k
Keep the currently set
.Ic PRIMARY
and
.Ic SECONDARY
selections in persistent memory by taking them over, so they
can be accessed even if the originating program terminates.
See
.Sx CAVEATS
for details.
.It Fl l Ar logfile
Write errors to
.Ar logfile
when detached.
.Pp
Default:
.Pa ~/.etc/xsel.log
.It Fl n
Do not detach from the controlling tty.
.It Fl o
Output current content of the selection.
.It Fl p
Operate on the
.Ic PRIMARY
selection
.Pq default .
.It Fl s
Operate on the
.Ic SECONDARY
selection.
.It Fl t Ar timeout
Specify the
.Ar timeout
in milliseconds within which the selection must have been retrieved.
A value of 0
.Pq default
specifies no timeout.
.It Fl V
Display the version and exit.
.It Fl v
Increase verbosity, print informative messages.
.It Fl x
Exchange the contents of the
.Ic PRIMARY
and
.Ic SECONDARY
selections with each other.
.El
.Pp
.Sh EXAMPLES
Similar to
.Nm tail
.Fl f ,
follow a growing file and append to the selection:
.Pp
.Dl $ xsel -f </var/log/messages
.Sh SEE ALSO
.Xr tail 1 ,
.Xr Xserver 1 ,
.Xr xset 1 ,
.Xr xclipboard 1 ,
.Xr xpaste 1 ,
.Xr X\& 7
.Pp
.Pa http://www.vergenet.net/\*(TIconrad/software/xsel/
.Sh STANDARDS
.Nm XSel
conforms to the X Window System Inter-Client Communication Conventions
Manual Version 2.0
.Pq Tn ICCCM2 ,
including correct handling of TARGETS, MULTIPLE, TIMESTAMP, and DELETE
targets, INCR properties and large data transfers.
The author's thoughts on
.Tn ICCCM
.Pq Warning: explicit language
are available at:
.Pa http://lists.slug.org.au/archives/slug\-chat/2001/July/msg00054.html
.Sh AUTHORS
.Nm XSel
was written by
.An Conrad Parker Aq conrad@vergenet.net .
.An Sergey Kogan Aq kogan@sklad.bacon.ru
provided UTF-8 support.
.Pp
The
.Xr mdoc 7
format manpage was cobbled together by
.An Thorsten Glaser Aq tg@mirbsd.org .
.Sh CAVEATS
.Em There is no X selection buffer .
The selection mechanism in X11 is an interclient communication mediated by the X server each time any program wishes to know the selection contents, eg. to perform a middle mouse button paste.
In order to implement modification of the selection(s) (in input, keep and exchange modes) this utility detaches from the terminal, spawning a child process to supply the new selection(s) on demand.
This
.Xr daemon 3
process exits immediately when any other program takes over the selection(s), eg. when the user next selects some text in a terminal window, or by running
.Ic xsel Fl c .
