# $MirOS: src/distrib/ramtools/less/Makefile,v 1.2 2006/05/26 17:09:35 tg Exp $

.include <bsd.own.mk>

SRC_PATH=	${BSDSRCDIR}/usr.bin/less

CPPFLAGS+=	-DSMALL=1

.include "${SRC_PATH}/less/Makefile"
