.\" $MirOS: src/share/doc/legal/lbsd.mdoc,v 1.11 2006/08/08 21:38:03 tg Exp $
.\" partially derived from:
.\" $OpenBSD: COPYRIGHT,v 1.3 2003/06/04 16:08:07 deraadt Exp $
.\" @(#)COPYRIGHT	5.1 (Berkeley) 7/1/91
.\"-
.Dd August 8, 2006
.Dt BSD-Licence 7
.Os MirOS
.Sh NAME
This is the
.Nm BSD-Licence
for the
.Mx
base system.
.Sh DESCRIPTION
This document provides a list of all advertising clauses
required to be reproduced when distributing
.Mx ,
as well as the terms and conditions covering the operating system.
.Sh MIROS PROJECT
MirOS is Copyright \(co 2003, 2004, 2005, 2006
.D1 An The MirOS Project Aq miros-dev@mirbsd.org
.br
For a list of developers and the current licence terms of MirOS itself,
refer to the file
.Pa /usr/share/doc/legal/LICENCE .
.Pp
MirBSD is Copyright \(co 1999, 2002, 2003 \(ff.
.D1 An Thorsten Do mirabile Dc Glaser Aq tg@mirbsd.de
.br
All rights reserved.
.Pp
Licensee is hereby permitted to deal in this work without restriction,
including unlimited rights to use, publicly perform, modify,
merge, distribute, sell, give away or sublicence, provided all copyright
notices above, these terms and the disclaimer are retained
in all redistributions or reproduced in accompanying documentation
or other materials provided with binary redistributions.
.Pp
Licensor offers the work
.Dq AS IS
and WITHOUT WARRANTY of any kind,
express, or implied, to the maximum extent permitted by applicable
law, without malicious intent or gross negligence; in no event may
licensor, an author or contributor be held liable for any indirect
or other damage, or direct damage except proven a consequence of a
direct error of said person and intended use of this work, loss or
other issues arising in any way out of its use, even if advised of
the possibility of such damage or existence of a defect.
.Pp
This licence agreement shall be governed in all aspects by the law
of Germany; designated place of court is Bonn, NRW, Germany.
(Der Gerichtsstand ist Bonn, NRW/Deutschland.
Es gilt deutsches Recht.)
.Pp
I as the MirOS Project leader and MirBSD's owner hereby assert a collective-work
copyright on
.Dq MirBSD
including the MirPorts Framework and the (OpenBSD-derived) kernel and userland,
as well as the MirOS Portable Subprojects (for example, mksh, MirMake and jupp),
but excluding single ports, the contributed sections (the modules gcc, x11 and
contrib) and any part of MirBSD with copyright assignments in place (appropriate
CVS access control ought to be set). Please note that this copyright still applies
to some work contained within the X11 and contrib modules.
.Pp
I hereby rescind the advertising clause with my name in it whenever either my
death is confimed by German authorities or all other advertising clauses within
MirOS are rescinded, whatever comes first.
.Sh UCB
.so lbsd-ucb.mdoc
.Sh IEEE
.so lbsd-ieee.mdoc
.Sh ANSI
.so lbsd-ansi.mdoc
.Sh DARPA
.so lbsd-darpa.mdoc
.Sh SCO
.so lbsd-caldera.mdoc
.Sh TRADEMARKS
All trademarks are properties of their respective holders.
Particularily, the UNIX\(rg trademark changed its owner so
often it's impossible to track it down.
.Sh ADVERTISING CLAUSES
The following attribution clauses are required to be reproduced
when advertising for
.Mx :
.Bl -bullet -compact
.so lbsd-adv.mdoc
.El
.Pp
.Mx
contains contributed material from GNU and XFree86\(rg, which require
these additional advertising clauses to be reproduced:
.Bl -bullet -compact
.so lbsd-adc.mdoc
.El
.Pp
The MirPorts Framework currently requires reproducing these clauses:
.Bl -bullet -compact
.so lbsd-adp.mdoc
.El
.Pp
All trademarks and registered trademarks are properties of their
respective owners.
.Sh NO-ENDORSEMENT CLAUSE
Neither the name of licensor, nor the names of the authors
and contributors may be used to endorse or promote products
derived from this work without specific prior written permission.
.Sh AUTHORS
This manual was carefully put together first for the release of
.Mx 8
by
.An Thorsten Do mirabile Dc Glaser Aq tg@mirbsd.de .
It is still maintained for
.Mx 9bis .
.Sh FILES
.Bl -tag -width 8n -compact
.It Pa /usr/share/doc/legal/1stREAD
Overview over all legal documents.
.It Pa /usr/share/doc/legal/LICENCE
The terms covering the whole of
.Mx
base.
.It Pa /usr/share/misc/licence.template
Licence preferred to be used for code newly added to
.Mx .
.It Pa http://mirbsd.de/MirOS-Licence
Online version of
.Pa licence.template .
.El
.Sh SEE ALSO
.Pa http://mirbsd.de/
.Pp
.Pa http://www.mirbsd.org/
.Sh BUGS
Although collected carefully, there might be some.
Please report to the
.Mx
project at
.Aq miros-discuss@mirbsd.org
if you think you have discovered a bug.
