.\" $MirOS: src/share/doc/legal/lbsd.mdoc,v 1.36 2015/01/02 13:54:20 tg Exp $
.\" partially derived from:
.\" $OpenBSD: COPYRIGHT,v 1.3 2003/06/04 16:08:07 deraadt Exp $
.\" @(#)COPYRIGHT	5.1 (Berkeley) 7/1/91
.\"-
.Dd $Mdocdate: January 2 2015 $
.Dt BSD-Licence 7
.Os MirOS
.Sh NAME
This is the
.Nm BSD-Licence
for the
.Mx
.ie \ng==1 \{\
bsd4grml
.\}
.el .ie \ng==2 \{\
bsd4me
.\}
.el \{\
base
.\}
system.
.Sh DESCRIPTION
This document provides a list of all advertising clauses
required to be reproduced when distributing
.Mx ,
as well as the terms and conditions covering the operating system.
.Sh MIROS PROJECT
MirOS is Copyright \(co 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
2011, 2012, 2013, 2014, 2015, 2016
.ie \ng>0 \{\
.D1 An The MirOS Project Aq miros-dev@mirbsd.org
and its contributors.
.Pp
It is available under the terms listed below.
We strive to make MirOS available on OSD conformant licences and
believe that it is DFSG free.
This subset included with
.ie \ng==2 bsd4me
.el grml
certainly is.
.\}
.el \{\
.D1 An The MirOS Project Aq miros-dev@mirbsd.org
.br
For a list of developers and the current licence terms of MirOS itself,
refer to the file
.Pa /usr/share/doc/legal/LICENCE .
.\}
.Sh MirOS' origins
MirBSD is Copyright \(co 1999, 2002, 2003 \(ff.
.D1 An Thorsten Do mirabilos Dc Glaser Aq tg@mirbsd.de
.br
All rights reserved.
.Pp
Provided that these terms and disclaimer and all copyright notices
are retained or reproduced in an accompanying document, permission
is granted to deal in this work without restriction, including unlimited
rights to use, publicly perform, distribute, sell, modify,
merge, give away, or sublicence.
.Pp
Where legally impermissible the licensor does not disclaim liability
for direct physical injury or death caused solely by defects in the
work unless it is modified by a third party.
.Pp
This work is provided
.Dq AS IS
and WITHOUT WARRANTY of any kind, to
the utmost extent permitted by applicable law, neither express nor
implied; without malicious intent or gross negligence.
In no event
may a licensor, author or contributor be held liable for indirect,
direct, other damage, loss, or other issues arising in any way out
of dealing in the work, even if advised of the possibility of such
damage or existence of a defect, except proven that it results out
of said person's immediate fault when using the work as intended.
.Pp
This licence agreement shall be governed in all aspects by the law
of Germany; designated place of court is Bonn, NRW, Germany.
.Po
Gerichtsstand ist Bonn, NRW/Deutschland.
Es gilt deutsches Recht.
.Pc
.Pp
I as the MirOS Project leader and MirBSD's owner hereby assert a
collective-work copyright on
.Dq MirBSD
including the MirPorts Framework and the (OpenBSD-derived) kernel and
userland, as well as the MirOS Portable Subprojects (for example, mksh,
MirMake and jupp), but excluding single ports, the contributed sections
(the modules gcc, x11 and contrib) and any part of MirBSD that is either
marked as "Public Domain" and not derived from another project's work
under a good copyright licence, or with copyright assignments in place,
unless stated otherwise.
Please note that this copyright still applies to some work
contained within the X11 and contrib modules.
.Sh MIDNIGHTBSD
.so lbsd-mnbsd.mdoc
.Sh NON-BSD SOFTWARE
MirOS aggregates third-party work, which is owned by their respective
authors and covered by their respective licences
.Pq Sendmail , Apache , LGPL , GPL .
.ie \ng>0 \{\
In this edition, the
.Nm e3
editor (GPLv2) and the
.Nm tinyirc
IRC client (GPLv1) are aggregated on the rescue kernel.
Their sources accompany this document, as demanded by the GNU GPL.
The
.Nm tinyirc
author has agreed for it to be crunched into the instbin binary;
full source code for the other binaries and libraries linked is
available from our CVS repository.
.\}
.el \{\
They are listed in the overview file, see
.Sx FILES
below.
.\}
.Sh UCB
.so lbsd-ucb.mdoc
.Sh IEEE
.so lbsd-ieee.mdoc
.Sh ANSI
.so lbsd-ansi.mdoc
.Sh DARPA
.so lbsd-darpa.mdoc
.Sh SCO
.so lbsd-caldera.mdoc
.Sh TRADEMARKS
All trademarks are properties of their respective holders.
Particularily, the UNIX\(rg trademark changed its owner so
often it's impossible to track it down.
.Sh ADVERTISING CLAUSES
The following attribution clauses are required to be reproduced
when advertising for
.Mx :
.Bl -bullet -compact
.so lbsd-adv.mdoc
.El
.if \ng==0 \{\
.Pp
.Mx
contains contributed material from GNU and XFree86\(rg, which require
these additional advertising clauses to be reproduced:
.Bl -bullet -compact
.so lbsd-adc.mdoc
.El
.\}
.Pp
All trademarks and registered trademarks are properties of their
respective owners.
.Sh NO-ENDORSEMENT CLAUSE
Neither the name of licensor, nor the names of the authors
and contributors may be used to endorse or promote products
derived from this work without specific prior written permission.
.Sh AUTHORS
This manual was carefully put together first for the release of
.Mx 8
by
.An Thorsten Do mirabilos Dc Glaser Aq tg@mirbsd\.org .
It is still maintained for
.Mx 11 .
.Sh SOURCE ACCESS CLAUSE
Some licences require access to source code.
When said code is not part of the original distribution medium or
placed alongside it, it is either available via standard means,
specifically AnonCVS, AnonRSYNC, or HTTP distfile download, from
the project server, or, in some cases, available upon request for
a reasonable time period, such as three years.
.if \ng==0 \{\
.Sh FILES
.Bl -tag -width 8n -compact
.It Pa /usr/share/doc/legal/1stREAD
Overview over all legal documents.
.It Pa /usr/share/doc/legal/LICENCE
The terms covering the whole of
.Mx
base.
.It Pa /usr/share/misc/licence\.template
Licence preferred to be used for code newly added to
.Mx .
.It Pa http://mirbsd\.de/MirOS-Licence
Online version of
.Pa licence\.template .
.El
.\}
.Sh SEE ALSO
.Pa http://mirbsd\.de/
.Pp
.Pa https://www\.mirbsd\.org/
.Sh BUGS
Although collected carefully, there might be some.
Please report to the
.Mx
project at
.Aq miros-discuss@mirbsd\.org
if you think you have discovered a bug.
