.\" $MirOS: src/share/doc/legal/lbsd.mdoc,v 1.4 2005/12/03 23:13:18 tg Exp $
.\" partially derived from:
.\" $OpenBSD: COPYRIGHT,v 1.3 2003/06/04 16:08:07 deraadt Exp $
.\" @(#)COPYRIGHT	5.1 (Berkeley) 7/1/91
.\"-
.Dd January 12, 2005
.Dt BSD-Licence 7
.Os MirOS
.Sh NAME
This is the
.Nm BSD-Licence
for the
.Mx
base system.
.Sh DESCRIPTION
This document provides a list of all advertising clauses
required to be reproduced when distributing
.Mx ,
as well as the terms and conditions covering the operating system.
.Sh MIROS PROJECT
See
.Pa /usr/share/doc/legal/LICENCE .
.Sh UCB
.so lbsd-ucb.mdoc
.Sh IEEE
.so lbsd-ieee.mdoc
.Sh ANSI
.so lbsd-ansi.mdoc
.Sh DARPA
.so lbsd-darpa.mdoc
.Sh SCO
.so lbsd-caldera.mdoc
.Sh TRADEMARKS
All trademarks are properties of their respective holders.
Particularily, the UNIX\(rg trademark changed its owner so
often it's impossible to track it down.
.Sh ADVERTISING CLAUSES
The following attribution clauses are required to be reproduced
when advertising for
.Mx .
.Bl -bullet -compact
.so lbsd-adv.mdoc
.El
.Pp
.Mx
contains contributed material from GNU and XFree86, which require
these additional advertising clauses to be reproduced:
.Bl -bullet -compact
.so lbsd-adc.mdoc
.El
.Pp
All trademarks and registered trademarks are properties of their
respective owners.
.Sh AUTHORS
This manual was carefully put together for
.Mx 8
by
.An Thorsten Do mirabile Dc Glaser Aq tg@MirBSD.org .
.Sh FILES
.Bl -tag -width 8n -compact
.It Pa /usr/share/doc/legal/1stREAD
Overview over all legal documents.
.It Pa /usr/share/doc/legal/LICENCE
The terms covering the whole of
.Mx
base.
.It Pa /usr/share/misc/licence.template
Licence preferred to be used for code newly added to
.Mx .
.El
.Sh SEE ALSO
.Pa http://mirbsd.mirsolutions.de/?about
.Sh BUGS
Although collected carefully, there might be some.
Please report them if you think you have discovered a bug.
.Pp
The list of advertising clauses is complete except for the kernel source.
