.\" $MirOS: src/lib/libmbfun/ambstowcs.3,v 1.2 2018/10/07 00:55:51 tg Exp $
.\"-
.\" Copyright (c) 2008, 2009, 2018
.\"	Thorsten Glaser <tg@mirbsd.org>
.\"
.\" Provided that these terms and disclaimer and all copyright notices
.\" are retained or reproduced in an accompanying document, permission
.\" is granted to deal in this work without restriction, including un-
.\" limited rights to use, publicly perform, distribute, sell, modify,
.\" merge, give away, or sublicence.
.\"
.\" This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
.\" the utmost extent permitted by applicable law, neither express nor
.\" implied; without malicious intent or gross negligence. In no event
.\" may a licensor, author or contributor be held liable for indirect,
.\" direct, other damage, loss, or other issues arising in any way out
.\" of dealing in the work, even if advised of the possibility of such
.\" damage or existence of a defect, except proven that it results out
.\" of said person's immediate fault when using the work as intended.
.\"-
.Dd $Mdocdate: October 7 2018 $
.Dt AMBSTOWCS 3
.Os
.Sh NAME
.Nm ambsntowcs ,
.Nm ambstowcs ,
.Nm awcsntombs ,
.Nm awcstombs
.Nd convert between multibyte and wide strings with allocation
.Sh SYNOPSIS
.In mbfun.h
.Ft "wchar_t *"
.Fn ambsntowcs "const char *s" "size_t n"
.Ft "wchar_t *"
.Fn ambstowcs "const char *s"
.Ft "char *"
.Fn awcsntombs "const wchar_t *s" "size_t n"
.Ft "char *"
.Fn awcstombs "const wchar_t *s"
.Sh DESCRIPTION
The
.Fn ambsntowcs
and
.Fn ambstowcs
functions convert the NUL-terminated multibyte
.Pq MirOS OPTU\-8 encoded
string
.Fa s
into a wide
.Pq MirOS OPTU\-16 encoded
string, requesting just enough storage via
.Xr calloc 3
from the system to store the result, including a terminating WNUL character.
The
.Fn awcsntombs
and
.Fn awcstombs
functions convert the WNUL-terminated wide
.Pq MirOS OPTU\-16 encoded
string
.Fa s
into a multibyte
.Pq MirOS OPTU\-8 encoded
string, requesting just enough storage via
.Xr malloc 3
from the system to store the result, including a terminating NUL byte.
The
.Fn ambsntowcs
and
.Fn awcsntombs
functions convert at most
.Fa n
characters; the
.Fn ambstowcs
and
.Fn awcstombs
functions convert the entire string.
.Sh RETURN VALUES
.Fn ambsntowcs
and
.Fn ambstowcs
return the newly allocated wide character string.
.Fn awcsntombs
and
.Fn awcstombs
return the newly allocated multibyte character string.
Failure to allocate enough memory will terminate the calling program,
.Nm xmalloc
style, with errorlevel 1 and an appropriate error message.
Passing a
.Dv NULL
pointer results in undefined behaviour.
.Sh SEE ALSO
.Xr mbsrtowcs 3 ,
.Xr wcsrtombs 3
.Sh HISTORY
The
.Nm ambsntowcs ,
.Nm ambstowcs ,
.Nm awcsntombs ,
and
.Nm awcstombs
functions are
.Mx BSD
extensions and first appeared in
.Mx 11 .
.Sh AUTHORS
.An Thorsten Glaser Aq tg@mirbsd.de
wrote the entire internationalisation implementation in
.Mx .
He is also the steward for the OPTU encoding.
