.\" $MirOS: src/usr.sbin/getextent_cd9660/getextent_cd9660.1,v 1.1 2008/08/05 22:36:06 tg Exp $
.\"-
.\" Copyright (c) 2008
.\"	Thorsten Glaser <tg@mirbsd.org>
.\"
.\" Provided that these terms and disclaimer and all copyright notices
.\" are retained or reproduced in an accompanying document, permission
.\" is granted to deal in this work without restriction, including un-
.\" limited rights to use, publicly perform, distribute, sell, modify,
.\" merge, give away, or sublicence.
.\"
.\" This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
.\" the utmost extent permitted by applicable law, neither express nor
.\" implied; without malicious intent or gross negligence. In no event
.\" may a licensor, author or contributor be held liable for indirect,
.\" direct, other damage, loss, or other issues arising in any way out
.\" of dealing in the work, even if advised of the possibility of such
.\" damage or existence of a defect, except proven that it results out
.\" of said person's immediate fault when using the work as intended.
.\"-
.Dd $Mdocdate: August 5 2008 $
.Dt GETEXTENT_CD9660 1
.Os
.Sh NAME
.Nm getextent_cd9660
.Nd get directory information on ISO 9660 filesystems
.Sh SYNOPSIS
.Nm
.Op Fl bens
.Fl f Ar fs.iso
.Op Ar
.Sh DESCRIPTION
The
.Nm
utility prints out a list of files in the root directory of the
.Ar fs.iso
ISO 9660 image.
If
.Ar files
are specified, only entries with these names (exact match, no
wildcards) are considered.
.Pp
The options are as follows:
.Bl -tag -width xxxxxxxxx
.It Fl b
Show a column with the start block number of the file.
.It Fl e
Show a column with the end block number of the file.
.It Fl f Ar fs.iso
Specify which filesystem image (or device) to operate on.
.It Fl n
Show a column with the name of the file.
.It Fl s
Show a column with the size of the file.
.El
.Pp
The
.Fl bens
flags determine the format of the output.
Column order is: start_block end_block size name.
If none of these flags are specified, the default is
.Fl ben .
.Pp
The special files
.Pa $BootCatalog$
and
.Pa $BootImage$
are a somewhat crude attempt at parsing the El Torito volume descriptor
and boot catalogue to find out the default boot image.
.Sh HISTORY
A
.Nm
utility appeared in
.Mx 11
to get rid of J?rg Schilling's mkisofs tools.
.Sh AUTHORS
.Nm
was written by
.An Thorsten Glaser Aq tg@mirbsd.de .
