# $MirOS: ports/devel/p5-YAML-Syck/Makefile,v 1.1 2007/09/15 22:23:27 bsiegert Exp $

COMMENT=		fast, lightweight YAML loader and dumper
DISTNAME=		YAML-Syck-0.97
DASH_VER=		1
PKGNAME=		p5-${DISTNAME}-${DASH_VER}
CATEGORIES=		devel perl5
MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=YAML/}
HOMEPAGE=		http://search.cpan.org/~audreyt/${DISTNAME}/

# MIT licence
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	perl

.include <bsd.port.mk>
