  <li><a href="/main.htm">Main</a><ul class="lv2">
	<li><a href="/wlog-9.htm">Weblog</a> for #9</li>
	<li><a href="/?older">Old News</a> &amp; Log</li>
  </ul></li>
  <li><a href="/?about">About</a></li>
  <li><a href="/mksh.htm">mksh</a></li>
<!-- these are not in a usable state
  <li><a href="/?ports">MirPorts</a></li>
  <li><a href="/?docs">Documentation</a></li>
  <li><a href="/?faq">FAQ</a></li>
-->
  <li><a href="/getting.htm">Download</a><!-- <ul class="lv2">
	<li><a href="/?mirrors">Mirrors</a></li>
  </ul>--></li>
  <li><a href="/?irc">IRC</a></li>
  <li><a href="/projects.htm">Project Ideas</a></li>
  <li><a href="/?danke">Donate</a></li>
  <li><a href="/cman/">Manpages</a></li>
  <li><a href="/?style">StyleSelect</a></li>
