  <li><a href="/main.htm">Main</a><ul class="lv2">
	<li><a href="/wlog-9.htm">Weblog</a> for #9</li>
	<li><a href="/?older">Old News</a> &amp; Log</li>
  </ul></li>
  <li><a href="/?about">About</a></li>
<!-- these are not in a usable state
  <li><a href="/?docs">Documentation</a></li>
  <li><a href="/?faq">FAQ</a></li>
-->
  <li class="spacer"><a href="/getting.htm">Download</a><!-- <ul class="lv2">
	<li><a href="/?mirrors">Mirrors</a></li>
  </ul>--></li>
  <li><a href="/irc.htm">IRC</a></li>
  <li><a href="/projects.htm">Project Ideas</a></li>
  <li><a href="/danke.htm">Donate</a></li>
  <li>Manpages<ul class="lv2">
    <li><a href="/htman/i386/">i386</a></li>
    <li><a href="/htman/sparc/">sparc</a></li>
  </ul></li>
  <li><a href="/ports.htm">MirPorts</a> Framework</li>
  <li>Subprojects<ul class="lv2">
	<li><a href="/jupp.htm">jupp</a> Editor</li>
	<li><a href="/mksh.htm">mksh</a> Shell</li>
  </ul></li>
