# $MirOS$

COMMENT=		@COMMENT@
DISTNAME=		@DISTNAME@
PKGNAME=		p5-${DISTNAME}-${DASH_VER}
CATEGORIES=		@CATEGORY@ perl5
MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=../../authors/id/@PATH@}

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	perl

@DECLS@

.include <bsd.port.mk>
