#!/bin/sh
# $MirOS$
#
# Pre/post-installation setup of CUPS

PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}


do_notice_etc_install()
{
    echo
    echo "+---------------"
    echo "| You appear to already have CUPS configuration files in"
    echo "| ${SYSCONFDIR}/cups."
    echo "|"
    echo "| The configuration files have been preserved. If you want to"
    echo "| start from the default setup, you should perform these steps"
    echo "| as root:"
    echo "|"
    echo "|       rm -rf ${SYSCONFDIR}/cups"
    echo "|       cp -Rp ${PREFIX}/share/examples/cups ${SYSCONFDIR}"
}

do_notice_var_install()
{
    echo "|"
    echo "| You appear to already have CUPS spool directories in"
    echo "| /var/spool/cups."
    echo "|"
    echo "| The spool directories have been preserved. If you want to"
    echo "| start from the default setup, you should perform these steps"
    echo "| as root:"
    echo "|"
    echo "|       rm -rf /var/spool/cups"
    echo "|       install -d -m 0700 -o _cups -g _cups /var/spool/cups"
    echo "|       install -d -m 1700 -o _cups -g _cups /var/spool/cups/tmp"
    echo "+---------------"
    echo
}

do_etc_install()
{
    cp -Rp ${PREFIX}/share/examples/cups ${SYSCONFDIR}
    echo
    echo "+---------------"
    echo "| CUPS configuration files have been installed in"
    echo "| ${SYSCONFDIR}/cups."
}

do_var_install()
{ 
    install -d -o _cups -g _cups -m 0700 /var/spool/cups
    install -d -o _cups -g _cups -m 1700 /var/spool/cups/tmp
    echo "|"
    echo "| CUPS spool directories have been installed in"
    echo "| /var/spool/cups."
    echo "+---------------"
    echo
}

# verify proper execution
#
if [ $# -ne 2 ]; then
    echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
    exit 1
fi

# Verify/process the command
#
case $2 in
    PRE-INSTALL)
        ;;
    POST-INSTALL)
        if [ -d ${SYSCONFDIR}/cups ]; then
            do_notice_etc_install
        else
            do_etc_install
        fi

        if [ -d /var/spool/cups ]; then
            do_notice_var_install
        else
            do_var_install
        fi
        mkdir -p /var/log/cups
        ;;
    *)
        echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
        exit 1
        ;;
esac

exit 0
