#!/bin/mksh
# $MirOS: ports/essentials/ca-certificates/mntner/moz2tdb,v 1.2 2012/05/30 18:26:15 tg Exp $
#-
# Copyright (c) 2009, 2012, 2016
#	mirabilos <m@mirbsd.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un-
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person's immediate fault when using the work as intended.

[[ $(openssl version) = 'OpenSSL 1'* ]] && exit 1

[[ -s certdata.txt ]] || exit 1
[[ -d tdb/. ]] && exit 1
mkdir tdb
[[ -d tdb/. ]] || exit 1

cd tdb
s=0
f=0
while IFS= read -r line; do
	case $s {
	(0)
		[[ $line = "CKA_VALUE MULTILINE_OCTAL" ]] || continue
		s=1
		f=0
		c=
		;;
	(1)
		if [[ $line = END ]]; then
			s=2
			h=$(printf "$c" | openssl x509 -inform der -noout -hash)
		else
			c=$c$line
		fi
		;;
	(2)
		case $line {
		(CKA_TRUST_STEP_UP_APPROVED*)
			(( f )) && s=0
			;;
		(CKA_CERTIFICATE_TYPE*)
			s=0
			;;
		(@(CKA_TRUST_SERVER_AUTH|CKA_TRUST_EMAIL_PROTECTION|CKA_TRUST_CODE_SIGNING)*)
			print -r -- "$line" | sed \
			    -e 's/CKT_NSS_NOT_TRUSTED/CKT_NETSCAPE_VALID/g' \
			    -e 's/CKT_NSS_MUST_VERIFY_TRUST/CKT_NETSCAPE_TRUST_UNKNOWN/g' \
			    -e 's/\(CK[OT]_\)NSS_/\1NETSCAPE_/g' >>$h
			f=1
			;;
		}
		;;
	}
done <../certdata.txt
