#!/bin/mksh
rcsid='$MirOS: contrib/hosted/tg/deb/ca-bundle/debian/ca-bundle.links.in,v 1.2 2011/04/24 17:08:16 tg Exp $'
#-
# Run this on Debian/sid to generate a list of symlinks
# for OpenSSL 1.0.0+ compatibility of hashed directory.

[[ $(openssl version) = 'OpenSSL 1'* ]] || exit 1

# XXX pem/* must already have normalised names
[[ -d pem/. ]] || exit 1
[[ -d lnk/. ]] && exit 1
rm -f certhash.lnk
[[ -e certhash.lnk ]] && exit 1
mkdir lnk
[[ -d lnk/. ]] || exit 1

cp pem/* lnk/
cd lnk
set -A files -- *.*
set -A links

for file in "${files[@]}"; do
	if [[ $file != [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f].+([0-9]) ]]; then
		print -ru2 "Invalid file '$file'"
		exit 1
	fi
	fbase=${file%.*}
	hash0=$(openssl x509 -subject_hash_old -noout -in $file)
	hash1=$(openssl x509 -subject_hash -noout -in $file)
	if [[ $file != "${hash0}."+([0-9]) ]]; then
		print -ru2 "Invalid hash $file expected $hash0"
		exit 1
	fi
	print -ru2 "Processing $file → $hash1"
	num=0
	while [[ -e $hash1.$num ]]; do
		let num++
	done
	ln -s $file $hash1.$num
	print $file $hash1.$num >>OUT
done

cd ..
mv -f lnk/OUT certhash.lnk
rm -rf lnk
