# $OpenBSD: Makefile,v 1.1.1.1 2004/04/11 11:52:43 sturm Exp $

COMMENT=			Abstract class wrapper for Autoloader

DISTNAME=	Class-MethodMapper-1.0
PKGNAME=	p5-${DISTNAME}-0
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=Class/}


# Same as Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE= perl

.include <bsd.port.mk>
