#!/bin/mksh
# $MirOS: src/usr.bin/oldroff/nrcon/nrcon,v 1.2 2005/04/16 03:22:01 tg Exp $
#-
# Copyright (c) 2003, 2004, 2005
#	Thorsten "mirabile" Glaser <tg@66h.42h.de>
#
# Licensee is hereby permitted to deal in this work without restric-
# tion, including unlimited rights to use, publicly perform, modify,
# merge, distribute, sell, give away or sublicence, provided all co-
# pyright notices above, these terms and the disclaimer are retained
# in all redistributions or reproduced in accompanying documentation
# or other materials provided with binary redistributions.
#
# All advertising materials mentioning features or use of this soft-
# ware must display the following acknowledgement:
#	This product includes material provided by Thorsten Glaser.
#
# Licensor hereby provides this work "AS IS" and WITHOUT WARRANTY of
# any kind, expressed or implied, to the maximum extent permitted by
# applicable law, but with the warranty of being written without ma-
# licious intent or gross negligence; in no event shall licensor, an
# author or contributor be held liable for any damage, direct, indi-
# rect or other, however caused, arising in any way out of the usage
# of this work, even if advised of the possibility of such damage.
#-
# Feed everything (stdin, parametres) to nroff -Tcol (though that could
# be overridden...) and its output to col(1).

if [[ $1 = -8 || $1 = -e ]]; then
	if [[ $1 = -8 ]]; then
		c=
	else
		c=-7
	fi
	shift
	F=
	P=
	while [[ $# -gt 0 ]]; do
		if [[ $1 = @(-)* ]]; then
			P="$P $1"
		else
			F="$F $1"
		fi
		shift
	done
	# no useless use of cat!
	cat $F \
	    | /usr/libexec/nr8pre $c \
	    | /usr/bin/nroff -Tcol $P | /usr/bin/col \
	    | /usr/libexec/nr8post
else
	/usr/bin/nroff -Tcol "$@" | /usr/bin/col
fi
