.\" $MirOS: src/usr.bin/oldroff/nrcon/nrcon.1,v 1.5 2009/11/22 17:10:42 tg Exp $
.\"-
.\" Copyright (c) 2007, 2009, 2016
.\"	mirabilos <m@mirbsd.org>
.\"
.\" Provided that these terms and disclaimer and all copyright notices
.\" are retained or reproduced in an accompanying document, permission
.\" is granted to deal in this work without restriction, including un-
.\" limited rights to use, publicly perform, distribute, sell, modify,
.\" merge, give away, or sublicence.
.\"
.\" Advertising materials mentioning features or use of this work must
.\" display the following acknowledgement:
.\"	This product includes material provided by Thorsten Glaser.
.\"
.\" This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
.\" the utmost extent permitted by applicable law, neither express nor
.\" implied; without malicious intent or gross negligence. In no event
.\" may a licensor, author or contributor be held liable for indirect,
.\" direct, other damage, loss, or other issues arising in any way out
.\" of dealing in the work, even if advised of the possibility of such
.\" damage or existence of a defect, except proven that it results out
.\" of said person's immediate fault when using the work as intended.
.\"-
.\" Try to make GNU groff and AT&T nroff more compatible
.\" * ` generates ‘ in gnroff, so use \`
.\" * ' generates ’ in gnroff, \' generates ´, so use \*(aq
.\" * - generates ‐ in gnroff, \- generates −, so .tr it to -
.\"   thus use - for hyphens and \- for minus signs and option dashes
.\" * ~ is size-reduced and placed atop in groff, so use \*(TI
.\" * ^ is size-reduced and placed atop in groff, so use \*(ha
.\" * \(en does not work in nroff, so use \*(en
.\" * <>| are problematic, so redefine and use \*(Lt\*(Gt\*(Ba
.\" Also make sure to use \& *before* a punctuation char that is to not
.\" be interpreted as punctuation, and especially with two-letter words
.\" but also (after) a period that does not end a sentence (“e.g.\&”).
.\" The section after the "doc" macropackage has been loaded contains
.\" additional code to convene between the UCB mdoc macropackage (and
.\" its variant as BSD mdoc in groff) and the GNU mdoc macropackage.
.\"
.ie \n(.g \{\
.	if \*[.T]ascii .tr \-\N'45'
.	if \*[.T]latin1 .tr \-\N'45'
.	if \*[.T]utf8 .tr \-\N'45'
.	ds <= \[<=]
.	ds >= \[>=]
.	ds Rq \[rq]
.	ds Lq \[lq]
.	ds sL \(aq
.	ds sR \(aq
.	if \*[.T]utf8 .ds sL `
.	if \*[.T]ps .ds sL `
.	if \*[.T]utf8 .ds sR '
.	if \*[.T]ps .ds sR '
.	ds aq \(aq
.	ds TI \(ti
.	ds ha \(ha
.	ds en \(en
.\}
.el \{\
.	ds aq '
.	ds TI ~
.	ds ha ^
.	ds en \(em
.\}
.\"
.\" Implement .Dd with the Mdocdate RCS keyword
.\"
.rn Dd xD
.de Dd
.ie \\$1$Mdocdate: \{\
.	xD \\$2 \\$3, \\$4
.\}
.el .xD \\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8
..
.\"
.\" .Dd must come before definition of .Mx, because when called
.\" with -mandoc, it might implement .Mx itself, but we want to
.\" use our own definition. And .Dd must come *first*, always.
.\"
.Dd $Mdocdate: November 22 2009 $
.\"
.\" Check which macro package we use, and do other -mdoc setup.
.\"
.ie \n(.g \{\
.	if \*[.T]utf8 .tr \[la]\*(Lt
.	if \*[.T]utf8 .tr \[ra]\*(Gt
.	ie d volume-ds-1 .ds tT gnu
.	el .ds tT bsd
.\}
.el .ds tT ucb
.\"
.\" Implement .Mx (MirBSD)
.\"
.ie "\*(tT"gnu" \{\
.	eo
.	de Mx
.	nr curr-font \n[.f]
.	nr curr-size \n[.ps]
.	ds str-Mx \f[\n[curr-font]]\s[\n[curr-size]u]
.	ds str-Mx1 \*[Tn-font-size]\%MirOS\*[str-Mx]
.	if !\n[arg-limit] \
.	if \n[.$] \{\
.	ds macro-name Mx
.	parse-args \$@
.	\}
.	if (\n[arg-limit] > \n[arg-ptr]) \{\
.	nr arg-ptr +1
.	ie (\n[type\n[arg-ptr]] == 2) \
.	as str-Mx1 \~\*[arg\n[arg-ptr]]
.	el \
.	nr arg-ptr -1
.	\}
.	ds arg\n[arg-ptr] "\*[str-Mx1]
.	nr type\n[arg-ptr] 2
.	ds space\n[arg-ptr] "\*[space]
.	nr num-args (\n[arg-limit] - \n[arg-ptr])
.	nr arg-limit \n[arg-ptr]
.	if \n[num-args] \
.	parse-space-vector
.	print-recursive
..
.	ec
.	ds sP \s0
.	ds tN \*[Tn-font-size]
.\}
.el \{\
.	de Mx
.	nr cF \\n(.f
.	nr cZ \\n(.s
.	ds aa \&\f\\n(cF\s\\n(cZ
.	if \\n(aC==0 \{\
.		ie \\n(.$==0 \&MirOS\\*(aa
.		el .aV \\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8 \\$9
.	\}
.	if \\n(aC>\\n(aP \{\
.		nr aP \\n(aP+1
.		ie \\n(C\\n(aP==2 \{\
.			as b1 \&MirOS\ #\&\\*(A\\n(aP\\*(aa
.			ie \\n(aC>\\n(aP \{\
.				nr aP \\n(aP+1
.				nR
.			\}
.			el .aZ
.		\}
.		el \{\
.			as b1 \&MirOS\\*(aa
.			nR
.		\}
.	\}
..
.\}
.\"-
.Dt NRCON 1
.Os
.Sh NAME
.Nm nrcon
.Nd text formatting for the console
.Sh SYNOPSIS
.Nm nrcon
.Op option
.Ar ...
.Op Ar
.Sh DESCRIPTION
The
.Nm
utility formats text in the named
.Ar files ,
or from standard input, if none present,
for the BSD console.
Input is first pre-processed (see below), then passed through
.Xr nroff 1 ,
then post-processed and passed through
.Xr col 1
with the
.Fl x
option, in UTF-8 mode.
The full capabilities of
.Nm nroff
are described in the
.%T "Nroff/Troff User's Manual" .
.Pp
A single dash
.Pq Fl
is taken to be a file name corresponding to the standard input.
.Pp
The
.Nm
utility supports all standard options of
.Nm nroff
as well as several options of its own.
Both are listed below, where
.Nm
options are marked specially.
As long as they appear before any
.Ar file
argument, the following options are recognised:
.Bl -tag -width indent
.It Cm + Ns Ar N
Start printing at page
.Ar N .
Default: 1
.It Cm \- Ns Ar N
Stop printing at page
.Ar N .
Default: 10000
.It Fl B
Ignored for compatibility with
.Mx
.Xr nroff 1 .
.It Fl C Ns Ar codeset
Process input in the
.Ar codeset
encoding and write output in the same, using
.Xr iconv 3 .
This option is special to
.Nm nrcon .
Default: utf-8
.It Fl c
Ignored for compatibility with GNU groff.
.It Fl e
Produce equally-spaced words in adjusted lines, using full terminal resolution.
.It Fl h
Use 8-column-wide output tabs during horizontal spacing to speed up output and
reduce character count.
.It Fl i
Read standard input after the input files are exhausted.
.It Fl m Ns Ar name
Prepend the macro file
.Pa /usr/share/tmac/tmac. Ns Ar name
to the input
.Ar files .
.It Fl n Ns Ar N
Number first generated page
.Ar N .
.It Fl o Ns Ar list
Print only pages whose page numbers appear in the comma-separated
.Ar list
of numbers and ranges.
A range
.Ar N\-M
means pages
.Ar N
through
.Ar M ;
an initial
.Ar \-N
means from the beginning to page
.Ar N ;
a final
.Ar N\-
means from
.Ar N
to the end.
.It Fl p Ns Ar N
Ignored for compatibility with
.Xr troff 1 .
.It Fl q
Invoke the simultaneous input-output mode of the
.Ar rd
request.
.It Fl r Ns Ar aN
Set the one-char register
.Ar a
to
.Ar N .
.It Fl S
Ignored for compatibility with
.Xr troff 1 .
.It Fl s Ns Ar N
Stop every
.Ar N
pages to allow paper loading or changing, resume upon receipt of a newline.
.It Fl T Ns Ar name
Prepare output for a specified device.
While
.Xr nroff 1
supports more devices, only the following make sense:
.Pp
.Bl -tag -width xxx -compact
.It Cm col
standard teletype terminal after processing through
.Xr col 1 ;
identical to
.Cm crt
except that reverse-line and half-line capabilities are supported.
Also known as
.Cm ascii ,
.Cm latin1 .
This is the default.
.It Cm crt
standard teletype terminal with ASCII (ISO_646.irv:1991) character set.
Also known as
.Cm lpr ,
.Cm tn300 .
.It Cm ucs
extension of the
.Cm col
terminal driver to produce, with support of the post processor,
output suitable for unicode devices, with improved support for
superscript, subscript, non-ASCII characters, etc.
Also known as
.Cm utf8 .
Not yet implemented.
.El
.It Fl z
Suppress formatted output.
Only produce output to standard error (from
.Ar tm
requests or diagnostics).
.El
.Sh PRE\- AND POST\-PROCESSING
.Ss Changes to the device files
.Ss Unicode encapsulation
.Ss Non-Unicode 8-bit encapsulation
.Ss Extensions to the language
.Ss Extended support with the ucs device
(not yet implemented)
.Ss Character set conversion
(iconv)
.Ss Output considerations
(nroff2html)
.Sh FILES
\&...
