#!/usr/bin/perl
# $MirOS: src/usr.bin/brainfuck/brainfuck,v 1.1.7.1 2005/03/06 16:46:48 tg Exp $
# Public domain by Marko Nippula
# Corrected by Thorsten Glaser

$/=$a;while(<>){tr(+\-<>[].,){}cd;s/./$&;/g;
s/\+|-/P$&$&/g;s/<|>/\$p$&$&/g;y/<>[]/-+{}/;
s/{/while(P){/g;s/\./print chr P/g;s/,/P=ord
getc/g;s/P/\$m[\$p]/g;eval$_;print$@if$@}
