.\" $MirOS: src/usr.bin/brainfuck/brainfuck.1,v 1.2 2005/12/17 05:46:27 tg Exp $
.\"-
.\" Copyright (c) 2003, 2004
.\"	Thorsten "mirabile" Glaser <tg@66h.42h.de>
.\"
.\" Licensee is hereby permitted to deal in this work without restric-
.\" tion, including unlimited rights to use, publicly perform, modify,
.\" merge, distribute, sell, give away or sublicence, provided all co-
.\" pyright notices above, these terms and the disclaimer are retained
.\" in all redistributions or reproduced in accompanying documentation
.\" or other materials provided with binary redistributions.
.\"
.\" All advertising materials mentioning features or use of this soft-
.\" ware must display the following acknowledgement:
.\"	This product includes material provided by Thorsten Glaser.
.\"
.\" Licensor offers the work "AS IS" and WITHOUT WARRANTY of any kind,
.\" express, or implied, to the maximum extent permitted by applicable
.\" law, without malicious intent or gross negligence; in no event may
.\" licensor, an author or contributor be held liable for any indirect
.\" or other damage, or direct damage except proven a consequence of a
.\" direct error of said person and intended use of this work, loss or
.\" other issues arising in any way out of its use, even if advised of
.\" the possibility of such damage or existence of a nontrivial bug.
.\"-
.Dd November 3, 2002
.Dt BRAINFUCK 1
.Os
.Sh NAME
.Nm brainfuck
.Nd perl brainfuck interpreter
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility interprets its standard input as a brainfuck script.
Processing will start after EOF.
If you started
.Nm
interactively, hit Ctrl-D on a new line to start.
.Pp
.Sh THE LANGUAGE
brainfuck is a simple enough language to include the entire official language
describtion in this man page.
The following is from the original brainfuck distribution by Urban Mueller
\f(CW<umueller@amiga.physik.unizh.ch\fR>, who also invented the language:
.Pp
The language \fIbrainfuck\fR knows the following commands:
.Pp
.Bd -literal -offset indent
\& Cmd  Effect                                    Equivalent in C
\& ---  ------                                    ---------------
\& +    Increases element under pointer           array[p]++;
\& -    Decrases element under pointer            array[p]--;
\& >    Increases pointer                         p++;
\& <    Decreases pointer                         p--;
\& [    Starts loop, counter under pointer        while(array[p]) {
\& ]    Indicates end of loop                     }
\& .    Outputs ASCII code under pointer          putchar(array[p]);
\& ,    Reads char and stores ASCII under ptr     array[p]=getchar();
.Ed
.Pp
All other characters are ignored.
.Pp
The array elements and p are being initialized to zero at the beginning.
Now while this seems to be a pretty useless language, it can be proven
that it can compute every solvable mathematical problem (if we ignore
the array size limit and the executable size limit).
.Sh HISTORY
.Nm
first appeared in
.Mx 1 .
.Sh AUTHORS
.Bl -inset
.It Em Urban Mueller
designed the language.
.It Em Marko Nippula
wrote this interpreter.
.It The Em Chaos Computer Club Cologne
gave some hints for the man page.
.It Em Thorsten Glaser
wrote this man page and put things together for
.Mx .
.El
