#!/bin/mksh
# $MirOS$
# $Xorg: Xsetup_0,v 1.3 2000/08/17 19:54:17 cpqbld Exp $
#xsetroot -solid '#cccccc'
if [[ $DISPLAY = ":0" || $DISPLAY = ":0.0" ]]; then
xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail
fi
xset s off

#sxpm OpenBSD.xpm &
