#!/bin/mksh
# $MirSecuCron$
# $MirOS: X11/xc/programs/xdm/config/Xsetup_0,v 1.6 2008/11/06 23:02:41 tg Exp $
# $Xorg: Xsetup_0,v 1.3 2000/08/17 19:54:17 cpqbld Exp $
#xsetroot -solid '#cccccc'
#[[ $DISPLAY = ":0" || $DISPLAY = ":0.0" ]] && xconsole \
#    -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail
xset s off

#sxpm OpenBSD.xpm &
