#!/bin/ksh
# $MirOS$
#
# pre-/post-installation setup for bsdgames

# exit on errors, use a sane path and install prefix
#
set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}

# verify proper execution
#
if [ $# -ne 2 ]; then
	print -u2 "usage: $0 distname { PRE-INSTALL | POST-INSTALL }"
	exit 1
fi

# Verify/process the command
#
case $2 in
PRE-INSTALL)
	: nothing to pre-install for this port
	;;
POST-INSTALL)
	if [[ -d /var/games ]]; then
		print "Warning: check /var/games with the $1 package's"
		print "contents in $PREFIX/share/games/_tarball.dist"
	else
		cd /var && tar xphf $PREFIX/share/games/_tarball.dist
	fi
	;;
*)
	print -u2 "usage: $0 distname { PRE-INSTALL | POST-INSTALL }"
	exit 1
	;;
esac

exit 0
