.\" Copyright (c) 1998-2000, 2008 Sendmail, Inc. and its suppliers.
.\"	 All rights reserved.
.\"
.\" By using this file, you agree to the terms and conditions set
.\" forth in the LICENSE file which can be found at the top level of
.\" the sendmail distribution.
.\"
.\"
.\"	$MirOS: src/gnu/usr.sbin/sendmail/praliases/praliases.8,v 1.5 2011/07/02 20:52:52 tg Exp $
.\"	$OpenBSD: praliases.1,v 1.9 2011/05/17 15:54:23 millert Exp $
.\"	$Id$
.\"
.Dd $Mdocdate: July 2 2011 $
.Dt PRALIASES 8
.Os
.Sh NAME
.Nm praliases
.Nd display system mail aliases
.Sh SYNOPSIS
.Nm praliases
.Op Fl C Ar file
.Op Fl f Ar file
.Op key ...
.Sh DESCRIPTION
The
.Nm praliases
utility displays the current system aliases,
one per line, in no particular order.
The special internal @:@ alias will be displayed if present.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl C Ar file
Read the specified sendmail configuration
.Ar file
instead of the default
.Nm sendmail
configuration file.
.It Fl f Ar file
Read the specified
.Ar file
instead of the configured
.Nm sendmail
system aliases file(s).
.El
.Pp
If one or more keys are specified on the command line,
only entries which match those keys are displayed.
.Sh FILES
.Bl -tag -width /etc/mail/sendmail.cf -compact
.It Pa /etc/mail/sendmail.cf
The default
.Nm sendmail
configuration file.
.It Pa /etc/mail/aliases
The default
.Nm sendmail
system aliases file.
.It Pa /etc/mail/aliases.db
The database version of the
.Pa /etc/mail/aliases
file.
.El
.Sh EXIT STATUS
.Ex -std praliases
.Sh SEE ALSO
.Xr mailq 8 ,
.Xr sendmail 8
