.\" $MirOS: ports/infrastructure/pkgtools/rtfm/cvs-distfiles.7,v 1.6 2009/11/22 18:23:35 tg Exp $
.\"-
.\" Copyright (c) 2007, 2008, 2009, 2010, 2016 mirabilos
.\" Copyright (c) 2007 Benny Siegert
.\"
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE DEVELOPERS ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE DEVELOPERS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"-
.\" Try to make GNU groff and AT&T nroff more compatible
.\" * ` generates ‘ in gnroff, so use \`
.\" * ' generates ’ in gnroff, \' generates ´, so use \*(aq
.\" * - generates ‐ in gnroff, \- generates −, so .tr it to -
.\"   thus use - for hyphens and \- for minus signs and option dashes
.\" * ~ is size-reduced and placed atop in groff, so use \*(TI
.\" * ^ is size-reduced and placed atop in groff, so use \*(ha
.\" * \(en does not work in nroff, so use \*(en
.\" * <>| are problematic, so redefine and use \*(Lt\*(Gt\*(Ba
.\" Also make sure to use \& *before* a punctuation char that is to not
.\" be interpreted as punctuation, and especially with two-letter words
.\" but also (after) a period that does not end a sentence (“e.g.\&”).
.\" The section after the "doc" macropackage has been loaded contains
.\" additional code to convene between the UCB mdoc macropackage (and
.\" its variant as BSD mdoc in groff) and the GNU mdoc macropackage.
.\"
.ie \n(.g \{\
.	if \*[.T]ascii .tr \-\N'45'
.	if \*[.T]latin1 .tr \-\N'45'
.	if \*[.T]utf8 .tr \-\N'45'
.	ds <= \[<=]
.	ds >= \[>=]
.	ds Rq \[rq]
.	ds Lq \[lq]
.	ds sL \(aq
.	ds sR \(aq
.	if \*[.T]utf8 .ds sL `
.	if \*[.T]ps .ds sL `
.	if \*[.T]utf8 .ds sR '
.	if \*[.T]ps .ds sR '
.	ds aq \(aq
.	ds TI \(ti
.	ds ha \(ha
.	ds en \(en
.\}
.el \{\
.	ds aq '
.	ds TI ~
.	ds ha ^
.	ds en \(em
.\}
.\"
.\" Implement .Dd with the Mdocdate RCS keyword
.\"
.rn Dd xD
.de Dd
.ie \\$1$Mdocdate: \{\
.	xD \\$2 \\$3, \\$4
.\}
.el .xD \\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8
..
.\"
.\" .Dd must come before definition of .Mx, because when called
.\" with -mandoc, it might implement .Mx itself, but we want to
.\" use our own definition. And .Dd must come *first*, always.
.\"
.Dd $Mdocdate: November 22 2009 $
.\"
.\" Check which macro package we use, and do other -mdoc setup.
.\"
.ie \n(.g \{\
.	if \*[.T]utf8 .tr \[la]\*(Lt
.	if \*[.T]utf8 .tr \[ra]\*(Gt
.	ie d volume-ds-1 .ds tT gnu
.	el .ds tT bsd
.\}
.el .ds tT ucb
.\"
.\" Implement .Mx (MirBSD)
.\"
.ie "\*(tT"gnu" \{\
.	eo
.	de Mx
.	nr curr-font \n[.f]
.	nr curr-size \n[.ps]
.	ds str-Mx \f[\n[curr-font]]\s[\n[curr-size]u]
.	ds str-Mx1 \*[Tn-font-size]\%MirOS\*[str-Mx]
.	if !\n[arg-limit] \
.	if \n[.$] \{\
.	ds macro-name Mx
.	parse-args \$@
.	\}
.	if (\n[arg-limit] > \n[arg-ptr]) \{\
.	nr arg-ptr +1
.	ie (\n[type\n[arg-ptr]] == 2) \
.	as str-Mx1 \~\*[arg\n[arg-ptr]]
.	el \
.	nr arg-ptr -1
.	\}
.	ds arg\n[arg-ptr] "\*[str-Mx1]
.	nr type\n[arg-ptr] 2
.	ds space\n[arg-ptr] "\*[space]
.	nr num-args (\n[arg-limit] - \n[arg-ptr])
.	nr arg-limit \n[arg-ptr]
.	if \n[num-args] \
.	parse-space-vector
.	print-recursive
..
.	ec
.	ds sP \s0
.	ds tN \*[Tn-font-size]
.\}
.el \{\
.	de Mx
.	nr cF \\n(.f
.	nr cZ \\n(.s
.	ds aa \&\f\\n(cF\s\\n(cZ
.	if \\n(aC==0 \{\
.		ie \\n(.$==0 \&MirOS\\*(aa
.		el .aV \\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8 \\$9
.	\}
.	if \\n(aC>\\n(aP \{\
.		nr aP \\n(aP+1
.		ie \\n(C\\n(aP==2 \{\
.			as b1 \&MirOS\ #\&\\*(A\\n(aP\\*(aa
.			ie \\n(aC>\\n(aP \{\
.				nr aP \\n(aP+1
.				nR
.			\}
.			el .aZ
.		\}
.		el \{\
.			as b1 \&MirOS\\*(aa
.			nR
.		\}
.	\}
..
.\}
.\"-
.Dt CVS\-DISTFILES 7
.Os
.Sh NAME
.Nm cvs\-distfiles
.Nd fetch distfiles for MirPorts via CVS
.Sh SYNOPSIS
.Fd CVS_DISTREPO=:ext:cvs.example.com:/cvs
.Fd CVS_DISTDATE=2007\-09\-22
.Fd CVS_DISTTAGS=1_0_release
.Fd CVS_DISTMODS=src
.Pp
.Fd SVN_DISTPATH=https://svn.example.com/projects/foo/trunk
.Fd SVN_DISTFILE=foo\-svn
.Fd SVN_DISTREV=123
.Fd SVN_DISTDIR=foo
.Sh DESCRIPTION
This document describes how the
.Dq fetch distfile via CVS
.Pq or Subversion
method in MirPorts operates.
.Ss The problem
Often, software is not distributed as nicely as we would like
to have it \*(en in a versioned tarball, gzip'd or compress'd.
Sometimes, tarballs are not versioned, broken, or just too old.
But almost universally, source code is available via a revision control
system \*(en such as CVS or Subversion.
.Pp
This manual documents a method to fetch sources via CVS, while
retaining control over correct checksums etc.
.Ss From a user's point of view: CVS
To enable the _CVS_DISTF fetch method, you have to put a few
liness into your port Makefile.
As usual, learning by an example is
.Dq the way to go
\*(en prominent
examples are the three ports essentials/pkgtools, games/bsdgames,
and devel/libtool.
.Pp
The user interface consists of a few variables you can set:
.Bl -tag -width CVS_DISTREPO
.It Ev CVS_DISTREPO
the value of the \-d option to cvs
.It Ev CVS_DISTDATE
.Pq optional
value of \-D option to cvs checkout
.It Ev CVS_DISTTAGS
.Pq optional
value of \-r option to cvs checkout
.It Ev CVS_DISTMODS
module(s) to check out, separated by space
.It Ev CVS_DISTFILE
.Pq optional
file name prefix
.El
.Pp
Note that if
.Ev CVS_DISTREPO
does not start with a colon,
.Ev CVSREADONLYFS
is set automatically, which is not compatible with the
.Ox
version of anoncvssh.
.Pp
Note: while both CVS_DISTDATE and CVS_DISTTAGS are optional,
it is required to set one of them because HEAD checkouts are
a moving target and thus not supported benefitting checksumming.
.Pp
Setting CVS_DISTREPO${_i} enables _CVS_DISTF operation on a
specific distfile.
${_i} can be empty or a single decimal digit, in case you need more
than one distfile.
.Pp
Once operation has started, _CVS_DISTF${_i} is set to the name
of the file created in ${FULLDISTDIR}
.Po Pa /usr/ports/Distfiles Pc ,
in the following scheme: basename[\-dateext][\-tagext].mcz
.Pp
The basename is CVS_DISTFILE${_i}, or (if unset) CVS_DISTMODS${_i}
with dashes removed.
The dateext (only if CVS_DISTDATE is set) is exactly this, but with
all non-numerical parts removed.
The tagext (if CVS_DISTTAGS) is the tag, with all characters except
digits, letters, dash or underscore removed, and a capital T prepended.
This ensures in almost all cases that _CVS_DISTF is unique.
.Pp
Then, _CVS_FETCH${_i} is set to a command to
.Dq retrieve the file
if it is not yet there.
If any _CVS_DISTF${_i} is set, archivers/mpczar is pulled in
as a fetch dependency automatically.
.Pp
All _CVS_DISTF${_i} are added to _DISTFILES automatically, so there
is no need to do this.
Now you only need to set a PKGNAME (unless the default is fine
to you) and you are done.
.Ss From a user's point of view: Subversion
To enable the _CVS_DISTF fetch method, you have to put a few
liness into your port Makefile.
As usual, learning by an example is
.Dq the way to go
\*(en prominent
example is the port
.Pa sysutils/vesautils .
.Pp
The user interface consists of a few variables you can set:
.Bl -tag -width CVS_DISTREPO
.It Ev SVN_DISTDIR
Name of the directory to check out into (top-level package dir).
Defaults to the basename of
.Ev SVN_DISTREPO .
.It Ev SVN_DISTFILE
Optional file name prefix.
Defaults to the basename of
.Ev SVN_DISTDIR .
.It Ev SVN_DISTREPO
Full path to the repository and subdirectory to check out.
.It Ev SVN_DISTREV
Revision number to check out.
.El
.Pp
Setting SVN_DISTREPO${_i} enables _CVS_DISTF operation on a
specific distfile.
${_i} can be empty or a single decimal digit, in case you need more
than one distfile.
.Pp
Once operation has started, _CVS_DISTF${_i} is set to the name
of the file created in ${FULLDISTDIR}
.Po Pa /usr/ports/Distfiles Pc ,
in the following scheme: basename\-revext.mcz
.Pp
The basename is SVN_DISTFILE${_i}.
The revext is the letter
.Sq r
followed by the numerical SVN_DISTREV revision.
This ensures in almost all cases that _CVS_DISTF is unique.
.Pp
Then, _CVS_FETCH${_i} is set to a command to
.Dq retrieve the file
if it is not yet there.
If any _CVS_DISTF${_i} is set, archivers/mpczar and devel/subversion
are pulled in as fetch dependencies automatically.
.Pp
All _CVS_DISTF${_i} are added to _DISTFILES automatically, so there
is no need to do this.
Now you only need to set a PKGNAME (unless the default is fine
to you) and you are done.
.Ss More interesting possibilities
The infrastructure automatically defaults to setting the (first)
distribution directory:
.D1 WRKDIST?=${WRKDIR}/${CVS_DISTMODS}
.D1 WRKDIST?=${WRKDIR}/${SVN_DISTDIR}
.Pp
If CVS_DISTMODS (without ${_i}) contains more than one module, you
must, consequentially, set WRKDIST yourself (also if you differ from
what the infrastructure thinks is a sensible default).
.Pp
The package name is a requirement which still must be set manually,
unless the new default of ${_CVS_DISTF:R}\-${DASH_VER} (CVS) or
${SVN_DISTFILE}\-${SVN_DISTREV}\-${DASH_VER} (SVN) suits your
port, which will cover 95% of the cases.
FOR CVS, THIS ONLY WORKS IF YOU USE CVS_DISTDATE *AND* *NOT* CVS_DISTTAGS.
Another example is to just set a sensible one yourself, like libtool
does (which pulls from the branch\-1\-5 tag):
.D1 PKGNAME=libtool\-1.5.23a.${CVS_DISTDATE:S!/!!g}\-${DASH_VER}
.Pp
Of course, this needs more maintenance.
.Ss What is working behind the curtains
The infrastructure defines a target ${FULLDISTDIR}/${_CVS_DISTF${_i}}
for each file, which is invoked by 
.Sq Cm mmake Ar fetch
automatically and only if the file does not exist.
However, the target itself also checks for the existence of the
distfile, because in some rare cases all dependencies are invoked.
.Pp
First thing is to execute a
.Sq Cm mmake Ar fetch\-depends
so that mpczar is only built if one of the _CVS_DISTF files is missing,
and subversion is only built if needed as well.
This is done already inside the check for existence.
.Pp
After that, _CVS_FETCH${_i} is invoked on the file and the size is
checked (cloned from a
.Dq normal
fetch process).
.Pp
Checksumming, extracting and so on are processed with no difference;
the .mcz file extension yielded an addition to EXTRACT_CASES, of course.
.Pp
Operation of _CVS_FETCH:
.Pp
The script
.Pa /usr/ports/infrastructure/scripts/mkmcz
is invoked with
a few parameters (target, repo, date, tag, modules) and
then creates said *.mcz file, as follows:
.Pp
Prepare a temporary directory (mkdtemp), change into it, invoke
.Sq Cm cvs Ar checkout ,
or
.Sq Cm svn Ar checkout ,
call mpczar on the current directory with an appropriate set of
.Dq ignore files
.Pq So CVS Sc and So .svn Sc .
.Pp
.Xr mpczar 1
then archives all files (no directories, pipes, devices,
symbolic links, and other funky stuff) in ASCII sort order into an
System V CPIO archive with CRC, using the new \-M option to
.Xr cpio 1 ,
which tells it to
.Dq normalise
the archive: serialise inode numbers,
zero out mtime, ownership and device information, and, for efficiency,
store hard links' file contents only once.
This is safe in the scenario (it would not be safe if one of the files
to pack had a hard link to outside the area which is packed, because
its link count is increased by one then).
The CPIO archive is LZ compressed using the
.Sq mpczar.z
helper (really just
.Xr compress 1
in disguise), which is a mathematical function.
.Pp
This achieves that the same unordered set of input files always
creates the same archive (with the same checksum).
.Sh SEE ALSO
.Xr bsd.port.mk 5 ,
.Xr ports 7 ,
.Xr mpczar 1 .
