.\" $MirOS: contrib/hosted/tg/deb/arngc/arngc.1,v 1.1 2011/08/04 20:39:03 tg Exp $
.\"-
.Dd May 9, 2012
.Dt ARNGC 1
.Os
.Sh NAME
.Nm arngc
.Nd pipe entropy from SSL into rngd
.Sh SYNOPSIS
.Nm
.Ic start
.Op Ar server Op Ar threshold
.Nm
.Ic stop
.Nm
.Ic status
.Sh DESCRIPTION
The
.Nm
utility starts, stops or dumps the status thereof into syslog of
a daemon which opens an SSL network connection, retrieves data
from there, and feeds that into rngd.
The
.Ic server
consists of an IPv4 address in dotted-quad notation followed
by a colon and a port number.
The
.Ic threshold
is a positive number smaller than 4096 (the size of the Linux
2.6 and 3.0 entropy pool).
.Pp
The options
.Ic server
and
.Ic threshold
can also be written in the format
.Dq Ar key No space Ar value No newline
into the configuration file
.Pa /etc/arngc.cfg .
.Sh SEE ALSO
.Xr rngd 8
.Sh AUTHORS
.An Thorsten Glaser Aq tg@mirbsd.org
wrote this script.
.Sh CAVEATS
Since the actual daemons are started in the background,
detached from the session and controlling terminal,
failure to start stunnel or rngd is not reflected in
the exit status of this script.
