# $MirOS: ports/devel/p5-Test-Tester/Makefile,v 1.1 2009/01/02 12:27:26 bsiegert Exp $

COMMENT=		ease testing test modules built with Test::Builder
DISTNAME=		Test-Tester-0.107
PKGNAME=		p5-${DISTNAME}-${DASH_VER}
CATEGORIES=		devel perl5
MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=../../authors/id/F/FD/FDALY/}

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	perl

PKG_ARCH=		*

.include <bsd.port.mk>
