.\"	$MirOS: src/lib/libc/sys/statvfs.2,v 1.1 2007/05/19 22:07:03 tg Exp $
.\"	$NetBSD: statvfs.2,v 1.4 2005/11/04 06:09:20 gendalia Exp $
.\"
.\" Copyright (c) 1989, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)statfs.2	8.5 (Berkeley) 5/24/95
.\"
.Dd May 19, 2007
.Dt STATVFS 2
.Os
.Sh NAME
.Nm statvfs ,
.Nm fstatvfs ,
.Nd get filesystem statistics
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In sys/statvfs.h
.Ft int
.Fn statvfs "const char *path" "struct statvfs *buf"
.Ft int
.Fn fstatvfs "int fd" "struct statvfs *buf"
.Sh DESCRIPTION
.Fn statvfs
return information about a mounted filesystem.
.Fa path
is the path name of any file within the mounted filesystem.
.Fa buf
is a pointer to a
.Nm statvfs
structure.
.Pp
.Fn fstatvfs
return the same information about an open file referenced by descriptor
.Fa fd .
.Sh RETURN VALUES
Upon successful completion, a value of 0 is returned.
Otherwise, \-1 is returned and the global variable
.Va errno
is set to indicate the error.
.Sh ERRORS
.Fn statvfs
and
.Fn fstatvfs
fail for the same reasons
.Fn statfs
and
.Fn statvfs
can fail.
.Sh SEE ALSO
.Xr fstatfs 3 ,
.Xr statfs 3
.Sh HISTORY
The
.Fn statvfs ,
and
.Fn fstatvfs
functions first appeared in
.Mx 10
as a pure user-space implementation.
.Sh AUTHORS
The actual implementation of the user-space functions was taken from
.Nx
libnbcompat.
