# $MirOS: ports/devel/p5-App-CLI/Makefile,v 1.1 2007/10/04 22:01:20 bsiegert Exp $

COMMENT=		select a pager, optionally pipe its output
DISTNAME=		IO-Pager-0.06
PKGNAME=		p5-${DISTNAME}-${DASH_VER}
CATEGORIES=		devel perl5
MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=IO/}
HOMEPAGE=		http://search.cpan.org/~jpierce/${DISTNAME}/

EXTRACT_SUFX=		.tgz

# like Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	perl

.include <bsd.port.mk>
