.\" $MirOS$
.\"-
.\" Copyright (c) 2004
.\"	Thorsten "mirabile" Glaser <tg@66h.42h.de>
.\"
.\" Licensee is hereby permitted to deal in this work without restric-
.\" tion, including unlimited rights to use, publicly perform, modify,
.\" merge, distribute, sell, give away or sublicence, provided all co-
.\" pyright notices above, these terms and the disclaimer are retained
.\" in all redistributions or reproduced in accompanying documentation
.\" or other materials provided with binary redistributions.
.\"
.\" Licensor hereby provides this work "AS IS" and WITHOUT WARRANTY of
.\" any kind, expressed or implied, to the maximum extent permitted by
.\" applicable law, but with the warranty of being written without ma-
.\" licious intent or gross negligence; in no event shall licensor, an
.\" author or contributor be held liable for any damage, direct, indi-
.\" rect or other, however caused, arising in any way out of the usage
.\" of this work, even if advised of the possibility of such damage.
.\"-
.Dd October 22, 2004
.Dt PNG 5
.Os
.Sh NAME
.Nm png
.Nd Portable Network Graphics format
.Sh DESCRIPTION
The
.Nm
library contains functions dealing with files in the PNG format.
PNG (Portable Network Graphics) is an extensible file format for
the lossless, portable, well-compressed storage of raster images.
PNG provides a patent-free replacement for GIF and can also
replace many common uses of TIFF.
Indexed-colour, grayscale, and truecolour images are supported,
plus an optional alpha channel.
Sample depths range from 1 to 16 bits.
.Pp
PNG is designed to work well in online viewing applications, such
as the World Wide Web, so it is fully streamable with a
progressive display option.
PNG is robust, providing both full file integrity checking and
fast, simple detection of common transmission errors.
Also, PNG can storegamma and chromaticity data for improved
colour matching on heterogeneous platforms.
.Sh FILES
.Pa /usr/include/png.h ,
.Pa /usr/lib/libpng.a
.Sh SEE ALSO
.Xr libpng 3 ,
.Xr compress 3 .
.Sh STANDARDS
The PNG specification, second edition, November 2003
.br
.Pa http://www.w3.org/TR/2003/REC-PNG-20031110/
.Pp
The PNG 1.2 specification, July 1999
.br
.Pa http://www.libpng.org/pub/png
.Pp
The PNG 1.0 specification, October 1996
.br
RFC 2083,
.Pa ftp://ds.internic.net/rfc/rfc2083.txt
.br
A W3C draft is at
.Pa http://www.w3.org/TR/REC-png.html
.Sh HISTORY
The
.Nm
library became part of the base install with
.Mx 8 .
.Sh AUTHORS
The current
.Nm libpng
maintainer is
.An Glenn Randers-Pehrson Aq glennrp@users.sourceforge.net .
.Pp
This manual page and the
.Mx
adaptions are courtesy of
.An Thorsten Do mirabile Dc Glaser Aq tg@66h.42h.de .
.Pp
For detailed authorship and copyright information, refer to
.Pa /usr/include/png.h .
