<li><a href="/?main">Main</a><ul class="lv2">
	<li><a href="/?news">News</a></li>
	<li><a href="/?wlog-7">Weblog</a> for #7</li>
	<li><a href="/?clog-2005">Changes</a> for 2005</li>
	<li><a href="/?older">Old News</a> &amp; Log</li>
    </ul></li>
<li><a href="/?about">About</a></li>
<li><a href="/?getting">Download</a><ul class="lv2">
	<li><a href="/?mirrors">Mirrors</a></li>
    </ul></li>
<li><a href="http://wiki.mirbsd.de/MirPorts">MirPorts</a></li>
<li><a href="/?docs">Documentation</a></li>
<li><a href="/?danke">Donate</a></li>
<li style="list-style:none;"></li>
<li><a href="http://wiki.mirbsd.de/HomePage">MirWiki</a></li>
<li><a href="/cman/">Manpages</a></li>
<li style="list-style:none;"></li>
<li><a href="/?style">StyleSelect</a></li>
