<li><a href="/?overview">All in 1 page</a></li>
<li><a href="/?main">Main</a><ul class="lv2">
	<li><a href="/?news">News</a></li>
	<li><a href="/?wlog-9">Weblog</a> for #9</li>
	<li><a href="/?clog-2006">Changes</a> for 2006</li>
	<li><a href="/?older">Old News</a> &amp; Log</li>
    </ul></li>
<li><a href="/?faq">FAQ</a></li>
<li><a href="http://mirbsd.de/irc">IRC</a></li>
<li><a href="/?getting">Download</a><ul class="lv2">
	<li><a href="/?mirrors">Mirrors</a></li>
    </ul></li>
<li><a href="/?ports">MirPorts</a></li>
<li><a href="/?docs">Documentation</a></li>
<li><a href="/?projects">Project Ideas</a></li>
<li><a href="/?danke">Donate</a></li>
<li style="list-style:none;"></li>
<li><a href="/cman/">Manpages</a></li>
<li style="list-style:none;"></li>
<li><a href="/?style">StyleSelect</a></li>
