# $MirOS$
# $OpenBSD: Makefile,v 1.2 2004/02/27 19:41:39 david Exp $

PROG=	spamlogd
MAN=	spamlogd.8

CFLAGS+=	-Wall -Wstrict-prototypes -ansi
CPPFLAGS+=	-I${.CURDIR}/../spamd

.include <bsd.prog.mk>
