# $MirOS$
#-
# Use this if you want to manually compile the croatian gpc(1)
# manual page into a Unicode catman page on MirOS BSD.

MAN=		gpc-hr.1
NROFF=		nrcon -u ${MACROS} ${PAGES}

gpc-hr.1: gpc.1
	iconv -f iso-8859-2 <$> >$@

.include <bsd.prog.mk>
