# $OpenBSD: Makefile,v 1.1.1.1 2002/11/24 14:30:05 margarida Exp $

COMMENT=			module for dealing with time periods

DISTNAME=		Period-1.20
PKGNAME=		p5-Time-${DISTNAME}-0
CATEGORIES=		devel perl5


# Artistic
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=Time/}

CONFIGURE_STYLE=	perl

.include <bsd.port.mk>	
