# $MirOS: ports/www/pear-HTML-Common/Makefile,v 1.3 2005/07/07 21:28:17 bsiegert Exp $
# $OpenBSD: Makefile,v 1.3 2003/11/15 20:02:40 avsm Exp $

COMMENT=			base package for HTML handling in PHP
V=		1.2.1
DISTNAME=	HTML_Common-${V}
PKGNAME=	pear-HTML-Common-${V}-0
CATEGORIES=	devel www pear
MASTER_SITES=	http://pear.php.net/get/
EXTRACT_SUFX=	.tgz

MODULES=	www/php/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
