.\" $MirOS: src/share/misc/licence.template,v 1.14 2006/08/09 19:35:23 tg Rel $
.\"-
.\" Copyright (c) 2006
.\"	Thorsten Glaser <tg@mirbsd.de>
.\"
.\" Licensee is hereby permitted to deal in this work without restric-
.\" tion, including unlimited rights to use, publicly perform, modify,
.\" merge, distribute, sell, give away or sublicence, provided all co-
.\" pyright notices above, these terms and the disclaimer are retained
.\" in all redistributions or reproduced in accompanying documentation
.\" or other materials provided with binary redistributions.
.\"
.\" Advertising materials mentioning features or use of this work must
.\" display the following acknowledgement:
.\"	This product includes material provided by Thorsten Glaser.
.\"
.\" Licensor offers the work "AS IS" and WITHOUT WARRANTY of any kind,
.\" express, or implied, to the maximum extent permitted by applicable
.\" law, without malicious intent or gross negligence; in no event may
.\" licensor, an author or contributor be held liable for any indirect
.\" or other damage, or direct damage except proven a consequence of a
.\" direct error of said person and intended use of this work, loss or
.\" other issues arising in any way out of its use, even if advised of
.\" the possibility of such damage or existence of a defect.
.\"
.Dd October 2, 2006
.Dt ADDUSER 8
.Os
.Sh NAME
.Nm adduser
.Nd create new users with a text-driven menu interface
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility creates a user with a group whose name and GID
correspond to the user's name and UID, and populates his
home directory with the contents of
.Pa /etc/skel .
The user is by default put into the login class
.Dq default ,
has no password timeouts, secondary groups, or other special options.
.Pp
To change the login class, use the following command:
.Bd -literal -offset indent
$ sudo vipw
.Ed
.Pp
To add a user to a secondary group or remove him from any groups,
or to add not yet existing groups, use the following command:
.Bd -literal -offset indent
$ sudoedit /etc/group
.Ed
.Pp
Users and groups are never removed. To disable a user, change his
login class to default (empty field), his home directory to
.Pa /nonexistant ,
and his shell to
.Pa /sbin/nologin .
Remove his former home directory and set the password so that the
user cannot login any more (only an asterisk), but do not delete
the entry.
.Sh SEE ALSO
.Xr ed 1 ,
.Xr mksh 1 ,
.Xr passwd 1 ,
.Xr group 5 ,
.Xr login.conf 5 ,
.Xr passwd 5 ,
.Xr nologin 8 ,
.Xr sudo 8 ,
.Xr vipw 8
.Sh AUTHORS
.Nm
was written by
.An Thorsten Glaser Aq tg@mirbsd.de .
