.\" $MirOS: src/share/misc/licence.template,v 1.20 2006/12/11 21:04:56 tg Rel $
.\"-
.\" Copyright (c) 2006
.\"	Thorsten Glaser <tg@mirbsd.de>
.\"
.\" Provided that these terms and disclaimer and all copyright notices
.\" are retained or reproduced in an accompanying document, permission
.\" is granted to deal in this work without restriction, including un-
.\" limited rights to use, publicly perform, distribute, sell, modify,
.\" merge, give away, or sublicence.
.\"
.\" Advertising materials mentioning features or use of this work must
.\" display the following acknowledgement:
.\"	This product includes material provided by Thorsten Glaser.
.\"
.\" This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
.\" the utmost extent permitted by applicable law, neither express nor
.\" implied; without malicious intent or gross negligence. In no event
.\" may a licensor, author or contributor be held liable for indirect,
.\" direct, other damage, loss, or other issues arising in any way out
.\" of dealing in the work, even if advised of the possibility of such
.\" damage or existence of a defect, except proven that it results out
.\" of said person's immediate fault when using the work as intended.
.\"-
.Dd April 17, 2007
.Dt ADDUSER 8
.Os
.Sh NAME
.Nm adduser
.Nd create new users with a text-driven menu interface
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility creates a user with a group whose name and GID
correspond to the user's name and UID, and populates his
home directory with the contents of
.Pa /etc/skel .
The user is by default put into the login class
.Dq default ,
has no password timeouts, secondary groups, or other special options.
.Pp
To change the login class, use the following command:
.Bd -literal -offset indent
$ sudo vipw
.Ed
.Pp
To add a user to a secondary group or remove him from any groups,
or to add not yet existing groups, use the following command:
.Bd -literal -offset indent
$ sudoedit /etc/group
.Ed
.Pp
Users and groups are never removed. To disable a user, change his
login class to default (empty field), his home directory to
.Pa /nonexistant ,
and his shell to
.Pa /sbin/nologin .
Remove his former home directory and set the password so that the
user cannot login any more (only an asterisk), but do not delete
the entry.
.Sh SEE ALSO
.Xr ed 1 ,
.Xr mksh 1 ,
.Xr passwd 1 ,
.Xr group 5 ,
.Xr login.conf 5 ,
.Xr passwd 5 ,
.Xr nologin 8 ,
.Xr sudo 8 ,
.Xr vipw 8
.Sh HISTORY
.Nm
first appeared in
.Mx 10 .
.Sh AUTHORS
.Nm
was written by
.An Thorsten Glaser Aq tg@mirbsd.de .
.Sh CAVEATS
.Mx 8
and previous had a complex user-management suite mixed from
shell, perl, and C code, with an added advertising clause,
and many more unneeded functions.
It is recommended to never delete users and groups, just disable them,
anyway, so that the UIDs and GIDs will not be reused.
This utility scans for collisions with both UIDs and GIDs, so that,
in practice, retaining the group is enough.
.Pp
Changing the login class or group memberships of a user, as well as
group management, must be done manually by using
.Nm vipw
and editing
.Pa /etc/group ,
respectively.
This is actually by design.
.Pp
To make an S/Key- or SSH public key only user account, set his password
field to the string
.Dq skey
using
.Nm vipw ,
to prevent the daily cron job's security checks from complaining.
