<!-- PageID: irc -->
<small class="rcsid">$MirOS: www/content/aXJj.inc,v 1.4 2006/07/30 21:38:36 tg Exp $</small>

<h1>The MirOS Project on IRC</h1>

<p>We're in <tt>#MirBSD</tt> (and <tt>#MirOS</tt>, just in case) on <a
 href="http://freenode.net/">OPN/Freenode</a>. Connect to irc.mirbsd.org
 Port 6667 and be happy. (IPv4-only: irc4.mirbsd.org / IPv6-only:
 irc6.mirbsd.org)</p>

<p>There's also <tt>#!/bin/mksh</tt> on Freenode; this is the channel
 for <a href="/mksh.htm">the MirBSD Korn Shell</a> (mksh(1)).</p>
