<!-- PageID: licence -->
<small class="rcsid">$MirOS: www/content/bGljZW5jZQ__.inc,v 1.9 2006/08/11 00:57:59 tg Exp $</small>
<h1>The MirOS Licence Template</h1>

<h2>Normative</h2>
<p>The first paragraph of the licence (up to the *- or #-) is normative;
 the <a href="/cvs.cgi/src/share/misc/licence.template?rev=HEAD">latest
 revision</a> can be retrieved in plain text form via CVS. The RCS status
 of the file denotes its release status (Rel = adapted by MirOS team).</p>

<h2>Informative, with clickable links</h2>
<pre>/* &#36;MirOS: src/share/misc/licence.template,v 1.20 2006/12/11 21:04:56 tg Rel $ */

/*-
 * Copyright (c) year, year, year, ...
 *      First M. Last &lt;user@host.domain&gt;
 *
 * Provided that these terms and disclaimer and all copyright notices
 * are retained or reproduced in an accompanying document, permission
 * is granted to deal in this work without restriction, including un-
 * limited rights to use, publicly perform, distribute, sell, modify,
 * merge, give away, or sublicence.
 *
 * This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
 * the utmost extent permitted by applicable law, neither express nor
 * implied; without malicious intent or gross negligence. In no event
 * may a licensor, author or contributor be held liable for indirect,
 * direct, other damage, loss, or other issues arising in any way out
 * of dealing in the work, even if advised of the possibility of such
 * damage or existence of a defect, except proven that it results out
 * of said person's immediate fault when using the work as intended.
 *-
 * <span id="manual">INSTRUCTIONS</span>:
 * To apply the template<a id="rf1" href="#fn1">[1]</a> specify the years of copyright (separated
 * by comma, not as range), the legal names of the copyright holders,
 * and the real names of the authors if different. Avoid adding text.
 *
 * OPTIONAL ADVERTISING CLAUSE:
 * Adding advertising clauses is not recommended because they accumu-
 * late (MirOS #9 has a list of 130 required acknowledgements, out of
 * which several were duplicates with only minor changes) but if this
 * kind of crediting is desired, insert between the two paragraphs a-
 * bove the evaluation result of the following mksh(1)-style (grouped
 * by parentheses, separated by bars, can be omitted if prefixed by a
 * question mark) expression:
 *
 * (All a|A)dvertising materials mentioning features or use of this (
 * software|work) must display the following acknowledgement:
 *      This product includes (material|software) (provided by|devel-
 *      oped (at|?(or owned )by|under|for?( use (in|with)))) $name?(,
 *      )?( and (its|their|by other) contributors)?( (for|by) $name).
 *
 * RATIONALE:
 * This licence is apt for any kind of work (such as source code, do-
 * cumentation, fonts, graphics, sound, etc.) and the preferred terms
 * for works added to MirOS. It has been drafted as universally usab-
 * le equivalent of the "historic permission notice"<a id="rf2" href="#fn2">[2]</a> adapted to EU
 * law, because in some (droit d'auteur) countries one can't disclaim
 * all liabilities. Compliance to OSD<a id="rf3" href="#fn3">[3]</a> 1.9 and DFSG<a id="rf4" href="#fn4">[4]</a> 1.1 is safe,
 * and GPLv2 compatibility is asserted unless advertising clauses are
 * used or other (restrictive) text is added.
 *
 * We believe you are not liable for code inserted which is intellec-
 * tual property of third parties, if you were not aware of the fact,
 * act appropriately as soon as you become aware of this problem, and
 * seek an amicable solution for all parties.
 *
 * REFERENCES:
 * <a href="#rf1" id="fn1">[1]</a> also at <a href="http://mirbsd.de/MirOS-Licence">http://mirbsd.de/MirOS-Licence</a>
 * <a href="#rf2" id="fn2">[2]</a> <a href="http://www.opensource.org/licenses/historical.php">http://www.opensource.org/licenses/historical.php</a>
 * <a href="#rf3" id="fn3">[3]</a> <a href="http://www.opensource.org/docs/definition_plain.php">http://www.opensource.org/docs/definition_plain.php</a>
 * <a href="#rf4" id="fn4">[4]</a> <a href="http://www.debian.org/social_contract#guidelines">http://www.debian.org/social_contract#guidelines</a>
 */</pre>
