<small class="rcsid">$MirOS: www/content/bGljZW5jZQ__.inc,v 1.1 2005/06/06 10:19:51 tg Exp $</small>
<h1>The MirOS Licence Template</h1>

<pre>/* $MirOS: www/content/bGljZW5jZQ__.inc,v 1.1 2005/06/06 10:19:51 tg Exp $ */

/*-
 * Copyright (c) year, year, year...
 *	First M. Last &lt;<a href="#manual">user@host.domain</a>&gt;
 *
 * Licensee is hereby permitted to deal in this work without restric-
 * tion, including unlimited rights to use, publicly perform, modify,
 * merge, distribute, sell, give away or sublicence, provided all co-
 * pyright notices above, these terms and the disclaimer are retained
 * in all redistributions or reproduced in accompanying documentation
 * or other materials provided with binary redistributions.
 *
 * Licensor hereby provides this work "AS IS" and WITHOUT WARRANTY of
 * any kind, expressed or implied, to the maximum extent permitted by
 * applicable law, but with the warranty of being written without ma-
 * licious intent or gross negligence; in no event shall licensor, an
 * author or contributor be held liable for any damage, direct, indi-
 * rect or other, however caused, arising in any way out of the usage
 * of this work, even if advised of the possibility of such damage.
 *-
 * OPTIONAL ADVERTISING CLAUSE:
 * Adding advertising clauses is not recommended, because they reduce
 * the interoperability of the licence and place, if overused, a huge
 * load on distributors. Still there are cases in which adding an ad-
 * vertising clause might be appropriate. To add an advertising clau-
 * se, insert the following paragraph in between the first and second
 * paragraph shown above:
 *
 * All advertising materials mentioning features or use of this soft-
 * ware must display the following acknowledgement:
 *	This product includes (material|software) (provided by|devel-
 *	oped (at|?(or owned )by|under|for?( use (in|with)))) &lt;<i>NAME</i>&gt;?(
 *	?, and (its|their|by other) contributors)?( (for|by) &lt;<i>NAME</i>&gt;).
 *
 * Please adjust the above mksh-like expression for your needs; items
 * prefixed with a question mark can be left out.
 *
 * <a id="manual">INSTRUCTIONS</a>:
 * When applying the template specify the year(s) of copyright; addi-
 * tional years should be separated by commas, not denoted by range.
 * When adding extra text, be careful to not add further restrictions
 * and avoid adding text at all if possible.
 *
 * RATIONALE:
 * This template contains the preferred licence for new work (code or
 * data, e.g. documentation, fonts, audio/video) added to MirOS. This
 * licence is OSD<a id="rf1" href="#fn1">[1]</a> 1.9 compliant.
 * Because in some (droit d'auteur) countries you cannot disclaim all
 * liabilities this licence is drafted to behave better under Europe-
 * an law but otherwise be equivalent to the "historic permission no-
 * tice"<a id="rf2" href="#fn2">[2]</a>. You can (e.g. in German law) only be held liable if mal-
 * ware (such as backdoors) or intellectual property of third parties
 * (without a licence to do so) is added with intent; it equals a do-
 * nation.
 *
 * ADDITIONAL NOTES:
 * This template does not imply a choice of law; the MirOS project<a id="rf3" href="#fn3">[3]</a>
 * sets forth applicable law to be German law and site of court to be
 * Bonn, Germany (in an extra provision and only for MirOS). We think
 * this licence thus is compatible to the GNU GPL (unless an explicit
 * advertising clause is used).
 *
 * Licensor and Licensee are not defined by the licence text, neither
 * is there a statement like "perpetual, non-exclusive, irrevocable".
 * These terms have been omitted because usually your country's copy-
 * right/droit d'auteur law already defines them, and in latter coun-
 * tries it's often impossible to give out irrevocable, perpetual li-
 * cences (confirmed for Germany, where the original author can revo-
 * ke it after thirty (30) years, at the time of this writing).
 *
 * We believe you are not liable for code inserted which is intellec-
 * tual property of third parties, if you were not aware of the fact,
 * and remove it as soon as you get aware of it (that's why it's cal-
 * led a "gross neglicence").
 *
 * REFERENCES:
 * <a href="#rf1" id="fn1">[1]</a> <a href="http://www.opensource.org/docs/definition_plain.php">http://www.opensource.org/docs/definition_plain.php</a>
 * <a href="#rf2" id="fn2">[2]</a> <a href="http://www.opensource.org/licenses/historical.php">http://www.opensource.org/licenses/historical.php</a>
 * <a href="#rf3" id="fn3">[3]</a> <a href="http://mirbsd.de/">http://mirbsd.de/</a>
 */</pre>
