<!-- PageID: licence -->
<small class="rcsid">$MirOS: src/share/misc/licence.template,v 1.14 2006/08/09 19:35:23 tg Rel $</small>
<h1>The MirOS Licence Template</h1>

<pre>/* &#36;MirOS: src/share/misc/licence.template,v 1.14 2006/08/09 19:35:23 tg Rel $ */

/*-
 * Copyright (c) year, year, year, ...
 *      First M. Last &lt;user@host.domain&gt;
 *
 * Licensee is hereby permitted to deal in this work without restric-
 * tion, including unlimited rights to use, publicly perform, modify,
 * merge, distribute, sell, give away or sublicence, provided all co-
 * pyright notices above, these terms and the disclaimer are retained
 * in all redistributions or reproduced in accompanying documentation
 * or other materials provided with binary redistributions.
 *
 * Licensor offers the work "AS IS" and WITHOUT WARRANTY of any kind,
 * express, or implied, to the maximum extent permitted by applicable
 * law, without malicious intent or gross negligence; in no event may
 * licensor, an author or contributor be held liable for any indirect
 * or other damage, or direct damage except proven a consequence of a
 * direct error of said person and intended use of this work, loss or
 * other issues arising in any way out of its use, even if advised of
 * the possibility of such damage or existence of a defect.
 *-
 * <span id="manual">INSTRUCTIONS</span>:
 * To apply the template<a id="rf1" href="#fn1">[1]</a> specify the years of copyright (separated
 * by comma, not as range), the legal names of the copyright holders,
 * and the real names of the authors if different. Avoid adding text.
 *
 * OPTIONAL ADVERTISING CLAUSE:
 * Adding advertising clauses is not recommended because they accumu-
 * late (MirOS #9 has a list of 130 required acknowledgements, out of
 * which several were duplicates with only minor changes) but if this
 * kind of crediting is desired, insert between the two paragraphs a-
 * bove the evaluation result of the following mksh(1)-style (grouped
 * by parentheses, separated by bars, can be omitted if prefixed by a
 * question mark) expression:
 *
 * (All a|A)dvertising materials mentioning features or use of this (
 * software|work) must display the following acknowledgement:
 *      This product includes (material|software) (provided by|devel-
 *      oped (at|?(or owned )by|under|for?( use (in|with)))) $name?(,
 *      )?( and (its|their|by other) contributors)?( (for|by) $name).
 *
 * RATIONALE:
 * This template contains the preferred licence for any work (such as
 * source code, documentation, fonts, graphics, sound, etc.) added to
 * MirOS and is OSD<a id="rf2" href="#fn2">[2]</a> 1.9 and DFSG<a id="rf3" href="#fn3">[3]</a> 1.1 compliant. It's drafted as
 * equivalent of the "historic permission notice"<a id="rf4" href="#fn4">[4]</a> adapted to Euro-
 * pean law because in some (droit d'auteur) countries one can't dis-
 * claim all liability. There is no implied choice of law (MirOS uses
 * extra provision for that); the licence is GPL-compatible if adver-
 * tising clauses are not used.
 *
 * We believe you are not liable for code inserted which is intellec-
 * tual property of third parties, if you were not aware of the fact,
 * act appropriately as soon as you become aware of this problem, and
 * seek an amicable solution for all parties.
 *
 * REFERENCES:
 * <a href="#rf1" id="fn1">[1]</a> also at <a href="http://mirbsd.de/MirOS-Licence">http://mirbsd.de/MirOS-Licence</a>
 * <a href="#rf2" id="fn2">[2]</a> <a href="http://www.opensource.org/docs/definition_plain.php">http://www.opensource.org/docs/definition_plain.php</a>
 * <a href="#rf3" id="fn3">[3]</a> <a href="http://www.debian.org/social_contract#guidelines">http://www.debian.org/social_contract#guidelines</a>
 * <a href="#rf4" id="fn4">[4]</a> <a href="http://www.opensource.org/licenses/historical.php">http://www.opensource.org/licenses/historical.php</a>
 */</pre>
