<small class="rcsid">$MirOS: www/content/bmV3cw__.inc,v 1.29 2005/09/12 23:05:31 tg Exp $</small>

<h1>Current MirOS News</h1><ul>

<li>18.09.2005<br />A new version of MirMake has been released; test it on
	as many platforms as you can please.<br />Development slowed down,
	mostly due to influenza, also studying work increases. Sorry.</li>

<li>12.09.2005<br />
	The MirPorts Framework now can be installed as user too. The newly
	written infrastructure is active; Support for Darwin, OpenBSD and,
	eventually, Interix will make it into the framework the next days.
	Along with this, new versions of the Mir* tools have been released
	(gzsig'd as usual).</li>

<li>20.08.2005<br />
	The MirPorts Framework now installs into <tt>/usr/mpkg</tt> on all
	platforms by default. This improves coexistence with other porting
	frameworks, such as the OpenBSD Ports Tree; simplifies cleaning up
	by removal of all installed packages; provides a consistent, among
	all platforms, interface; leaves <tt>/usr/local</tt> to the admin.
	Of course, this means, reinstallation is necessary.<br />Please to
	be keeping in mind that most ports (that were using libtool) still
	need to be updated.</li>

<li>09.08.2005<br />
	The <a href="http://wiki.mirbsd.de/">MirWiki</a> is read-only, for
	a transition phase. The content will be merged into the main page,
	as time permits. After that, it will be shut down entirely.</li>

<li>02.08.2005<br />
	MirOS hasn't stopped, it's just progressing slowly because current
	development is progressing in rather big steps. There is a status,
	mirror and "all-in-one overview" page now which we will keep up to
	date if no other one. There are also some hardware issues to solve
	(such as a broken Socket 7 fan, and a non-working coffee machine),
	but we will continue development and fighting lobbyism, politician
	nonsense etc.<br />mksh R24 has been released some time ago and is
	the first one who actually made it into Debian testing, hooray!</li>

</ul>
<p>For older news, please refer to the <a href="/?older">historical news
 page</a>, or the developers' weblog.</p>
