<!-- PageID: main -->
<small class="rcsid">$MirOS: www/content/bWFpbg__.inc,v 1.51 2006/04/23 00:57:51 tg Exp $</small>

<h1>Welcome to the MirOS Project!</h1>

<h2>What is MirOS?</h2>

<p>MirOS BSD is a secure operating system from the BSD family for i386 and
 sparc systems. It is based on <a
 href="http://www.openbsd.org/">OpenBSD</a>. MirPorts is a portable ports
 tree to facilitate the installation of additional software. The project
 also releases some portable software: mksh, a ksh-based shell;
 PaxMirabilis, an archiver for various formats; MirMake, a framework for
 building software.</p>

<p>If you want to know more about these programs, visit the <a
 href="/?about">About MirOS</a> page.</p>

<h2>News</h2>

<p>All announcements from the MirOS team are <a
 href="/cvs.cgi/src/share/doc/README?rev=HEAD">cryptographically signed</a>
 using gzsig(1) in order to prevent abuse of our name and provide integrity
 of distfiles.</p>

<p>Please read the <a href="/?irc">FreeForge IRC network information</a> as
 well.</p>

<div class="newsentry"> <!-- have to add this to css -->
<h3>25.07.2006: MirPorts heads-up</h3>
<p>Due to the introduction of a new ld wrapper, you will have to re-do
 "make setup" (or a similar command line) after updating the infrastructure
 from CVS.</p>
</div>

<div class="newsentry"> <!-- have to add this to css -->
<h3>05.07.2006: New web server</h3>
<p>We changed our web server. The former mirsolutions server is no longer.
 gecko2 hosts the box behind www.mirbsd.org now. waldi's
 Zope is still operational and helps a lot.</p>
</div>

<div class="newsentry">
<h3>01.04.2006: MirOS #8 released</h3>
<p><a href="/?ann-8">MirOS #8</a> is available via our <a
 href="http://f.scarywater.net/miros/">BitTorrent tracker</a>. There is
 also an <a href="/MirOS/v8/">HTTP(S)</a> download/netinstall
 option.</p>
<p>Please read the <a href="/?errata">errata</a>.</p>
</div>

<div class="newsentry">
<h3>27.03.2006: Some bad CDs distributed on FOSDEM</h3>
<p>In case you have acquired a MirOS CD-ROM "FOSDEM 2006"
 edition please verify the checksums of the data on the CD. Some of
 the CDs we distributed at FOSDEM were burned from a bad ISO.</p>
</div>



