<small class="rcsid">$MirOS: www/content/bWFpbg__.inc,v 1.70 2005/01/27 23:23:57 tg Exp $</small>
<h1>MirBSD &nbsp; MirLinux &nbsp; MirPorts &nbsp; &mdash; &nbsp; Main Page</h1>
<h3>Software Patent Issues</h3>
<p>The <tt>MirOS Project</tt> would like to join the hundreds of thousands of
 parties protesting against software, algorithm and even data structure
 patentability in the European Union!</p>
<p class="erecta">More information at <a href="http://swpat.ffii.org/">FFII
 website</a>.</p>
<p><a href="http://demo.ffii.org/kuenast/brief.html"><img
 src="http://demo.ffii.org/kuenast/kuenast_banner60.png"
 alt="Renate K&uuml;nast, bitte hier klicken!"></a></p>
<p><a href="http://www.ffii.org/"><img
 src="http://demo.ffii.org/cons0501/fishy_banner82.jpg"
 alt="Something fishy's going on..." /></a></p>
<h2>Welcome to the MirOS Project!</h2>
<p>This project is driven by a small number of people, that's why this
 website isn't always up to date. It's optimized for lynx and works in
 Konqueror; IE and Mozilla&trade;-crap do have problems with it.<br />New:
 <a href="/?style">the Stylesheet selector</a> to improve readability.</p>
<p><big>Where to go next?</big><br />If you want to read about what MirOS
 actually <b>is</b>, visit the &quot;about&quot; href (hyperlink) on the
 left side. &quot;get MirOS!&quot; should be self-explanatory, and files
 are available as well as a full ISO image!</p>
<p><big>We're looking</big> for people wanting to ensure quality of MirPorts
 under MirOS BSD and OpenBSD. If you're interested and have &gt;1
 year of experience with the OpenBSD Ports Tree, and are not scared of
 &lt;bsd.port.mk&gt;; please contact us. We also <big>need web site
 hackers</big> who keep track of source changes.</p>
<h3>News</h3>
<p>If you're coming from <tt>bsdforen.de</tt>, one of the worst pro-BSD
 websites I've seen, read <a href="/?wlog-7#rantbsdforen20050115">this</a>.</p>
<p>Attention: All announcements from the MirOS team are <a
 href="/cvs.cgi/contrib/samples/devel-keys">cryptographically
 signed using PGP or OpenSSL</a> in order to prevent abuse of our name.</p>
<p>Go to <a href="/?news">the main news page</a>.</p>
<h3 style="color:red;">Latest Release</h3>
<p>CURRENT: January 27th, 2005: #8-Beta snapshot (tech preview), via <a
 href="/MirOS/current/i386-20050127/">https</a> and at the usual <a
 href="http://f.scarywater.net/miros/">usual BitTorrent tracker</a>.
 This is a less tested, less stable, more current version without even
 an X-Windowing system built, lest alone source and stuff. At least
 you get Ports and a special boot floppy for Strato dedicated servers.</p>
<p>CURRENT: November 29th, 2004: #8-Beta snapshot available via <a
 href="https://mirbsd.bsdadvocacy.org:8890/MirOS/current/i386-20041129/">http</a>.
 There is an updated <a
 href="http://users.mirsolutions.de/~tg/bsd/encrypt.gz">/usr/bin/encrypt</a>
 (gzip compressed) available to fix a core dump.</p>
<p>CURRENT: November 29th, 2004: Development snapshot available on the <a
 href="http://f.scarywater.net/miros/">BitTorrent</a> tracker.</p>
<p>MERCHANDISING: There are still T-Shirts up for order. Contact <a
 href="mailto:tg@66h.42h.de">tg@</a> for purchase information.</p>
<p>PORTS: January 9th, 2005: If updating MirPorts, always use 'cd /usr/ports;
 make setup' before using. Also, review <tt>/etc/mk.conf</tt> because some of
 the settings which used to be on top have been moved to the bottom; you must
 delete them from the top of the file. Please read the page on <a
 href="/?ports">MirPorts</a> for usage and update/upgrade instructions.</p>
<p>STABLE: January 6th, 2005: <a href="/?ann-7">MirOS #7quinquies</a> is
 available for retrieval. Click the &quot;get MirOS!&quot; link on the left
 for further information - where you can buy CDs or download the sets.</p>
<p><a href="/MirOS/CVS/cvsroot-20050123.cgz">CVSROOT</a>: January 23th, 2005:
 new seed file (324 MB) available to reduce the initial amount of traffic
 required for mirroring /ocvs by rsync. CTM is available on request, we'd
 like to do it but nobody uses it.<br />Attention: the CVSROOT is no longer
 <tt>/cvs</tt> but rather <b><tt>/ocvs</tt></b>.</p>
<p><a href="/MirOS/CVS/cvsrepo-20050123.cgz">CVSREPO</a>: January 7th, 2005:
 seed file (168 MB) for peeking into ncvs.</p>
<h2>Big Warning</h2>
<p>Do not go to &quot;mirbsd.org&quot; - it's not a domain of ours and
 used to transfer you to a faecal website.</p>
