<small class="rcsid">$MirBSD: www/content/bWFpbA__.inc,v 1.1 2004/11/12 17:54:23 tg Exp $</small>
<h1>The Mailing Lists</h1>

<p>We've got a <a href="mailto:miros-discuss@66h.42h.de">discussion
 mailing list</a> and a CVS changes mailing list, both of which are
 public. All subscribers of the CVS changes mailing list automatically
 are on the discussion mailing list as well. In order to subscribe, send
 a mail to <a href="mailto:postmaster@66h.42h.de">the postmaster</a>.
 We've also got an internal developers-only list, although our development
 process is usually done in IRC entirely.</p>

<p>The <tt>miros-discuss@</tt> list is published bidirectionally as
 <tt>gmane.os.miros.general</tt>, and <tt>miros-changes@</tt> can be read
 via <tt>gmane.os.miros.cvs</tt> now, see <a href="http://gmane.org/">their
 website</a> for further information, or jump directly to the read interface
 for the <a href="http://news.gmane.org/gmane.os.miros.general">discussion
 list</a> or the <a href="http://news.gmane.org/gmane.os.miros.cvs">source
 changes</a>.</p>
