<small class="rcsid">$MirOS: www/content/bWFpbg__.inc,v 1.31 2005/12/06 00:00:43 tg Exp $</small>
<h1>MirBSD &nbsp; MirLinux &nbsp; MirPorts &nbsp; &mdash; &nbsp; Main Page</h1>
<h2>Welcome to the MirOS Project!</h2>
<p>This project is driven by a small number of people, that's why this
 website isn't always up to date. It's optimised for lynx and works well in
 Konqueror; IE and Mozilla&trade;-crap have certain problems with it.</p>
<p><big>Where to go next?</big><br />If you want to read about what MirOS
 actually <b>is</b>, visit the &quot;about&quot; href (hyperlink) on the
 left side. &quot;Download&quot; should be self-explanatory, and files
 are available as well as a full ISO image!</p>
<p><big>We're looking</big> for people wanting to ensure quality of MirPorts
 under MirOS BSD, OpenBSD, Mac OSX Panther and Tiger, and Microsoft Services
 for Unix (aka Interix). If you're interested and have &gt;1
 year of experience with the OpenBSD Ports Tree, and are not scared of
 &lt;bsd.port.mk&gt;; please contact us. We also <big>need web site
 hackers</big> who keep track of source changes.</p>
<h3>News</h3>
<p>Attention: All announcements from the MirOS team are <a
 href="/cvs.cgi/src/share/doc/README?rev=HEAD">cryptographically signed</a>
 using gzsig(1) or the older, deprecated, <a
 href="/cvs.cgi/contrib/samples/devel-keys">PGP (RFC1991) or OpenSSL</a>,
 in order to prevent abuse of our name and provide integrity of distfiles.</p>
<p>Go to <a href="/?news">the main news page</a>.</p>
<h3 style="color:red;">Latest Releases</h3>
<p>Please do <b>not</b> use any of the snapshots still available on our
 servers; they are very outdated and broken. If you had the chance to
 get a <a href="/MirOS/ISOs/snap8lt2005.iso">CD at the LinuxTag 2005</a>, lucky you but don't update Ports yet.
 If not, you will have to wait for the next MirOS #8 snapshot.</p>
<!-- p>CURRENT: May 2nd, 2005: #8-gamma snapshot available via our <a
 href="http://f.scarywater.net/miros/">BitTorrent</a> tracker.</p>
<p>CURRENT: May 5th, 2005: #8-gamma snapshot available for <a
 href="/MirOS/current/i386-20050505/">download</a> via the usual mirrors.</p -->
<p>STABLE: December 12th, 2005: <a href="/?ann-7">MirOS #7quinquies</a> is
 available for retrieval, but it has been "end of life"d some time ago.</p>
<p>PORTS: December 12, 2005: The great reorganisation has settled down; you
 can install the <a href="/?ports">MirPorts Framework</a> as regular user,
 all pre-requisites including a recent enough <tt>mksh</tt> are being taken
 care of automatically. This is for MirOS #8, OpenBSD and Darwin only at the
 moment; Interix support is not yet complete (but almost), and support for
 older MirOS releases will only be added on request. The existing
 documentation is inaccurate, especially the (former) MirWiki. Perl ports
 do not work correctly on Darwin.</p>
<p>MERCHANDISING: There are still T-Shirts up for order. Contact <a
 href="mailto:tg@66h.42h.de">tg@</a> for purchase information. ONLY ONE
 WHITE "LinuxTag 2004" T-SHIRT LEFT, NO REPRINTS. BUY THIS RARITY!</p>
<p><a href="/MirOS/CVS/cvsrepo-20050804.cgz">CVSREPO</a>: August 4th, 2005:
 seed file (153 MiB, gzsig(1)d) for reducing the
 initial transfer costs. We would like to offer CTM too; it is available on
 request but nobody uses it yet.</p>
<p><a href="/MirOS/CVS/cvsroot-20050316.cgz">CVSROOT</a>: March 16th, 2005:
 final and complete seed file (325 MB) for the historic old repository.</p>
