<!-- PageID: mirrors -->
<small class="rcsid">$MirOS: www/content/bWlycm9ycw__.inc,v 1.10 2006/01/27 10:37:15 tg Exp $</small>
<h1>MirOS mirrors</h1>

<h2>Kinds of mirrors</h2>

<p>The MirOS project employs various kinds of mirrors.</p>
<p>Website mirrors provide access to this website and, probably,
 the download area (<tt>/MirOS/</tt>). The MirWiki is mirrored,
 but officially not accessible on the mirrors.<br />Source mirrors
 provide access to the MirOS CVS Repository through various means.</p>

<h2>Mirror list</h2>

<h3>Website</h3>
<p><a href="http://mirbsd.de/">Another list</a>.</p><ul>
<li><a href="http://www.mirbsd.org/">mirbsd.mirsolutions.de</a>
 (www and distfiles, updated frequently)</li>
</ul>
<p>Note: distfiles is <tt>/MirOS/distfiles/</tt> &ndash; where you can
 retrieve sources for both MirOS offsprings (such as the now-famous <a
 href="/?mksh">MirbsdKsh</a>) and third-party
 sources (such as BIND, Joe 2.8, WineX).</p>

<h3>CVSweb</h3>
<p>CVSweb is usually provided by website mirrors. More <a
 href="/?cvsweb">information</a> about CVSweb and the special
 properties of MirOS CVSweb is available.</p><ul>
<li><a href="http://cvs.mirbsd.de/">cvs.mirbsd.de</a> (GENERIC redirection)</li>
<li><a href="http://mirbsd.mirsolutions.de/cvs.cgi/">mirbsd.mirsolutions.de</a>
 (updated frequently)</li>
</ul>

<h3>anonCVS</h3>
<p>_anoncvs@anoncvs.66h.42h.de:/cvs</p>

<h3>anonRSYNC</h3>
<p>click <a href="/?anoncvs">...</a> for more info until some lazy bum
 gets around and writes proper text here</p>
<p>Look at <a href="http://www.allbsd.org/">AllBSD</a> as well.</p>

<h3>CTM</h3>
<p>none yet</p>

<h3>CVSup</h3>
<p>probably none, unless allbsd.org offers them; we don't support it</p>

<h3>CVSync</h3>
<p>probably none, unless allbsd.org offers them; we don't support it</p>

<h3>Download Area</h3>
<p>These are mirrors of the MirOS http/ftp download area. Note: Do not
 use or advocate FTP. It's a bad, ancient protocol and barely deserves
 to die peacefully. Use https, http or rsync instead, or participiate
 in BitTorrent file swarming.</p><ul>
<li>ftp.gwdg.de (?)</li>
<li>...?</li>
</ul>

<h3>BitTorrent</h3>
<p>All our currently active files can be seen directly at the <a
 href="http://f.scarywater.net/miros/">tracker</a>; the torrents
 and their detached PGP signatures can also be found in the
 <tt>/MirOS/BT/</tt> directory on every Download Area mirror.</p>
