<!-- PageID: style -->
<small class="rcsid">$MirOS: www/content/c3R5bGU_.inc,v 1.2 2005/02/05 22:43:39 tg Exp $</small>
<h1>Stylesheet Selector</h1>
<p>The MirOS project website has a number of CSS style sheets to
 offer in order to improve usability and readability on web browsers
 other than <a href="http://lynx.isc.org/">Lynx</a>, our preferred
 web browser. Please choose one of the following style sheets;
 this selection needs cookies enabled in order to work.</p>
<form method="get" action="/setcss.php"><p>
 <input type="radio" name="sheet" value="XXXX" /> Default<br />
 <input type="radio" name="sheet" value="konq" /> Old (better in Konqueror, worse in Bloatzilla)<br />
 <input type="radio" name="sheet" value="root" /> Admin (shows additional info)<br />
 <input type="radio" name="sheet" value="bare" /> bare (no colours)<br />
 <input type="radio" name="sheet" value="mini" /> mini (no fonts either)<br />
 <br /><input type="submit" value="OK" />
</p></form>
