<small class="rcsid">$MirOS: www/content/cG9ydHM_.inc,v 1.6 2005/12/20 09:00:39 tg Exp $</small>
<h1>MirPorts: The MirOS Ports Framework</h1>

<h2>Installation instructions</h2>

<p>Please refer to the <a href="/cman/man8/Setup.sh.htm">installer's
 manual page</a> for an invocation reference.</p>

<p>On MirOS BSD, you can do the backwards-compatible</p><pre>
 $ cd /usr/ports
 $ make setup
</pre><p>as well (SUDO is invoked automatically).</p>

<h2>Using the MirPorts Framework</h2>

<p>To be filled in...</p>
<p>Basically:</p><pre>
 $ cd /usr/ports/editors/joe
 $ <b>m</b>make install clean
 $ echo export EDITOR=/usr/mpkg/bin/jupp &gt;&gt;~/.profile
</pre>

<h2>Writing ports for the framework</h2>

<p>To be filled in...</p>

<h2>Old stuff... not up to date</h2>

<p>This page has been moved to the MirWiki at the <a
 href="http://wiki.mirbsd.de/MirPorts">MirPorts</a> page.</p>

<p>The MirWiki is about to be disabled, so please link to this
 page again if referring to information about MirPorts.</p>
