<!-- PageID: want -->
<small class="rcsid">$MirOS: www/content/d2FudA__.inc,v 1.5 2006/01/27 00:14:30 tg Exp $</small>
<h1>Hardware wishlist</h1>

<p>Alphabetically sorted by developers; short-term first,
 long-term wishes last. Food, beer, travel tickets welcome.</p>

<h3>tg@</h3><ul>
<li>A large (100 GB or 120 GB), <em>very</em> quiet, 2.5" IDE
 laptop hard disc (however no cooling can be provided)</li>
<li>A passively cooled Baby-AT (not ATX/ITX/BTX) power
 supply unit for use with low-power desktops (P-233)</li>
<li>An external CD burning device, for use at exhibitions (the one
 built into my laptop is old and gets hot pretty fast)</li>
<li>Upgrades of any kind for a SPARCstation 20 (such as a CPU
 faster than the 75 MHz one, more RAM, more HDD, good NIC)</li>
<li>A memory expansion for an Acer Aspire 1300 laptop</li>
<li>A supported USB 2 adapter as PCMCIA card</li>
</ul>
