<small class="rcsid">$MirOS: www/content/d2xvZy04.inc,v 1.2 2005/12/27 22:47:06 tg Exp $</small>
<h1>MirBSD &ndash; WTF, We Have a Release!?</h1>
<p><small><a href="#eof">bottom</a> or <a href="/?older">older</a>
 editions</small></p>

<div class="wlentry">
<h3>27.12.2005 by bsiegert@</h3>
<p>We finally have a new release, over two years afer #7! To
celebrate this event, rotate the wlog and start a new one.</p>
</div>

<div class="wlentry">
 <h3>27.12.2005 by tg@</h3>
 <p>I've been prodded by bsiegert@ to write here again. Curious, isn't
  it? After the last release I've been the only one to write here. But
  today is somehow unproductive... I can't get myself to do something;
  will probably hunt some autoconf bugs later. I got a new laptop HDD,
  80 GB and waaaaaay faster, and re-installed BSD. pb@openbsd, who has
  arrived at the OpenBSD booth @22C3 in the meantime, didn't recognise
  me as I showed up in front of him until I threatened to throw all 70
  or so MirOS CDs we have at them.</p>
</div>

<p id="eof">Good luck, have fun, take care etc.pp</p>
