<small class="rcsid">$MirOS: www/content/Y2xvZy0yMDA1.inc,v 1.6 2005/12/07 00:41:16 tg Exp $</small>
<!--
 Full list of release focuses in freshmeat.net-compatible format:
	N/A
	Initial freshmeat announcement
	Documentation
	Code cleanup
	Minor feature enhancements
	Major feature enhancements
	Minor bugfixes
	Major bugfixes
	Minor security fixes
	Major security fixes
 -->
<h1>2006 snapshots of MirOS-current</h1>
<h3>Infos &ndash; <a href="#eof">bottom</a></h3>

<p>(There are no new snapshots yet.)</p>

<p>The first 2006 snapshot is relative to the <a
 href="/?ann-8">MirOS #8semel</a> release, not to
 the <a href="/?clog-2005#snap1207">2005-12-07
 snapshot</a> of MirOS #8-beta.</p>

<p id="eof">That's all for 2006, folks.</p>
