<!-- PageID: bt -->
<small class="rcsid">$MirOS: www/content/d2xvZy04.inc,v 1.89 2006/06/19 12:16:20 tg Exp $</small>
<!-- http://www.mirbsd.org/?bt#id -->
<h1>BitTorrent information</h1>
<p><strong>Warning:</strong> Not finished yet.</p>
<h2>Tracker</h2>
<p>This information represents the files shown on the <a
 href="http://f.scarywater.net/miros/">Scarywater MirOS tracker</a>.</p>
<h2>Generic information</h2>
<p>... (live, install, arch, dd to hda, etc)</p>
<p>Releases never contain Live CD functionality. The releases offered
 are always ISO images (single file torrent).</p>
<h2>Information about specific torrents</h2>
<h3>Releases</h3>
<p>If you're helping us to seed, please seed as many old releases as
 possible as well. If you cannot seed them all, seed at least #9semel
 (latest for i386) and #7quater (latest for sparc), please.</p>
<h4 id="r9semel">#9-RELEASE</h4>
<h4 id="r8semel">MirOS #8</h4>
<h4 id="r7quater">#7quater</h4>
<h3>Snapshots</h3>
<h4 id="s20060617">2006-06-17</h4>
<p>This one's actually a life CD, MirOS #9-beta, old, but Live CD and
 thus not yet disabled on the tracker yet. Please seed it too.</p>
