<!-- PageID: anargeek -->
<small class="rcsid">$MirOS: www/content/YW5hcmdlZWs_.inc,v 1.9 2005/12/06 18:39:02 tg Exp $</small>
<h1><a href="http://anargeek.net/">Anargeek</a></h1>
<p>Go <a href="#manifest">directly to the manifesto</a>, or read the <a
 href="#koffie">unrelated side note</a> about coffee.</p>
<h2>Why this page?</h2>
<p>On <a href="http://www.fosdem.org/">FOSDEM</a> 2005 some guy walked past
 me and gave me a paper containing the &quot;anargeek manifesto&quot; since
 he saw my laptop being full of BSD, <a href="http://koeln.ccc.de/">CCC</a>
 and <a href="http://fau.netzladen.org/">FAU-IAA</a> stickers.</p>
<p>I consider the <a href="http://www.netzladen.org/">Netzladen</a> members
 all to be Anargeeks, and even the <tt>HolaBSDng</tt> gang (i.e. the public
 relationship &quot;common exterior frontier&quot; of Holarse (not the game
 project), MirOS and BOSng), which is how we call ourselves at exhibitions,
 consists mainly of anargeeks of more or less strong flavour.</p>
<p>I've translated the English language version of the "Anargeek Manifesto"
 into German, and bsiegert@ compared it with the original, French language,
 version afterwards. I've created a logo to proudly show you're an anargeek
 (that is licenced, for formal reasons, under <a href="/?licence">the MirOS
 Licence</a>), whose design idea got approved by various Netzladen members,
 hackers and anarcho-syndicalists.</p>
<p>The anargeek manifesto itself is covered by a "Creative Commons" Licence
 (<a href="http://creativecommons.org/licenses/by-nc-sa/2.0/">BY-NC-SA</a>)
 and so is the text below.</p>
<address><small>Thorsten Glaser &mdash; Benny Siegert</small></address>
<hr />
<table width="100%"><tr><td>
<h2 id="manifest">Das Anargeek Manifest</h2><pre>
&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;
&middot;&middot; m a n i f e s t &middot; e i n e s &middot;&middot;
&middot;&middot; a n a r g e e k &middot; &middot; v 1 . 1 &middot;&middot;
&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;
</pre></td>
<td style="width:160px;"><img src="/pics/anargeek.png" alt="Anargeek Emblem" /></td></tr></table>
<p>Ich bin ein Anargeek. Ein Anarchist und Geek, und mehr.</p>
<p><tt>&middot;&nbsp;&middot;&nbsp;&middot;</tt></p>
<p>Ich bin ein Geek, weil man mich zu denen z&auml;hlen kann, die es
 m&ouml;gen, diese seltsamen Ger&auml;te, die wir Computer nennen,
 zu nutzen, verstehen und ver&auml;ndern.</p>
<p>Ich bin auch ein Geek, weil ich neugierig bin, wie diese funktionieren.
 Ich frage mich, was man mit ihren Programmen machen kann. Und manchmal
 bin ich begeistert von den Funktionen und Anwendungen, die noch nicht
 entdeckt worden sind oder an die noch niemand gedacht hat.</p>
<p>Ich bin ein Geek, weil diese Maschinen ein Teil meines t&auml;glichen
 Lebens sind. Ich nutze sie als Uhr, Stereoanlage, Bibliothek,
 Schreibmaschine, Kaffeemaschine, als Telephon oder Notizblock. Aber
 haupts&auml;chlich sind sie mein Spielplatz. Ein Helfer bei Kommunikation,
 Erforschung und Kreativit&auml;t.</p>
<p>Ich bin ebenfalls ein Geek, weil ich digitale Kommunikation in mein
 Leben integriert habe. Fast jeden Tag, wenn nicht mehrere Male am Tag,
 lese ich meine eMail, verwalte Server im Internet, schaue nach dem
 Netzwerk, das ich nutze, informiere mich, lerne, tausche Wissen in Fora,
 Mailing-Listen und Newsgroups sowie unterschiedlichsten Webseiten aus;
 unterhalte mich und treffe Leute via IRC.</p>
<p>Schlie&szlig;lich bin ich ein Geek, weil ich diesen Terminus mag.
 Urspr&uuml;nglich war es eine Beleidigung, aber sp&auml;ter wurde es
 von denen, die es betrifft, f&uuml;r sich eingefordert, ins Gute
 gewandelt und hat die Wurzeln f&uuml;r eine Gemeinschaft gesetzt,
 genau wie es einige andere kulturelle Minderheiten taten.</p>
<p><tt>&middot;&nbsp;&middot;&nbsp;&middot;</tt></p>
<p>Ich bin ein Anarchist, weil ich eine Gesellschaft, die auf Dominanz Weniger
 &uuml;ber die Anderen basiert, zur&uuml;ckweise. Es ist meine
 &Uuml;berzeugung, da&szlig; es m&ouml;glich ist, sich mit Respekt vor jedem
 Einzelnen sowie durch Praktizieren von Gleichberechtigung, Solidarit&auml;t
 und Eigenverantwortung selbst zu verwirklichen.</p>
<p>Auch bin ich ein Anarchist, weil mich die sozialen Strukturen, die
 Massenausnutzung, t&auml;gliches Leiden und Tod verursachen, in
 Rage versetzen. Ich m&ouml;chte dazu beitragen, dieses System
 niederzuschlagen, indem ich mich in gesellschaftlichen Bewegungen und an
 Str&ouml;mungen f&uuml;r den radikalen Wandel des Systems beteilige.</p>
<p>Ich bin ein Anarchist, weil ich mein t&auml;gliches Leben als eine
 Gelegenheit sehe, meine Prinzipien zu testen. Ich bin bereit, mit sozialen
 Normen zu brechen, zum Beispiel durch Verweigerung der Aufrufe zu Konsum
 und Wettbewerb; Entfremdung zur&uuml;ckzuweisen; durch Zersetzen von
 unterdr&uuml;ckerischem und dominantem Verhalten, durch Entwickeln von
 kollektiven und gleichberechtigenden Alternativen.</p>
<p>Ich bin auch ein Anarchist, weil ich &quot;offiziellen&quot; Informationen
 meist skeptisch gegen&uuml;berstehe; ich m&ouml;chte Massenmedien und
 institutionalisierten Medien kritisch begegnen, weil diese unsere Sicht
 der Dinge durch Auslassungen, L&uuml;gen und Falschinformationen tr&uuml;ben.
 Selbstausgesprochene Objektivit&auml;t zur&uuml;ckweisend suche ich nach
 anderen und neuen Wegen, mich selbst zu informieren und zu bilden, nach
 alternativen Mitteln, Nachrichten zu verfassen und zu verbreiten.</p>
<p>Schlie&szlig;lich bin ich ein Anarchist, weil ich gegen die Paranoia,
 die die Gesellschaft durch die Manipulation der Furcht der Leute in Beschlag
 nimmt, stehe. Ich bin entschieden gegen die Kriminalisierung, Sammlung
 personenbezogener Daten und Unterdr&uuml;ckungsprozesse, die durch die
 Obrigkeit gegen die Armen, das gemeine Volk und die Aktivisten gef&uuml;hrt
 werden. Unn&ouml;tig zu erw&auml;hnen, da&szlig; wir Widerstand leisten
 m&uuml;ssen.</p>
<p><tt>&middot;&nbsp;&middot;&nbsp;&middot;</tt></p>
<p>Ich bin ein Anargeek, weil ich bereit bin, Neugierde und Fachwissen
 mit ethischen &Uuml;berlegungen und politischen Methoden zu vereinen.
 W&auml;hrend der Gedanke den Weg bereitet durch Deutung und Lenkung,
 erweitert die Anwendung den Gedanken und schafft neuen Ide&euml;n eine
 konkrete Ausdrucksm&ouml;glichkeit.</p>
<p>Weiterhin bin ich ein Anargeek, weil ich in einer Gesellschaft leben
 m&ouml;chte, die auf Selbstbestimmung, freier Zusammenarbeit und
 gemeinschaftlicher Intelligenz basiert. Darum unterst&uuml;tze ich die
 Open-Source-Bewegung, die durch die weltweite freiwillige Zusammenarbeit
 Tausender zustandekommt, jedem erlaubend, Computerprogramme nicht nur zu
 teilen und zu verstehen, sondern auch zu ver&auml;ndern und
 weiterzuverbreiten.</p>
<p>Ich bin ein Anargeek, weil ich mich weigere, von einem politischen
 oder auch einem Computersystem versklavt zu werden. W&auml;hrend Staaten
 die B&uuml;rger mit Gesetzen reglementieren, forciert propriet&auml;re
 Software sogenannte Standards. W&auml;hrend Autorit&auml;ten Aufst&auml;nde
 und Ver&auml;nderung durch Unterdr&uuml;ckung zu verhindern suchen, sind
 die gro&szlig;en Konzerne dabei, Alternativen zu ihnen durch Patente zu
 t&ouml;ten. Ich m&ouml;chte dazu in der Lage sein, mein Leben selbst in
 die Hand zu nehmen, genau so wie ich dazu f&auml;hig sein m&ouml;chte, die
 Werkzeuge, die ich nutze, zu verstehen, modifizieren oder zu erzeugen.</p>
<p>Ich bin au&szlig;erdem ein Anargeek, weil ich dem nie enden wollenden
 Konsumzwang, den der Kapitalismus, der immer und immer wieder G&uuml;ter
 erzeugt, wegschmei&szlig;t und Ressourcen verschwendet, w&auml;hrend er
 den Verstand der Leute manipuliert, erzwingt, widerstehen m&ouml;chte.
 Ich verwende Hardware, die andere als veraltet ansehen, weiter, belebe sie
 mit unbenutzten Komponenten sowie befreie sie mit offener Software. Ich mag
 es, die Grenzen aus der Mode gekommener Maschinen zu erforschen; statt
 verbrauchend sch&ouml;pferisch Kreativit&auml;t im Umgang mit dem System,
 Vorstellungskraft und Experimentierfreude bei meinen elektronischen
 Basteleien anwenden.</p>
<p>Ich bin ein Anargeek, weil ich es notwendig finde, einige der
 Einstellungen, die die Gemeinschaften, denen ich angeh&ouml;re, sich zu
 Eigen gemacht haben, aufzurei&szlig;en. Ich w&uuml;nsche, die radikale
 Linke und alternative Computerkulturen miteinander bekannt zu machen,
 mir scheint insbesondere wichtig, den Sexismus, der bei den Geeks und
 allgemein Technikern, Naturwissenschaftlern und Mathematikern verbreitet
 ist, anzufechten und einen kritischen Blick auf die extreme Spezialisierung
 und das Fachidiotentum im IT-Bereich zu werfen; genau so wichtig ist es
 aber auch, dem Bereich der Aktivisten die Augen f&uuml;r die Perspektiven
 der digitalen Welt zu &ouml;ffnen, w&auml;hrend sie dieser so oft
 verschlossen und zynisch gegen&uuml;berstehen.</p>
<p>Ich bin ebenfalls ein Anargeek, weil der Umgang mit Technik nun mal ein
 exzellentes Medium f&uuml;r das Verfassen und Verbreiten unabh&auml;ngiger
 Information bereitstellt. Daher nehme ich an Netzwerken zur Verbreitung
 von kontradiktiver bzw. autonomer Information, wider den offiziellen
 Standpunkt, wie Indymedia teil &ndash; einem selbst&auml;ndigen Medium, das
 &uuml;ber die ganze Welt verteilt offen f&uuml;r alle ist, das die Grenzen
 zwischen Handelnden, Zuschauenden und Journalisten aufbricht und Probleme
 zum Vorschein kommen l&auml;&szlig;t, die die Massenmedien vorsichtig
 ignorieren oder &uuml;ber die sie gar Desinformationen verbreiten.</p>
<p>Ich m&ouml;chte nicht dumm und nichtswissend bleiben, ebensowenig
 m&ouml;chte ich ein Besserwisser oder Fachidiot sein oder auf meinem
 Standpunkt stehen bleiben, ohne jemals hinzulernen zu wollen &ndash;
 auch darum bin ich ein Anargeek. Ich &ouml;ffne mich neuem Wissen,
 lerne und lehre, teile und entdecke F&auml;higkeiten, von denen ich
 noch nie geh&ouml;rt habe, schaue &uuml;ber den Tellerrand hinaus.
 Ich weigere mich anzuerkennen, da&szlig; &ndash; in einer Art
 traditioneller Hierarchie &ndash; die &Auml;lteren oder Vorgesetzten
 immer und &uuml;berall Recht haben, nur weil sie &auml;lter sind
 oder l&auml;nger partizipieren.</p>
<p>Schlie&szlig;lich bin ich ein Anargeek, weil ich glaube, da&szlig;
 Computer nicht nur Instrumente der Datensammlung, Beherrschung und
 Entfremdung darstellen, sondern auch als Hilfsmittel zur St&auml;rkung
 des Einzelnen, Selbstverwirklichung, Kommunikation und gesellschaftlichen
 Ver&auml;nderung genutzt werden k&ouml;nnen. Ich teile mein Wissen lieber,
 als es eifers&uuml;chtig f&uuml;r mich zu behalten; daher beteilige ich
 mich an Arbeitskreisen und Nutzergruppen oder stelle kollektive,
 nichtkommerzielle Werkzeuge und Dienste &ndash; autonome Server, freie
 Internetzug&auml;nge, Webseiten oder ohne Gegenleistung nutzbare
 Hardware &ndash; zur Verf&uuml;gung.</p>
<p><tt>&middot;&nbsp;&middot;&nbsp;&middot;</tt></p>
<p>Diese Grundsatzerkl&auml;rung nimmt keineswegs in Anspruch, f&uuml;r Dich
 zu sprechen. Es ist Dir vollkommen freigestellt, es teilweise anzunehmen,
 v&ouml;llig dahinterzustehen oder es total zur&uuml;ckzuweisen. Und weil es
 so viele Anargeeks wie Individu&euml;n gibt, ermuntere ich hiermit jeden, sein
 bzw. ihr eigenes Manifest zu schreiben und auszuf&uuml;hren, seine oder ihre
 Ide&euml;n auszuprobieren, das eigene Grafitti oder ASCII zu malen.</p>
<p>Wider den Personenkult, gegen blindes Folgen von Vorgesetzten und
 Passivit&auml;t! Jeder kann sich selbst neu erfinden und verwirklichen.</p>
<p>Dezember 2002,<br /><a
 href="mailto:darkveggy@anargeek.net">darkveggy</a>.</p>
<p>Deutsche &Uuml;bersetzung, M&auml;rz 2005,<br />von <a
 href="mailto:tg@mirbsd.org">mirabile</a>.</p>
<hr />
<h2 id="koffie">Official MirBSD&trade; coffee provider</h2>
<p>Thorsten Glaser drinks fairly traded anarcho-syndicalistic zapatist coffee
 (Caf&eacute; Libertad and others, e.g. Caf&eacute; So&ntilde;ador, Flores
 Mag&oacute;n, Espresso Rebeld&iacute;a, Met (honey wine) with or without few
 espresso beans, etc.) from <a href="http://www.cafe-libertad.de/">Caf&eacute;
 Libertad &ndash; Kaffeekooperative</a> (they also have a polyglot (multilingual)
 ordering page).</p>
