<small class="rcsid">$MirOS: www/content/YW5hcmdlZWs_.inc,v 1.1 2005/03/17 00:01:39 tg Exp $</small>
<h1><a href="http://anargeek.net/">Anargeek</a></h1>
<h2>Why this page?</h2>
<p>On <a href="http://www.fosdem.org/">FOSDEM</a> 2005 some boy walked past
 me and gave me a paper containing the &quot;anargeek manifesto&quot; since
 he saw my laptop being full of BSD, <a href="http://koeln.ccc.de/">CCC</a>
 and <a href="http://fau.netzladen.org/">FAU-IAA</a> stickers.</p>
<p>I consider the <a href="http://www.netzladen.org/">Netzladen</a> members
 all to be Anargeeks, and even the <tt>HolaBSDng</tt> gang (i.e. the public
 relationship &quot;common exterior frontier&quot; of Holarse (not the game
 project), MirOS and BOSng), which is how we call ourselves at exhibitions,
 consists mainly of anargeeks of more or less strong flavour.</p>
<p>I've translated the English language version of the "Anargeek Manifesto"
 into German, and bsiegert@ compared it with the original, French language,
 version afterwards. I've created a logo to proudly show you're an anargeek
 (it's covered by <a href="http://wiki.mirbsd.de/LicenceTemplate">the MirOS
 Licence</a> for formal reasons), whose design idea got approved by various
 Netzladen members (hacker and anarcho-syndicalist).</p>
<p>The anargeek manifesto itself is covered by a "Creative Commons" Licence
 (<a href="http://creativecommons.org/licenses/by-nc-sa/2.0/">BY-NC-SA</a>)
 and so is the text below.</p>
<address><small>Thorsten Glaser &mdash; Benny Siegert</small></address>
<hr />
<table width="100%"><tr><td>
<h2>Das Anargeek Manifest</h2><pre>
&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;
&middot;&middot; m a n i f e s t &middot; e i n e s &middot;&middot;
&middot;&middot; a n a r g e e k &middot; v 1 . 0 b &middot;&middot;
&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;&middot;
</pre></td>
<td style="width:160px;"><img src="/pics/anargeek.png" alt="Anargeek Emblem" /></td></tr></table>
<p>Ich bin ein Anargeek. Ein Anarchist und Geek, und mehr.</p>
<p>&middot; &middot; &middot;</p>
<p>Ich bin ein Geek, weil man mich zu denen z&auml;hlen kann, die es
 m&ouml;gen, diese seltsamen Ger&auml;te, die wir Computer nennen,
 zu nutzen, verstehen und ver&auml;ndern.</p>
<p>Ich bin auch ein Geek, weil ich neugierig bin, wie diese funktionieren.
 Ich frage mich, was man mit ihren Programmen machen kann. Und manchmal
 bin ich begeistert von den Funktionen und Anwendungen, die noch nicht
 entdeckt worden sind oder an die noch niemand gedacht hat.</p>
<p>Ich bin ein Geek, weil diese Maschinen ein Teil meines t&auml;glichen
 Lebens sind. Ich nutze sie als Uhr, Musikinstrument, Bibliothek,
 Schreibmaschine, Kaffeemaschine, als Telephon oder Notizblock. Aber
 haupts&auml;chlich sind sie mein Spielplatz. Ein Helfer bei Kommunikation,
 Erforschung und Kreativit&auml;t.</p>
<p>Ich bin ebenfalls ein Geek, weil ich digitale Kommunikation in mein
 Leben integriert habe. Fast jeden Tag, wenn nicht mehrere Male am Tag,
 lese ich meine eMail, verwalte Server im Internet, schaue nach dem
 Netzwerk, das ich nutze, informiere mich, lerne, tausche Wissen in Fora,
 Mailing-Listen und Newsgroups sowie unterschiedlichsten Webseiten aus;
 unterhalte mich und treffe Leute via IRC.</p>
<p>Schlie&szlig;lich bin ich ein Geek, weil ich diesen Terminus mag.
 Urspr&uuml;nglich war es eine Beleidigung, aber sp&auml;ter wurde es
 von denen, die es betrifft, f&uuml;r sich eingefordert, ins Gute
 gewandelt und hat die Wurzeln f&uuml;r eine Gemeinschaft gesetzt,
 genau wie es einige andere kulturelle Minderheiten taten.</p>
<p>&middot; &middot; &middot;</p>
<p>Ich bin ein Anarchist, weil ich eine Gesellschaft, die auf Dominierung
 basiert, zur&uuml;ckweise. Ich glaube, da&szlig; sich eigene St&auml;rke
 und gegenseitiger Respekt sind nicht nur gleichzeitig m&ouml;glich und
 w&uuml;nschenswert, sondern da&szlig; sie durch Gleichheit, Solidarit&auml;t
 und Eigenverantwortung erreicht werden k&ouml;nnen.</p>
<p>Auch bin ich ein Anarchist, weil mich die sozialen Strukturen, die
 Massenausnutzung, Leiden und Tod auf einer permanenten Basis verursachen, in
 Rage versetzen. Ich m&ouml;chte dabei helfen, dieses System niederzuschlagen,
 indem ich bei sozialen Aufst&auml;nden teilnehme und in Basisdemokratie bzw.
 &quot;grass roots&quot; Kollektiven eingebunden bin.</p>
<p>Ich bin ein Anarchist, weil ich mein t&auml;gliches Leben als eine
 Gelegenheit sehe, meine Prinzipien zu testen. Ich bin bereit, mit sozialen
 Normen zu brechen, zum Beispiel durch Verweigerung der Aufrufe zu Konsum
 und Wettbewerb; Entfremdung zur&uuml;ckzuweisen; durch Zersetzen von
 unterdr&uuml;ckerischem und dominantem Verhalten, durch Entwickeln von
 kollektiven und gleichberechtigenden Alternativen.</p>
<p>Ich bin auch ein Anarchist, weil ich &quot;offiziellen&quot; Informationen
 meist skeptisch gegen&uuml;berstehe; ich m&ouml;chte Massenmedien und
 institutionalisierten Medien kritisch begegnen, weil diese unsere Sicht
 der Dinge durch Auslassungen, L&uuml;gen und Falschinformationen tr&uuml;ben.
 Selbstzertifizierte Objektivit&auml;t zur&uuml;ckweisend suche ich nach
 anderen und neuen Wegen, mich selbst zu informieren und zu bilden, nach
 alternativen Mitteln, Nachrichten zu verfassen und zu verbreiten.</p>
<p>Schlie&szlig;lich bin ich ein Anarchist, weil ich gegen die Paranoia,
 die die Gesellschaft durch die Manipulation der Furcht der Leute in Beschlag
 nimmt, stehe. Ich bin entschieden gegen die Kriminalisation, Sammlung
 personenbezogener Daten und Unterdr&uuml;ckungsprozesse, die durch die
 Obrigkeit gegen die Armen, das gemeine Volk und die Aktivisten gef&uuml;hrt
 werden. Unn&ouml;tig zu erw&auml;hnen, da&szlig; wir Widerstand leisten
 m&uuml;ssen.</p>
<p>&middot; &middot; &middot;</p>
<p>Ich bin ein Anargeek, weil ich bereit bin, technologische Kreativit&auml;t
 und Fachwissen mit ethischen &Uuml;berlegungen und politischen Methoden
 zu vereinen. W&auml;hrend der Gedanke den Weg bereitet durch Deutung und
 Lenkung, erweitert die Anwendung den Gedanken und schafft neuen Ide&euml;n
 eine konkrete Ausdrucksm&ouml;glichkeit.</p>
<p>Weiterhin bin ich ein Anargeek, weil ich in einer Gesellschaft leben
 m&ouml;chte, die auf Selbstbestimmung, freier Zusammenarbeit und
 gemeinschaftlicher Intelligenz basiert. Darum unterst&uuml;tze ich die
 Open-Source-Bewegung, die durch die weltweite freiwillige Zusammenarbeit
 Tausender zustandekommt, jedem erlaubend, Computerprogramme nicht nur zu
 teilen und zu verstehen, sondern auch zu ver&auml;ndern und
 weiterzuverbreiten.</p>
<p>Ich bin ein Anargeek, weil ich mich weigere, von einem politischen
 oder auch einem Computersystem versklavt zu werden. W&auml;hrend Staaten
 die B&uuml;rger mit Gesetzen reglementieren, forciert propriet&auml;re
 Software sogenannte Standards. W&auml;hrend Autorit&auml;ten Aufst&auml;nde
 und Ver&auml;nderung durch Unterdr&uuml;ckung zu verhindern suchen, sind
 die gro&szlig;en Konzerne dabei, Alternativen zu ihnen durch Patente zu
 t&ouml;ten. Ich m&ouml;chte dazu in der Lage sein, mein Leben selbst in
 die Hand zu nehmen, genau so wie ich dazu f&auml;hig sein m&ouml;chte, die
 Werkzeuge, die ich nutze, zu verstehen, modifizieren oder zu erzeugen.</p>
<p>Ich bin au&szlig;erdem ein Anargeek, weil ich dem nie enden wollenden
 Konsumzwang, den der Kapitalismus, der immer und immer wieder G&uuml;ter
 erzeugt, wegschmei&szlig;t und Ressourcen verschwendet, w&auml;hrend er
 den Verstand der Leute manipuliert, erzwingt, widerstehen m&ouml;chte.
 Ich verwende Hardware, die andere als veraltet ansehen, weiter, belebe sie
 mit unbenutzten Komponenten weiter, befreie sie mit offener Software. Ich
 mag es, die Grenzen alter Maschinen zu finden, sch&ouml;pferisch statt
 verbrauchend, in einem Versuch, die Vorstellungskraft und Politik zu
 vermischen. (???)</p>
<p>Ich bin ein Anargeek, weil ich es notwendig finde, einige der
 Einstellungen, die die Gemeinschaften, denen ich angeh&ouml;re, sich zu
 Eigen gemacht haben, aufzurei&szlig;en. Ich w&uuml;nsche, die radikale
 Linke und alternative Computerkulturen miteinander bekannt zu machen,
 und dies aus mehreren Gr&uuml;nden: es ist n&ouml;tig, die stark sexistische
 Grundeinstellung, die im Geek-sein wie in allen technischen Berufen
 verankert ist, anzufechten; genau so ist es wichtig, militante Bewegungen
 das digitale Potential verstehen zu lassen.</p>
<p>Ich bin ebenfalls ein Anargeek, weil der Umgang mit Technik nun mal ein
 exzellentes medium f&uuml;r das Verfassen und Verbreiten unabh&auml;ngiger
 Information bereitstellt. Daher nehme ich an Gegeninformationsnetzwerken
 wie Indymedia teil &ndash; ein autonomes Medium, das &uuml;ber die ganze
 Welt verteilt offen f&uuml;r alle ist, das die Grenzen zwischen Handelnden,
 Zuschauenden und Journalisten aufbricht und Probleme zum Vorschein kommen
 l&auml;&szlig;t, die die Massenmedien vorsichtig ignorieren oder &uuml;ber
 die sie gar Disinformationen verbreiten.</p>
<p>Schlie&szlig;lich bin ich ein Anargeek, weil ich glaube, da&szlig; wenn
 Computer soziale Kontrolle und Beherrschung aus&uuml;ben k&ouml;nnen, sie
 auch als Instrumente zur St&auml;rkung des Einzelnen, Kommunikation und
 Aufwiegelung genutzt werden k&ouml;nnen. Weil Wissen geteilt n&uuml;tzlicher
 ist als wenn man es f&uuml;r sich beh&auml;lt, nehme ich auch an
 Arbeitskreisen zum Teilen von Fertigkeiten teil, oder involviere mich darin,
 kollektive, nichtkommerzielle Werkzeuge und Dienste wie autonome Server,
 freien Internetzugang, Webseiten oder Hardwarespendenprojekte zu
 f&ouml;rdern.</p>
<p>&middot; &middot; &middot;</p>
<p>Diese Grundsatzerkl&auml;rung nimmt keineswegs in Anspruch, f&uuml;r Dich
 zu sprechen. Es ist Dir vollkommen freigestellt, es teilweise anzunehmen,
 v&ouml;llig dahinterzustehen oder es total zur&uuml;ckzuweisen. Und weil es
 so viele Anargeeks wie Individuen gibt, ermuntere ich hiermit jeden, sein
 bzw. ihr eigenes Manifest zu schreiben und auszuf&uuml;hren, seine oder ihre
 Ide&euml;n auszuprobieren, das eigene Grafitti oder ASCII zu malen.</p>
<p>Gegen einen Personenkult, blindes Folgen von Vorgesetzten und
 Passivit&auml;t! Jeder kann sich selber neu erfinden und realisieren.</p>
<p>Dezember 2002,<br /><a
 href="mailto:darkveggy@anargeek.net">darkveggy</a>.</p>
<p>Deutsche &Uuml;bersetzung, M&auml;rz 2005, von <a
 href="mailto:tg@mirbsd.org">mirabile</a>.</p>
