<small class="rcsid">$MirOS: www/content/YW5uLTg_.inc,v 1.1 2005/10/07 22:21:56 tg Exp $</small>

<p style="font-size:smaller; text-align:right;">Codename: WTF we have a release?</p>

<h1>MirOS #8</h1>

<p style="font-size:smaller; text-align:right; font-variant:small-caps;">All
 your build system are belong to us!</p>

<p>The MirOS Project is proud to announce the immediate release of MirOS XP,
 consisting of MirOS BSD #8 and the MirPorts Framework. This release is the
 first in the MIROS_8 branch and still highly experimental.</p>

<p>[...]</p>
