<small class="rcsid">$MirBSD: www/content/YWJvdXQ_.inc,v 1.20 2005/01/07 02:47:03 tg Exp $</small>
<p class="admin">ATTN: Candidate for moving into MirWiki!</p>
<h1>About MirOS, MirBSD, MirPorts</h1>

<p>The MirOS project presents a Europe-based open source operating
 system with goals similar to these of the other BSD projects to
 the skilled system administrator.</p>

<p>MirOS currently is available as a BSD flavour, which originated
 as an OpenBSD patchkit, but has grown very much on its own, though
 still being synchronized with the ongoing development of OpenBSD,
 thus inheriting most of its good security history. This variant is
 also called &quot;MirBSD&quot;, but the usage of that word to denote
 MirOS BSD is highly deprecated.</p>

<p>MirOS will provide the same look and feel, the same userland, just
 with a Linux 2.6 kernel, by means of &quot;MirLinux&quot;, which is
 due not earlier (but most likely much later) than summer of 2005.</p>
<p>In addition to that, we might start a port of MirOS to the <a
 href="http://www.microsoft.com/windows/sfu/">platform we call Interix</a>
 (because it's the Interix (sub-)kernel) if we get enough documentation
 and maybe (freely reusable) code from Microsoft&reg; - we would even
 do a port if some of the stuff has to be placed in contrib/ only.</p>

<p>You might want to read about the Project's <a href="/?mail">mailing
 lists</a> or the <a href="/?history">History of MirOS</a>.</p>

<p>Read more about the <a href="/?features">Features</a> of MirOS or
 the <a href="/?devel">People</a> behind it.</p>

<p><a href="/?about-logo">[insert MirOS logo here]</a></p>

<h1>Licencing information</h1>

<p>For the full copyright statement of MirOS, please refer to the
 <a href="/cvs.cgi/src/share/man/man0/COPYRIGHT">COPYRIGHT
 file</a>, whose <a
 href="/cvs.cgi/~checkout~/src/share/man/man0/COPYRIGHT?rev=HEAD&amp;content-type=text/plain">latest
 version</a> is available by means of CVSweb.</p>

<p>For material added to MirOS, we prefer it is placed under our
 <a href="/cvs.cgi/src/share/misc/licence.template">licence
 template</a> which is currently under reviewal by the <a
 href="http://www.opensource.org/">OSI</a>.</p>

<p>For a list of other licences, please refer to the <a
 href="/cvs.cgi/src/share/doc/LICENCE">LICENCE overview</a>
 and the respective licences (GNU GPL, GNU LGPL, Apache&trade;/mod_ssl
 licence, XFree86&trade; advertising clause, Sendmail licence, Netscape
 Public Licence).</p>
