<!-- PageID: about -->
<small class="rcsid">$MirOS: www/content/YWJvdXQ_.inc,v 1.9 2006/01/27 00:14:27 tg Exp $</small>
<h1>About MirOS, MirBSD, MirPorts</h1>

<p>The MirOS project presents a Europe-based open source operating
 system with goals similar to these of the other BSD projects to
 the skilled system administrator.</p>

<p>MirOS currently is available as a BSD flavour which originated
 as an OpenBSD patchkit, but has grown very much on its own, though
 still being synchronized with the ongoing development of OpenBSD,
 thus inheriting most of its good security history. This variant is
 also called &quot;MirBSD&quot;, but the usage of that word to denote
 MirOS BSD is highly deprecated.</p>

<p>MirOS will provide the same look and feel, the same userland, just
 with a Linux 2.6 kernel, by means of &quot;MirLinux&quot; which is
 due not earlier (but most likely much later) than summer of 2005.</p>
<p>In addition to that, we might start a port of MirOS to the <a
 href="http://www.microsoft.com/windows/sfu/">platform we call Interix</a>
 (because it's the Interix (sub-)kernel) if we get enough documentation
 and maybe (freely reusable) code from Microsoft&reg; - we would even
 do a port if some of the stuff has to be placed in contrib/ only.</p>

<p>You might want to read about the Project's <a href="/?mail">mailing
 lists</a> or the <a href="/?history">History of MirOS</a>.</p>

<p>Read more about the XXX Features XXX of MirOS or
 the <a href="/?devel">People</a> behind it.</p>

<h3>Licencing information</h3>

<p>For the full copyright statement of MirOS, please refer to the
 <a href="/cvs.cgi/src/share/doc/legal/">1stREAD and LICENCE</a>
 files; the <a href="/LICENCE">website licence</a> is also available.
 We prefer new code and documentation to be placed under our
 <a href="/?licence">licence template</a> which is compliant to the
 Open Source Definition and conforms to the Debian Free Software
 Guidelines. (Don't be scared by the length of the template, the actual
 licence stops after the first *- followed by instructions only, and
 is way below 1 Kibibyte.)</p>
