<!-- PageID: getting -->
<small class="rcsid">$MirOS: www/content/Z2V0dGluZw__.inc,v 1.15 2006/07/30 21:18:36 tg Exp $</small>
<h1>How to get MirOS</h1>

<p>MirOS consists of several parts: the base system (including X11), the
 MirPorts framework, and the source tree.</p>

<h2>On a CD</h2>

<p>You can get MirOS CDs in exchange for a donation of your choice at events
 where the MirOS developers have a booth. Normally, this booth is held together
 with the <a href="http://www.allbsd.de/">AllBSD</a> people. Events with a
 MirOS booth include:</p>

<ul>
 <li><a href="http://www.froscon.org/">FROSCON</a>, St. Augustin (near Bonn),
  .de</li>
 <li><a href="http://www.ccc.de/congress/">Chaos Communication Congress</a>, Berlin,
  .de</li>
 <li><a href="http://www.fosdem.org/">FOSDEM</a>, Bruxelles, .be</li>
</ul>

<p>You can also ask <a href="mailto:tg@66h.42h.de">Thorsten</a> for install
 CDs and <a href="mailto:bsiegert@66h.42h.de">Benny</a> for CDs with binary
 packages, distfiles and MirPorts on them. They will ship per snail mail;
 the usual pricing is: at least 15 EUR per CD (25 for both) to Germany.
 We cannot ship to outside the European Union and Switzerland.</p>

<h2>Downloads</h2>

<p>Please verify the gzsig(1) signature of the checksums and the integrity of
 all checksummed files!</p>

<p>The preferred download method is BitTorrent, as it means lower bandwidth
 costs for us. You will find all downloads on <a
 href="http://f.scarywater.net/miros/">our tracker page</a>. <b>Please leave
 the download window open for as long as possible after you finish.</b></p>

<table style="border: 1px solid #333333">
 <tr>
  <th></th>
  <th style="border: 1px solid #333333">Download</th>
 </tr><tr>
  <td style="border: 1px solid #333333"><p><b>MirOS #9semel (stable, i386)</b></p>
   <p>Released 25.06.2006 (<a href="http://marc.theaimsgroup.com/?m=115110448632235">Release
    announcement</a>).</p></td>
  <td style="border: 1px solid #333333"><p><a href="/MirOS/ISOs/MIR60625.ISO">via HTTP</a> &ndash;
   <a href="http://f.scarywater.net/miros/">via BitTorrent</a></p></td>
 </tr><tr>
  <td style="border: 1px solid #333333"><p><b>MirOS #8semel (stable, i386)</b></p>
   <p>Released 23.12.2005 (<a href="/?ann-8">Release
    announcement</a>).</p></td>
  <td style="border: 1px solid #333333"><p><a href="/MirOS/v8/i386/">via HTTP</a> &ndash;
   <a href="http://f.scarywater.net/miros/">via BitTorrent</a></p></td>
 </tr><tr>
  <td style="border: 1px solid #333333"><p><b>MirOS #7quater (stable, sparc)</b></p>
   <p>Released in 2003.</p></td>
  <td style="border: 1px solid #333333"><p><a href="/MirOS/v7/bsd/sparc/">via HTTP</a> &ndash;
   <a href="http://f.scarywater.net/miros/">via BitTorrent</a></p></td>
 </tr><tr>
  <td style="border: 1px solid #333333"><p><b>Development snapshots (current, i386 or sparc)</b></p></td>
  <td style="border: 1px solid #333333"><p><a href="/MirOS/current/">via HTTP</a> &ndash;
   <a href="http://f.scarywater.net/miros/">via BitTorrent</a></p></td>
 </tr>
</table>

<p>More information about <a href="/?anoncvs">anonCVS</a> and
 anonRSYNC can be found on the <a href="/?mirrors">Mirrors</a> list.</p>
