<small class="rcsid">$MirOS: www/content/ZG9jcw__.inc,v 1.2 2005/01/07 02:47:03 tg Exp $</small>
<p class="admin">ATTN: Candidate for moving into MirWiki!</p>
<h1>Documentation</h1>

<p>There should probably be some documentation here.
 For now, there's only the <a href="http://wiki.mirbsd.de/">MirWiki</a>
 and the following unsorted list of various documents:</p><ul>
<li><a href="/?bsd-intro">BSD Introduction</a>
 (English, generic)</li>
<li><a href="/?mirwarum">Why MirBSD?</a> &ndash; Warum MirBSD?
 (<strong>German</strong>)</li>
<li><a href="/?devel">Developers</a>
 &ndash; Who are you crazy people?</li>
<li><a href="/?mail">Mailing Lists</a>
 &ndash; How do I reach you?</li>
<li><a href="/?features">Features &amp; Caveats</a>
 (unmaintained, for #7 mostly)</li>
<li><a href="/?history">History of MirOS</a>
 (pretty accurate)</li>
<li> &mdash; Problem Solution &mdash;</li>
<li><a href="/?ipv6-sixxs">IPv6 with SixXS</a>
 (how to get connectivity; outdated but works)</li>
<li><a href="/?isdn">ISDN HOWTO</a>
 (quickstart, how to do ISDN with MirBSD)</li>
</ul>

<p>Most of the documentation above will move to the MirWiki.</p>
