<!-- PageID: docs -->
<small class="rcsid">$MirOS: www/content/ZG9jcw__.inc,v 1.4 2005/12/07 00:58:36 tg Exp $</small>
<h1>Documentation</h1>

<p>There should probably be some documentation here.
 For now, there's only the <big><big><a href="http://wiki.mirbsd.de/">MirWiki</a></big></big>
 and the following unsorted list of various documents:</p><ul>
<li><a href="/?mksh">MirbsdKsh</a> (software produced by us)</li>
<li><a href="/?jupp">JuppEditor</a> (software forked by us)</li>
<li><a href="/?bsd-intro">BSD Introduction</a>
 (English, generic)</li>
<li><a href="/?mirwarum">Why MirBSD?</a> &ndash; Warum MirBSD?
 (<strong>German</strong>)</li>
<li><a href="/?devel">Developers</a>
 &ndash; Who are you crazy people?</li>
<li><a href="/?mail">Mailing Lists</a>
 &ndash; How do I reach you?</li>
<li><a href="/?history">History of MirOS</a>
 (pretty accurate)</li>
<li> &mdash; Problem Solution &mdash;</li>
<li><a href="/?ipv6-sixxs">IPv6 with SixXS</a>
 (how to get connectivity; outdated but works)</li>
<li><a href="/?isdn">ISDN HOWTO</a>
 (quickstart, how to do ISDN with MirBSD)</li>
</ul>
