<small class="rcsid">$MirBSD: www/content/ZGV2ZWw_.inc,v 1.19 2005/01/23 01:24:18 tg Exp $</small>
<p class="admin">ATTN: Candidate for moving into MirWiki!</p>
<h1>MirOS Project Members</h1>
<p>The links below show details about every MirOS Project
 team member - developer or contributor. The content is whatever
 the person wants to disclose about himself.</p>
<h2>Developers - active and inactive</h2><ul>
<li><a href="http://wiki.mirbsd.de/BennySiegert">bsiegert@</a> (Benny Siegert)</li>
<li>cnuke@ (Josef S&ouml;ntgen)</li>
<li>dave@ (Dave Steinberg)</li>
<li><a href="http://wiki.mirbsd.de/StephenPaskaluk">sap@</a> (Stephen Paskaluk)</li>
<li><a href="http://wiki.mirbsd.de/MirAbile">tg@</a> (Thorsten Glaser)</li>
<li><a href="/?devel.tyler">tyler@</a> (R. Tyler Ballance)</li>
<li>wbx@ (Waldemar Brodkorb)</li>
</ul><h2>Sponsors</h2>
<h4>Webspace</h4><ul>
<li>Robin S. Socha (historic)</li>
<li>http://www.bsdadvocacy.org/</li>
</ul><h4>misc. services</h4><ul>
<li>Bastian Blank</li>
<li>Andreas Kupfer</li>
<li>Eike Frost</li>
<li>Eimann (http://eimann.etherkiller.de/)</li>
</ul>
