<!-- PageID: devel -->
<small class="rcsid">$MirOS: www/content/ZGV2ZWw_.inc,v 1.12 2006/04/10 12:39:11 tg Exp $</small>
<h1>MirOS Project Members</h1>
<p>The links below show details about every MirOS Project
 team member - developer or contributor. The content is whatever
 the person wants to disclose about himself.</p>
<h2>Developers</h2>
<h3>active</h3><ul>
<li><a href="http://wiki.mirbsd.de/BennySiegert">bsiegert@</a> (Benny Siegert)</li>
<li>tg@ (Thorsten Glaser)</li>
</ul><h3>inactive</h3><ul>
<li>cnuke@ (Josef S&ouml;ntgen)</li>
<li>dave@ (Dave Steinberg)</li>
<li><a href="http://wiki.mirbsd.de/StephenPaskaluk">sap@</a> (Stephen Paskaluk)</li>
<li><a href="http://wiki.mirbsd.de/RTyler">tyler@</a> (R. Tyler Ballance)</li>
<li>wbx@ (Waldemar Brodkorb)</li>
</ul><h2>Sponsors</h2>
<h4>Webspace</h4><ul>
<li>Bastian "waldi" Blank</li>
<li>Eimann (historic)</li>
<li>Robin S. Socha (historic)</li>
<li>Joshua C. Steele (historic)</li>
</ul><h4>DNS</h4><ul>
<li>Ingo "bogus" Dyck</li>
<li>Andreas "ScottyTM" Kupfer</li>
</ul><h4>mailing lists</h4><ul>
<li>Diana Eichert</li>
<li>The guys at GMane</li>
<li>The guys at marc.theaimsgroup.com</li>
</ul><h4>mirroring</h4><ul>
<li>Eike Frost</li>
<li>Hiroki Sato and the guys at allbsd.org</li>
</ul><h4>services</h4><ul>
<li>Der Verein <a href="http://www.trash.net/verein/">trash.net</a></li>
</ul>
