<!-- PageID: devel -->
<small class="rcsid">$MirOS: www/content/ZGV2ZWw_.inc,v 1.15 2006/04/19 19:01:16 tg Exp $</small>
<h1>MirOS Project Members</h1>
<p>The links below show details about every MirOS Project
 team member - developer or contributor. The content is whatever
 the person wants to disclose about himself.</p>
<h2>Developers</h2>
<h3>active</h3><ul>
<li><a href="http://wiki.mirbsd.de/BennySiegert">bsiegert@</a> (Benny Siegert)</li>
<li>tg@ (Thorsten Glaser)</li>
</ul><h3>inactive</h3><ul>
<li>cnuke@ (Josef S&ouml;ntgen)</li>
<li>dave@ (Dave Steinberg)</li>
<li><a href="http://wiki.mirbsd.de/StephenPaskaluk">sap@</a> (Stephen Paskaluk)</li>
<li><a href="http://wiki.mirbsd.de/RTyler">tyler@</a> (R. Tyler Ballance)</li>
<li>wbx@ (Waldemar Brodkorb)</li>
</ul><h2 id="sponsors">Sponsors</h2>
<h3>Webspace</h3><ul>
<li>Bastian "waldi" Blank</li>
<li>Eimann (historic)</li>
<li>Robin S. Socha (historic)</li>
<li>Joshua C. Steele (historic)</li>
<li>Andreas "gecko2" Gockel</li>
</ul><h3>DNS</h3><ul>
<li>Ingo "bogus" Dyck</li>
<li>Andreas "ScottyTM" Kupfer</li>
</ul><h3>mailing lists</h3><ul>
<li>Diana Eichert</li>
<li>The guys at GMane</li>
<li>The guys at marc.theaimsgroup.com</li>
</ul><h3>mirroring</h3><ul>
<li>Eike Frost</li>
<li>Hiroki Sato and the guys at allbsd.org</li>
<li>Andreas "gecko2" Gockel</li>
</ul><h3>services</h3><ul>
<li>Der Verein <a href="http://www.trash.net/verein/">trash.net</a></li>
<li>The people at <a href="http://www.allbsd.de/">AllBSD.de</a></li>
</ul><h3>donations</h3><ul>
<li>See the <a href="/?danke#donators">donations</a> page</li>
</ul>
