<!-- PageID: fornow -->
<small class="rcsid">$MirOS: www/content/Zm9ybm93.inc,v 1.3 2006/05/09 09:25:37 tg Exp $</small>
<h1>MirOS Website (for now)</h1>

<h2>About this page</h2>
<p>This page tries to clean up the mess which is called a pathetic
 excuse for a website by at least informing the users what they can
 expect. Due to constant lack of manpower, all other pages (which
 are still accessible via the list on the left) are basically not
 maintained or updated. The <a href="/?overview">Overview</a> is
 pretty comprehensible, though.</p>
<p>There is a commitment to keep this very page on both the <a
 href="http://mirbsd.mirsolutions.de/?fornow">MirSolutions</a> and the <a
 href="http://mirbsd.de/fornow">Zope</a> server current and synched.
 We can also be reached via IRC (<a href="/?irc">web page</a> or <a
 href="http://mirbsd.de/irc">Zope</a>).</p>
<p>If the MirSolutions webserver is not reachable, try alternative DNS
 names: <a href="http://www.mirbsd.org/">mirbsd.org</a> (now preferred)
 or <a href="http://www.66h.42h.de/">www.66h.42h.de</a> (may point to
 another mirror which may differ from the MirSolutions server). We do
 have both server reachability and DNS issues from time to time.</p>

<h2>Current versions</h2>
<p>This is a list of the as-of-now current versions of whatever
 the MirOS Project offers, structured like this: the name of the
 work (linking to a directory containing all versions; you might
 want to adjust the mirror though), and the current version.</p><ul>
<li>MirOS RELEASE<ul>
  <li><a href="/MirOS/ISOs/">ISO (i386)</a> 2005-12-23 (MIR51223.ISO)</li>
  <li><a href="/MirOS/v8/">direct download</a> 2005-12-23 (MirOS #8)</li>
  <li><a href="/MirOS/ISOs/">ISO (sparc)</a> 2004-06-05 (mbsd7quater.iso)</li>
  <li><a href="/MirOS/v7.4/bsd/sparc/">direct download</a> MirOS #7quater</li>
 </ul></li>
<li>MirOS CURRENT<ul>
  <li><a href="http://f.scarywater.net/miros/">BitTorrent</a> 2006-05-29</li>
  <li><a href="/MirOS/current/i386/">direct download (i386)</a> 2006-04-20</li>
  <li><a href="/MirOS/ISOs/">ISO (i386)</a> 2006-04-20</li>
  <li>(nothing yet for sparc)</li>
 </ul></li>
<li><a href="/MirOS/current/">MirPorts Framework</a> 2006-04-20</li>
<li><a href="/MirOS/dist/mir/mksh/">mksh</a> R26c</li>
<li><a href="/MirOS/dist/mir/make/">MirMake</a> 2006-03-27</li>
<li><a href="/MirOS/dist/jupp/">jupp</a> joe-3.1jupp5</li>
<li><a href="/MirOS/BT/">mirrored torrents</a> (see above)</li>
<li><a href="/MirOS/CVS/">CVS Repo</a> 2006-04-12</li>
<li><a href="/MirOS/CVS/">CVS root</a> historic</li>
<li>AnonCVS: <tt>_anoncvs@mirbsd.org:/cvs</tt></li>
<li>AnonRSYNC: <tt>_anoncvs@mirbsd.org:/cvs</tt></li>
<li><a href="http://www.mirbsd.org/cvs.cgi/">CVSweb</a></li>
<li>(more cvs mirrors can be found <a href="/?overview">externally</a>)</li>
</ul>

<h2>Index of files on mirbsd.de</h2><ul>
<li><a href="http://mirbsd.de/MirOS-Licence">MirOS-Licence</a> (our licence template)</li>
<li><a href="http://mirbsd.de/ISC-Licence">ISC-Licence</a> (ISC/OpenBSD)</li>
<li><a href="http://mirbsd.de/impressum">impressum</a> (German)</li>
<li><a href="http://mirbsd.de/irc">irc</a> info</li>
<li><a href="http://mirbsd.de/root">root</a> = standard page (redirector)</li>
<li><a href="http://mirbsd.de/fornow">fornow</a> (this page)</li>
</ul>

<h2>Other useful links</h2><ul>
<li><a href="http://mira.66h.42h.de/pub/jdos16.exe">Jupp 2.8 for MS-DOS&reg;</a></li>
<li><a href="http://mira.66h.42h.de/pub/KBDmir1U.exe">Keyboard driver with Meta key for Windows NT&reg;/2000</a> and up</li>
<li><a href="http://mira.66h.42h.de/pub/openntpd-3.7p1-leapsecs.diff">Leap second diff against portable OpenNTPD 3.7p1</a> (see <a href="http://www.openntpd.org/">OpenNTPD homepage</a>)</li>
</ul>
