<!-- PageID: faq.es -->
<small class="rcsid">$MirOS: www/content/ZmFxLmVz.inc,v 1.2 2005/12/15 18:24:41 tg Exp $</small>

<h1>FAQ en espa&ntilde;ol</h1>

<h2>Otros linguas</h2>

<ul>
<li><a href="/?faq">ingles</a> (english)</li>
</ul>

<h2 id="toc">Table of Contents</h2>

<ol>
<li><a href="#s_comm">General</a><ul>
 <li><a href="#comm_donate">&iquest;Os alimentais del aire o que chicos?</a></li>
 <li><a href="/?about">De MirOS</a></li>
 <li>...</li>
</ul></li>
<li><a href="#s_down">Descargando</a><ul>
 <li><a href="#down_bt">&iquest;Donde est&aacute; el servidor BitTorrent?</a></li>
 <li>...</li>
</ul></li>
<li><a href="#s_inst">Instalaci&oacute;n</a><ul>
 <li>...</li>
</ul></li>
<li><a href="#s_adm">Administraci&oacute;n</a><ul>
 <li>...</li>
</ul></li>
<li><a href="#s_soft">Ports &amp; Paquetes</a><ul>
 <li>...</li>
</ul></li>
</ol>

<hr />

<h2 id="s_comm">General</h2>

<h3 id="comm_donate">&iquest;Os alimentais del aire o que chicos?</h3>
<p>No, claro. Hacemos este trabajo com ovoluntarios adem&aacute;s
 de nuestro trabajo a diario. Puedes <a href="/?danke">ayudarnos</a>
 dandonos apoyo
 personalmente. Dado que inertimos todo nuestro tiempo libre
 con MirOS, no esperes que podamos trabajar duro con ello.</p>
<small><a href="#toc">back</a></small>

<h2 id="s_down">Descargando</h2>

<h3 id="down_bt">&iquest;Donde est&aacute; el servidor BitTorrent?</h3>
<p>Los torrents de MirOS estt&aacute;n alojados en un largo tracker
 alcanzable en <a href="http://f.scarywater.net/miros/">http://f.scarywater.net/miros/</a>
 (por favor, considera
 patrocinar el administrador del servidor tambi&eacute;n).</p>
<small><a href="#toc">back</a></small>

<h2 id="s_inst">Instalaci&oacute;n</h2>

<h2 id="s_adm">Administraci&oacute;n</h2>

<h2 id="s_soft">Ports &amp; Paquetes</h2>

