<small class="rcsid">$MirOS$</small>

<h1>FAQ</h1>

<h2 id="toc">Table of Contents</h2>

<ol>
<li><a href="#s_comm">General</a><ul>
 <li><a href="#comm_donate">Do you guys eat air or what?</a></li>
 <li>...</li>
</ul></li>
<li><a href="#s_down">Downloading</a><ul>
 <li><a href="#down_bt">Where is the BitTorrent server?</a></li>
 <li>...</li>
</ul></li>
<li><a href="#s_inst">Installation</a><ul>
 <li>...</li>
</ul></li>
<li><a href="#s_adm">Administration</a><ul>
 <li>...</li>
</ul></li>
<li><a href="#s_soft">Ports &amp; Packages</a><ul>
 <li>...</li>
</ul></li>
</ol>

<hr />

<h2 id="s_comm">General</h2>

<h3 id="comm_donate">Do you guys eat air or what?</a></h3>
<p>Of course not. We do this as volunteer work besides our normal
 day job. You can help us by <a href="/?danke">donating</a> to
 support us personally. Since we already invest nearly all our spare
 time into MirOS, you cannot expect us to work harder on it or make
 earmarked donations, though.</p>
<small><a href="#toc">back</a></small>

<h2 id="s_down">Downloading</h2>

<h3 id="down_bt">Where is the BitTorrent server?</a></h3>
<p>The MirOS torrents are hosted at a large tracker reachable at <a
 href="http://f.scarywater.net/miros/">http://f.scarywater.net/miros/</a>
 (plase consider sponsoring the server administrator as well).</p>
<small><a href="#toc">back</a></small>

<h2 id="s_inst">Installation</h2>

<h2 id="s_adm">Administration</h2>

<h2 id="s_soft">Ports &amp; Packages</h2>

