<!-- Editing note: this file is reverse chronologically
     sorted, i.e. add new entries at the top not bottom -->

<small class="rcsid">$MirOS$</small>

<h1>Errata</h1>

<h2>Errata for MirOS #8</h2>

<h3>Errata for MirOS #8semel</h3>
<p>Updates for the errata below can be found in the directory
 <tt>/MirOS/v8.1/updates/</tt> on your favourite <a
 href="/MirOS/v8.1/updates/">mirror</a>.</p><ul>
<li>An updated MirPorts Framework installation set (snapshot) is
 available as <tt>ports8.ngz</tt> (usually taken from the last
 snapshot of MirOS-current).</li>
<li>An updated ld(1) and shared libraries with DT_RPATH set will
 be available as <tt>i386/shlibs.ngz</tt> soon.</li>
</ul>
