/*	$MirOS$	*/

/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from;	MirOS: src/sys/compat/openbsd/syscalls.master,v 1.6 2005/11/23 19:18:42 tg Exp 
 */

/* syscall: "syscall" ret: "int" args: "int" "..." */
#define	OPENBSD_SYS_syscall	0

/* syscall: "exit" ret: "void" args: "int" */
#define	OPENBSD_SYS_exit	1

/* syscall: "fork" ret: "int" args: */
#define	OPENBSD_SYS_fork	2

/* syscall: "read" ret: "ssize_t" args: "int" "void *" "size_t" */
#define	OPENBSD_SYS_read	3

/* syscall: "write" ret: "ssize_t" args: "int" "const void *" "size_t" */
#define	OPENBSD_SYS_write	4

/* syscall: "open" ret: "int" args: "char *" "int" "..." */
#define	OPENBSD_SYS_open	5

/* syscall: "close" ret: "int" args: "int" */
#define	OPENBSD_SYS_close	6

/* syscall: "wait4" ret: "pid_t" args: "pid_t" "int *" "int" "struct rusage_compat *" */
#define	OPENBSD_SYS_wait4	7

/* syscall: "ocreat" ret: "int" args: "char *" "mode_t" */
#define	OPENBSD_SYS_ocreat	8

/* syscall: "link" ret: "int" args: "char *" "char *" */
#define	OPENBSD_SYS_link	9

/* syscall: "unlink" ret: "int" args: "char *" */
#define	OPENBSD_SYS_unlink	10

				/* 11 is obsolete execv */
/* syscall: "chdir" ret: "int" args: "char *" */
#define	OPENBSD_SYS_chdir	12

/* syscall: "fchdir" ret: "int" args: "int" */
#define	OPENBSD_SYS_fchdir	13

/* syscall: "mknod" ret: "int" args: "char *" "mode_t" "dev_t" */
#define	OPENBSD_SYS_mknod	14

/* syscall: "chmod" ret: "int" args: "char *" "mode_t" */
#define	OPENBSD_SYS_chmod	15

/* syscall: "chown" ret: "int" args: "char *" "uid_t" "gid_t" */
#define	OPENBSD_SYS_chown	16

/* syscall: "break" ret: "int" args: "char *" */
#define	OPENBSD_SYS_break	17

/* syscall: "ogetfsstat" ret: "int" args: "struct statfs *" "long" "int" */
#define	OPENBSD_SYS_ogetfsstat	18

/* syscall: "olseek" ret: "long" args: "int" "long" "int" */
#define	OPENBSD_SYS_olseek	19

/* syscall: "getpid" ret: "pid_t" args: */
#define	OPENBSD_SYS_getpid	20

/* syscall: "mount" ret: "int" args: "const char *" "char *" "int" "void *" */
#define	OPENBSD_SYS_mount	21

/* syscall: "unmount" ret: "int" args: "char *" "int" */
#define	OPENBSD_SYS_unmount	22

/* syscall: "setuid" ret: "int" args: "uid_t" */
#define	OPENBSD_SYS_setuid	23

/* syscall: "getuid" ret: "uid_t" args: */
#define	OPENBSD_SYS_getuid	24

/* syscall: "geteuid" ret: "uid_t" args: */
#define	OPENBSD_SYS_geteuid	25

/* syscall: "ptrace" ret: "int" args: "int" "pid_t" "caddr_t" "int" */
#define	OPENBSD_SYS_ptrace	26

/* syscall: "recvmsg" ret: "ssize_t" args: "int" "struct msghdr *" "int" */
#define	OPENBSD_SYS_recvmsg	27

/* syscall: "sendmsg" ret: "ssize_t" args: "int" "const struct msghdr *" "int" */
#define	OPENBSD_SYS_sendmsg	28

/* syscall: "recvfrom" ret: "ssize_t" args: "int" "void *" "size_t" "int" "struct sockaddr *" "socklen_t *" */
#define	OPENBSD_SYS_recvfrom	29

/* syscall: "accept" ret: "int" args: "int" "struct sockaddr *" "socklen_t *" */
#define	OPENBSD_SYS_accept	30

/* syscall: "getpeername" ret: "int" args: "int" "struct sockaddr *" "socklen_t *" */
#define	OPENBSD_SYS_getpeername	31

/* syscall: "getsockname" ret: "int" args: "int" "struct sockaddr *" "socklen_t *" */
#define	OPENBSD_SYS_getsockname	32

/* syscall: "access" ret: "int" args: "char *" "int" */
#define	OPENBSD_SYS_access	33

/* syscall: "chflags" ret: "int" args: "char *" "u_int" */
#define	OPENBSD_SYS_chflags	34

/* syscall: "fchflags" ret: "int" args: "int" "u_int" */
#define	OPENBSD_SYS_fchflags	35

/* syscall: "sync" ret: "void" args: */
#define	OPENBSD_SYS_sync	36

/* syscall: "kill" ret: "int" args: "int" "int" */
#define	OPENBSD_SYS_kill	37

/* syscall: "ostat" ret: "int" args: "char *" "struct stat43 *" */
#define	OPENBSD_SYS_ostat	38

/* syscall: "getppid" ret: "pid_t" args: */
#define	OPENBSD_SYS_getppid	39

/* syscall: "olstat" ret: "int" args: "char *" "struct stat43 *" */
#define	OPENBSD_SYS_olstat	40

/* syscall: "dup" ret: "int" args: "int" */
#define	OPENBSD_SYS_dup	41

/* syscall: "opipe" ret: "int" args: */
#define	OPENBSD_SYS_opipe	42

/* syscall: "getegid" ret: "gid_t" args: */
#define	OPENBSD_SYS_getegid	43

/* syscall: "profil" ret: "int" args: "caddr_t" "size_t" "u_long" "u_int" */
#define	OPENBSD_SYS_profil	44

/* syscall: "ktrace" ret: "int" args: "char *" "int" "int" "pid_t" */
#define	OPENBSD_SYS_ktrace	45

/* syscall: "sigaction" ret: "int" args: "int" "const struct sigaction *" "struct sigaction *" */
#define	OPENBSD_SYS_sigaction	46

/* syscall: "getgid" ret: "gid_t" args: */
#define	OPENBSD_SYS_getgid	47

/* syscall: "sigprocmask" ret: "int" args: "int" "sigset_t" */
#define	OPENBSD_SYS_sigprocmask	48

/* syscall: "getlogin" ret: "int" args: "char *" "u_int" */
#define	OPENBSD_SYS_getlogin	49

/* syscall: "setlogin" ret: "int" args: "const char *" */
#define	OPENBSD_SYS_setlogin	50

/* syscall: "acct" ret: "int" args: "char *" */
#define	OPENBSD_SYS_acct	51

/* syscall: "sigpending" ret: "int" args: */
#define	OPENBSD_SYS_sigpending	52

/* syscall: "osigaltstack" ret: "int" args: "const struct osigaltstack *" "struct osigaltstack *" */
#define	OPENBSD_SYS_osigaltstack	53

/* syscall: "ioctl" ret: "int" args: "int" "u_long" "..." */
#define	OPENBSD_SYS_ioctl	54

/* syscall: "reboot" ret: "int" args: "int" */
#define	OPENBSD_SYS_reboot	55

/* syscall: "revoke" ret: "int" args: "char *" */
#define	OPENBSD_SYS_revoke	56

/* syscall: "symlink" ret: "int" args: "char *" "char *" */
#define	OPENBSD_SYS_symlink	57

/* syscall: "readlink" ret: "int" args: "char *" "char *" "size_t" */
#define	OPENBSD_SYS_readlink	58

/* syscall: "execve" ret: "int" args: "char *" "char *const *" "char *const *" */
#define	OPENBSD_SYS_execve	59

/* syscall: "umask" ret: "mode_t" args: "mode_t" */
#define	OPENBSD_SYS_umask	60

/* syscall: "chroot" ret: "int" args: "char *" */
#define	OPENBSD_SYS_chroot	61

/* syscall: "ofstat" ret: "int" args: "int" "struct stat43 *" */
#define	OPENBSD_SYS_ofstat	62

/* syscall: "ogetkerninfo" ret: "int" args: "int" "char *" "int *" "int" */
#define	OPENBSD_SYS_ogetkerninfo	63

/* syscall: "ogetpagesize" ret: "int" args: */
#define	OPENBSD_SYS_ogetpagesize	64

/* syscall: "omsync" ret: "int" args: "caddr_t" "size_t" */
#define	OPENBSD_SYS_omsync	65

/* syscall: "vfork" ret: "int" args: */
#define	OPENBSD_SYS_vfork	66

				/* 67 is obsolete vread */
				/* 68 is obsolete vwrite */
				/* 69 is obsolete sbrk */
/* syscall: "ommap" ret: "int" args: "caddr_t" "size_t" "int" "int" "int" "long" */
#define	OPENBSD_SYS_ommap	71

/* syscall: "vadvise" ret: "int" args: "int" */
#define	OPENBSD_SYS_vadvise	72

/* syscall: "munmap" ret: "int" args: "void *" "size_t" */
#define	OPENBSD_SYS_munmap	73

/* syscall: "mprotect" ret: "int" args: "void *" "size_t" "int" */
#define	OPENBSD_SYS_mprotect	74

/* syscall: "madvise" ret: "int" args: "void *" "size_t" "int" */
#define	OPENBSD_SYS_madvise	75

				/* 76 is obsolete vhangup */
				/* 77 is obsolete vlimit */
/* syscall: "mincore" ret: "int" args: "void *" "size_t" "char *" */
#define	OPENBSD_SYS_mincore	78

/* syscall: "getgroups" ret: "int" args: "int" "gid_t *" */
#define	OPENBSD_SYS_getgroups	79

/* syscall: "setgroups" ret: "int" args: "int" "const gid_t *" */
#define	OPENBSD_SYS_setgroups	80

/* syscall: "getpgrp" ret: "int" args: */
#define	OPENBSD_SYS_getpgrp	81

/* syscall: "setpgid" ret: "int" args: "pid_t" "int" */
#define	OPENBSD_SYS_setpgid	82

/* syscall: "setitimer" ret: "int" args: "int" "const struct itimerval_compat *" "struct itimerval_compat *" */
#define	OPENBSD_SYS_setitimer	83

/* syscall: "owait" ret: "int" args: */
#define	OPENBSD_SYS_owait	84

/* syscall: "swapon" ret: "int" args: "char *" */
#define	OPENBSD_SYS_swapon	85

/* syscall: "getitimer" ret: "int" args: "int" "struct itimerval_compat *" */
#define	OPENBSD_SYS_getitimer	86

/* syscall: "ogethostname" ret: "int" args: "char *" "u_int" */
#define	OPENBSD_SYS_ogethostname	87

/* syscall: "osethostname" ret: "int" args: "char *" "u_int" */
#define	OPENBSD_SYS_osethostname	88

/* syscall: "ogetdtablesize" ret: "int" args: */
#define	OPENBSD_SYS_ogetdtablesize	89

/* syscall: "dup2" ret: "int" args: "int" "int" */
#define	OPENBSD_SYS_dup2	90

/* syscall: "fcntl" ret: "int" args: "int" "int" "..." */
#define	OPENBSD_SYS_fcntl	92

/* syscall: "select" ret: "int" args: "int" "fd_set *" "fd_set *" "fd_set *" "struct timeval_compat *" */
#define	OPENBSD_SYS_select	93

/* syscall: "fsync" ret: "int" args: "int" */
#define	OPENBSD_SYS_fsync	95

/* syscall: "setpriority" ret: "int" args: "int" "id_t" "int" */
#define	OPENBSD_SYS_setpriority	96

/* syscall: "socket" ret: "int" args: "int" "int" "int" */
#define	OPENBSD_SYS_socket	97

/* syscall: "connect" ret: "int" args: "int" "const struct sockaddr *" "socklen_t" */
#define	OPENBSD_SYS_connect	98

/* syscall: "oaccept" ret: "int" args: "int" "caddr_t" "int *" */
#define	OPENBSD_SYS_oaccept	99

/* syscall: "getpriority" ret: "int" args: "int" "id_t" */
#define	OPENBSD_SYS_getpriority	100

/* syscall: "osend" ret: "int" args: "int" "caddr_t" "int" "int" */
#define	OPENBSD_SYS_osend	101

/* syscall: "orecv" ret: "int" args: "int" "caddr_t" "int" "int" */
#define	OPENBSD_SYS_orecv	102

/* syscall: "sigreturn" ret: "int" args: "struct sigcontext *" */
#define	OPENBSD_SYS_sigreturn	103

/* syscall: "bind" ret: "int" args: "int" "const struct sockaddr *" "socklen_t" */
#define	OPENBSD_SYS_bind	104

/* syscall: "setsockopt" ret: "int" args: "int" "int" "int" "const void *" "socklen_t" */
#define	OPENBSD_SYS_setsockopt	105

/* syscall: "listen" ret: "int" args: "int" "int" */
#define	OPENBSD_SYS_listen	106

				/* 107 is obsolete vtimes */
/* syscall: "osigvec" ret: "int" args: "int" "struct sigvec *" "struct sigvec *" */
#define	OPENBSD_SYS_osigvec	108

/* syscall: "osigblock" ret: "int" args: "int" */
#define	OPENBSD_SYS_osigblock	109

/* syscall: "osigsetmask" ret: "int" args: "int" */
#define	OPENBSD_SYS_osigsetmask	110

/* syscall: "sigsuspend" ret: "int" args: "int" */
#define	OPENBSD_SYS_sigsuspend	111

/* syscall: "osigstack" ret: "int" args: "struct sigstack *" "struct sigstack *" */
#define	OPENBSD_SYS_osigstack	112

/* syscall: "orecvmsg" ret: "int" args: "int" "struct omsghdr *" "int" */
#define	OPENBSD_SYS_orecvmsg	113

/* syscall: "osendmsg" ret: "int" args: "int" "caddr_t" "int" */
#define	OPENBSD_SYS_osendmsg	114

				/* 115 is obsolete vtrace */
/* syscall: "gettimeofday" ret: "int" args: "struct timeval_compat *" "struct timezone *" */
#define	OPENBSD_SYS_gettimeofday	116

/* syscall: "getrusage" ret: "int" args: "int" "struct rusage_compat *" */
#define	OPENBSD_SYS_getrusage	117

/* syscall: "getsockopt" ret: "int" args: "int" "int" "int" "void *" "socklen_t *" */
#define	OPENBSD_SYS_getsockopt	118

				/* 119 is obsolete resuba */
/* syscall: "readv" ret: "ssize_t" args: "int" "const struct iovec *" "int" */
#define	OPENBSD_SYS_readv	120

/* syscall: "writev" ret: "ssize_t" args: "int" "const struct iovec *" "int" */
#define	OPENBSD_SYS_writev	121

/* syscall: "settimeofday" ret: "int" args: "const struct timeval_compat *" "const struct timezone *" */
#define	OPENBSD_SYS_settimeofday	122

/* syscall: "fchown" ret: "int" args: "int" "uid_t" "gid_t" */
#define	OPENBSD_SYS_fchown	123

/* syscall: "fchmod" ret: "int" args: "int" "mode_t" */
#define	OPENBSD_SYS_fchmod	124

/* syscall: "orecvfrom" ret: "int" args: "int" "caddr_t" "size_t" "int" "caddr_t" "int *" */
#define	OPENBSD_SYS_orecvfrom	125

/* syscall: "setreuid" ret: "int" args: "uid_t" "uid_t" */
#define	OPENBSD_SYS_setreuid	126

/* syscall: "setregid" ret: "int" args: "gid_t" "gid_t" */
#define	OPENBSD_SYS_setregid	127

/* syscall: "rename" ret: "int" args: "char *" "char *" */
#define	OPENBSD_SYS_rename	128

/* syscall: "otruncate" ret: "int" args: "char *" "long" */
#define	OPENBSD_SYS_otruncate	129

/* syscall: "oftruncate" ret: "int" args: "int" "long" */
#define	OPENBSD_SYS_oftruncate	130

/* syscall: "flock" ret: "int" args: "int" "int" */
#define	OPENBSD_SYS_flock	131

/* syscall: "mkfifo" ret: "int" args: "char *" "mode_t" */
#define	OPENBSD_SYS_mkfifo	132

/* syscall: "sendto" ret: "ssize_t" args: "int" "const void *" "size_t" "int" "const struct sockaddr *" "socklen_t" */
#define	OPENBSD_SYS_sendto	133

/* syscall: "shutdown" ret: "int" args: "int" "int" */
#define	OPENBSD_SYS_shutdown	134

/* syscall: "socketpair" ret: "int" args: "int" "int" "int" "int *" */
#define	OPENBSD_SYS_socketpair	135

/* syscall: "mkdir" ret: "int" args: "char *" "mode_t" */
#define	OPENBSD_SYS_mkdir	136

/* syscall: "rmdir" ret: "int" args: "char *" */
#define	OPENBSD_SYS_rmdir	137

/* syscall: "utimes" ret: "int" args: "char *" "const struct timeval_compat *" */
#define	OPENBSD_SYS_utimes	138

				/* 139 is obsolete 4.2 sigreturn */
/* syscall: "adjtime" ret: "int" args: "const struct timeval_compat *" "struct timeval_compat *" */
#define	OPENBSD_SYS_adjtime	140

/* syscall: "ogetpeername" ret: "int" args: "int" "caddr_t" "socklen_t *" */
#define	OPENBSD_SYS_ogetpeername	141

/* syscall: "ogethostid" ret: "int32_t" args: */
#define	OPENBSD_SYS_ogethostid	142

/* syscall: "osethostid" ret: "int" args: "int32_t" */
#define	OPENBSD_SYS_osethostid	143

/* syscall: "ogetrlimit" ret: "int" args: "int" "struct ogetrlimit *" */
#define	OPENBSD_SYS_ogetrlimit	144

/* syscall: "osetrlimit" ret: "int" args: "int" "struct ogetrlimit *" */
#define	OPENBSD_SYS_osetrlimit	145

/* syscall: "okillpg" ret: "int" args: "int" "int" */
#define	OPENBSD_SYS_okillpg	146

/* syscall: "setsid" ret: "int" args: */
#define	OPENBSD_SYS_setsid	147

/* syscall: "quotactl" ret: "int" args: "char *" "int" "int" "char *" */
#define	OPENBSD_SYS_quotactl	148

/* syscall: "ogetsockname" ret: "int" args: "int" "caddr_t" "int *" */
#define	OPENBSD_SYS_ogetsockname	150

/* syscall: "nfssvc" ret: "int" args: "int" "void *" */
#define	OPENBSD_SYS_nfssvc	155

/* syscall: "ogetdirentries" ret: "int" args: "int" "char *" "int" "long *" */
#define	OPENBSD_SYS_ogetdirentries	156

/* syscall: "statfs25" ret: "int" args: "char *" "struct ostatfs *" */
#define	OPENBSD_SYS_statfs25	157

/* syscall: "fstatfs25" ret: "int" args: "int" "struct ostatfs *" */
#define	OPENBSD_SYS_fstatfs25	158

/* syscall: "getfh" ret: "int" args: "char *" "fhandle_t *" */
#define	OPENBSD_SYS_getfh	161

/* syscall: "ogetdomainname" ret: "int" args: "char *" "int" */
#define	OPENBSD_SYS_ogetdomainname	162

/* syscall: "osetdomainname" ret: "int" args: "char *" "int" */
#define	OPENBSD_SYS_osetdomainname	163

/* syscall: "ouname" ret: "int" args: "struct outsname *" */
#define	OPENBSD_SYS_ouname	164

/* syscall: "sysarch" ret: "int" args: "int" "void *" */
#define	OPENBSD_SYS_sysarch	165

/* syscall: "osemsys" ret: "int" args: "int" "int" "int" "int" "int" */
#define	OPENBSD_SYS_osemsys	169

/* syscall: "omsgsys" ret: "int" args: "int" "int" "int" "int" "int" "int" */
#define	OPENBSD_SYS_omsgsys	170

/* syscall: "oshmsys" ret: "int" args: "int" "int" "int" "int" */
#define	OPENBSD_SYS_oshmsys	171

/* syscall: "pread" ret: "ssize_t" args: "int" "void *" "size_t" "int" "off_t" */
#define	OPENBSD_SYS_pread	173

/* syscall: "pwrite" ret: "ssize_t" args: "int" "const void *" "size_t" "int" "off_t" */
#define	OPENBSD_SYS_pwrite	174

/* syscall: "setgid" ret: "int" args: "gid_t" */
#define	OPENBSD_SYS_setgid	181

/* syscall: "setegid" ret: "int" args: "gid_t" */
#define	OPENBSD_SYS_setegid	182

/* syscall: "seteuid" ret: "int" args: "uid_t" */
#define	OPENBSD_SYS_seteuid	183

/* syscall: "stat35" ret: "int" args: "char *" "struct stat35 *" */
#define	OPENBSD_SYS_stat35	188

/* syscall: "fstat35" ret: "int" args: "int" "struct stat35 *" */
#define	OPENBSD_SYS_fstat35	189

/* syscall: "lstat35" ret: "int" args: "char *" "struct stat35 *" */
#define	OPENBSD_SYS_lstat35	190

/* syscall: "pathconf" ret: "long" args: "char *" "int" */
#define	OPENBSD_SYS_pathconf	191

/* syscall: "fpathconf" ret: "long" args: "int" "int" */
#define	OPENBSD_SYS_fpathconf	192

/* syscall: "swapctl" ret: "int" args: "int" "const void *" "int" */
#define	OPENBSD_SYS_swapctl	193

/* syscall: "getrlimit" ret: "int" args: "int" "struct rlimit *" */
#define	OPENBSD_SYS_getrlimit	194

/* syscall: "setrlimit" ret: "int" args: "int" "const struct rlimit *" */
#define	OPENBSD_SYS_setrlimit	195

/* syscall: "getdirentries" ret: "int" args: "int" "char *" "int" "long *" */
#define	OPENBSD_SYS_getdirentries	196

/* syscall: "mmap" ret: "void *" args: "void *" "size_t" "int" "int" "int" "long" "off_t" */
#define	OPENBSD_SYS_mmap	197

/* syscall: "__syscall" ret: "quad_t" args: "quad_t" "..." */
#define	OPENBSD_SYS___syscall	198

/* syscall: "lseek" ret: "off_t" args: "int" "int" "off_t" "int" */
#define	OPENBSD_SYS_lseek	199

/* syscall: "truncate" ret: "int" args: "char *" "int" "off_t" */
#define	OPENBSD_SYS_truncate	200

/* syscall: "ftruncate" ret: "int" args: "int" "int" "off_t" */
#define	OPENBSD_SYS_ftruncate	201

/* syscall: "__sysctl" ret: "int" args: "int *" "u_int" "void *" "size_t *" "void *" "size_t" */
#define	OPENBSD_SYS___sysctl	202

/* syscall: "mlock" ret: "int" args: "const void *" "size_t" */
#define	OPENBSD_SYS_mlock	203

/* syscall: "munlock" ret: "int" args: "const void *" "size_t" */
#define	OPENBSD_SYS_munlock	204

/* syscall: "futimes" ret: "int" args: "int" "const struct timeval_compat *" */
#define	OPENBSD_SYS_futimes	206

/* syscall: "getpgid" ret: "pid_t" args: "pid_t" */
#define	OPENBSD_SYS_getpgid	207

/* syscall: "semctl23" ret: "int" args: "int" "int" "int" "union semun *" */
#define	OPENBSD_SYS_semctl23	220

/* syscall: "semget" ret: "int" args: "key_t" "int" "int" */
#define	OPENBSD_SYS_semget	221

/* syscall: "semop35" ret: "int" args: "int" "struct sembuf *" "u_int" */
#define	OPENBSD_SYS_semop35	222

				/* 223 is obsolete sys_semconfig */
/* syscall: "msgctl23" ret: "int" args: "int" "int" "struct msqid_ds23 *" */
#define	OPENBSD_SYS_msgctl23	224

/* syscall: "msgget" ret: "int" args: "key_t" "int" */
#define	OPENBSD_SYS_msgget	225

/* syscall: "msgsnd" ret: "int" args: "int" "const void *" "size_t" "int" */
#define	OPENBSD_SYS_msgsnd	226

/* syscall: "msgrcv" ret: "int" args: "int" "void *" "size_t" "long" "int" */
#define	OPENBSD_SYS_msgrcv	227

/* syscall: "shmat" ret: "void *" args: "int" "const void *" "int" */
#define	OPENBSD_SYS_shmat	228

/* syscall: "shmctl23" ret: "int" args: "int" "int" "struct shmid_ds23 *" */
#define	OPENBSD_SYS_shmctl23	229

/* syscall: "shmdt" ret: "int" args: "const void *" */
#define	OPENBSD_SYS_shmdt	230

/* syscall: "shmget35" ret: "int" args: "key_t" "int" "int" */
#define	OPENBSD_SYS_shmget35	231

/* syscall: "clock_gettime" ret: "int" args: "clockid_t" "struct timespec_compat *" */
#define	OPENBSD_SYS_clock_gettime	232

/* syscall: "clock_settime" ret: "int" args: "clockid_t" "const struct timespec_compat *" */
#define	OPENBSD_SYS_clock_settime	233

/* syscall: "clock_getres" ret: "int" args: "clockid_t" "struct timespec_compat *" */
#define	OPENBSD_SYS_clock_getres	234

/* syscall: "nanosleep" ret: "int" args: "const struct timespec_compat *" "struct timespec_compat *" */
#define	OPENBSD_SYS_nanosleep	240

/* syscall: "minherit" ret: "int" args: "void *" "size_t" "int" */
#define	OPENBSD_SYS_minherit	250

/* syscall: "rfork" ret: "int" args: "int" */
#define	OPENBSD_SYS_rfork	251

/* syscall: "poll" ret: "int" args: "struct pollfd *" "u_int" "int" */
#define	OPENBSD_SYS_poll	252

/* syscall: "issetugid" ret: "int" args: */
#define	OPENBSD_SYS_issetugid	253

/* syscall: "lchown" ret: "int" args: "char *" "uid_t" "gid_t" */
#define	OPENBSD_SYS_lchown	254

/* syscall: "getsid" ret: "pid_t" args: "pid_t" */
#define	OPENBSD_SYS_getsid	255

/* syscall: "msync" ret: "int" args: "void *" "size_t" "int" */
#define	OPENBSD_SYS_msync	256

/* syscall: "semctl35" ret: "int" args: "int" "int" "int" "union semun *" */
#define	OPENBSD_SYS_semctl35	257

/* syscall: "shmctl35" ret: "int" args: "int" "int" "struct shmid_ds35 *" */
#define	OPENBSD_SYS_shmctl35	258

/* syscall: "msgctl35" ret: "int" args: "int" "int" "struct msqid_ds35 *" */
#define	OPENBSD_SYS_msgctl35	259

/* syscall: "getfsstat" ret: "int" args: "struct statfs *" "size_t" "int" */
#define	OPENBSD_SYS_getfsstat	260

/* syscall: "statfs" ret: "int" args: "char *" "struct statfs *" */
#define	OPENBSD_SYS_statfs	261

/* syscall: "fstatfs" ret: "int" args: "int" "struct statfs *" */
#define	OPENBSD_SYS_fstatfs	262

/* syscall: "pipe" ret: "int" args: "int *" */
#define	OPENBSD_SYS_pipe	263

/* syscall: "fhopen" ret: "int" args: "const fhandle_t *" "int" */
#define	OPENBSD_SYS_fhopen	264

/* syscall: "fhstat35" ret: "int" args: "fhandle_t *" "struct stat_compat *" */
#define	OPENBSD_SYS_fhstat35	265

/* syscall: "fhstatfs" ret: "int" args: "const fhandle_t *" "struct statfs *" */
#define	OPENBSD_SYS_fhstatfs	266

/* syscall: "preadv" ret: "ssize_t" args: "int" "const struct iovec *" "int" "int" "off_t" */
#define	OPENBSD_SYS_preadv	267

/* syscall: "pwritev" ret: "ssize_t" args: "int" "const struct iovec *" "int" "int" "off_t" */
#define	OPENBSD_SYS_pwritev	268

/* syscall: "kqueue" ret: "int" args: */
#define	OPENBSD_SYS_kqueue	269

/* syscall: "kevent" ret: "int" args: "int" "const struct kevent *" "int" "struct kevent *" "int" "const struct timespec_compat *" */
#define	OPENBSD_SYS_kevent	270

/* syscall: "mlockall" ret: "int" args: "int" */
#define	OPENBSD_SYS_mlockall	271

/* syscall: "munlockall" ret: "int" args: */
#define	OPENBSD_SYS_munlockall	272

/* syscall: "getpeereid" ret: "int" args: "int" "uid_t *" "gid_t *" */
#define	OPENBSD_SYS_getpeereid	273

/* syscall: "getresuid" ret: "int" args: "uid_t *" "uid_t *" "uid_t *" */
#define	OPENBSD_SYS_getresuid	281

/* syscall: "setresuid" ret: "int" args: "uid_t" "uid_t" "uid_t" */
#define	OPENBSD_SYS_setresuid	282

/* syscall: "getresgid" ret: "int" args: "gid_t *" "gid_t *" "gid_t *" */
#define	OPENBSD_SYS_getresgid	283

/* syscall: "setresgid" ret: "int" args: "gid_t" "gid_t" "gid_t" */
#define	OPENBSD_SYS_setresgid	284

				/* 285 is obsolete sys_omquery */
/* syscall: "mquery" ret: "void *" args: "void *" "size_t" "int" "int" "int" "long" "off_t" */
#define	OPENBSD_SYS_mquery	286

/* syscall: "closefrom" ret: "int" args: "int" */
#define	OPENBSD_SYS_closefrom	287

/* syscall: "sigaltstack" ret: "int" args: "const struct sigaltstack *" "struct sigaltstack *" */
#define	OPENBSD_SYS_sigaltstack	288

/* syscall: "shmget" ret: "int" args: "key_t" "size_t" "int" */
#define	OPENBSD_SYS_shmget	289

/* syscall: "semop" ret: "int" args: "int" "struct sembuf *" "size_t" */
#define	OPENBSD_SYS_semop	290

/* syscall: "stat" ret: "int" args: "char *" "struct stat_compat *" */
#define	OPENBSD_SYS_stat	291

/* syscall: "fstat" ret: "int" args: "int" "struct stat_compat *" */
#define	OPENBSD_SYS_fstat	292

/* syscall: "lstat" ret: "int" args: "char *" "struct stat_compat *" */
#define	OPENBSD_SYS_lstat	293

/* syscall: "fhstat" ret: "int" args: "const fhandle_t *" "struct stat_compat *" */
#define	OPENBSD_SYS_fhstat	294

/* syscall: "__semctl" ret: "int" args: "int" "int" "int" "union semun *" */
#define	OPENBSD_SYS___semctl	295

/* syscall: "shmctl" ret: "int" args: "int" "int" "struct shmid_ds *" */
#define	OPENBSD_SYS_shmctl	296

/* syscall: "msgctl" ret: "int" args: "int" "int" "struct msqid_ds *" */
#define	OPENBSD_SYS_msgctl	297

#define	OPENBSD_SYS_MAXSYSCALL	298
