.\" $MirOS: ports/Setup.sh.8,v 1.31 2014/05/29 18:40:45 tg Exp $
.\"-
.\" Copyright (c) 2005, 2006, 2008, 2009, 2014, 2015, 2016
.\"	mirabilos <m@mirbsd.org>
.\" Derived from work Copyright (c) 1991
.\"	The Regents of the University of California.
.\"
.\" Provided that these terms and disclaimer and all copyright notices
.\" are retained or reproduced in an accompanying document, permission
.\" is granted to deal in this work without restriction, including un-
.\" limited rights to use, publicly perform, distribute, sell, modify,
.\" merge, give away, or sublicence.
.\"
.\" This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
.\" the utmost extent permitted by applicable law, neither express nor
.\" implied; without malicious intent or gross negligence. In no event
.\" may a licensor, author or contributor be held liable for indirect,
.\" direct, other damage, loss, or other issues arising in any way out
.\" of dealing in the work, even if advised of the possibility of such
.\" damage or existence of a defect, except proven that it results out
.\" of said person's immediate fault when using the work as intended.
.\"-
.\" Try to make GNU groff and AT&T nroff more compatible
.\" * ` generates ‘ in gnroff, so use \`
.\" * ' generates ’ in gnroff, \' generates ´, so use \*(aq
.\" * - generates ‐ in gnroff, \- generates −, so .tr it to -
.\"   thus use - for hyphens and \- for minus signs and option dashes
.\" * ~ is size-reduced and placed atop in groff, so use \*(TI
.\" * ^ is size-reduced and placed atop in groff, so use \*(ha
.\" * \(en does not work in nroff, so use \*(en
.\" * <>| are problematic, so redefine and use \*(Lt\*(Gt\*(Ba
.\" Also make sure to use \& *before* a punctuation char that is to not
.\" be interpreted as punctuation, and especially with two-letter words
.\" but also (after) a period that does not end a sentence (“e.g.\&”).
.\" The section after the "doc" macropackage has been loaded contains
.\" additional code to convene between the UCB mdoc macropackage (and
.\" its variant as BSD mdoc in groff) and the GNU mdoc macropackage.
.\"
.ie \n(.g \{\
.	if \*[.T]ascii .tr \-\N'45'
.	if \*[.T]latin1 .tr \-\N'45'
.	if \*[.T]utf8 .tr \-\N'45'
.	ds <= \[<=]
.	ds >= \[>=]
.	ds Rq \[rq]
.	ds Lq \[lq]
.	ds sL \(aq
.	ds sR \(aq
.	if \*[.T]utf8 .ds sL `
.	if \*[.T]ps .ds sL `
.	if \*[.T]utf8 .ds sR '
.	if \*[.T]ps .ds sR '
.	ds aq \(aq
.	ds TI \(ti
.	ds ha \(ha
.	ds en \(en
.\}
.el \{\
.	ds aq '
.	ds TI ~
.	ds ha ^
.	ds en \(em
.\}
.\"
.\" Implement .Dd with the Mdocdate RCS keyword
.\"
.rn Dd xD
.de Dd
.ie \\$1$Mdocdate: \{\
.	xD \\$2 \\$3, \\$4
.\}
.el .xD \\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8
..
.\"
.\" .Dd must come before definition of .Mx, because when called
.\" with -mandoc, it might implement .Mx itself, but we want to
.\" use our own definition. And .Dd must come *first*, always.
.\"
.Dd $Mdocdate: May 29 2014 $
.\"
.\" Check which macro package we use, and do other -mdoc setup.
.\"
.ie \n(.g \{\
.	if \*[.T]utf8 .tr \[la]\*(Lt
.	if \*[.T]utf8 .tr \[ra]\*(Gt
.	ie d volume-ds-1 .ds tT gnu
.	el .ds tT bsd
.\}
.el .ds tT ucb
.\"
.\" Implement .Mx (MirBSD)
.\"
.ie "\*(tT"gnu" \{\
.	eo
.	de Mx
.	nr curr-font \n[.f]
.	nr curr-size \n[.ps]
.	ds str-Mx \f[\n[curr-font]]\s[\n[curr-size]u]
.	ds str-Mx1 \*[Tn-font-size]\%MirOS\*[str-Mx]
.	if !\n[arg-limit] \
.	if \n[.$] \{\
.	ds macro-name Mx
.	parse-args \$@
.	\}
.	if (\n[arg-limit] > \n[arg-ptr]) \{\
.	nr arg-ptr +1
.	ie (\n[type\n[arg-ptr]] == 2) \
.	as str-Mx1 \~\*[arg\n[arg-ptr]]
.	el \
.	nr arg-ptr -1
.	\}
.	ds arg\n[arg-ptr] "\*[str-Mx1]
.	nr type\n[arg-ptr] 2
.	ds space\n[arg-ptr] "\*[space]
.	nr num-args (\n[arg-limit] - \n[arg-ptr])
.	nr arg-limit \n[arg-ptr]
.	if \n[num-args] \
.	parse-space-vector
.	print-recursive
..
.	ec
.	ds sP \s0
.	ds tN \*[Tn-font-size]
.\}
.el \{\
.	de Mx
.	nr cF \\n(.f
.	nr cZ \\n(.s
.	ds aa \&\f\\n(cF\s\\n(cZ
.	if \\n(aC==0 \{\
.		ie \\n(.$==0 \&MirOS\\*(aa
.		el .aV \\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8 \\$9
.	\}
.	if \\n(aC>\\n(aP \{\
.		nr aP \\n(aP+1
.		ie \\n(C\\n(aP==2 \{\
.			as b1 \&MirOS\ #\&\\*(A\\n(aP\\*(aa
.			ie \\n(aC>\\n(aP \{\
.				nr aP \\n(aP+1
.				nR
.			\}
.			el .aZ
.		\}
.		el \{\
.			as b1 \&MirOS\\*(aa
.			nR
.		\}
.	\}
..
.\}
.\"-
.Dt SETUP.SH 8
.Os MirPorts\ Framework
.Sh NAME
.Nm Setup.sh
.Nd first-time installation of MirPorts Framework
.Sh SYNOPSIS
.Nm
.Op Fl DiNT
.Op Fl e | Fl E Ar sysconfdir
.Op Fl l Ar localbase
.Oo
. Fl u |
. Fl U Ar user Ns Op Ar :group
.Oc
.Op Fl X Ar xfbase
.Op Ar mirror
.Sh DESCRIPTION
The
.Nm
bourne shell script searches for an installed
.Xr mksh 1
and invokes the MirPorts Framework set-up programme with it.
If no suitable
.Xr mksh 1
version is found, the current version is fetched, built and installed
for bootstrapping purposes.
During installation, the environment is set up, various programmes are
installed, and several files are generated (see below).
To use the MirPorts Framework after installation, execute either of the
following two commands, depending on your user shell:
.Bd -literal
$ . ${LOCALBASE}/db/SetEnv.sh
% source ${LOCALBASE}/db/SetEnv.csh
.Ed
.Pp
Description of the command line options is shown further below.
.Sh ENVIRONMENT
.Bl -tag -width LD_LIBRARY_PATH
.It CC
Set this to the C compiler used.
.Pp
Default value: mgcc, gcc (probed), cc (last resort)
.It DISTDIR
Path to store downloaded cpio-balls (and tarballs and other distfiles).
.Pp
Default value: ${PORTSDIR}/Distfiles
.It INFOPATH
Prepended in SetEnv with
.Pa ${LOCALBASE}/info .
.It LD_LIBRARY_PATH
Prepended in SetEnv with
.Pa ${LOCALBASE}/lib .
.It MANPATH
Prepended in SetEnv with
.Pa ${LOCALBASE}/man .
.Pp
Default value:
.Li ${LOCALBASE}/man:/usr/local/man:/usr/share/man:/usr/X11R6/man
.It MKSH
Alternative location of
.Xr mksh 1
binary to use for installation, hard-code into
.Xr make 1 ,
and several other places, including, but not limited to, packages.
This must be a single file which does not need to exist.
If it does not exist, the
.Xr mksh 1
built is installed there.
The directory it is located in, however, must exist.
.Pp
.Bl -tag -compact -width "Suggested value:"
.It Default value:
/bin/mksh
.It Suggested value:
${LOCALBASE}/bin/mksh
.El
.It NROFF
Full command line prefix of
.Xr nroff 1
binary or equivalent.
If unset, MirOS nrcon (from
.At
nroff) is used if found.
.Pp
Default value: /usr/bin/env nroff \-Tascii
.Pp
Suggested value for operating systems with GNU groff:
.Li /path/to/nroff \-c \-Tlatin1
.Pp
Some operating systems with GNU groff can also use:
.Li /path/to/nroff \-c \-Tutf8
.It OPENNT_ROOT
If set, Interix operating system type is assumed.
.It OVERRIDE_MKSH
Used only internally for bootstrapping on Interix.
.It PATH_WINDOWS
Included in modified
.Ev PATH
variable in SetEnv scripts.
This is usually set by the Interix
.Pa /etc/profile .
.It PERL5LIB
Prepended in SetEnv with
.Pa ${LOCALBASE}/libdata/perl5{,/site_perl} .
.It SFUDIR
If set, Interix operating system type is assumed.
.It SHELL
The user's default shell.
Used as a candidate during search for
.Xr mksh 1 .
This can be the C Shell, too.
.It UPGRADE
Set this to
.Dq no
to prevent an
.Xr mksh 1
found but too old from being overwritten.
Unsupported, deprecated.
.It fetch
If set, the command line prefix of the fetch programme to use.
Defaults to Weihenstephan's GNU wget on Interix, any
.Xr wget 1 ,
.Xr ftp 1 ,
or
.Xr fetch 1
programme found in
.Pa $localbase/bin
(see below),
.Pa /usr/mpkg/bin ,
.Pa /usr/local/bin ,
.Pa /bin ,
or
.Pa /usr/bin
else.
This must include the argument to name the output, i.e.\&
.Fl O
.Pq for Nm wget ,
and
.Fl o
otherwise.
.It localbase
Setting this environment variable has almost the same functionality as the
.Fl l
option, however, it is being used much earlier in the process, such as
.Ev PATH
manipulation during
.Xr mksh 1
build, and divining a fetch utility (see above).
This option is almost unsupported, and you ought to use the
.Fl l
option as well if you employ setting this variable.
If you set these two to different values, you have lost.
.It xfbase
This does for
.Fl X
what
.Ev localbase
does for
.Fl l .
The same warnings apply.
.El
.Sh PARAMETERS
.Bl -tag -width "-U user[:group]"
.It Fl D
Enable debugging mode.
This calls the Korn shell installation script with
.Nm mksh
.Fl x .
Also, temporary files are not removed on exit.
.It Fl E Ar sysconfdir
Set the
.Ev SYSCONFDIR
variable to its argument.
.Pp
Default:
.Pa /etc
.It Fl e
This is the same as
.Fl E Ar ${LOCALBASE}/etc .
.It Fl i
Used internally for bootstrapping on Interix only.
.It Fl l Ar localbase
Set the
.Ev LOCALBASE
variable to its argument.
.Pp
Default:
.Pa /usr/mpkg
.It Fl N
Semi-Upgrade Mode.
Do not install any software (if the system has already been
set up correctly before), only rewrite the configuration files.
Use with care.
Better don't use (see
.Sx CAVEATS
below).
.It Fl T
Use the locally checked out version of the package tools for
bootstrapping, instead of downloading a distfile and using it.
Note this might break things horridly and hard-codes a specific
version number.
This is, however, used by MirOS native MirPorts
.Dq make setup
command, so that users of a fresh MirOS BSD + MirPorts installation
can install binary packages without having to download anything.
This does not prevent MirMake from being downloaded even on MirOS
if it's not recent enough, and is only intended for current snapshots.
.It Fl U Ar user Ns Op Ar :group
Use its arguments as
.Ev BINOWN
and
.Ev BINGRP
to determine default ownership of files being installed.
.Pp
Default: root:bin
.It Fl u
This is the same as calling
.Fl U
with your current UID and GID as parameters.
This option is the default behaviour on Interix,
and necessary to use the MirPorts Framework as non-root
user (together with
.Fl e
or similar).
.Pp
Note that this may not be enough to work on Interix, since domain
users don't work, and spaces aren't allowed in user or group names.
You can try calling
.Nm
with
.Fl U
and the numeric uid and gid, separated by a colon
.Pq Sq :\& ,
if you encounter chown or chgrp problems.
.It Fl X Ar xfbase
Set the
.Ev X11BASE
to its argument.
.Pp
Default:
.Pa ${LOCALBASE}/X11
if found,
.Pa /usr/X11R6
else.
.It Ar mirror
Set this to the MirOS Distribution Server mirror you'd like to use
for retrieving files installed during the first-time set-up process.
.Pp
If this starts with a
.Dq / ,
it is interpreted as an absolute pathname of a directory containing
the needed cpio-balls, else, it is read as an HTTP (or FTP) URI and
used in conjunction with the ${fetch} programme.
.Pp
Default:
.Pa http://www.mirbsd.org/MirOS/dist/
.El
.Sh FILES
.Bl -tag -width "${LOCALBASE}/db/shareddirs.db"
.It Pa /bin/mksh
Default location of
.Xr mksh 1
to use.
.Pp
This file is overwritten if it's too old, and the
.Ev MKSH
environment variable is not set.
.It Pa /etc/make.cfg
System-wide
.Xr make 1
configuration, usually included if found.
.It Pa /etc/mk.conf
Legacy system-wide configuration, included if found.
Useful on
.Ox .
.It Pa ${LOCALBASE}/db/SetEnv.csh
Sourcing this
.Xr csh 1
script sets up the necessary environment for
building and installing packages using the
MirPorts Framework, and running the installed
binaries.
.Pp
Running
.Nm
overwrites this file.
.It Pa ${LOCALBASE}/db/SetEnv.make
This
.Xr make 1
script contains the same definitions as the two
shell SetEnv scripts, to the extent duplicating
them in the MirMake variable space makes sense.
Also, some variables have different names here.
.Pp
Running
.Nm
overwrites this file.
.It Pa ${LOCALBASE}/db/SetEnv.sh
This Bourne Shell script is the equivalent of
.Pa SetEnv.csh
for
.Xr sh 1 .
.Pp
Running
.Nm
overwrites this file.
.It Pa ${LOCALBASE}/db/mmake.cfg
Contains installation-wide (as opposed to system-wide)
configuration for building MirPorts packages.
.Pp
This script is generated by
.Nm
but never overwritten.
.It Pa ${LOCALBASE}/db/pkg/
This directory contains the package database.
.It Pa ${LOCALBASE}/db/shareddirs.db
This file keeps a list of all directories created using
.Xr pkg_add 1
during package installation, and their reference count.
.It Pa ${PORTSDIR}/Distfiles/
This directory will be used by
.Nm
as well as the MirPorts Framework to store all distfiles
retrieved during installation and package builds, if not overridden by
.Ev DISTDIR .
.El
.Sh INSTALLED SOFTWARE
During the first-time set-up process,
.Nm
installs various software packages in your system.
All of these (except
.Xr mksh 1
in the standard configuration) will be located under
.Ev LOCALBASE .
.Pp
You should not re-run
.Nm
to upgrade these pieces of software; instead, use
.Xr pkg_upgrade 1 .
.Ss MKSH
Port location:
.Pa shells/mksh
.Pp
The MirBSD Korn Shell is always installed if it's not found or too old.
Currently, at least R31 (2007/08/19) is required.
A manual page is attempted to be installed into
.Pa /usr/share/man/cat1/
or
.Pa /usr/share/man/man1/
but failure is not deemed important.
For a properly installed mksh honouring default COPTS,
CFLAGS etc. use the port.
.Ss MIRMAKE
Port location:
.Pa devel/mirmake
.Pp
The
.Mx
version of
.Xr make 1
is installed if the system
.Xr make 1
is no MirMake or too old.
If a recent version of MirMake is already found on the
system or in ${LOCALBASE}/bin, no action is taken, or
a wrapper is put into ${LOCALBASE}/bin/mmake so that a
user can install \*(Ltbsd.port.mk\*(Gt himself.
.Ss NROFF
Port location:
none yet
.Pp
If no
.Pa /usr/bin/nroff
or
.Pa ${LOCALBASE}/bin/nroff
is found (usually the case only on Interix), the
.Mx
version of
.At
.Xr nroff 1
is installed.
Note that this check is currently only tested on Interix,
and that, since MirMake is a dependency to build nroff,
bootstrapping can fail on non-Interix systems without
either nroff, ditroff or GNU groff installed.
.Ss MTREE
Port location:
none yet
.Pp
If
.Xr mtree 8
is not being found at
.Pa /usr/sbin/mtree
or within
.Pa ${LOCALBASE}/bin ,
this programme is installed.
.Ss PACKAGE TOOLS
Port location:
.Pa essentials/pkgtools
.Pp
The package tools of the MirPorts Framework, namely
.Xr pkg_add 1 ,
.Xr pkg_create 1 ,
.Xr pkg_delete 1 ,
and
.Xr pkg_info 1 ,
are installed as part of the build as well.
They are upgradable using a port, too.
.Ss CPIO
Port location:
.Pa archivers/mircpio
.Pp
On Darwin (Mac OSX), Interix and MidnightBSD, paxmirabilis aka MirCpio
is installed because the native archivers lack functionality.
This programme and all following are actually already
installed using a MirPort during set up time, too.
.Ss PATCH
Port location:
.Pa essentials/patch
.Pp
Interix does not come with
.Xr patch 1 .
MidnightBSD's is broken.
.Ss CKSUM
Port location:
.Pa essentials/cksum
.Pp
This port is needed on Darwin, Interix and MidnightBSD, and optional on
.Ox ,
to verify file checksums.
.Ss GNU TEXINFO
Port location:
.Pa essentials/texinfo
.Pp
This is being pulled in as a build dependency of m4 and wget on Interix.
.Ss GNU M4
Port location:
.Pa lang/m4
.Pp
.Tn GNU
.Xr m4 1
is installed early on Interix and MidnightBSD because autoconf depends on it.
.Ss GNU WGET
Port location:
.Pa net/wget
.Pp
On Interix, there is no really suitable fetch utility, so this
beast is being built.
It pulls in metaauto, autoconf-new (2.60 and up) and help2man.
.Sh EXAMPLES
Install the MirPorts Framework natively on MirOS-current:
.Bd -literal
$ cd /usr/ports; make setup
  # - or -
$ sudo sh /usr/ports/Setup.sh
.Ed
.Pp
Install the MirPorts Framework as a user on a shell on an
.Ox
box:
.Bd -literal
% cd
% mkdir \-p .etc/bin .etc/pkg
% setenv MKSH ~/.etc/bin/mksh
% sh mirports/Setup.sh \-uel ~/.etc/pkg
.Ed
.Pp
Install the MirPorts Framework system-wide on a MidnightBSD box:
.Bd -literal
$ cd /usr/mirports
$ /bin/mksh Setup.sh \-e
# (users must source /usr/mpkg/db/SetEnv.sh before using)
.Ed
.Sh DIAGNOSTICS
Most error messages are displayed on stderr, some on stdout.
Error messages from external utilities are usually retained.
.Pp
The bourne shell script
.Nm
usually aborts in error cases, but leaves a temporary directory,
whose name is printed to stderr directly after startup.
You must delete it manually.
.Pp
The korn shell script called later cleans up (unless
.Fl D
is given) the temporary directory created by
.Nm
in cases of errors and should abort on all errors and corner cases.
.Sh SEE ALSO
.Xr cksum 1 ,
.Xr csh 1 ,
.Xr fetch 1 ,
.Xr ftp 1 ,
.Xr gzsig 1 ,
.Xr m4 1 ,
.Xr make 1 ,
.Xr mksh 1 ,
.Xr mtree 8 ,
.Xr nroff 1 ,
.Xr patch 1 ,
.Xr pkg_add 1 ,
.Xr pkg_create 1 ,
.Xr pkg_delete 1 ,
.Xr pkg_info 1 ,
.Xr pkg_upgrade 1 ,
.Xr sh 1 ,
.Xr wget 1
.Pp
.Pa http://www.mirbsd.org/man7/BSD\-Licence
.Sh AUTHORS
.Nm
was written by
.An Thorsten Glaser Aq tg@mirbsd.de .
The MirPorts Framework is maintained by
.Aq miros-discuss@MirBSD.org .
The package tools have been taken over from
.Fx
and
.Ox
and are now maintained by
.An Benny Siegert Aq bsiegert@mirbsd.org .
.Sh CAVEATS
Be careful with passing environment variables to
.Nm
(even if they are automatically set).
.Pp
Running
.Nm
more than once overwrites some files and doesn't
touch some others.
You must check them manually in any case.
For upgrading, you should use package tools upgrades
whenever possible \*(en this is only a bootstrapping tool.
.Pp
For many tools, upgrade them using packages even after
bootstrapping, because ports/packages honour ${CC}, ${CFLAGS}
and stuff like that.
Also, on Interix, mksh and MirMake are usually built without
any manual pages being installed during bootstrapping.
.Pp
When installing the MirPorts Framework without sudo, i.e. using the
.Fl u
or
.Fl U
options to
.Nm ,
some applications may misbehave or introduce potential security
risks by using set-uid or set-gid bits on executables, handling
them only properly if suid-root or sgid-wheel though.
If possible, avoid installing MirPorts as regular user.
.Sh BUGS
Probably many.
Report them to
.Aq miros-discuss@mirbsd.org .
There are so many possible scenarios and corner cases, as well
as incompatibilities, so that some breakage might always occur.
.Pp
On Interix,
.Xr mtree 8
does not come with the base system.
It is being used by
.Nm
before it's built, though.
.Pp
On non-Interix systems without nroff, ditroff or GNU groff,
the detection whether to build nroff and re-build MirMake
afterwards is not done, and stuff might break.
.Pp
When giving
.Fl ul
but omitting
.Fl e ,
the SYSCONFDIR is still
.Pa /etc ,
although that is not writable.
