#!/bin/sh
# $MirOS$
#
# dillo de-installation

set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
SYSCONFDIR=${SYSCONFDIR:-/etc}

if [ "$PKG_DELETE_EXTRA" != Yes -a -f $SYCONFDIR/dillorc ]; then
    echo
    echo "+---------------"
    echo "| To completely deinstall the $1 package you need to perform"
    echo "| these steps as root:"
    echo "|"
    echo "|           rm -f $SYSCONFDIR/dillorc"
    echo "|           rm -f $SYSCONFDIR/dpidrc"
    echo "|"
    echo "| Do not do this if you plan on re-installing $1"
    echo "| at some future time."
    echo "+---------------"
    echo
fi

exit 0
