#!/bin/sh
# $MirOS$

PATH=/bin:/usr/bin:/sbin:/usr/sbin

extra()
{
	echo "Creating logfile: /var/log/clam-update.log"
	touch /var/log/clam-update.log
	chown ${CLAMUSER}:${CLAMGROUP} /var/log/clam-update.log
        chmod 644 /var/log/clam-update.log
        echo "Changing permissions on virus database directory"
	chown -R ${CLAMUSER}:${CLAMGROUP} ${PREFIX}/libdata/clamav
        echo "Creating local socket directoy"
        mkdir -p /var/run/clamd
        chown -R ${CLAMUSER}:${CLAMGROUP} /var/run/clamd
        chmod -R 711 /var/run/clamd
}

do_notice()
{
        echo "----------------"
        echo "clamav is almost installed"
	echo "----------------"
        echo
	echo "clamav.conf has been placed in ${PREFIX}/share/example/clamav"
	echo "it should be configured and placed into ${SYSCONFDIR}"
	echo
        echo "Warning: Never set the SUID/SGID bit on Clam Antivirus programs"
        echo
	echo "To keep up to date run freshclam on a regular basis(cron):"
	echo "0 8 * * * ${PREFIX}/bin/freshclam --quiet -l /var/log/clam-update.log --daemon-notify"
	echo "Or run freshclam as a daemon:"
	echo "freshclam -d -c 2 -l /var/log/clam-update.log --daemon-notify"
	echo
	echo "You should run freshclam immediately, because port"
	echo "do not come with virus definitions!"
        echo "Enjoy clamav!"
}

# verify proper execution
#
if [ $# -ne 2 ]; then
	echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
	exit 1
fi

# Verify/process the command
#
case $2 in
	PRE-INSTALL)
		: nothing to pre-install for this port
		;;
	POST-INSTALL)
		extra
		do_notice $1
		;;
	*)
		echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
		exit 1
		;;
esac

exit 0
