#!/usr/bin/env mksh
fifo=~/.etc/mcabber/mcabber.fifo
fn=~/tmp/music
mknod $fifo p
while [[ -e $fifo ]]; do
	read a b m <$fifo
	[[ $a = /status ]] || continue
	[[ $m = ∅ ]] && continue
	print "/m #MirBSD np: $m" >$fn
	screen -x chat -X eval "readbuf $fn" 'paste .'
done
rm -f $fifo $fn
