#!/bin/sh
# $MirOS: src/share/misc/licence.template,v 1.28 2008/11/14 15:33:44 tg Rel $
#-
# Copyright (c) 2004
#	Thorsten Glaser <tg@mirbsd.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un-
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person's immediate fault when using the work as intended.

usage() {
	echo "Syntax: $0 start +length [input] [output] [ifactor] [ofactor]"
	echo "Syntax: $0 start -end [input] [output] [ifactor] [ofactor]"
	exit 1
}

S="$1"
xL="$2"
fI="$3"
fO="$4"
[ -z "$S" -o -z "$xL" ] && usage

case "$xL" in
  +*)	L="${xL#+}"		;;
  -*)	L="$((${xL#-}-$S))"	;;
  *)	usage			;;
esac

[ x"$S" = x"0" ] || \
    for facS in $5 4096 2048 1024 512 256 128 64 32 16 8 4 2 1; do
	if [ x"$facS" = x"1" ]; then
		cS="$S"
		break
	fi
	cS="$(printf '%s/%s\n' $S $facS|bc)"
	fS="$(printf '%s*%s\n' $cS $facS|bc)"
	[ x"$S" = x"$fS" ] && break
done

for facL in $6 4096 2048 1024 512 256 128 64 32 16 8 4 2 1; do
	if [ x"$facL" = x"1" ]; then
		cL="$L"
		break
	fi
	cL="$(printf '%s/%s\n' $L $facL|bc)"
	fL="$(printf '%s*%s\n' $cL $facL|bc)"
	[ x"$L" = x"$fL" ] && break
done

if [ -z "$fI" ]; then
	I=""
  else	I="if=${fI}"
fi

if [ -z "$fO" ]; then
	O=""
  else	O="of=${fO}"
fi

if [ x"$S" = x"0" ]; then
	if [ -z "$fI" ]; then
		cat
	  else
		cat "$fI"
	fi
  else
	dd "$I" bs="$cS" skip="$facS"
fi | dd bs="$cL" count="$facL" "$O"
