#!/bin/mksh
# ideal: 1-1/e ~= 0.6321205588
set +U
bc |&
print -p scale=10
print -p cum=0
print -p nrs=0
while :; do
	set -A bitfield
	read -a -N 8192 </dev/arandom
	integer i=-1
	while (( ++i < 4096 )); do
		(( bitfield[((REPLY[i*2] << 8) | REPLY[i*2+1]) & 4095]=1 ))
	done
	print -p "cur=${#bitfield[*]}/4096"
	print -p cur
	read -p cur
	print -p "cum+=cur"
	print -p "nrs+=1"
	print -p "cum/nrs"
	read -p tot
	print "${#bitfield[*]}	$cur	$tot"
	sleep 0.01
done
