#!/bin/mksh
set +U
bc |&
print -p scale=10
print -p cum=0
print -p nrs=0
while :; do
	set -A bitfield
	read -a -N 256 </dev/arandom
	integer i=-1
	while (( ++i < 256 )); do
		bitfield[${REPLY[i]}]=1
	done
	print -p "cur=${#bitfield[*]}/256"
	print -p cur
	read -p cur
	print -p "cum+=cur"
	print -p "nrs+=1"
	print -p "cum/nrs"
	read -p tot
	print "${#bitfield[*]}	$cur	$tot"
	sleep 0.01
done
