.\" $MirOS$
.\"-
.\" Copyright (c) 2004, 2005
.\"	Thorsten "mirabile" Glaser <tg@66h.42h.de>
.\"	Benny Siegert <bsiegert@gmx.de>
.\"
.\" Licensee is hereby permitted to deal in this work without restric-
.\" tion, including unlimited rights to use, publicly perform, modify,
.\" merge, distribute, sell, give away or sublicence, provided all co-
.\" pyright notices above, these terms and the disclaimer are retained
.\" in all redistributions or reproduced in accompanying documentation
.\" or other materials provided with binary redistributions.
.\"
.\" Licensor hereby provides this work "AS IS" and WITHOUT WARRANTY of
.\" any kind, expressed or implied, to the maximum extent permitted by
.\" applicable law, but with the warranty of being written without ma-
.\" licious intent or gross negligence; in no event shall licensor, an
.\" author or contributor be held liable for any damage, direct, indi-
.\" rect or other, however caused, arising in any way out of the usage
.\" of this work, even if advised of the possibility of such damage.
.\"-
.Dd April 12, 2004
.Dt pkg_scan 8
.Os
.Sh NAME
.Nm pkg_scan
.Nd populate a MirPorts shared directories database
.Sh SYNOPSIS
.Nm
.Op Fl df
.Ar target
.Sh DESCRIPTION
The
.Nm
utility processes the packaging lists of all installed MirPorts packages for
.Cm @dirrm
and
.Ar dir Ns Cm /
directives, and counts the number of times each directory within
.Ev $LOCALBASE
is referenced.
It then writes the information into a temporary MirPorts-style shareddirs
database file, which is copied over
.Pa target .
If
.Pa target
already exists,
.Nm
aborts with an error, unless the
.Fl f
option is given.
If the
.Fl d
option is given, a dry run is performed, which can be done as non-root.
.Sh FILES
.Pa /var/db/shareddirs.db
.Sh EXAMPLES
.Li $ pkg_scan -f
.Pp
Convert, at your own risk, a
.Mx
\#7ter to a
.Mx
\#7quater system once.
.Sh SEE ALSO
.Xr pkg_add 1 ,
.Xr pkg_delete 1
.Sh HISTORY
The
.Nm
utility appeared in
.Mx
\#7-stable.
.Sh AUTHORS
.An Thorsten Glaser Aq tg@66h.42h.de
designed the
.Mx
package tools changes for MirPorts after the
.Ox
project decided to rewrite their packaging tools in perl.
.Pp
.An Benny Siegert Aq bsiegert@66h.42h.de
originated the idea and most of the code for
.Nm "" .
