.\" $MirOS: src/usr.bin/splitb/splitb.1,v 1.3 2005/03/17 09:27:37 tg Exp $
.\"-
.\" Copyright (c) 2005
.\"	Thorsten "mirabile" Glaser <tg@66h.42h.de>
.\"
.\" Licensee is hereby permitted to deal in this work without restric-
.\" tion, including unlimited rights to use, publicly perform, modify,
.\" merge, distribute, sell, give away or sublicence, provided all co-
.\" pyright notices above, these terms and the disclaimer are retained
.\" in all redistributions or reproduced in accompanying documentation
.\" or other materials provided with binary redistributions.
.\"
.\" All advertising materials mentioning features or use of this soft-
.\" ware must display the following acknowledgement:
.\"	This product includes material provided by Thorsten Glaser.
.\"
.\" Licensor offers the work "AS IS" and WITHOUT WARRANTY of any kind,
.\" express, or implied, to the maximum extent permitted by applicable
.\" law, without malicious intent or gross negligence; in no event may
.\" licensor, an author or contributor be held liable for any indirect
.\" or other damage, or direct damage except proven a consequence of a
.\" direct error of said person and intended use of this work, loss or
.\" other issues arising in any way out of its use, even if advised of
.\" the possibility of such damage or existence of a nontrivial bug.
.\"-
.Dd March 14, 2005
.Dt SPLITB 1
.Os
.Sh NAME
.Nm splitb
.Nd split a file bytewise into pieces
.Sh SYNOPSIS
.Nm
.Op Fl dhkq
.Op Fl B Ar bufsiz
.Op Fl b Ar blocksize
.Op Fl t Ar template
.Op Fl w Ar width
.Op Ar file
.Sh DESCRIPTION
The
.Nm
utility reads the given
.Ar file
(or from standard input, if no file is specified)
and breaks it into smaller files at defined byte boundaries.
.Pp
The operation of
.Nm
is controlled by the following options:
.Bl -tag -width Ds
.It Fl B Ar bufsiz
Set the size of the buffer to
.Ar bufsiz .
Default is 1048576 (1 MiB).
.It Fl b Ar blocksize
Set the size of the file to
.Ar blocksize
buffers of
.Ar bufsiz
each.
Default is 1.
.It Fl d
Toggle the use of decimal respective sedecimal sequence numbers.
Default is sedecimal.
.It Fl h
Display a verbose synopsis.
.It Fl k
Set
.Ar bufsiz
to 1024 (1 KiB).
.It Fl q
Be quiet during operation.
.It Fl t Ar template
Specify pathname which is prepended to generated files.
Default is
.Dq split .
.Ar template
is followed by a dot and three
.Ns ( Ar width )
sedecimal numbers (000-FFF) as sequence number; if more than 4096
(16^3) files are to be generated, it simply runs off unless the
.Fl w
option is used.
.It Fl w Ar width
Specify the number of sedecimal digits to append,
in the range from 1 to
.Dv PATH_MAX \- 2 \- Fn strlen template .
Default is 3.
.El
.Pp
An additional argument specified is used as the name
of the input file which is to be split.
.Sh SEE ALSO
.Xr cat 1 ,
.Xr split 1
.Sh HISTORY
A
.Nm
command appeared in
.Mx 8 .
