#!/bin/mksh
# $MirOS: src/usr.bin/fdialog/samples/gauge1,v 1.1.7.1 2005/03/06 16:52:42 tg Exp $
# $ekkoBSD: gauge1,v 1.3 2004/02/26 00:31:00 dave Exp $
FDIALOG=${FDIALOG=fdialog}

PCT=0
(
while test $PCT -le 100
do
$FDIALOG --gauge "<C>Hi, you're at $PCT percent." $PCT 20 40 --ptitle "Gauge Sample 1" --sleep 2
PCT=`expr $PCT + 10`
done
)
