# $MirOS$

  # libraries
  SUBDIR+= libiberty
  SUBDIR+= bfd
  SUBDIR+= opcodes

  # executables
  SUBDIR+= binutils
  SUBDIR+= gas
# SUBDIR+= gdb
  SUBDIR+= ld

prereq: _SUBDIRUSE

.include <bsd.subdir.mk>
