# $MirOS: src/usr.sbin/pwd_mkdb/Makefile,v 1.3 2008/03/27 13:41:34 tg Exp $
# $OpenBSD: Makefile,v 1.8 2002/06/27 20:01:59 art Exp $

PROG=		pwd_mkdb
MAN=		pwd_mkdb.8
LDADD+=		-lutil
DPADD+=		${LIBUTIL}
BINDIR?=	/usr/dsbin

.include <bsd.prog.mk>
