# $MirOS: ports/comms/ssfe/Makefile,v 1.8 2006/09/14 00:07:37 tg Exp $

COMMENT=		split-screen front end for dumb programmes
CATEGORIES=		comms devel misc
DIST_NAME=		ssfe
DIST_DATE=		20070109
DIST_SOURCE=		port
RESPONSIBLE=		Thorsten Glaser <tg@66h.42h.de>

# GNU GPLv2
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes

NO_REGRESS=		Yes

.include <bsd.port.mk>
