# $MirOS: ports/comms/ssfe/Makefile,v 1.12 2008/11/08 23:03:35 tg Exp $

COMMENT=		split-screen front end for dumb programmes
CATEGORIES=		comms devel misc
DIST_NAME=		ssfe
DIST_DATE=		20120623
DIST_SOURCE=		port
DASH_VER=		1
RESPONSIBLE=		Thorsten Glaser <tg@mirbsd.org>

# GNU GPLv2
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes

NO_REGRESS=		Yes
CONFIGURE_STYLE=	bmake

.include <bsd.port.mk>
