# $MirOS$

COMMENT=		"split-screen front end for dumb programmes"
CATEGORIES=		comms devel misc
DISTNAME=		ssfe-20050901
RESPONSIBLE=		Thorsten Glaser <tg@66h.42h.de>

# GNU GPLv2
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes

DIST_SOURCE=		port

.include <bsd.port.mk>
