# $MirOS: src/share/man/man4/man4.sparc/Makefile,v 1.3 2005/03/28 22:39:41 tg Exp $

MANSECT=	4

MLINKS=	fd.4 fdc.4 \
	fga.4 fvme.4 \
	le.4 lebuffer.4 le.4 ledma.4 \
	mem.4 kmem.4 \
	pninek.4 btcham.4 \
	zs.4 zskbd.4 zs.4 zstty.4

.include "../../automan.mk"
.include <bsd.prog.mk>
