#!/bin/sh
# $OpenBSD$
#
# De-installation setup of ProFTPd

# exit on errors, use a sane path and install prefix
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
CONFIG_DIR=${SYSCONFDIR}/proftpd
STATEDIR=/var/run/proftpd

if [ "$PKG_DELETE_EXTRA" != Yes -a -d $CONFIG_DIR ]; then
    echo
    echo "+---------------"
    echo "| To completely deinstall the $1 package you need to perform"
    echo "| these steps as root:"
    echo "|"
    echo "|       rm -rf ${CONFIG_DIR}"
    echo "|       rm -rf ${STATEDIR}"
    echo "|"
    echo "| Do not do this if you plan on re-installing $1"
    echo "| at some future time."
    echo "+---------------"
    echo
fi

exit 0
