# $MirOS: src/sbin/ancontrol/Makefile,v 1.2 2005/03/06 19:49:48 tg Exp $
# $OpenBSD: Makefile,v 1.8 2004/01/29 03:42:49 deraadt Exp $

PROG=		ancontrol
MAN=		ancontrol.8
CPPFLAGS+=	-DANCACHE

.include <bsd.prog.mk>
