Flags: USENN
RCSID: $MirOS: www/data/datatest.inc,v 1.4 2012/07/15 14:16:42 tg Exp $
Title: A test posting
Date: 28.10.2009 12:34
Author: tg@
Tag: rant

<p>The GNU Project is famous for its coding style – Linus Torvalds even
 suggests to print them out, but not read them; burning them is a great
 symbolic gesture. Legibility issues aside (Linus’ own are interestingly
 similar to style(9) aka KNF, the BSD coding styles), why is that so?</p>
----
Title: Pitcher test
Date: 31.10.2009
Author: tg@
Pictures: 0 1:20 2:20 3:12
Picture0: wtf ist hallowe’en
Picture1: MirGRML “Hello, Wien!” 2009.10
Picture2: MirBSD „Samhain“ 2009-10-31
Picture3: Look" <ma> • & Entities

<h3 class="revbox">@!PICTURE0!@</h3>
<p>Gee…</p>
<h4 class="revbox">@!PICTURE1!@</h4>
<p>That’s in!</p>
<h4 class="revbox">@!PICTURE2!@</h4>
<p>That too!</p>
<hr />
<p class="revbox">@!PICTURE3!@</p>
----
Title: Timezone test (1)
Date: 14.07.2012 23:42

<p>This should be 14.07.2012 23:42 +0000
 (including filename/permalink/HTML title)
 and thus sorted later than (2) in the feed…</p>
----
Title: Timezone test (2)
Date: 15.07.2012 01:15 +0200

<p>This should be 15.07.2012 01:15 +0200
 (including filename/permalink/HTML title)
 but 14.07.2012 23:15 +0000 when sorting…</p>
<p>(actually, the order in the .inc source is deliberately wrong)</p>
----
Title: Empty content test
Date: 08.06.2013 00:22
ObComment: I should be sleeping already
----
