RCSID: $MirOS: www/data/wlog-10.inc,v 1.247 2009/10/30 17:05:30 tg Exp $
Title: A test posting
Date: 28.10.2009 12:34
Author: tg@
Tag: rant

<p>The GNU Project is famous for its coding style – Linus Torvalds even
 suggests to print them out, but not read them; burning them is a great
 symbolic gesture. Legibility issues aside (Linus’ own are interestingly
 similar to style(9) aka KNF, the BSD coding styles), why is that so?</p>
----
