RCSID: $MirOS: www/… $
Title: Homepage of the original Korn Shell
Link: http://www.kornshell.com/

This is the homepage for the original (AT&amp;T) Korn Shell,
where sources and binaries for ksh93 as well as information
are available. It is a modern shell with many features for
both interactive and script use, extensible, and can be used
as shared library. It’s also locale aware and thus Unicode
ready on most modern operating systems.
----
Title: Homepage of the MirBSD Korn Shell
Link: @@RELPATH@@mksh.htm

This is the homepage of the MirBSD Korn Shell (mksh), which
is <strong>the</strong> actively developed successor of pdksh.
The focus is a compact yet featureful shell, so several of the
ksh93/bash/zsh extensions are present, while others, such as
floating point arithmetic, will not be provided, even though
the aim is as generic as ksh93’s (interactive and script use;
embedding is not yet possible) and to be very portable, also
to include some extensions of its own. It’s Unicode aware.
----
Title: Homepage of the Public Domain Korn Shell
Link: http://www.cs.mun.ca/~michael/pdksh/

This is the homepage of the Public Domain Korn Shell (pdksh),
where last development happened in 1999, when the original
Korn Shell used to be commercial/proprietary software.
----
Title: CVSweb for OpenBSD’s ksh
Link: http://www.openbsd.org/cgi-bin/cvsweb/src/bin/ksh/

This is OpenBSD’s version of pdksh, which has been enhanced
and bugfixed relative to it and eventually spawned mksh.
It has been ported to other operating systems several times:
<a href="http://www.delilinux.de/oksh/">oksh in DeliLinux</a>,
<a href="http://people.freebsd.org/~tmclaugh/">OpenKSH by
 FreeBSD’s Tom McLaughlin</a>, etc.
----
Title: Package page for pdksh in Debian
Link: http://packages.debian.org/sid/pdksh

This is Debian’s packaging of pdksh, which includes several
fixes from oksh and some of their own. These that were not
bogus found their way into mksh. It spawned posh (the POsix
SHell), which attempts to use pdksh code with Korn Shell
features removed to provide a viable <tt>/bin/sh</tt> for
Debian (and has since begun to take patches from mksh).
----
Title: ksh88 manual page
Link: http://uw714doc.sco.com/en/man/html.1/ksh88.1.html

ksh88 was the AT&amp;T Korn Shell before ksh93 happened.
It lacks many features from later pdksh versions and
especially pdksh/mksh. It’s mainly suited for scripting
these days, and comes with many commercial/proprietary
operating systems.
----
Title: MKS Toolkit
Link: http://www.mkssoftware.com/products/tk/ds_tkdev.asp

The MKS ksh is the one David Korn lost some disapproving
words about. Nevertheless, it implements some part of the
Korn Shell language and is available for certain systems.
----
Title: Morris Bolsky, The KornShell Command and Programming Language
ISBN: 978-0-13-516972-8 (0-13-516972-0)

Prentice Hall PTR, xvi + 356 pages, 1989.
Covers ksh88.
----
Title: Morris I. Bolsky and David G. Korn, The New KornShell Command and Programming Language (2nd Edition)
ISBN: 978-0-13-182700-4 (0-13-182700-6)

Prentice Hall PTR, xvi + 400 pages, 1995.
Covers ksh93; co-authored by its creator.
----
Title: Stephen G. Kochan and Patrick H. Wood, UNIX Shell Programming
ISBN: 978-0-672-48448-3 (0-672-48448-X)

Hayden, Revised Edition, xi + 490 pages, 1990.
----
Title: IEEE Standard for Information Technology – Portable Operating System Interface (POSIX)
ISBN: 978-1-55937-255-8 (1-55937-255-9)

IEEE Press, Part 2: Shell and Utilities, xvii + 1195 pages, 1993.
----
Title: The Open Group Base Specifications Issue 7 – IEEE Std 1003.1-2008 – Shell &amp; Utilities
Link: http://www.opengroup.org/onlinepubs/9699919799/utilities/toc.html

Online version of the POSIX/SUSv4 standard on shells.
----
Title: Bill Rosenblatt, Learning the Korn Shell
ISBN: 978-1-56592-054-5 (1-56592-054-6)

O'Reilly, 360 pages, 1993.
It’s a good introduction and reference to ksh88; most of it
(except the DEBUG trap related part) also applies to pdksh/mksh.
The ridge between shell scripting and shell programming is
surpassed a few times.
----
Title: Bill Rosenblatt and Arnold Robbins, Learning the Korn Shell, Second Edition
ISBN: 978-0-596-00195-7 (0-596-00195-9)

O'Reilly, 432 pages, 2002.
Second Edition of the famous ksh book from O’Reilly, targetting
ksh93 this time.
----
Title: Barry Rosenberg, KornShell Programming Tutorial
ISBN: 978-0-201-56324-5 (0-201-56324-X)

Addison-Wesley Professional, xxi + 324 pages, 1991.
According to the old <tt>#ksh</tt> topic, this is a “good book”.
----
Title: Solaris ksh93-integration project
Link: http://www.opensolaris.org/os/project/ksh93-integration/

Homepage of the project attempting to integrate ksh93 in Solaris,
replacing both ksh88 and their Bourne (nōn-POSIX) <tt>/bin/sh</tt>.
(Although <tt>mirabilos</tt> thinks that the old ksh88 should not
be available as <tt>/usr/bin/oksh</tt> but rather ksh88, due to
oksh’s existence as pdksh derivate.)
----
Title: OpenSolaris shell coding style guidelines
Link: http://www.opensolaris.org/os/project/shell/shellstyle/

[DRAFT] Bourne/Korn Shell Coding Conventions
----
Title: Introduction into Korn Shell (ksh) Programming
Link: http://www.bolthole.com/solaris/ksh.html

Basic tutorial for shell scripting, with focus on ksh.
----
Title: IBM Developerworks articles on Korn shell scripting
Link: http://www.ibm.com/developerworks/aix/library/au-kornshellscripting/

Korn shell scripting is something all UNIX® users should learn how to
use. Shell scripting provides you with the ability to automate many
tasks and can save you a great deal of time. It may seem daunting at
first, but with the right instruction you can become highly skilled in
it. This article will teach you to write your own Korn shells scripts.
----
Title: Programming Language News – Shell
Link: http://plnews.org/category/Languages__Shell/

Generic shell-related newsfeed.
----
Title: Sven Mascheck’s Unix and Shell page
Link: http://www.in-ulm.de/~mascheck/

Plethora of historic and recent information on shells on
various unicēs, the shebang, urban legends, etc.
----
Title: comp.unix.shell Frequently Asked Questions
Link: http://cfajohnson.com/shell/cus-faq.html

FAQ of the Usenet group <tt>comp.unix.shell</tt>
----
Title: csh Programming Considered Harmful
Link: http://www.faqs.org/faqs/unix-faq/shell/csh-whynot/

Rather polarising article about why the C Shell is not desirable.
----
Title: * Portable Shell::
Link: http://www.gnu.org/software/autoconf/manual/html_node/Portable-Shell.html

Part of the GNU Autoconf manual dealing with how to make shell
scripts portable (if desirable to not target one specific shell,
such as ksh93 or mksh, and making that one portable). Interesting
for archæologists as well.
----
