RCSID: $MirOS: www/data/wlog2018.inc,v 1.1 2018/05/05 17:40:33 tg Exp $
Title: FixedMisc [MirOS] 20180429 released
Date: 29.04.2018 17:30
Author: tg@
Tag: news pcli

<p>Today I’ve released another new CVS snapshot of the <a
 href="@@ABSPATH@@/MirOS/dist/mir/Foundry/"><tt>FixedMisc [MirOS]</tt>
 font</a>; as usual, the tarball contains the font in BDF form, with
 no conflict with the system <tt>Fixed [Misc]</tt> font; <a
 href="@@RELPATH@@cvs.cgi/contrib/fonts/fixed/">sources</a>
 for use (compilation, editing) with bdfctool(1) are in CVS.</p>
----
Date: 2018-05-05 17:11
Title: Website consolidation

<p>I’m currently working on consolidating <tt>mirsolutions.de</tt>
 (as my former business is long defunct) and “The MirOS Project”
 (that as of 2018 is also back to being my own one-man show / hobby)
 into <tt>www.mirbsd.org</tt> as my hobby / personal sorta homepage
 to not need any vhosts and simplify EU-DSGVO conformity. (I’ve also
 reduced logging.) Please excuse upheavals, as well as the continued
 presence of old, obsoleted or outdated content that may even be, as
 of now, completely wrong; I’ll fix it as time permits.</p>
----
