RCSID: $MirOS: www/data/WPtg.inc,v 1.89 2013/11/08 21:56:52 tg Exp $
# ^K/ mksh -c '. ../mk/common; xhtml_escape'
ID: 1
Date: 09.07.2006
Waypoint: GCN89C OC01A9
Title: Endenich-City-Cache
Tag: recommended
----
ID: 2
Date: 29.10.2006
Waypoint: GCQD10 OC03E3
Title: Bonner Aussicht
----
ID: 3
Date: 05.08.2007
Waypoint: GCPJDM OC08CA
Title: Knochenarbeit
Tag: recommended
----
ID: 4
Date: 11.08.2007
Waypoint: GC11B5G OC3073
Title: Sisutl - die doppelköpfige Schlange
Tag: recommended
----
ID: 5
Date: 12.08.2007
Waypoint: GCTH34 OC181A
Title: Mineralbrunnen Bad Godesberg
Tag: recommended
----
ID: 6
Date: 12.08.2007
Waypoint: GC13FTW OC38D1
Title: Kleines Theater Bad Godesberg
----
ID: 7
Date: 12.08.2007
Waypoint: GC13D5T OC3CDA
Title: Jotts Bonncaches - Stadthaus
----
ID: 8
Date: 19.08.2007
Waypoint: GCRFW6 OC0FA4 N01D62
Title: Urzeit im Bergischen - 2 : Dolomitkorallen
----
ID: 9
Date: 20.08.2007
Waypoint: GC12XJK OC368A
Title: Bonner Aussicht (reloaded)
Tag: recommended
----
ID: 10
Date: 12.09.2007
Waypoint: OC0B53
Title: chameleon at night
----
ID: 11
Date: 19.09.2007
Waypoint: GCTEYQ OC18F8
Title: Geocoin Micro #4
----
ID: 12
Date: 19.09.2007
Waypoint: GCYZR8 N0230A OC2777
Title: Heute schon gelesen? [de/en/fr]
Tag: recommended
----
ID: 13
Date: 23.09.2007
Waypoint: GC14VCA OC3D6C
Title: Park Friesdorf
----
ID: 14
Date: 23.09.2007
Waypoint: GCTEYN OC18F6
Title: Geocoin Micro #2
----
ID: 15
Date: 23.09.2007
Waypoint: GCTPRE OC18D5
Title: Bismarckturm Godesberg
----
ID: 16
Date: 23.09.2007
Waypoint: GCTEYP OC18F7
Title: Geocoin Micro #3
----
ID: 17
Date: 23.09.2007
Waypoint: GCTY5D OC1960
Title: Bismarckturm Gronau
----
ID: 18
Date: 24.09.2007
Waypoint: GCW7QP OC1D38
Title: Gotteshäuser : Stimson Memorial Chapel
----
ID: 19
Date: 05.10.2007
Waypoint: GCTH09 OC1810
Title: Kirchen &amp; Kapellen #1 - Kapelle St. Michael
----
ID: 20
Date: 05.10.2007
Waypoint: GCZ3DE OC3466
Title: MPI: Radi
----
ID: 21
Date: 07.10.2007
Waypoint: GCQT3Z OC06E0
Title: Burgen &amp; Schlösser #2 - La Redoute
----
ID: 22
Date: 07.10.2007
Waypoint: GCME6W OC17DC
Title: Oberkasseler Seen
Tag: recommended
----
ID: 23
Date: 14.10.2007
Waypoint: GCQGJB OC06D3
Title: Burgen &amp; Schlösser #1 - Godesburg
----
ID: 24
Date: 14.10.2007
Waypoint: GCV49V OC1D3B
Title: Gotteshäuser: Alter Kirchturm
----
ID: 25
Date: 23.10.2007
Waypoint: GCZTF4
Title: EMA Haus
----
ID: 26
Date: 23.10.2007
Waypoint: GCPC7P
Title: Gotteshäuser: Bonner Münster
----
ID: 27
Date: 28.10.2007
Waypoint: GCPV0W
Title: Der Heilige Gral
----
ID: 28
Date: 28.10.2007
Waypoint: GCR2QX OC06E2
Title: Burgen &amp; Schlösser #5 - Hexenturm
----
ID: 29
Date: 28.10.2007
Waypoint: GC171HX OC280D
Title: Beuelskopf
Tag: recommended
----
ID: 30
Date: 28.02.2008
Waypoint: GCY1ZJ
Title: Gotteshäuser: Waldkapelle Rheinbach
Tag: recommended
----
ID: 31
Date: 08.03.2008
Waypoint: GC13DV2 OC45C0
Title: Jotts Bonncaches - RLK
----
ID: 32
Date: 13.03.2008
Waypoint: GC16DTB OC45BD
Title: Jotts Bonncaches - Sportpark Nord
----
ID: 33
Date: 29.03.2008
Waypoint: GC14KN7
Title: Ein Stern, der Deinen Namen trägt
----
ID: 34
Date: 06.04.2008
Waypoint: OC4FCA
Title: Park and Ride Bad Godesberg
----
ID: 35
Date: 06.04.2008
Waypoint: GCQJ9P OC0159
Title: Bonner Sudoku #1
----
ID: 36
Date: 06.04.2008
Waypoint: GC17VKW OC4AEB
Title: Kirchen &amp; Kapellen #7 - Sebastianus Kapelle
----
ID: 37
Date: 12.04.2008
Waypoint: GCTEZ0 OC18FC
Title: Geocoin Micro #8
----
ID: 38
Date: 12.04.2008
Waypoint: GC14BJ2 OC3C69
Title: Tauschstübchen - Vinyl
----
ID: 39
Date: 14.04.2008
Waypoint: TC9AV
Title: Deutscher Terracachingpreis 2008
----
ID: 40
Date: 14.04.2008
Waypoint: LCHU
Title: WCG (aka How to Fold a Protein)
----
ID: 41
Date: 17.04.2008
Waypoint: GC10BF9
Title: Erdbeergraben
----
ID: 42
Date: 20.04.2008
Waypoint: GCQT4B OC06E1
Title: Burgen &amp; Schlösser #3 - Kommende Muffendorf
----
ID: 43
Date: 21.04.2008
Waypoint: GC17VKD OC4AEA
Title: Kirchen &amp; Kapellen #6 - Rigalsche Kapelle
----
ID: 44
Date: 24.04.2008
Waypoint: GCT7PV N01ECF OC1698
Title: Durch den Langeberg - Canyon
Tag: recommended exceptional
----
ID: 45
Date: 25.04.2008
Waypoint: OC58A8 N0294A GC171JK
Title: Gotteshäuser: Rüngsdorf Marienkapelle
nTF: 0
----
ID: 46
Date: 25.04.2008
Waypoint: OC58A9
Title: Gotteshäuser: Mehlem Kirche St. Severin
nTF: 0
----
ID: 47
Date: 25.04.2008
Waypoint: GC18N2M OC6641
Title: Gotteshäuser: Erlöserkirche Bad Godesberg
----
ID: 48
Date: 12.05.2008
Waypoint: GC1AB2F OC59B8
Title: Underground Embassy
Tag: recommended exceptional
----
ID: 49
Date: 20.06.2008
Waypoint: GC1DC3T OC5E73
Title: IPTC BN
Tag: recommended
----
ID: 50
Date: 11.07.2008
Waypoint: GC17828 OC47C0
Title: Der Riese am Strom
----
ID: 51
Date: 11.07.2008
Waypoint: GCXHKQ OC22C7
Title: Kirchen &amp; Kapellen #4 - Kirche Oberdollendorf
----
ID: 52
Date: 13.07.2008
Waypoint: GCQGKG OC06D6
Title: Den Wald vor lauter Bäumen ...
----
ID: 53
Date: 14.07.2008
Waypoint: GCW1C0 OC272D
Title: Das Baumschulwäldchen
----
ID: 54
Date: 15.07.2008
Waypoint: OC58AE
Title: Bonner Stolpersteine
----
ID: 55
Date: 19.07.2008
Waypoint: GC13MZN OC399D
Title: Unter Dampf No. #4 - Drachenfelsbahn
----
ID: 56
Date: 19.07.2008
Waypoint: GCTEZ1 OC18FD
Title: Geocoin Micro #9
----
ID: 57
Date: 19.07.2008
Waypoint: GCTEYY OC18FB
Title: Geocoin Micro #7
----
ID: 58
Date: 26.07.2008
Waypoint: GCHDCV N00D17 OC0154
Title: Kreuzberg (Patch)
----
ID: 59
Date: 09.08.2008
Waypoint: GC1AQE9
Title: Gundeldinger Feld
----
ID: 60
Date: 10.08.2008
Waypoint: LCHX
Title: Google Up A Locationless!
----
ID: 61
Date: 10.08.2008
Waypoint: GC15QBA
Title: La Fonderie
----
ID: 62
Date: 10.08.2008
Waypoint: GC17K93
Title: Le &#34;Schweissdissi&#34;
----
ID: 63
Date: 10.08.2008
Waypoint: GC1BF7A
Title: CIT'in #01
----
ID: 64
Date: 13.08.2008
Waypoint: GCXYKM
Title: Alte Eiche
----
ID: 65
Date: 14.08.2008
Waypoint: GC1CYW0
Title: Thurbo Altstätten
----
ID: 66
Date: 14.08.2008
Waypoint: GC14367
Title: Nervensäge  #4 - Rheintal
----
ID: 67
Date: 24.08.2008
Waypoint: GC16AT3 OC438C
Title: Jens ärgere dich nicht!
----
ID: 68
Date: 01.09.2008
Waypoint: GC1BBVN
Title: Basel Big City II.
----
ID: 69
Date: 07.09.2008
Waypoint: GC17550
Title: Parc de la Bourse  ( SIM )
----
ID: 70
Date: 07.09.2008
Waypoint: GC1E8CZ
Title: La Loco
----
ID: 71
Date: 07.09.2008
Waypoint: GC1EQ5G
Title: Le passage
Tag: recommended exceptional
----
ID: 72
Date: 09.09.2008
Waypoint: GC1E752
Title: IWB Cache
----
ID: 73
Date: 11.09.2008
Waypoint: GC13ET7
Title: Basel SBB B-Seite (Bahnhof-Micro-Cache)
----
ID: 74
Date: 06.10.2008
Waypoint: GC1FMN4
Title: XVII. Geocacher Stammtisch Bonn
----
ID: 75
Date: 15.10.2008
Waypoint: GC1D4PK OC5DF1
Title: Römerbad
----
ID: 76
Date: 18.10.2008
Waypoint: GC1GZJW OC6A88
Title: AWK-Nachleese
----
ID: 77
Date: 21.01.2009
Waypoint: GC14Y1G OC3DD1
Title: K.Ö.B. ein Micro
----
ID: 78
Date: 25.01.2009
Waypoint: GC1J35E OC7153
Title: Candy OrdersTation
----
ID: 79
Date: 07.03.2009
Waypoint: GC1JQ65
Title: Haus Carstanjen
----
ID: 80
Date: 07.03.2009
Waypoint: GC1J188
Title: Japanischer Garten
----
ID: 81
Date: 07.03.2009
Waypoint: GCW9DC
Title: Stunde Null
----
ID: 82
Date: 11.03.2009
Waypoint: GC144QN
Title: Gotteshäuser in Karlsruhe: St. Stephan
----
ID: 83
Date: 11.03.2009
Waypoint: GC12ZKB
Title: Die G-Serie: &#34;Nullrunde&#34;
----
ID: 84
Date: 13.03.2009
Waypoint: GCZRJF
Title: Karlsruher Hauptbahnhof (Gleis 9 ¾)
----
ID: 85
Date: 28.03.2009
Waypoint: GC1N4D7
Title: Wir lieben Schach
----
ID: 86
Date: 29.03.2009
Waypoint: OC7CEB
Title: Friesdorfer Schrebergärten
nTF: 1
----
ID: 87
Date: 31.03.2009
Waypoint: GC1P8CB OC7CD7
Title: Bonn Hbf reloaded
----
ID: 88
Date: 12.04.2009
Waypoint: GC1NN6F
Title: Häuser der Helfer - DRK Kreisverband Bonn
----
ID: 89
Date: 15.04.2009
Waypoint: OC6961
Title: Töffi´s freie Hotspots
----
ID: 90
Date: 25.06.2009
Waypoint: GC14AXW
Title: Amtsgericht
----
ID: 91
Date: 26.06.2009
Waypoint: GC1CNRA
Title: Deutschlandhalle - das Ende naht
----
ID: 92
Date: 26.06.2009
Waypoint: GC1GD07
Title: Messewelten
----
ID: 93
Date: 26.06.2009
Waypoint: GC1JGX1
Title: Sender Witzleben
----
ID: 94
Date: 29.06.2009
Waypoint: GC1R4BE OC8A78
Title: Gotteshäuser: St. Quirinus (Dottendorf)
----
ID: 95
Date: 14.07.2009
Waypoint: GC16H3M
Title: Kliever Rakete
----
ID: 96
Date: 14.07.2009
Waypoint: GC18WZY
Title: Zum Piepen
Tag: recommended
----
ID: 97
Date: 14.07.2009
Waypoint: GC172DA
Title: Am Wegesrand #1
----
ID: 98
Date: 19.07.2009
Waypoint: GC1FPE4
Title: Kriegerdenkmal
----
ID: 99
Date: 20.07.2009
Waypoint: GCTYFY
Title: H2O
----
ID: 100
Date: 20.07.2009
Waypoint: GC1PQR1
Title: GC an der CG
----
ID: 101
Date: 21.07.2009
Waypoint: GC1PPQ3
Title: Benni's Bahnhof (Dortmund Hbf)
----
ID: 102
Date: 25.07.2009
Waypoint: GC1R8CB
Title: Posttower
----
ID: 103
Date: 04.08.2009
Waypoint: GC1V4T4
Title: St. Hildegard
----
ID: 104
Date: 16.08.2009
Waypoint: GC1X13J
Title: LPG
----
ID: 105
Date: 17.08.2009
Waypoint: GC182W4 OC87EA
Title: Gotteshäuser: St. Peter (Lengsdorf - Tradi)
----
ID: 106
Date: 22.08.2009
Waypoint: GC1AAY8 OC5463
Title: Pleiser Park
----
ID: 107
Date: 22.08.2009
Waypoint: GC1PKT5
Title: The Rock
----
ID: 108
Date: 31.08.2009
Waypoint: GC1QTP9
Title: Knackes Park (D1,5/T1;micro)
----
ID: 109
Date: 31.08.2009
Waypoint: GC1P0G3 OCB3FA
Title: Bonner Kunstwerke: Vorgang - Zustand
----
ID: 110
Date: 27.09.2009
Waypoint: GC1XCN9
Title: Gotteshäuser: Friedenskirche Bonn
----
ID: 111
Date: 06.10.2009
Waypoint: GC1X8D6
Title: Cachicamo2
----
ID: 112
Date: 13.03.2010
Waypoint: GC1BJYC
Title: UPN (RPN)
Tag: recommended tech
----
ID: 113
Date: 13.03.2010
Waypoint: GC1ENRB
Title: Wasserfall in Chemnitz
----
ID: 114
Date: 06.04.2010
Waypoint: GC1Z2TP
Title: Dancefloor
----
ID: 115
Date: 18.04.2010
Waypoint: GC1HW1B OC6D5F
Title: Schlauchomat am 50. Breitengrad
----
ID: 116
Date: 24.04.2010
Waypoint: GC2785K
Title: Friesdorfer Schleichwege 2
----
ID: 117
Date: 24.04.2010
Waypoint: GC267YH
Title: Friesdorfer Schleichwege 1
----
ID: 118
Date: 25.04.2010
Waypoint: GC26Z0F
Title: Der Schatz am Steinspielplatz (Stone Playground)
----
ID: 119
Date: 25.04.2010
Waypoint: GC25DAR
Title: Japanischer Garten
----
ID: 120
Date: 26.04.2010
Waypoint: GC1ZDQ4
Title: Gotteshäuser &#34; St.Matthias &#34;
----
ID: 121
Date: 03.05.2010
Waypoint: GC20C97 OC661E
Title: Technik trifft Ästhetik
----
ID: 122
Date: 03.05.2010
Waypoint: GC1X2NM
Title: Hochwasserpumpwerk

Duplikat von OC661E (welches bereits als GC20C97 gelistet ist)
----
ID: 123
Date: 08.05.2010
Waypoint: GC27JED OCA47D
Title: New BriTge
----
ID: 124
Date: 10.05.2010
Waypoint: GC18BFD
Title: Gotteshäuser: Benediktinerinnenkloster
----
ID: 125
Date: 18.05.2010
Waypoint: GC28KGC OCA569
Title: Gotteshäuser: Erlöserkirche Bad Godesberg II
----
ID: 126
Date: 28.05.2010
Waypoint: GC27W5J OC2E5B
Title: Uni-Werkstätten
----
ID: 127
Date: 11.06.2010
Waypoint: GC1TXZE
Title: Willkommen in...NIEDERBACHEM
----
ID: 128
Date: 12.06.2010
Waypoint: GC202AK
Title: Kein COVO LOCO #0210
----
ID: 129
Date: 12.06.2010
Waypoint: GC1ZK8Y
Title: Die Brücke
----
ID: 130
Date: 26.06.2010
Waypoint: GCKFAQ N029CD OC020E
Title: IMC No. 2 P-LU – Music in the AIR
Tag: recommended
----
ID: 131
Date: 26.06.2010
Waypoint: GC2AEA1
Title: Irsental-Brücke am Waldpark-Eifel
----
ID: 132
Date: 09.07.2010
Waypoint: GC1HJDY
Title: Jeu à plusieurs dimensions
----
ID: 133
Date: 01.09.2010
Waypoint: GC27Y7G
Title: LP Bullenkloster
Tag: recommended
----
ID: 134
Date: 13.09.2010
Waypoint: GC21PBJ
Title: Advent-Advent: Nikolaus oder Weihnachtsmann?
----
ID: 135
Date: 13.09.2010
Waypoint: GC25ZYH
Title: Blütenzauber in Sülz - MARSILIUS Geschichte
----
ID: 136
Date: 25.09.2010
Waypoint: GC2F8CX OCB099
Title: DER SCHLÜSSEL ZUM CODE
----
ID: 137
Date: 26.09.2010
Waypoint: GC2FF7R OCB0FE
Title: Millionenfalle
----
ID: 138
Date: 04.10.2010
Waypoint: GC2DJRF OCAD67
Title: 555
----
ID: 139
Date: 04.10.2010
Waypoint: GC1WMEA
Title: Mal schnell nen Micro 2 !
----
ID: 140
Date: 10.10.2010
Waypoint: GC1ZWFD
Title: Haus der Kultur
----
ID: 141
Date: 07.11.2010
Waypoint: GC2HW42 OCB65A
Title: Regulaxus
nTF: 2

Und Natureshadow hat den LTF gemacht…
----
ID: 142
Date: 22.11.2010
Waypoint: GC2C0E2
Title: Klettenberger Stern
----
ID: 143
Date: 16.01.2011
Waypoint: GC2M3KH OCBAE9
Title: Erzähl mir von alten Zeiten... (D2/T1.5)
----
ID: 144
Date: 17.01.2011
Waypoint: GC2KTC2
Title: Kessenicher Schleichwege #2
----
ID: 145
Date: 17.01.2011
Waypoint: GC2KTBR
Title: Kessenicher Schleichwege #1
----
ID: 146
Date: 06.02.2011
Waypoint: GC2EWPX
Title: Le photographe 3
----
ID: 147
Date: 06.02.2011
Waypoint: GC2D9CV
Title: Brussels South Station
----
ID: 148
Date: 16.02.2011
Waypoint: GC2MP54
Title: Dottendorfer Schleichwege #1
Tag: recommended
----
ID: 149
Date: 17.02.2011
Waypoint: GC2JK66
Title: Der Nikolaus kommt aus Kessenich
----
ID: 150
Date: 19.03.2011
Waypoint: GC1H5ZA
Title: Gashavariehahn
----
ID: 151
Date: 27.03.2011
Waypoint: GC2N73B
Title: Noch ein Schleichweg
----
ID: 152
Date: 27.03.2011
Waypoint: GC24FW8
Title: ichkennedyecke
----
ID: 153
Date: 27.03.2011
Waypoint: GC259QP
Title: 4 - Alleen - Kreuzung
----
ID: 154
Date: 06.04.2011
Waypoint: GC2Q0XB
Title: Wachtberger Kreuze 7
----
ID: 155
Date: 06.04.2011
Waypoint: GC2C8YV
Title: Wachtberger Kreuze 5
----
ID: 156
Date: 20.04.2011
Waypoint: GC1XZFX
Title: Wegkreuz an der alten L 61
Tag: recommended
----
ID: 157
Date: 01.06.2011
Waypoint: GC23YYM
Title: Maus-oleum
----
ID: 158
Date: 01.06.2011
Waypoint: GC267WM
Title: Der vergessene Fisch
----
ID: 159
Date: 17.06.2011
Waypoint: GC24PEG
Title: Arboretum
----
ID: 160
Date: 17.06.2011
Waypoint: GCME69
Title: Wartenden
----
ID: 161
Date: 28.07.2011
Waypoint: OCCDDC
Title: Banja Luka • Бања Лука • #1
nTF: 0
----
ID: 162
Date: 20.08.2011
Waypoint: GC2D7KG
Title: TB-Hotel FH Sankt Augustin
----
ID: 163
Date: 20.08.2011
Waypoint: GC2BMDR
Title: Lost Place: &#34;Möbel Tacke&#34;
----
ID: 164
Date: 22.08.2011
Waypoint: GC2MTY8
Title: Stadtarchiv - Sülzer Neubau
----
ID: 165
Date: 03.09.2011
Waypoint: GC2X457
Title: das Tier in Dir  ;-)
----
ID: 166
Date: 03.09.2011
Waypoint: GC2WEP9
Title: Brücke an Magenta
----
ID: 167
Date: 03.09.2011
Waypoint: OCCCF4
Title: Pflaumenbaumhundeschleichweg
----
ID: 168
Date: 10.09.2011
Waypoint: GC2C8VH OCB56F
Title: das Goldene Em #BN1
----
ID: 169
Date: 10.09.2011
Waypoint: GC2VTRT OCC5D4
Title: Nächster Halt: Limperich Nord
----
ID: 170
Date: 11.09.2011
Waypoint: GC2VTR6 OCC5D5
Title: Nächster Halt: Küdinghoven
----
ID: 171
Date: 25.10.2011
Waypoint: GC2NVFZ
Title: BHO - Besondere Historische Orte 1
----
ID: 172
Date: 31.10.2011
Waypoint: GC1MDYJ
Title: Freundschaftscache Apfelallee
----
ID: 173
Date: 01.11.2011
Waypoint: GC2VKVZ
Title: MS19 - die älteste Cacherin Deutschlands
----
ID: 174
Date: 06.11.2011
Waypoint: GC1TABR OC9B8A
Title: Schwimmbad Bad Neuenahr
----
ID: 175
Date: 11.11.2011
Waypoint: GC33YM4 OCD217
Title: Kopfüber in die Nacht
Tag: recommended
----
ID: 176
Date: 11.11.2011
Waypoint: GC30F3G OCCE63
Title: Panoramabad Rüngsdorf
----
ID: 177
Date: 12.11.2011
Waypoint: GC244M1
Title: Ein Rundsitz auf der Promenade
----
ID: 178
Date: 13.11.2011
Waypoint: OCD2B7
Title: Sinn oder Sinnlosigkeit
----
ID: 179
Date: 02.02.2012
Waypoint: GC2YG0E
Title: Häuser d. Helfer: Freiwillige Feuerwehr Dottendorf
----
ID: 180
Date: 09.02.2012
Waypoint: GC281TW
Title: Schwimmbad Bonn Frankenbad
----
ID: 181
Date: 20.02.2012
Waypoint: GCK91R
Title: IMC No. 2 P-DE - No Wind over Schwelmer Stadwald?
Tag: recommended
----
ID: 182
Date: 20.02.2012
Waypoint: GC36MM4
Title: Warten auf die Nordbahntrasse
----
ID: 183
Date: 20.02.2012
Waypoint: GC2P5BB
Title: Eine von Zehn
Tag: recommended
----
ID: 184
Date: 20.02.2012
Waypoint: GC285T3
Title: Top Of Schwelm
----
ID: 185
Date: 22.02.2012
Waypoint: GC34FQV
Title: Sport ist Mord
----
ID: 186
Date: 29.02.2012
Waypoint: GC2PK4T
Title: Punktesammler
----
ID: 187
Date: 29.02.2012
Waypoint: GC1WEJD OC8B7F
Title: Römerbad - der Tradi
----
ID: 188
Date: 29.02.2012
Waypoint: GC313D2
Title: Pentaspastos
----
ID: 189
Date: 29.02.2012
Waypoint: GC371AB
Title: legio XXI rapax
----
ID: 190
Date: 29.02.2012
Waypoint: GC348WY
Title: Bonn
Tag: recommended

dreist
----
ID: 191
Date: 16.03.2012
Waypoint: GC23M4C
Title: Chemnitzer Brückenbauwerke - Bernhardstrasse
----
ID: 192
Date: 16.03.2012
Waypoint: GC36E83
Title: TB-Hotel Kirchheimer Dreieck
----
ID: 193
Date: 17.03.2012
Waypoint: GC248F9
Title: Technische Universität Chemnitz
----
ID: 194
Date: 17.03.2012
Waypoint: GC24582
Title: Chemnitzer Brückenbauwerke-Chemnitztalviadukt B95
----
ID: 195
Date: 17.03.2012
Waypoint: GC37EZ4
Title: BHF Chemnitz Mitte
----
ID: 196
Date: 17.03.2012
Waypoint: GC29AG3
Title: Such mich doch!
----
ID: 197
Date: 18.03.2012
Waypoint: GC2PTJK
Title: Diablos Nightmare - Der Totenbeschwörer
----
ID: 198
Date: 18.03.2012
Waypoint: GC2PTJ2
Title: Diablos Nightmare - Der Barbar
----
ID: 199
Date: 22.03.2012
Waypoint: GC31PGQ
Title: TbSC
----
ID: 200
Date: 24.03.2012
Waypoint: GC2Q86V
Title: crazy pics # 8
----
ID: 201
Date: 24.03.2012
Waypoint: GC2A5XP
Title: Ein einfaches Kreuz
----
ID: 202
Date: 09.04.2012
Waypoint: OCC5A3
Title: Der Wunschbaum
----
ID: 203
Date: 09.04.2012
Waypoint: GC273F3
Title: DENKstein (D1/T1.5/BYOP)
----
ID: 204
Date: 09.04.2012
Waypoint: GC36WAH
Title: Im Gedenken - In Memoriam
----
ID: 205
Date: 09.04.2012
Waypoint: GC2HCDM
Title: Alte Stadt Rheinbach (Öffnungszeiten beachten)
Tag: recommended
----
ID: 206
Date: 09.04.2012
Waypoint: GC2BGHQ
Title: Sankt Martin
----
ID: 207
Date: 09.04.2012
Waypoint: GC3DTG0
Title: Telefonjoker gesucht...
----
ID: 208
Date: 22.04.2012
Waypoint: GC1GEDG
Title: Hillijehüsje
----
ID: 209
Date: 25.04.2012
Waypoint: GC199YV
Title: Astronomie: Refraktorium
----
ID: 210
Date: 28.04.2012
Waypoint: GC3AV5W
Title: Nenn mich wie du willst
----
ID: 211
Date: 28.04.2012
Waypoint: GC260YR OCA170
Title: Unter Schafen
Tag: recommended
----
ID: 212
Date: 28.04.2012
Waypoint: GC313KA
Title: Lost Place - Das Autohaus
----
ID: 213
Date: 01.05.2012
Waypoint: GC161DG OCCF72
Title: Haus Carstanjen
----
ID: 214
Date: 01.05.2012
Waypoint: GC1TMRM
Title: Quer durch Plittersdorf
----
ID: 215
Date: 01.05.2012
Waypoint: GC28M7J
Title: Die &#34;Grünanlage&#34;
----
ID: 216
Date: 01.05.2012
Waypoint: GC2VPTF
Title: Park Sunday
----
ID: 217
Date: 01.05.2012
Waypoint: GC297FW
Title: Ev. Kliniken Bonn - Waldkrankenhaus
----
ID: 218
Date: 11.05.2012
Waypoint: GC2ZVQ3
Title: Der Medien-Cache - Reloaded
----
ID: 219
Date: 13.05.2012
Waypoint: GC2E86F
Title: Bonner Retter - Löscheinheit 11 -&gt; Bonn Mitte
----
ID: 220
Date: 28.05.2012
Waypoint: GC2YAH0
Title: Geo-Golf # 01
----
ID: 221
Date: 28.05.2012
Waypoint: GC2YAHC
Title: Geo-Golf # 02
----
ID: 222
Date: 28.05.2012
Waypoint: GC2YAHH
Title: Geo-Golf # 03
----
ID: 223
Date: 28.05.2012
Waypoint: GC2YAHQ
Title: Geo-Golf # 04
----
ID: 224
Date: 28.05.2012
Waypoint: GC2YAHX
Title: Geo-Golf # 05
----
ID: 225
Date: 28.05.2012
Waypoint: GC2YAJ0
Title: Geo-Golf # 06
----
ID: 226
Date: 28.05.2012
Waypoint: GC2YAJ3
Title: Geo-Golf # 07
----
ID: 227
Date: 28.05.2012
Waypoint: GC2YAJ8
Title: Geo-Golf # 09
----
ID: 228
Date: 28.05.2012
Waypoint: GC2YAJ9
Title: Geo-Golf # 10
----
ID: 229
Date: 28.05.2012
Waypoint: GC2YAJC
Title: Geo-Golf # 11
----
ID: 230
Date: 28.05.2012
Waypoint: GC2YAJE
Title: Geo-Golf # 12
----
ID: 231
Date: 28.05.2012
Waypoint: GC2YAJF
Title: Geo-Golf # 13
----
ID: 232
Date: 28.05.2012
Waypoint: GC2YAJH
Title: Geo-Golf # 14
----
ID: 233
Date: 28.05.2012
Waypoint: GC2YAJK
Title: Geo-Golf # 15
----
ID: 234
Date: 28.05.2012
Waypoint: GC2YAJQ
Title: Geo-Golf # 16
----
ID: 235
Date: 28.05.2012
Waypoint: GC2YAJT
Title: Geo-Golf # 17
----
ID: 236
Date: 28.05.2012
Waypoint: GC2YAJ4
Title: Geo-Golf # 18
----
ID: 237
Date: 28.05.2012
Waypoint: GC2YANG
Title: Geo-Golf Bonus
----
ID: 238
Date: 28.05.2012
Waypoint: GC24DN9
Title: Rätsel an der Rheinfähre
----
ID: 239
Date: 03.06.2012
Waypoint: GC2R1T3
Title: Drive In mit Aussicht
----
ID: 240
Date: 09.06.2012
Waypoint: GC3G5A2
Title: Bonn Grillt   2 0 1 2
----
ID: 241
Date: 09.06.2012
Waypoint: GC18ARR OC4D41
Title: Malen nach Zahlen II
----
ID: 242
Date: 09.06.2012
Waypoint: GC21K1J
Title: pünkTchen
----
ID: 243
Date: 09.06.2012
Waypoint: GC1M616
Title: The Cachers Home
----
ID: 244
Date: 09.06.2012
Waypoint: GC28VQ6
Title: Bonn - Südbrücke (A 562) - reloaded
----
ID: 245
Date: 10.06.2012
Waypoint: GC2E8G9
Title: Bonner Retter - BF Wache 2 -&gt; Bonn - Beuel
----
ID: 246
Date: 10.06.2012
Waypoint: GC2HPXC OCB9AF
Title: .
----
ID: 247
Date: 10.06.2012
Waypoint: GC3AH33
Title: Pfaffenpfädchenskreuz
----
ID: 248
Date: 10.06.2012
Waypoint: GC2PK16
Title: Ordo ab chao
----
ID: 249
Date: 10.06.2012
Waypoint: GC26QX2
Title: Bonn - Kennedybrücke (B 56)
----
ID: 250
Date: 10.06.2012
Waypoint: GC12B7W OC341E
Title: Augensausen II
----
ID: 251
Date: 24.06.2012
Waypoint: GC1Y54X
Title: Bonn Hbf re-reloaded
----
ID: 252
Date: 30.06.2012
Waypoint: GC2VVJT
Title: Ippendorfer Sportstätten #3
----
ID: 253
Date: 30.06.2012
Waypoint: GC2VVK7
Title: Ippendorfer Sportstätten #4
----
ID: 254
Date: 30.06.2012
Waypoint: GC2VV21
Title: Ippendorfer Sportstätten #2
----
ID: 255
Date: 30.06.2012
Waypoint: GC2VQ7P
Title: Ippendorfer Sportstätten #1
----
ID: 256
Date: 30.06.2012
Waypoint: GC2DCA6
Title: Kreuz am Wegesrand
----
ID: 257
Date: 30.06.2012
Waypoint: GC3MZJ5
Title: Ippendorfer Sportstätten #6
----
ID: 258
Date: 30.06.2012
Waypoint: GC2VTCD
Title: Drive in - Auf dem Weg zum größten Logbuch
----
ID: 259
Date: 30.06.2012
Waypoint: GC2TDN7
Title: Das größte Logbuch der Welt
Tag: recommended exceptional
----
ID: 260
Date: 05.07.2012
Waypoint: GC3KE8V
Title: Minden-/MuggelStation v3
----
ID: 261
Date: 05.07.2012
Waypoint: GC3KEH8
Title: (GC)TB-Lounge
----
ID: 262
Date: 07.07.2012
Waypoint: GC2N499
Title: Braunschweiger Spargel
Tag: recommended
----
ID: 263
Date: 07.07.2012
Waypoint: GC2771B
Title: Graffiti in Braunschweig
----
ID: 264
Date: 07.07.2012
Waypoint: GC3NY78
Title: Unterm Eis
----
ID: 265
Date: 07.07.2012
Waypoint: GC37WGE
Title: Kann schon mal länger dauern!!!
----
ID: 266
Date: 09.07.2012
Waypoint: GC3G0P1
Title: Düsseldorf Hbf - Bertha-von-Suttner-Platz
----
ID: 267
Date: 13.07.2012
Waypoint: GC1X77C
Title: It's All About the Numbers
----
ID: 268
Date: 14.07.2012
Waypoint: GC3KWY8
Title: Kessenicher Drive-In
----
ID: 269
Date: 11.08.2012
Waypoint: GC22944
Title: Königswinter Wanderparkplatz
----
ID: 270
Date: 11.08.2012
Waypoint: GC11EMP
Title: BAB3: Raststätte Fernthal West --&gt; Frankfurt
----
ID: 271
Date: 11.08.2012
Waypoint: GC174WD
Title: &#34;Lore ist silber!&#34;
----
ID: 272
Date: 11.08.2012
Waypoint: GC174WC
Title: &#34;Lore ist groß!&#34;
----
ID: 273
Date: 11.08.2012
Waypoint: GC17038
Title: &#34;Lore ist zu dritt!&#34;
----
ID: 274
Date: 11.08.2012
Waypoint: GC16VM0
Title: &#34;Lore ist flach!&#34;
----
ID: 275
Date: 18.08.2012
Waypoint: GC3K2JX
Title: Project
----
ID: 276
Date: 06.09.2012
Waypoint: GC2WW2T
Title: Wer lesen kann...
----
ID: 277
Date: 06.09.2012
Waypoint: GC36302
Title: Wildwechsel
----
ID: 278
Date: 06.09.2012
Waypoint: GC2WZDK
Title: Wachtberger Kreuze 9
----
ID: 279
Date: 06.09.2012
Waypoint: GC2XAFT
Title: Wachtberger Kreuze (sind wir bei 11?)
----
ID: 280
Date: 06.09.2012
Waypoint: GC35NXT
Title: Heiligenhäuschen Ließem
----
ID: 281
Date: 06.09.2012
Waypoint: GC2BJ0C
Title: Gotteshäuser – St. Gereon  (Niederbachem)
----
ID: 282
Date: 06.09.2012
Waypoint: GC2BHZK
Title: Häuser der Helfer – Feuerwehr Wachtberg #1
----
ID: 283
Date: 07.09.2012
Waypoint: GC37CWT
Title: &#34;Große Namen&#34; # 1
----
ID: 284
Date: 08.09.2012
Waypoint: GC38MCW
Title: Zum Burzeltag
----
ID: 285
Date: 08.09.2012
Waypoint: GC3N3KM
Title: In der Nähe meines großen gelben Bruders
----
ID: 286
Date: 09.09.2012
Waypoint: GC3BR42
Title: Kreuz am Wegesrand # 2
----
ID: 287
Date: 10.10.2012
Waypoint: GC1HGEH
Title: Eau de source à PARIS- Spring water in PARIS.
Tag: recommended earth
----
ID: 288
Date: 25.10.2012
Waypoint: GC2JBGV
Title: Blick auf Gewässer !
----
ID: 289
Date: 26.10.2012
Waypoint: GC3QPW7
Title: Starkes Bündnis
----
ID: 290
Date: 26.10.2012
Waypoint: GC3488X
Title: Eisenquelle Alfhausen / Iron source Alfhausen
Tag: recommended earth
----
ID: 291
Date: 26.10.2012
Waypoint: GC3QJWF
Title: Königswald
----
ID: 292
Date: 27.10.2012
Waypoint: GC2VA18
Title: noch'n apple a day ...
Tag: recommended
----
ID: 293
Date: 09.11.2012
Waypoint: GC2FW17
Title: Für S
----
ID: 294
Date: 24.11.2012
Waypoint: GC2BNY0
Title: Lore ist nicht weit (Tribute to Asbacher Bande)
----
ID: 295
Date: 25.12.2012
Waypoint: GC3CFD4
Title: Auf der Gassirunde...
----
ID: 296
Date: 05.01.2013
Waypoint: GC39NHA
Title: Unter den Linden
----
ID: 297
Date: 05.01.2013
Waypoint: GC3F81P
Title: ++++++++++[&gt;+++++++-]&gt;----.++++.
Tag: recommended tech
----
ID: 298
Date: 05.01.2013
Waypoint: GC32NGB
Title: Knubbelbaum
----
ID: 299
Date: 27.01.2013
Waypoint: GC3CFK2
Title: Burg-Bach-Kreuz-Ung
----
ID: 300
Date: 01.02.2013
Waypoint: GC1MZWP
Title: Expo58 - The Whirling Ear STEALTH
----
ID: 301
Date: 03.02.2013
Waypoint: GCRNQC
Title: Coudenberg
----
ID: 302
Date: 04.02.2013
Waypoint: GCR68J
Title: CINEMATEK
----
ID: 303
Date: 04.02.2013
Waypoint: GC2VH28
Title: Steinkreis
----
ID: 304
Date: 13.02.2013
Waypoint: GC22APZ
Title: Heinrichsblick
Tag: recommended
----
ID: 305
Date: 13.02.2013
Waypoint: GC2NDK9
Title: Burgen &amp; Schlösser - Rolandsbogen - dritte Ausgabe
----
ID: 306
Date: 13.02.2013
Waypoint: GC1TKGT
Title: Rodderberg Vulkan
Tag: recommended earth
----
ID: 307
Date: 02.03.2013
Waypoint: GC3YA6K
Title: Can you do it?
----
ID: 308
Date: 02.03.2013
Waypoint: GC40XBK
Title: Verschlumpft
Tag: recommended exceptional
----
ID: 309
Date: 10.03.2013
Waypoint: GC3NBWF
Title: The Invisible Bicycle
----
ID: 310
Date: 23.03.2013
Waypoint: GC40BKF
Title: Hagelsiepen
----
ID: 311
Date: 23.03.2013
Waypoint: GC3YJXK
Title: Oberbeck
----
ID: 312
Date: 23.03.2013
Waypoint: GC2NGB5
Title: Die Evangelisch-reformierte Kirche Radevormwald
----
ID: 313
Date: 24.03.2013
Waypoint: OCDF52
Title: Bonn estas bona
----
ID: 314
Date: 24.03.2013
Waypoint: GC1WPCE
Title: &#34;Der Gasometer&#34; vom Venusberg
----
ID: 315
Date: 24.03.2013
Waypoint: GC27TTG
Title: Im Gedenken an Dr. Gerold von Braunmühl
----
ID: 316
Date: 24.03.2013
Waypoint: GC3QRPH
Title: TB Hotel &#34;Fliegerbombe&#34;
----
ID: 317
Date: 24.03.2013
Waypoint: GC2QX6B
Title: Waldhütte
----
ID: 318
Date: 24.03.2013
Waypoint: GC43432
Title: Langweilliger Tradi weil einer keine Geduld hatte!
----
ID: 319
Date: 24.03.2013
Waypoint: GC14BJ8
Title: Tauschstübchen - Dvd
----
ID: 320
Date: 24.03.2013
Waypoint: GC1W442
Title: Lost Place: Diplomatenschule
----
ID: 321
Date: 24.03.2013
Waypoint: GC3B86C
Title: Wo die Sonne scheint
----
ID: 322
Date: 31.03.2013
Waypoint: GC1WVMW
Title: offenes Logbuch
----
ID: 323
Date: 31.03.2013
Waypoint: GC40WGQ
Title: Puddingbrezel und Kaffee
----
ID: 324
Date: 14.04.2013
Waypoint: GC40H1V
Title: Familie Levy
----
ID: 325
Date: 14.04.2013
Waypoint: GC3KZAX
Title: Asphaltcowboys
----
ID: 326
Date: 14.04.2013
Waypoint: GC3VHXY
Title: Willkommen in Mehlem 2.0
----
ID: 327
Date: 19.04.2013
Waypoint: GC1X2MD
Title: Bundesämter BBK und THW
----
ID: 328
Date: 19.04.2013
Waypoint: GC22BXK
Title: So ein Durcheinander
Tag: recommended tech
----
ID: 329
Date: 19.04.2013
Waypoint: GC31RJB
Title: Bonn-HiCOG, oder Stuttgart
----
ID: 330
Date: 19.04.2013
Waypoint: GC3DM51
Title: Muffendorf Bildstock II
----
ID: 331
Date: 19.04.2013
Waypoint: GC1P96M
Title: High Water Weinhaeuschen
----
ID: 332
Date: 20.04.2013
Waypoint: GC2C1QD
Title: Fliegen war ihr Leben
----
ID: 333
Date: 21.04.2013
Waypoint: GC3N21M
Title: ... in die Ferne
----
ID: 334
Date: 21.04.2013
Waypoint: GC3AJCG
Title: Lannesdorfer Pümpchen
----
ID: 335
Date: 21.04.2013
Waypoint: GC2JJ4D
Title: Häuser der Helfer &#34;Feuerwehr Bonn Lannesdorf“
----
ID: 336
Date: 22.04.2013
Waypoint: GC2TXZ3
Title: Gotteshäuser: Jesus-Christus-Kirche
----
ID: 337
Date: 28.04.2013
Waypoint: GC2PMYX
Title: Für Kinofans
----
ID: 338
Date: 06.05.2013
Waypoint: GC4AP8Y
Title: Gestrandet
----
ID: 339
Date: 06.05.2013
Waypoint: GC2NVG1
Title: HDH 1 - Helfer der Haustiere
----
ID: 340
Date: 07.05.2013
Waypoint: GC35YVZ
Title: SPANNEND!
----
ID: 341
Date: 07.05.2013
Waypoint: GC37CYC
Title: “Große Namen“ # 2
----
ID: 342
Date: 07.05.2013
Waypoint: GC2E8DX
Title: Bonner Retter - Löscheinheit 42 -&gt; Lengsdorf
----
ID: 343
Date: 07.05.2013
Waypoint: GC45V16
Title: Der größte TB der Welt
----
ID: 344
Date: 07.05.2013
Waypoint: GC3Y31B
Title: Ring*Con 2012
----
ID: 345
Date: 09.05.2013
Waypoint: GC3HRJQ
Title: Per &#34;Anhalter&#34; durch Buschdorf?
----
ID: 346
Date: 09.05.2013
Waypoint: GC13D9B
Title: Binnendüne Tannenbusch
Tag: earth
----
ID: 347
Date: 10.05.2013
Waypoint: GC3GRNT
Title: Eierkooche-Rötzje
----
ID: 348
Date: 10.05.2013
Waypoint: GC26TEW
Title: Sankt Augustin Mülldorf I
----
ID: 349
Date: 10.05.2013
Waypoint: GC3N0WW
Title: Grottis BK
----
ID: 350
Date: 10.05.2013
Waypoint: GC3YN2N
Title: Stellplatz
----
ID: 351
Date: 10.05.2013
Waypoint: GC2CEK0
Title: Häuser der Helfer: Polizeipräsidium Bonn
----
ID: 352
Date: 19.05.2013
Waypoint: GC4BJGJ
Title: Alles Lama oder was ?
----
ID: 353
Date: 20.05.2013
Waypoint: GC4C9HX
Title: In der Fremde Zuhause: Nepalesische Botschaft
----
ID: 354
Date: 20.05.2013
Waypoint: GC4C9RW
Title: PonyFish- Land - Außenstelle Mehlem
----
ID: 355
Date: 27.05.2013
Waypoint: GC30TF6
Title: Ich bin der Wald... (D2/T1.5/BYOP)
----
ID: 356
Date: 27.05.2013
Waypoint: GC210AZ
Title: Alles für den Ball – alles für den Verein…
----
ID: 357
Date: 28.05.2013
Waypoint: GC2E8DN
Title: Bonner Retter - Löscheinheit 41 -&gt; Duisdorf
----
ID: 358
Date: 30.05.2013
Waypoint: GC3D8H9
Title: Der Kolibri
----
ID: 359
Date: 30.05.2013
Waypoint: GC4BFHM
Title: Die Quelle des durstigen Wanderers
----
ID: 360
Date: 30.05.2013
Waypoint: GC43YQF
Title: Rodderberger Erdnuckel
----
ID: 361
Date: 30.05.2013
Waypoint: GCQCF8
Title: Auf dem Rodderberg
----
ID: 362
Date: 02.06.2013
Waypoint: GC2HKT7
Title: Projekttage: Lena Meyer-Landrut
----
ID: 363
Date: 02.06.2013
Waypoint: GC3A03V
Title: HERSEL 21
----
ID: 364
Date: 02.06.2013
Waypoint: GC42W4E
Title: Cacher - Rastplatz
----
ID: 365
Date: 02.06.2013
Waypoint: GC449JK
Title: Wider das Vergessen
----
ID: 366
Date: 02.06.2013
Waypoint: GC3JNKF
Title: Linie 16 - Haltepunkt Hersel
----
ID: 367
Date: 04.06.2013
Waypoint: GC2TJKT
Title: Godesberger Schleichwege
----
ID: 368
Date: 06.06.2013
Waypoint: GC4DDVE
Title: Auf den Spuren der Elfen
nTF: 1
----
ID: 369
Date: 06.06.2013
Waypoint: GC27MAQ
Title: Die Brücke
----
ID: 370
Date: 06.06.2013
Waypoint: GC48KGX
Title: Ausgefuchst
----
ID: 371
Date: 06.06.2013
Waypoint: GC1M87F
Title: Vorgartenschätzchen
----
ID: 372
Date: 06.06.2013
Waypoint: GC37WBE
Title: Bonner Katzenloch
----
ID: 373
Date: 06.06.2013
Waypoint: GC3VBVR
Title: Die Kurfürstenquelle
Tag: recommended
----
ID: 374
Date: 06.06.2013
Waypoint: GC35JTV
Title: Am alten Kloster
----
ID: 375
Date: 06.06.2013
Waypoint: GC33BD3
Title: Der Wächter ist ein Esel
----
ID: 376
Date: 08.06.2013
Waypoint: GC3XPT3
Title: TB-Hotel Rheinbach Nord
----
ID: 377
Date: 08.06.2013
Waypoint: GC26VVH
Title: Cache &amp; Rast - West (dt/en)
----
ID: 378
Date: 08.06.2013
Waypoint: GC2N8N8
Title: Cache &amp; Rast Ost - TB Motel

Haha, N-Acht Nacht… toller Waypoint-Code
----
ID: 379
Date: 08.06.2013
Waypoint: GC2P5WP
Title: T-Helferzelle
----
ID: 380
Date: 08.06.2013
Waypoint: GC27X28
Title: Ramershovener Verlies [LP]
Tag: recommended
----
ID: 381
Date: 08.06.2013
Waypoint: GC3CBKZ
Title: Schwarzes Steinkreuz
----
ID: 382
Date: 08.06.2013
Waypoint: GC30N2V
Title: Der Himmel über mir
----
ID: 383
Date: 08.06.2013
Waypoint: GC3CE7W
Title: Kleines Steinkreuz
----
ID: 384
Date: 09.06.2013
Waypoint: GC373EA
Title: Obsession bis zur Session
Tag: recommended tech
----
ID: 385
Date: 09.06.2013
Waypoint: GC3KBN1
Title: Das Planschbecken
----
ID: 386
Date: 09.06.2013
Waypoint: GC3HT0X
Title: Marias Rutsche
----
ID: 387
Date: 11.06.2013
Waypoint: GC2E89G
Title: Bonner Retter - Löscheinheit 14 -&gt; Endenich
----
ID: 388
Date: 17.06.2013
Waypoint: GC4BYEZ
Title: Wasserhäuschen
----
ID: 389
Date: 17.06.2013
Waypoint: GC2QA76
Title: Dorfbrunnen Hilgert

Wenn Du hier bist, bist Du falsch, wenn Du zur A3 Richtung Köln willst.
----
ID: 390
Date: 17.06.2013
Waypoint: GC188KM
Title: Das Goldene Em - Add on SU #1
----
ID: 391
Date: 20.06.2013
Waypoint: GC374F5
Title: Remember HIH
----
ID: 392
Date: 20.06.2013
Waypoint: GC2VQ5G
Title: Besuch aus der Antarktis ...

Natureshadow ist (multipel indirekt) schuld ☺
----
ID: 393
Date: 22.06.2013
Waypoint: OK00CA
Title: House of Correction
nTF: 2

Okay, I cheated a bit, here. But, pooh.
Whatever method is used to log the cache,
the result matters; it’s the same with
accidentally found Finals for Mystery or
other multi-stage caches.
----
ID: 394
Date: 22.06.2013
Waypoint: LC7TB
Title: Truly Well-Rounded Cacher LC - Level I
----
ID: 395
Date: 22.06.2013
Waypoint: LCR2
Title: WCG II - Keep it going
----
ID: 396
Date: 23.06.2013
Waypoint: LC7TL
Title: Birthday Coordinates
nTF: 3
----
ID: 397
Date: 24.06.2013
Waypoint: GC357H8
Title: Hintertürchen am Bolzplatz
----
ID: 398
Date: 24.06.2013
Waypoint: GC3DE82
Title: Kunst am Wegesrand
----
ID: 399
Date: 24.06.2013
Waypoint: GC3PZG4
Title: Muffendorfer Bildstöcke
----
ID: 400
Date: 28.06.2013
Waypoint: GC3VECK
Title: Project Eck 2013 - Meet &amp; Greet am Eck
----
ID: 401
Date: 28.06.2013
Waypoint: GCTJ8X
Title: ZEICHEN VND SÄTZE (Megaevent Version)
----
ID: 402
Date: 29.06.2013
Waypoint: GC3TECK
Title: Project Eck 2013
----
ID: 403
Date: 29.06.2013
Waypoint: GC4D97Q
Title: Weltrekord Lesen
----
ID: 404
Date: 29.06.2013
Waypoint: GC4EGFV
Title: Project Eck - Gabione

„Dosenfischer – Just another Brick in the Gabione“
(sie sind <em>wirklich</em> nicht Pink Floyd…)
----
ID: 405
Date: 29.06.2013
Waypoint: GC4E6VP
Title: Project Eck – Festungspark

Wenigstens den hier mal <em>ganz</em> alleine auf’m
MEGA-Event gefunden. Macht mehr Spaß als nur die
Schlange finden und sich hinten anstellen!
----
ID: 406
Date: 29.06.2013
Waypoint: GC4E6VK
Title: Project Eck – Kletterpark
----
ID: 407
Date: 29.06.2013
Waypoint: GC4E6TF
Title: Project Eck – BUGA2011

Hier mußten wir über die „Nachbarn“ schmunzeln,
fanden die angrenzenden Blumenbeete aber schöner
als den Matschweg.
----
ID: 408
Date: 29.06.2013
Waypoint: GC4E6TA
Title: Project Eck – Seilbahn

Ob Bonn auch so eine bekommt? Ist angenehmer als
die in den Alpen… immer noch suspekt, aber gut.
Wobei es am Venusberg ja nicht wirklich Not tut.
----
ID: 409
Date: 30.06.2013
Waypoint: GCGRNE
Title: Loreley
----
ID: 410
Date: 30.06.2013
Waypoint: GC3WECK
Title: Project Eck 2013 - Eine Schifffahrt die...

(Heißt aber Schiff<b>s</b>fahrt!) Trotzdem Danke
an die Orga, bis auf ein paar Nano-Stolperstellen
war das alles super organisiert und hat Spaß gemacht!
Und Kapitän Brummkreisel war auch gut drauf und wir
hatten definitiv das beste Schiff!
----
ID: 411
Date: 30.06.2013
Waypoint: GC4ACTK
Title: Weltkulturerbe Oberes Mittelrheintal
----
ID: 412
Date: 30.06.2013
Waypoint: GC4AF0X
Title: Wahrschau
----
ID: 413
Date: 30.06.2013
Waypoint: GC2QJVY
Title: Aussicht auf den Rhein
----
ID: 414
Date: 30.06.2013
Waypoint: GC4C4RB
Title: Verlorene Klöster Koblenz: Karmeliterkloster
----
ID: 415
Date: 02.07.2013
Waypoint: GC339M6
Title: 4 Freunde das sind wir
----
ID: 416
Date: 02.07.2013
Waypoint: GC34N3E
Title: Häuser der Beschaffer #00001: Das Beschaffungsamt
----
ID: 417
Date: 02.07.2013
Waypoint: GC2CG7T
Title: Ein Zwilling
----
ID: 418
Date: 07.07.2013
Waypoint: GC1V1EC
Title: Neue Perspektiven
----
ID: 419
Date: 11.07.2013
Waypoint: LC7TX
Title: WCG III - Ruby's Reward
nTF: 2
----
ID: 420
Date: 11.07.2013
Waypoint: GC3B0ZM
Title: First Davido
----
ID: 421
Date: 11.07.2013
Waypoint: GC2HJAC
Title: Peerd und Koh
----
ID: 422
Date: 12.07.2013
Waypoint: GC3VKY7
Title: Ich Glaub ich Seh Schwarz - Weiss
Tag: recommended
----
ID: 423
Date: 13.07.2013
Waypoint: GCN5KR
Title: Van Heek fabriek
----
ID: 424
Date: 13.07.2013
Waypoint: GC37CRJ
Title: klik en klaar
----
ID: 425
Date: 14.07.2013
Waypoint: GC2TZN3
Title: Godesberger Scheichwege
----
ID: 426
Date: 22.07.2013
Waypoint: LC7QP
Title: TerraCachin' Fashion
nTF: 2
----
ID: 427
Date: 27.07.2013
Waypoint: GC21CET
Title: Nacht der Vulkane 2013

Uns wurde nicht zuviel versprochen, und die Erde hat tatsächlich gebebt.
Die beiden Führungen in der Vulkan-Brauerei waren auch toll und sind
empfehlenswert… nur eine Marktlücke wäre da noch: Essen im Felsenkeller
(im Sommer schön kühl, im Winter wärmer).
----
ID: 428
Date: 27.07.2013
Waypoint: GC2BETC
Title: A u s l e g e r
----
ID: 429
Date: 27.07.2013
Waypoint: GC4FV10
Title: NdV 2013 - Street End
----
ID: 430
Date: 01.08.2013
Waypoint: GC4GDXD
Title: CAT - Eiszeit 1

Tolle Idee; übernehme ich mal, mit Einverständnis…
----
ID: 431
Date: 01.08.2013
Waypoint: GC3AGC4
Title: TBH: Gute Reise
----
ID: 432
Date: 01.08.2013
Waypoint: GC4E2A1
Title: Rosenhof Cache

Massiv off. Bessere Koordinaten in den Logs…
----
ID: 433
Date: 01.08.2013
Waypoint: GC4HHZZ
Title: Hinterm Busch gleich links
nTF: 4
----
ID: 434
Date: 02.08.2013
Waypoint: GC33PFB
Title: Wachtberger Kreuze # 12
----
ID: 435
Date: 03.08.2013
Waypoint: GC33PFW
Title: Wachtberger Kreuze # 13
----
ID: 436
Date: 04.08.2013
Waypoint: GC306MY
Title: Jagdbomber in Oberholtorf
----
ID: 437
Date: 04.08.2013
Waypoint: GCVNRH OC1CF3 N02049
Title: Gotteshäuser: Zwei Kirchen ohne Namen
Tag: recommended
----
ID: 438
Date: 05.08.2013
Waypoint: GC47F5Q
Title: Hier kämpft der Löwe
----
ID: 439
Date: 06.08.2013
Waypoint: GC48YTE
Title: C-H-B (Coin-Hotel-Bonn)
----
ID: 440
Date: 07.08.2013
Waypoint: GC35BNN
Title: Ankerbach
----
ID: 441
Date: 07.08.2013
Waypoint: GCV21F
Title: Burgen &amp; Schlösser #10 - Kommende Ramersdorf
----
ID: 442
Date: 08.08.2013
Waypoint: GC3GX1Y
Title: Planetenrunde-URANUS
----
ID: 443
Date: 09.08.2013
Waypoint: GC486WW
Title: Augustus MMXIII. (3)
----
ID: 444
Date: 10.08.2013
Waypoint: GC3TT0R
Title: Schafwiese
Tag: recommended

Korrekt müßte es Schaf<b>s</b>wiese heißen.
Geniales Logbuch!
----
ID: 445
Date: 10.08.2013
Waypoint: GC4F9VA
Title: Owerdreeser Ollichsmill
----
ID: 446
Date: 11.08.2013
Waypoint: GC4HMEG
Title: Sam´s Home

Der Owner möchte bitte einen
<a href="http://www.cl.cam.ac.uk/~mgk25/ucs/apostrophe.html">echten
Apostroph</a> verwenden, keinen Akzent Akut.
----
ID: 447
Date: 12.08.2013
Waypoint: GC4BQ6K
Title: Augustus MMXIII. (5)
----
ID: 448
Date: 13.08.2013
Waypoint: GC4B9T2
Title: Oberkasseler Schleichweg
----
ID: 449
Date: 14.08.2013
Waypoint: GC3KHW1
Title: Linie 66
----
ID: 450
Date: 15.08.2013
Waypoint: GC3CTKT
Title: Schieberjagd durch Duisdorf
----
ID: 451
Date: 16.08.2013
Waypoint: GC4644Q
Title: Das grunzende Schwein auf Oberwerth
----
ID: 452
Date: 17.08.2013
Waypoint: GC2WY3D
Title: Volvodidi&#96;s Werkstattcache

Den <a href="http://linuxwiki.de/ApoStrophen">Genitiv mit s</a> lernen wir noch.
----
ID: 453
Date: 18.08.2013
Waypoint: GC33VN3
Title: STOP - in 100 m
----
ID: 454
Date: 18.08.2013
Waypoint: GC2ZQYN
Title: Alfterer Kreuze 02
----
ID: 455
Date: 18.08.2013
Waypoint: GC337BR
Title: Alfterer Kreuze 13
----
ID: 456
Date: 18.08.2013
Waypoint: GC2ZVPG
Title: Alfterer Kreuze 09
----
ID: 457
Date: 19.08.2013
Waypoint: GC354VF
Title: Ruhe in Roisdorf
----
ID: 458
Date: 19.08.2013
Waypoint: GC3DGNB
Title: Der Birnbaum
----
ID: 459
Date: 20.08.2013
Waypoint: GC4G63X
Title: TB Hotel 24h open
----
ID: 460
Date: 20.08.2013
Waypoint: GC4EDZM
Title: Gemühtliches Plätzchen Drachenfelser Ländchen 1998

Gemütlich!
----
ID: 461
Date: 20.08.2013
Waypoint: GC4H000
Title: Der Apfelpetling
----
ID: 462
Date: 20.08.2013
Waypoint: GC4EP5K
Title: TBHotel am Zaun der Johannisbeeranlage 1998
----
ID: 463
Date: 20.08.2013
Waypoint: GC4ENN9
Title: Die Johannisbeere 1998
----
ID: 464
Date: 20.08.2013
Waypoint: GC4G3CG
Title: XXL Travel Bug House (Ließem)
Tag: recommended
----
ID: 465
Date: 20.08.2013
Waypoint: GC4H15Q
Title: Mathematik im Drachenfälser Ländchen

Der arme Fels… ;-)
----
ID: 466
Date: 20.08.2013
Waypoint: GC4EEFP
Title: TB Hotel an der Kuhweide 1998
----
ID: 467
Date: 20.08.2013
Waypoint: GC4EEGN
Title: Der Drahtspanner an der Schafswiese 1998
----
ID: 468
Date: 21.08.2013
Waypoint: GC4925P
Title: Bernd's Birthday 2
----
ID: 469
Date: 21.08.2013
Waypoint: GC49263
Title: Bernd's Birthday 3
----
ID: 470
Date: 22.08.2013
Waypoint: GC4JMH3
Title: Naturstrom-Bus
Tag: recommended
----
ID: 471
Date: 23.08.2013
Waypoint: GC4E446
Title: Kein Stein
----
ID: 472
Date: 23.08.2013
Waypoint: GC3EA3F
Title: Nepomuks Geheimnis
----
ID: 473
Date: 23.08.2013
Waypoint: GC4G1CG
Title: Bunker Beuel
----
ID: 474
Date: 24.08.2013
Waypoint: GC49258
Title: Bernd's Birthday 1
----
ID: 475
Date: 24.08.2013
Waypoint: GC4926M
Title: Bernd's Birthday 4
----
ID: 476
Date: 24.08.2013
Waypoint: GC49275
Title: Bernd's Birthday 5
Tag: recommended
----
ID: 477
Date: 24.08.2013
Waypoint: GC4926Y
Title: Bernd's Birthday 6
----
ID: 478
Date: 24.08.2013
Waypoint: GC49289
Title: Bernd's Birthday BONUS
----
ID: 479
Date: 25.08.2013
Waypoint: GC49Q9E
Title: Völker und Kulturen
----
ID: 480
Date: 26.08.2013
Waypoint: GC4BNWY
Title: Noch echte Dinos und das mitten in Oberkassel
----
ID: 481
Date: 27.08.2013
Waypoint: GC4G955
Title: Die Heiligen der letzten Tage
----
ID: 482
Date: 28.08.2013
Waypoint: GC1E8G7
Title: Unkelbacher Brücke
----
ID: 483
Date: 28.08.2013
Waypoint: GC4KY21
Title: Bandorfer Schutzbrücke
----
ID: 484
Date: 28.08.2013
Waypoint: GC33F6V
Title: Lost in Oedingen - GPS Gerät auf Abwegen
----
ID: 485
Date: 28.08.2013
Waypoint: GC1V5CW
Title: Willkommen in... Oedingen
----
ID: 486
Date: 28.08.2013
Waypoint: GC29GT4
Title: Aschermittwochs Cache
----
ID: 487
Date: 28.08.2013
Waypoint: GC4F9E3
Title: Micro im Dorf 1998
----
ID: 488
Date: 29.08.2013
Waypoint: GC35BNJ
Title: Wachtberger Kreuze # 19
----
ID: 489
Date: 29.08.2013
Waypoint: GC4HNY8
Title: Dűrschhaltevɑmȫjen / Stamina
Tag: D1 T1 Event
nTF: 0
----
ID: 490
Date: 29.08.2013
Waypoint: GC32HCK
Title: Gotteshäuser: Sankt Severin in Mehlem
Tag: D4 T35 Micro Mystery recommended

Geradezu faszinierend und ein würdiger Nachfolger für
meinen [#46] OC58A9 „Gotteshäuser: Mehlem Kirche St. Severin“!
----
ID: 491
Date: 30.08.2013
Waypoint: GC4H00C
Title: Willkommen auf dem Heiderhof 1998
Tag: D15 T2 Micro Tradi
----
ID: 492
Date: 30.08.2013
Waypoint: GC4H317
Title: Fuderbach/Heiderhof
Tag: D25 T15 Micro Tradi
----
ID: 493
Date: 31.08.2013
Waypoint: GC3WEZW
Title: Der Nachtfalke
Tag: D15 T15 Micro Tradi
----
ID: 494
Date: 20.08.2013
Waypoint: GC4G32E
Title: Nano statt Müll
Tag: D1 T15 Nano Tradi

Naja, bald sind die Sommerferien zum Glück zuende…
----
ID: 495
Date: 31.08.2013
Waypoint: GC4H12G
Title: ist nicht schwer ?! reloaded
Tag: D2 T1 Small Mystery
----
ID: 496
Date: 31.08.2013
Waypoint: GC1Z5AT
Title: Alles in ...
Tag: D3 T1 Micro Tradi
----
ID: 497
Date: 31.08.2013
Waypoint: GC3F6KK
Title: Welche Richtung ?
Tag: D2 T1 Micro Tradi
----
ID: 498
Date: 01.09.2013
Waypoint: GC17RCY
Title: Bonner Meilenstein
Tag: D25 T1 Micro Mystery
----
ID: 499
Date: 02.09.2013
Waypoint: GC36WWX
Title: Die Unvollendete - L471
Tag: D15 T2 Small Tradi
----
ID: 500
Date: 02.09.2013
Waypoint: GC36WQQ
Title: NRW 53 Challenge #Bonn
Tag: D2 T25 Small Mystery

T2½ ist etwas gewagt, wenn #499 nur T2 ist, aber… okay.
Ist jedenfalls nicht T4, auch wenn man’s gefrustet meint.
----
ID: 501
Date: 03.09.2013
Waypoint: GC2HX8V
Title: Spassaufgabe 100 Zellen
Tag: D25 T2 Micro Mystery
----
ID: 502
Date: 04.09.2013
Waypoint: GC44B4Q
Title: Geo-Schach in Unkelbach
Tag: D2 T2 Small Mystery recommended

Der Outdoorteil ist nicht zu unterschätzen und hat m.E. schon
eher D2½ T2½ verdient. Nicht nachts machen. Beim Rätsel auch
mal beim Rechnen nicht zu kompliziert denken.
----
ID: 503
Date: 05.09.2013
Waypoint: GC3FP98
Title: TB Bunker BONN Duisdorf
Tag: D2 T2 Large Tradi recommended
----
ID: 504
Date: 12.09.2013
Waypoint: GC4FE20
Title: geHÖRT das so?!
Tag: D3 T15 Micro Tradi
----
ID: 505
Date: 12.09.2013
Waypoint: GC4EEAT
Title: An der Kuhweide 1998
Tag: D2 T15 Micro Tradi
----
ID: 506
Date: 13.09.2013
Waypoint: GC40K27
Title: Bonner PETlinge #2
Tag: D1 T15 Micro Tradi
----
ID: 507
Date: 14.09.2013
Waypoint: GC2YAPG
Title: Wachtberger Kreuze # 3
Tag: D2 T1 Micro Tradi
----
ID: 508
Date: 15.09.2013
Waypoint: GC2TXYD
Title: Witterschlicker Grillplatz
Tag: D15 T2 Micro Tradi
----
ID: 509
Date: 16.09.2013
Waypoint: GC492MZ
Title: Planetenrunde-JUPITER
Tag: D15 T15 Small Tradi
----
ID: 510
Date: 17.09.2013
Waypoint: GC3YA55
Title: Königreich Ückesdorf 4
Tag: D1 T2 Micro Tradi
----
ID: 511
Date: 17.09.2013
Waypoint: GC1N76E
Title: Gotteshäuser: St. Hubertus (Ückesdorf)
Tag: D1 T1 Micro Tradi
----
ID: 512
Date: 18.09.2013
Waypoint: GC43K9N
Title: Geo-Matt in Niederbachem
Tag: D2 T15 Small Mystery recommended
----
ID: 513
Date: 19.09.2013
Waypoint: GC4305G
Title: Möge die Straße ...
Tag: D1 T1 Micro Tradi
----
ID: 514
Date: 20.09.2013
Waypoint: GC173FT
Title: Zechers Zuflucht
Tag: D1 T25 Micro Tradi
----
ID: 515
Date: 20.09.2013
Waypoint: GC34CJ9
Title: Rhöndorf grüsst seine Gäste
Tag: D1 T1 Small Tradi
----
ID: 516
Date: 21.09.2013
Waypoint: GC33VKZ
Title: Die Schlaufe
Tag: D1 T1 Micro Tradi
----
ID: 517
Date: 21.09.2013
Waypoint: GC2E4D1
Title: Kreuz an der Mühle
Tag: D2 T15 Small Tradi
----
ID: 518
Date: 22.09.2013
Waypoint: GC3429W
Title: Wachtberger Kreuze # 14
Tag: D1 T2 Micro Tradi
----
ID: 519
Date: 22.09.2013
Waypoint: GC37RYR
Title: Rettungswache Wachtberg
Tag: D2 T1 Micro Tradi recommended
----
ID: 520
Date: 26.09.2013
Waypoint: GC4918H
Title: Schwarzrheindorf
Tag: D1 T1 Micro Tradi
----
ID: 521
Date: 26.09.2013
Waypoint: GC45KPR
Title: Osterkirmes Beuel
Tag: D15 T15 Small Tradi
----
ID: 522
Date: 27.09.2013
Waypoint: GCVZR8
Title: Gotteshäuser Helenenkapelle
Tag: D15 T1 Micro Tradi recommended
----
ID: 523
Date: 28.09.2013
Waypoint: GC2VMD0
Title: Annaberger Bach - Mündung in den Rhein
Tag: D25 T2 Nano Tradi
----
ID: 524
Date: 29.09.2013
Waypoint: GC2E8E4
Title: Bonner Retter - Löscheinheit 43 -&gt; Lessenich
Tag: D15 T15 Micro Tradi
----
ID: 525
Date: 30.09.2013
Waypoint: GC40FG0
Title: Zauberhafter Adventsbazar
Tag: D15 T15 Small Tradi
----
ID: 526
Date: 30.09.2013
Waypoint: GC4J6H4
Title: Bandorfer Runde
Tag: D25 T25 Large Multi
----
ID: 527
Date: 01.10.2013
Waypoint: GC1ZG6N
Title: Keep Toming Back
Tag: D15 T2 Small Tradi
----
ID: 528
Date: 02.10.2013
Waypoint: GC337X6
Title: Alfterer Kreuze 22
Tag: D15 T1 Micro Tradi
----
ID: 529
Date: 02.10.2013
Waypoint: GC2R93G
Title: &#34;Beim Swisttaler GC Stammtisch&#34; - Beifangtradi!
Tag: D15 T15 Micro Tradi
----
ID: 530
Date: 02.10.2013
Waypoint: GC446DR
Title: &#34;O'zapft is&#34;- Tannen&#34;zapfen&#34;edition!
Tag: D15 T15 Micro Tradi
----
ID: 531
Date: 02.10.2013
Waypoint: GC2XHZ0
Title: Chicken Run 4 (Hochwasser)
Tag: D15 T15 Micro Tradi
----
ID: 532
Date: 02.10.2013
Waypoint: GC37W1T
Title: Ollis Monatsdose
Tag: D15 T15 Micro Tradi
----
ID: 533
Date: 02.10.2013
Waypoint: GC41MZK
Title: Der Goldene Saft
Tag: D1 T1 Nano Tradi
----
ID: 534
Date: 02.10.2013
Waypoint: GC315PP
Title: Schäfchenwiese
Tag: D15 T2 Micro Tradi
----
ID: 535
Date: 03.10.2013
Waypoint: GC4HMK8
Title: The Mountain of the Imperium
Tag: D25 T2 Micro Tradi
----
ID: 536
Date: 03.10.2013
Waypoint: GC4HHQH
Title: The Sideview of the Imperium
Tag: D15 T15 Micro Tradi
----
ID: 537
Date: 03.10.2013
Waypoint: GC4H2J0
Title: Der Weg zum Imperium
Tag: D15 T15 Micro Tradi
----
ID: 538
Date: 03.10.2013
Waypoint: GC4MHQ2
Title: Die Bahnstrecke zum Imperium
Tag: D15 T15 Nano Tradi
----
ID: 539
Date: 03.10.2013
Waypoint: GC4H026
Title: Das Imperium wächst...
Tag: D15 T15 Micro Tradi
----
ID: 540
Date: 03.10.2013
Waypoint: GC4H2AA
Title: The Imperium's Background
Tag: D15 T15 Nano Tradi
----
ID: 541
Date: 08.10.2013
Waypoint: GC4H327
Title: TB Hotel Fuderbach 1
Tag: D2 T3 Small Tradi
----
ID: 542
Date: 08.10.2013
Waypoint: GCZQQC
Title: Didn't find it - der Cache - Vol. 2 - Heiderhof
Tag: D1 T15 Regular Tradi
----
ID: 543
Date: 09.10.2013
Waypoint: GC2GFB7
Title: Häuser der Helfer: Rettungswache Rheinbach
Tag: D15 T15 Micro Multi
----
ID: 544
Date: 09.10.2013
Waypoint: GC2EXA1
Title: Rheinbach Nord 2
Tag: D15 T15 Regular Tradi
----
ID: 545
Date: 09.10.2013
Waypoint: GC4G7VH
Title: Der kleine See
Tag: D2 T2 Micro Tradi recommended
----
ID: 546
Date: 11.10.2013
Waypoint: GC4KEME
Title: If you go to San Francisco... - Meet &amp; Greet
Tag: D1 T1 Event
nTF: 1
----
ID: 547
Date: 12.10.2013
Waypoint: GC494W0
Title: Die älteste in der Stadt
Tag: D2 T2 Micro Mystery
----
ID: 548
Date: 13.10.2013
Waypoint: GC22ZCX
Title: The Deep Blue
Tag: D15 T3 Earth
----
ID: 549
Date: 13.10.2013
Waypoint: GC1B6J2
Title: P&amp;G #4
Tag: D15 T1 Micro Tradi
----
ID: 550
Date: 13.10.2013
Waypoint: GC2N98P
Title: Hennef: 100 Dörfer #69 Büllesfeld
Tag: D25 T25 Small Tradi
----
ID: 551
Date: 13.10.2013
Waypoint: GC2G85T
Title: Rote Tuer
Tag: D1 T15 Small Tradi
----
ID: 552
Date: 16.10.2013
Waypoint: GC38KAF
Title: Verstecketopf Beschusstest
Tag: D2 T2 Nano Tradi
----
ID: 553
Date: 16.10.2013
Waypoint: GC4F1R3
Title: Verstecketopf Aktennotiz
Tag: D25 T2 Micro Mystery
----
ID: 554
Date: 16.10.2013
Waypoint: GC425DB
Title: &#34;PECH&#34; gehabt
Tag: D15 T35 Micro Mystery
----
ID: 555
Date: 17.10.2013
Waypoint: GC4PH1Z
Title: Bonn - Rathaus
Tag: D15 T15 Micro Tradi
----
ID: 556
Date: 18.10.2013
Waypoint: GC4HHWM
Title: The recovery form the Imperium
Tag: D25 T2 Micro Tradi
----
ID: 557
Date: 19.10.2013
Waypoint: GC4ACQF
Title: Kunst am Wegesrand # 2
Tag: D25 T25 Micro Mystery
----
ID: 558
Date: 20.10.2013
Waypoint: GC4KFQC
Title: Von_Ost_nach_West
Tag: D2 T15 Small Tradi
----
ID: 559
Date: 21.10.2013
Waypoint: GC347VN
Title: Was wird denn hier gebaut?
Tag: D15 T15 Micro Tradi
----
ID: 560
Date: 22.10.2013
Waypoint: GC2XX9W
Title: Schools Out, Parken Verboten
Tag: D2 T1 Micro Tradi
----
ID: 561
Date: 24.10.2013
Waypoint: GC2ZTMX
Title: Alfterer Kreuze 04
Tag: D2 T15 Micro Tradi
----
ID: 562
Date: 25.10.2013
Waypoint: GC4NR65
Title: BDD - Bereitschaftsdienstdose
Tag: D15 T15 Micro Tradi
----
ID: 563
Date: 27.10.2013
Waypoint: GDBW-JUGA
Title: Dashpoint 50°N 7°E, Game 148 (Oktober 2013), AW-Weidenbach
nTF: 1
----
ID: 564
Date: 27.10.2013
Waypoint: GC3E7Q4
Title: Gotteshäuser Marien-Walfahrtskapelle Pützfeld
Tag: D15 T15 Micro Tradi recommended
----
ID: 565
Date: 27.10.2013
Waypoint: GC4PJHJ
Title: Ende der Eiszeit ⅯⅯⅩⅢ ☹
Tag: D1 T1 Event
nTF: 0
----
ID: 566
Date: 30.10.2013
Waypoint: GC4KK0H
Title: Faultier Heinz
Tag: D2 T2 Micro Mystery
----
ID: 567
Date: 31.10.2013
Waypoint: GC4FQYA
Title: TUS Germania Hersel - Erwartungen
Tag: D1 T15 Micro Tradi
----
ID: 568
Date: 01.11.2013
Waypoint: GDBX-JOYQ
Title: Dashpoint 50°N 6°E, Game 149 (November 2013), SU-Sechtem
nTF: 1
----
ID: 569
Date: 01.11.2013
Waypoint: GC3X4V9
Title: Machmaleibeidiemäh Sechtem 1
Tag: D1 T2 Micro Tradi
----
ID: 570
Date: 02.11.2013
Waypoint: GC4PGAT
Title: BASEBALL TP – No.4 – Erdkunde
Tag: D3 T1 Micro Tradi
----
ID: 571
Date: 03.11.2013
Waypoint: GC4R97Y
Title: Mitten in Bandorf
Tag: D1 T15 Micro Tradi
----
ID: 572
Date: 04.11.2013
Waypoint: GC1Y016
Title: Badminton in Bonn
Tag: D3 T1 Micro Mystery
----
ID: 573
Date: 05.11.2013
Waypoint: GC26VT0
Title: Grete's Memoiren
Tag: D1 T2 Micro Tradi
----
ID: 574
Date: 08.11.2013
Waypoint: GC2QR58
Title: Häuser der Helfer - Freiwillige Feuerwehr Siegburg
Tag: D15 T15 Micro Tradi
----
ID: 575
Date: 09.11.2013
Waypoint: GCP1YA
Title: Oberhausen HBF
Tag: D25 T1 Micro Tradi
----
ID: 576
Date: 10.11.2013
Waypoint: GC4164D
Title: 2. Oberhausener Praxiscache
Tag: D15 T15 Micro Tradi
----
ID: 577
Date: 11.11.2013
Waypoint: GC34FXA
Title: Gotteshäuschen Oberscheid
Tag: D2 T1 Micro Tradi
----
# ^K/ mksh -c '. ../mk/common; xhtml_escape'
# ^K/ datum=dd.mm.yyyy mksh WP2dat
