.Dd May 30, 2012
.Dt UPDATE\-CA\-CERTIFICATES 8
.Os Debian
.Sh NAME
.Nm update\-ca\-certificates
.Nd compatibility no-op script
.Sh SYNOPSIS
.Nm
.Op Fl fhv
.Op Fl \-fresh
.Op Fl \-help
.Op Fl \-verbose
.Sh DESCRIPTION
This script exists only for compatibility to the Debian
.Dq ca\-certificates
package and does nothing.
.Sh AUTHORS
The Debian WTF
.Dq ca\-bundle
package was authored using CA Certificates provided by The MirOS Project by
.An mirabilos Aq m@mirbsd.org .
