# $MirOS$
# $OpenBSD: Makefile.inc,v 1.10 2007/12/25 19:47:35 ajacoutot Exp $

MASTER_SITE_GCC+= ftp://gcc.gnu.org/pub/gcc/
MASTER_SITE_GCC+= ftp://ftp.uvsq.fr/pub/gcc/
MASTER_SITE_GCC+= ftp://gd.tuwien.ac.at/gnu/gcc/
MASTER_SITE_GCC+= ftp://gd.tuwien.ac.at/gnu/gcc/
MASTER_SITE_GCC+= ftp://ftp.fu-berlin.de/unix/languages/gcc/
MASTER_SITE_GCC+= ftp://ftp.gwdg.de/pub/linux/gcc/
MASTER_SITE_GCC+= ftp://ftp.mpi-sb.mpg.de/pub/gnu/mirror/gcc.gnu.org/pub/gcc/
MASTER_SITE_GCC+= ftp://ftp.sunet.se/pub/gnu/gcc/
MASTER_SITE_GCC+= ftp://ftp.ntua.gr/pub/gnu/gcc/
MASTER_SITE_GCC+= ftp://ftp.nluug.nl/pub/languages/gcc/
MASTER_SITE_GCC+= ftp://ftp.dti.ad.jp/pub/lang/gcc/
MASTER_SITE_GCC+= ftp://sunsite.icm.edu.pl/pub/programming/egcs/
