# $MirOS: ports/devel/p5-IPC-Run/Makefile,v 1.4 2007/04/29 23:38:38 tg Exp $
# $NetBSD: Makefile,v 1.6 2004/12/20 11:31:01 grant Exp $

# don't delete, cvsweb depends on it

DISTNAME=		IPC-Run-0.74
PKGNAME=		p5-${DISTNAME}-${DASH_VER}
CATEGORIES=		devel perl5
#MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=IPC/}
COMMENT=		Perl module for interacting with child processes

PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

CONFIGURE_STYLE=	perl

.include <bsd.port.mk>
