# $MirOS$
# $OpenBSD: Makefile,v 1.6 2004/05/27 18:36:34 sturm Exp $

COMMENT=		sql parsing and processing

DISTNAME=		SQL-Statement-1.15
PKGNAME=		p5-${DISTNAME}-${DASH_VER}
CATEGORIES=		databases perl5 
MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=SQL/}

# same as perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

CONFIGURE_STYLE=perl

PKG_ARCH=	*

.include <bsd.port.mk>
