#!/bin/sh
# $MirOS$
#-
# Copyright (c) 2003
#	Thorsten Glaser <x86@ePost.de>, for the MirOS Project
#
# Subject to these terms, everybody who obtained a copy of this work
# is hereby permitted to deal in the work without restriction inclu-
# ding without limitation the rights to use, distribute, sell, modi-
# fy, publically perform, give away, merge or sublicense it provided
# this notice is kept and the authors and contributors are given due
# credit in derivates or accompanying documents.
#
# This work is provided "as is" with no explicit or implicit warran-
# ties whatsoever to the maximum extend permitted by applicable law;
# in no event may an author or contributor be held liable for damage
# that is, directly or indirectly, caused by the work, even if advi-
# sed of the possibility of such damage.
#-
# FreenetProject run script

exec 2>&1
cd node
exec nice sudo -u _freenet envdir ../env \
    ../j -classic -cp freenet.jar:freenet-ext.jar \
    freenet.node.Main $(cat ../args 2>/dev/null)
