# $MirOS: ports/lang/python/2.3/Makefile,v 1.2 2005/07/07 21:22:32 bsiegert Exp $
# $OpenBSD: Makefile,v 1.18 2005/08/27 15:57:31 naddy Exp $

VERSION=		2.3
PATCHLEVEL=		.4

COMMENT-bsddb=		"Berkeley db module for Python"
FULLPKGNAME-bsddb=	python-bsddb-${VERSION}${PATCHLEVEL}-0

# needed for www/zope
THREAD_STACK_SIZE=	0x100000

.include <bsd.port.mk>
