# $MirOS: ports/lang/python/2.3/Makefile,v 1.3 2005/11/04 14:02:45 tg Exp $
# $OpenBSD: Makefile,v 1.18 2005/08/27 15:57:31 naddy Exp $

VERSION=		2.3
PATCHLEVEL=		.5
PKG_PATCHLEVEL=		0

# needed for www/zope
THREAD_STACK_SIZE=	0x100000

.include <bsd.port.mk>
