# $MirOS: ports/graphics/jpeg/files/Makefile.wrjpgcom,v 1.1.7.1 2005/03/18 15:46:58 tg Exp $

SRCDIR=		${.CURDIR}/..

PROG=		wrjpgcom
SRCS=		wrjpgcom.c
LDADD+=		-L${SRCDIR}/lib -ljpeg

.PATH:		${SRCDIR}

.include <bsd.prog.mk>
