# $MirOS: ports/graphics/jpeg/files/Makefile.jpegtran,v 1.1.7.1 2005/03/18 15:46:58 tg Exp $

SRCDIR=		${.CURDIR}/..

PROG=		jpegtran
SRCS=		jpegtran.c rdswitch.c cdjpeg.c transupp.c
LDADD+=		-L${SRCDIR}/lib -ljpeg

.PATH:		${SRCDIR}

.include <bsd.prog.mk>
