.\" $MirOS: src/lib/libc/locale/iswoctet.3,v 1.1 2008/11/22 09:02:33 tg Exp $
.\"-
.\" Copyright (c) 2008, 2009
.\"	Thorsten Glaser <tg@mirbsd.org>
.\"
.\" Provided that these terms and disclaimer and all copyright notices
.\" are retained or reproduced in an accompanying document, permission
.\" is granted to deal in this work without restriction, including un-
.\" limited rights to use, publicly perform, distribute, sell, modify,
.\" merge, give away, or sublicence.
.\"
.\" This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
.\" the utmost extent permitted by applicable law, neither express nor
.\" implied; without malicious intent or gross negligence. In no event
.\" may a licensor, author or contributor be held liable for indirect,
.\" direct, other damage, loss, or other issues arising in any way out
.\" of dealing in the work, even if advised of the possibility of such
.\" damage or existence of a defect, except proven that it results out
.\" of said person's immediate fault when using the work as intended.
.\"-
.Dd $Mdocdate: November 22 2008 $
.Dt ISWOCTET 3
.Os MirBSD
.Sh NAME
.Nm iswoctet
.Nd OPTU-16 Raw Octet identification macro
.Sh SYNOPSIS
.Fd #define _ALL_SOURCE
.In wchar.h
.Ft bool
.Fn iswoctet "wchar_t wc"
.Sh DESCRIPTION
The
.Nm
macro is a character classification utility function,
for use with wide characters
.Po
.Fa wchar_t
or
.Fa wint_t
.Pc .
Note that there is no companion function with external linkage available.
.Sh RETURN VALUES
The macro evaluates to true if the wide character is in the MirOS OPTU\-16
raw octet range (U+EF80 .. U+EFFF), false otherwise.
.Sh SEE ALSO
.Xr optu16to8 3 ,
.Xr optu8to16 3
.Sh HISTORY
The
.Nm
macro first appeared in
.Mx 11 .
.Sh AUTHORS
.An Thorsten Glaser Aq tg@mirbsd.org
wrote the entire internationalisation implementation in
.Mx .
He is also the steward for the OPTU encoding.
.Sh CAVEATS
The current macro expansion assumes a 16-bit
.Vt wchar_t .
