RCSID: $MirOS: www/users/tg/wlog-10-tg.inc,v 1.6 2014/05/13 16:26:11 tg Exp $
Date: 14.04.2014 19:22
Author: tg@
Title: Enough of IT…
Tag: geocache rant

<p>I’ve been only sleeping, cooking and geocaching this weekend.
 Rather productive. Better than being angry at idiots, slowpokes
 (StartCom and Mozilla in particular), etc.</p>
<p><a href="@@RELPATH@@wptg.htm#banners" style="border:0;"><img
 style="border:0;" alt="mirabilos’ Waypoints"
 src="@@RELPATH@@WPtg.png" /></a></p>
<p>Food was rather tasty, although I held back and put only ten
 pieces of garlic into it; gecko2 added some Pul Biber to his…</p>
----
Date: 04.05.2014 00:36
Author: tg@
Title: Maibaum für Ada
Tag: debian fun twitxr

<p>While taking the tram to our favourite Croatian restaurant,
 I spotted something dedicated to Ada. We’ll never know which
 one… the language, the famous programmer, or someone else. <a
 href="https://de.wikipedia.org/wiki/Maibrauchtum_(Rheinland)#Maibaum">A
 “Maibaum”</a> (may pole, one of its many meanings). Click on
 the picture to get a slightly different one which has the text
 better legible.</p>
<p><a href="@@RELPATH@@pics/wlog/Ada-Maibaum.jpg"><img
 alt="Ada-Maibaum" src="@@RELPATH@@pics/wlog/Ada_Maibaum.jpg" /></a></p>
----
Date: 13.05.2014 16:25
Author: tg@
Title: Lügen haben lange Leitern
Tag: debian fun politics rant twitxr

<p><a href="@@RELPATH@@pics/wlog/anti-nrw.jpg"><img
 style="float:right; margin-left:1em; margin-bottom:3px;"
 alt="Photo von Laternenmast mit Wahlplakaten, oben Pro NRW, unten…"
 src="@@RELPATH@@pics/wlog/anti_nrw.jpg" /></a></p>
<p>Endlich tut mal jemand was gegen <a
 href="https://de.wikipedia.org/wiki/B%C3%BCrgerbewegung_pro_NRW">die
 rechte Hetzpartei</a>! – Ein Arbeitskollege fragt, ob man die nicht
 einfach mit einem langen Heckenschneider abmachen kann… aber sie so
 lächerlich zu machen hat auch was ☺</p>
<p>Finally, someone is doing something against <a
 href="https://en.wikipedia.org/wiki/Pro_NRW">this Nazi party</a>!
 A coworker wondered whether it’s legal to cut them off with a long
 tool, but making them ridiculous like this is also funny ☻</p>
<p>(Explanation: the “Pro NRW” people put their campaign thingies
 (sorry, I don’t speak English well) up on lamp posts very high,
 because they are taken down by other citizens immediately otherwise,
 so there’s now people making fun of them for using long ladders (to
 put them up there, so the offended citizens need equally long ladders
 or tools with long arms) in leaning on the saying that lies have long
 legs ⇒ here: ladders.)</p>
<div style="clear:right; height:1px;"> </div>
----
