RCSID: $MirOS: www/users/tg/WPtg.inc,v 1.127 2014/11/27 21:22:08 tg Exp $
# ^K/ mksh -c '. ../../mk/common; xhtml_escape'
ID: 1
Date: 09.07.2006
Waypoint: GCN89C OC01A9
Title: Endenich-City-Cache
Tag: recommended
----
ID: 2
Date: 29.10.2006
Waypoint: GCQD10 OC03E3
Title: Bonner Aussicht
----
ID: 3
Date: 05.08.2007
Waypoint: GCPJDM OC08CA
Title: Knochenarbeit
Tag: recommended
----
ID: 4
Date: 11.08.2007
Waypoint: GC11B5G OC3073
Title: Sisutl - die doppelköpfige Schlange
Tag: recommended
----
ID: 5
Date: 12.08.2007
Waypoint: GCTH34 OC181A
Title: Mineralbrunnen Bad Godesberg
Tag: recommended
----
ID: 6
Date: 12.08.2007
Waypoint: GC13FTW OC38D1
Title: Kleines Theater Bad Godesberg
----
ID: 7
Date: 12.08.2007
Waypoint: GC13D5T OC3CDA
Title: Jotts Bonncaches - Stadthaus
----
ID: 8
Date: 19.08.2007
Waypoint: GCRFW6 OC0FA4 N01D62
Title: Urzeit im Bergischen - 2 : Dolomitkorallen
----
ID: 9
Date: 20.08.2007
Waypoint: GC12XJK OC368A
Title: Bonner Aussicht (reloaded)
Tag: recommended
----
ID: 10
Date: 12.09.2007
Waypoint: OC0B53
Title: chameleon at night
----
ID: 11
Date: 19.09.2007
Waypoint: GCTEYQ OC18F8
Title: Geocoin Micro #4
----
ID: 12
Date: 19.09.2007
Waypoint: GCYZR8 N0230A OC2777 WM5CZY
Title: Heute schon gelesen? [de/en/fr]
Tag: recommended
----
ID: 13
Date: 23.09.2007
Waypoint: GC14VCA OC3D6C
Title: Park Friesdorf
----
ID: 14
Date: 23.09.2007
Waypoint: GCTEYN OC18F6
Title: Geocoin Micro #2
----
ID: 15
Date: 23.09.2007
Waypoint: GCTPRE OC18D5
Title: Bismarckturm Godesberg
----
ID: 16
Date: 23.09.2007
Waypoint: GCTEYP OC18F7
Title: Geocoin Micro #3
----
ID: 17
Date: 23.09.2007
Waypoint: GCTY5D OC1960
Title: Bismarckturm Gronau
----
ID: 18
Date: 24.09.2007
Waypoint: GCW7QP OC1D38
Title: Gotteshäuser : Stimson Memorial Chapel
----
ID: 19
Date: 05.10.2007
Waypoint: GCTH09 OC1810
Title: Kirchen &amp; Kapellen #1 - Kapelle St. Michael
----
ID: 20
Date: 05.10.2007
Waypoint: GCZ3DE OC3466
Title: MPI: Radi
----
ID: 21
Date: 07.10.2007
Waypoint: GCQT3Z OC06E0
Title: Burgen &amp; Schlösser #2 - La Redoute
----
ID: 22
Date: 07.10.2007
Waypoint: GCME6W OC17DC
Title: Oberkasseler Seen
Tag: recommended
----
ID: 23
Date: 14.10.2007
Waypoint: GCQGJB OC06D3
Title: Burgen &amp; Schlösser #1 - Godesburg
----
ID: 24
Date: 14.10.2007
Waypoint: GCV49V OC1D3B
Title: Gotteshäuser: Alter Kirchturm
----
ID: 25
Date: 23.10.2007
Waypoint: GCZTF4
Title: EMA Haus
----
ID: 26
Date: 23.10.2007
Waypoint: GCPC7P
Title: Gotteshäuser: Bonner Münster
----
ID: 27
Date: 28.10.2007
Waypoint: GCPV0W
Title: Der Heilige Gral
----
ID: 28
Date: 28.10.2007
Waypoint: GCR2QX OC06E2
Title: Burgen &amp; Schlösser #5 - Hexenturm
----
ID: 29
Date: 28.10.2007
Waypoint: GC171HX OC280D
Title: Beuelskopf
Tag: recommended
----
ID: 30
Date: 28.02.2008
Waypoint: GCY1ZJ OC243A
Title: Gotteshäuser: Waldkapelle Rheinbach
Tag: recommended
----
ID: 31
Date: 08.03.2008
Waypoint: GC13DV2 OC45C0
Title: Jotts Bonncaches - RLK
----
ID: 32
Date: 13.03.2008
Waypoint: GC16DTB OC45BD
Title: Jotts Bonncaches - Sportpark Nord
----
ID: 33
Date: 29.03.2008
Waypoint: GC14KN7
Title: Ein Stern, der Deinen Namen trägt
----
ID: 34
Date: 06.04.2008
Waypoint: OC4FCA
Title: Park and Ride Bad Godesberg
----
ID: 35
Date: 06.04.2008
Waypoint: GCQJ9P OC0159
Title: Bonner Sudoku #1
----
ID: 36
Date: 06.04.2008
Waypoint: GC17VKW OC4AEB
Title: Kirchen &amp; Kapellen #7 - Sebastianus Kapelle
----
ID: 37
Date: 12.04.2008
Waypoint: GCTEZ0 OC18FC
Title: Geocoin Micro #8
----
ID: 38
Date: 12.04.2008
Waypoint: GC14BJ2 OC3C69
Title: Tauschstübchen - Vinyl
----
ID: 39
Date: 14.04.2008
Waypoint: TC9AV
Title: Deutscher Terracachingpreis 2008
Tag: Locationless Challenge
----
ID: 40
Date: 14.04.2008
Waypoint: CCHU
Title: WCG (aka How to Fold a Protein)
Tag: MC1 Locationless Challenge
----
ID: 41
Date: 17.04.2008
Waypoint: GC10BF9
Banner: jpg
Title: Erdbeergraben
----
ID: 42
Date: 20.04.2008
Waypoint: GCQT4B OC06E1
Title: Burgen &amp; Schlösser #3 - Kommende Muffendorf
----
ID: 43
Date: 21.04.2008
Waypoint: GC17VKD OC4AEA
Title: Kirchen &amp; Kapellen #6 - Rigalsche Kapelle
----
ID: 44
Date: 24.04.2008
Waypoint: GCT7PV N01ECF OC1698
Title: Durch den Langeberg - Canyon
Tag: recommended exceptional
----
ID: 45
Date: 25.04.2008
Waypoint: OC58A8 N0294A GC171JK
Title: Gotteshäuser: Rüngsdorf Marienkapelle
nTF: 0
----
ID: 46
Date: 25.04.2008
Waypoint: OC58A9
Title: Gotteshäuser: Mehlem Kirche St. Severin
nTF: 0
----
ID: 47
Date: 25.04.2008
Waypoint: GC18N2M OC6641
Title: Gotteshäuser: Erlöserkirche Bad Godesberg
----
ID: 48
Date: 12.05.2008
Waypoint: GC1AB2F OC59B8
Banner: jpg
Title: Underground Embassy
Tag: recommended exceptional
----
ID: 49
Date: 20.06.2008
Waypoint: GC1DC3T OC5E73
Title: IPTC BN
Tag: recommended
----
ID: 50
Date: 11.07.2008
Waypoint: GC17828 OC47C0
Title: Der Riese am Strom
----
ID: 51
Date: 11.07.2008
Waypoint: GCXHKQ OC22C7
Title: Kirchen &amp; Kapellen #4 - Kirche Oberdollendorf
----
ID: 52
Date: 13.07.2008
Waypoint: GCQGKG OC06D6
Title: Den Wald vor lauter Bäumen ...
----
ID: 53
Date: 14.07.2008
Waypoint: GCW1C0 OC272D
Title: Das Baumschulwäldchen
----
ID: 54
Date: 15.07.2008
Waypoint: OC58AE
Title: Bonner Stolpersteine
----
ID: 55
Date: 19.07.2008
Waypoint: GC13MZN OC399D WM9EBD
Title: Unter Dampf No. #4 - Drachenfelsbahn
----
ID: 56
Date: 19.07.2008
Waypoint: GCTEZ1 OC18FD
Title: Geocoin Micro #9
----
ID: 57
Date: 19.07.2008
Waypoint: GCTEYY OC18FB
Title: Geocoin Micro #7
----
ID: 58
Date: 26.07.2008
Waypoint: GCHDCV N00D17 OC0154
Title: Kreuzberg (Patch)
----
ID: 59
Date: 09.08.2008
Waypoint: GC1AQE9
Title: Gundeldinger Feld
----
ID: 60
Date: 10.08.2008
Waypoint: CCHX
Title: Google Up A Locationless!
Tag: MC5 Locationless
----
ID: 61
Date: 10.08.2008
Waypoint: GC15QBA
Title: La Fonderie
----
ID: 62
Date: 10.08.2008
Waypoint: GC17K93
Title: Le &#34;Schweissdissi&#34;
----
ID: 63
Date: 10.08.2008
Waypoint: GC1BF7A
Title: CIT'in #01
----
ID: 64
Date: 13.08.2008
Waypoint: GCXYKM
Title: Alte Eiche
----
ID: 65
Date: 14.08.2008
Waypoint: GC1CYW0
Title: Thurbo Altstätten
----
ID: 66
Date: 14.08.2008
Waypoint: GC14367
Title: Nervensäge  #4 - Rheintal
----
ID: 67
Date: 24.08.2008
Waypoint: GC16AT3 OC438C
Title: Jens ärgere dich nicht!
----
ID: 68
Date: 01.09.2008
Waypoint: GC1BBVN
Title: Basel Big City II.
----
ID: 69
Date: 07.09.2008
Waypoint: GC17550
Title: Parc de la Bourse  ( SIM )
----
ID: 70
Date: 07.09.2008
Waypoint: GC1E8CZ
Title: La Loco
----
ID: 71
Date: 07.09.2008
Waypoint: GC1EQ5G
Title: Le passage
Tag: recommended exceptional
----
ID: 72
Date: 09.09.2008
Waypoint: GC1E752
Title: IWB Cache
----
ID: 73
Date: 11.09.2008
Waypoint: GC13ET7
Title: Basel SBB B-Seite (Bahnhof-Micro-Cache)
----
ID: 74
Date: 06.10.2008
Waypoint: GC1FMN4
Title: XVII. Geocacher Stammtisch Bonn
----
ID: 75
Date: 15.10.2008
Waypoint: GC1D4PK OC5DF1
Title: Römerbad
----
ID: 76
Date: 18.10.2008
Waypoint: GC1GZJW OC6A88
Title: AWK-Nachleese
----
ID: 77
Date: 21.01.2009
Waypoint: GC14Y1G OC3DD1
Title: K.Ö.B. ein Micro
----
ID: 78
Date: 25.01.2009
Waypoint: GC1J35E OC7153
Title: Candy
----
ID: 79
Date: 07.03.2009
Waypoint: GC1JQ65
Title: Haus Carstanjen
----
ID: 80
Date: 07.03.2009
Waypoint: GC1J188
Title: Japanischer Garten
----
ID: 81
Date: 07.03.2009
Waypoint: GCW9DC
Title: Stunde Null
----
ID: 82
Date: 11.03.2009
Waypoint: GC144QN
Title: Gotteshäuser in Karlsruhe: St. Stephan
----
ID: 83
Date: 11.03.2009
Waypoint: GC12ZKB
Title: Die G-Serie: &#34;Nullrunde&#34;
----
ID: 84
Date: 13.03.2009
Waypoint: GCZRJF
Title: Karlsruher Hauptbahnhof (Gleis 9 ¾)
----
ID: 85
Date: 28.03.2009
Waypoint: GC1N4D7
Title: Wir lieben Schach
----
ID: 86
Date: 29.03.2009
Waypoint: OC7CEB
Title: Friesdorfer Schrebergärten
nTF: 1
----
ID: 87
Date: 31.03.2009
Waypoint: GC1P8CB OC7CD7
Title: Bonn Hbf reloaded
----
ID: 88
Date: 12.04.2009
Waypoint: GC1NN6F
Title: Häuser der Helfer - DRK Kreisverband Bonn
----
ID: 89
Date: 15.04.2009
Waypoint: OC6961
Title: Töffi´s freie Hotspots
----
ID: 90
Date: 25.06.2009
Waypoint: GC14AXW
Title: Amtsgericht
----
ID: 91
Date: 26.06.2009
Waypoint: GC1CNRA
Title: Deutschlandhalle - das Ende naht
----
ID: 92
Date: 26.06.2009
Waypoint: GC1GD07
Title: Messewelten
----
ID: 93
Date: 26.06.2009
Waypoint: GC1JGX1
Title: Sender Witzleben
----
ID: 94
Date: 29.06.2009
Waypoint: GC1R4BE OC8A78
Title: Gotteshäuser: St. Quirinus (Dottendorf)
----
ID: 95
Date: 14.07.2009
Waypoint: GC16H3M
Title: Kliever Rakete
----
ID: 96
Date: 14.07.2009
Waypoint: GC18WZY
Title: Zum Piepen
Tag: recommended
----
ID: 97
Date: 14.07.2009
Waypoint: GC172DA
Title: Am Wegesrand #1
----
ID: 98
Date: 19.07.2009
Waypoint: GC1FPE4
Title: Kriegerdenkmal
----
ID: 99
Date: 20.07.2009
Waypoint: GCTYFY
Title: H2O
----
ID: 100
Date: 20.07.2009
Waypoint: GC1PQR1
Title: GC an der CG
----
ID: 101
Date: 21.07.2009
Waypoint: GC1PPQ3
Title: Benni's Bahnhof (Dortmund Hbf)
----
ID: 102
Date: 25.07.2009
Waypoint: GC1R8CB
Title: Posttower
----
ID: 103
Date: 04.08.2009
Waypoint: GC1V4T4
Title: St. Hildegard
----
ID: 104
Date: 16.08.2009
Waypoint: GC1X13J
Title: LPG
----
ID: 105
Date: 17.08.2009
Waypoint: GC182W4 OC87EA
Title: Gotteshäuser: St. Peter (Lengsdorf - Tradi)
----
ID: 106
Date: 22.08.2009
Waypoint: GC1AAY8 OC5463
Title: Pleiser Park
----
ID: 107
Date: 22.08.2009
Waypoint: GC1PKT5
Title: The Rock
----
ID: 108
Date: 31.08.2009
Waypoint: GC1QTP9
Title: Knackes Park (D1,5/T1;micro)
----
ID: 109
Date: 31.08.2009
Waypoint: GC1P0G3 OCB3FA
Title: Bonner Kunstwerke: Vorgang - Zustand
----
ID: 110
Date: 27.09.2009
Waypoint: GC1XCN9
Title: Gotteshäuser: Friedenskirche Bonn
----
ID: 111
Date: 06.10.2009
Waypoint: GC1X8D6
Title: Cachicamo2
----
ID: 112
Date: 13.03.2010
Waypoint: GC1BJYC
Title: UPN (RPN)
Tag: recommended tech
----
ID: 113
Date: 13.03.2010
Waypoint: GC1ENRB
Title: Wasserfall in Chemnitz
----
ID: 114
Date: 06.04.2010
Waypoint: GC1Z2TP
Title: Dancefloor
----
ID: 115
Date: 18.04.2010
Waypoint: GC1HW1B OC6D5F
Title: Schlauchomat am 50. Breitengrad
----
ID: 116
Date: 24.04.2010
Waypoint: GC2785K
Title: Friesdorfer Schleichwege 2
----
ID: 117
Date: 24.04.2010
Waypoint: GC267YH
Title: Friesdorfer Schleichwege 1
----
ID: 118
Date: 25.04.2010
Waypoint: GC26Z0F
Title: Der Schatz am Steinspielplatz (Stone Playground)
----
ID: 119
Date: 25.04.2010
Waypoint: GC25DAR
Title: Japanischer Garten
----
ID: 120
Date: 26.04.2010
Waypoint: GC1ZDQ4
Title: Gotteshäuser &#34; St.Matthias &#34;
----
ID: 121
Date: 03.05.2010
Waypoint: GC20C97 OC661E
Title: Technik trifft Ästhetik
----
ID: 122
Date: 03.05.2010
Waypoint: GC1X2NM
Title: Hochwasserpumpwerk

Duplikat von OC661E (welches bereits als GC20C97 gelistet ist)
----
ID: 123
Date: 08.05.2010
Waypoint: GC27JED OCA47D
Title: New BriTge
----
ID: 124
Date: 10.05.2010
Waypoint: GC18BFD
Title: Gotteshäuser: Benediktinerinnenkloster
----
ID: 125
Date: 18.05.2010
Waypoint: GC28KGC OCA569
Title: Gotteshäuser: Erlöserkirche Bad Godesberg II
----
ID: 126
Date: 28.05.2010
Waypoint: GC27W5J OC2E5B
Title: Uni-Werkstätten
----
ID: 127
Date: 11.06.2010
Waypoint: GC1TXZE
Title: Willkommen in...NIEDERBACHEM
----
ID: 128
Date: 12.06.2010
Waypoint: GC202AK
Title: Kein COVO LOCO #0210
----
ID: 129
Date: 12.06.2010
Waypoint: GC1ZK8Y
Title: Die Brücke
----
ID: 130
Date: 26.06.2010
Waypoint: GCKFAQ N029CD OC020E
Title: IMC No. 2 P-LU – Music in the AIR
Tag: recommended
----
ID: 131
Date: 26.06.2010
Waypoint: GC2AEA1
Title: Irsental-Brücke am Waldpark-Eifel
----
ID: 132
Date: 09.07.2010
Waypoint: GC1HJDY
Title: Jeu à plusieurs dimensions
----
ID: 133
Date: 01.09.2010
Waypoint: GC27Y7G
Title: LP Bullenkloster
Tag: recommended
----
ID: 134
Date: 13.09.2010
Waypoint: GC21PBJ
Title: Advent-Advent: Nikolaus oder Weihnachtsmann?
----
ID: 135
Date: 13.09.2010
Waypoint: GC25ZYH
Banner: jpg
Title: Blütenzauber in Sülz - MARSILIUS Geschichte
----
ID: 136
Date: 25.09.2010
Waypoint: GC2F8CX OCB099
Title: DER SCHLÜSSEL ZUM CODE
----
ID: 137
Date: 26.09.2010
Waypoint: GC2FF7R OCB0FE
Title: Millionenfalle
----
ID: 138
Date: 04.10.2010
Waypoint: GC2DJRF OCAD67
Title: 555
----
ID: 139
Date: 04.10.2010
Waypoint: GC1WMEA
Title: Mal schnell nen Micro 2 !
----
ID: 140
Date: 10.10.2010
Waypoint: GC1ZWFD
Title: Haus der Kultur
----
ID: 141
Date: 07.11.2010
Waypoint: GC2HW42 OCB65A
Title: Regulaxus
nTF: 2

Und Natureshadow hat den LTF gemacht…
----
ID: 142
Date: 22.11.2010
Waypoint: GC2C0E2
Title: Klettenberger Stern
----
ID: 143
Date: 16.01.2011
Waypoint: GC2M3KH OCBAE9
Title: Erzähl mir von alten Zeiten... (D2/T1.5)
----
ID: 144
Date: 17.01.2011
Waypoint: GC2KTC2
Title: Kessenicher Schleichwege #2
----
ID: 145
Date: 17.01.2011
Waypoint: GC2KTBR
Title: Kessenicher Schleichwege #1
----
ID: 146
Date: 06.02.2011
Waypoint: GC2EWPX
Title: Le photographe 3
----
ID: 147
Date: 06.02.2011
Waypoint: GC2D9CV
Title: Brussels South Station
----
ID: 148
Date: 16.02.2011
Waypoint: GC2MP54
Title: Dottendorfer Schleichwege #1
Tag: recommended
----
ID: 149
Date: 17.02.2011
Waypoint: GC2JK66
Title: Der Nikolaus kommt aus Kessenich
----
ID: 150
Date: 19.03.2011
Waypoint: GC1H5ZA
Title: Gashavariehahn
----
ID: 151
Date: 27.03.2011
Waypoint: GC2N73B
Title: Noch ein Schleichweg
----
ID: 152
Date: 27.03.2011
Waypoint: GC24FW8
Title: ichkennedyecke
----
ID: 153
Date: 27.03.2011
Waypoint: GC259QP
Title: 4 - Alleen - Kreuzung
----
ID: 154
Date: 06.04.2011
Waypoint: GC2Q0XB
Title: Wachtberger Kreuze 7
----
ID: 155
Date: 06.04.2011
Waypoint: GC2C8YV
Title: Wachtberger Kreuze 5
----
ID: 156
Date: 20.04.2011
Waypoint: GC1XZFX
Title: Wegkreuz an der alten L 61
Tag: recommended
----
ID: 157
Date: 01.06.2011
Waypoint: GC23YYM
Title: Maus-oleum
----
ID: 158
Date: 01.06.2011
Waypoint: GC267WM
Title: Der vergessene Fisch
----
ID: 159
Date: 17.06.2011
Waypoint: GC24PEG
Title: Arboretum
----
ID: 160
Date: 17.06.2011
Waypoint: GCME69
Title: Wartenden
----
ID: 161
Date: 28.07.2011
Waypoint: OCCDDC
Title: Banja Luka • Бања Лука • #1
nTF: 0
----
ID: 162
Date: 20.08.2011
Waypoint: GC2D7KG
Title: TB-Hotel FH Sankt Augustin
----
ID: 163
Date: 20.08.2011
Waypoint: GC2BMDR
Title: Lost Place: &#34;Möbel Tacke&#34;
----
ID: 164
Date: 22.08.2011
Waypoint: GC2MTY8
Title: Stadtarchiv - Sülzer Neubau
----
ID: 165
Date: 03.09.2011
Waypoint: GC2X457
Title: das Tier in Dir  ;-)
----
ID: 166
Date: 03.09.2011
Waypoint: GC2WEP9
Title: Brücke an Magenta
----
ID: 167
Date: 03.09.2011
Waypoint: OCCCF4
Title: Pflaumenbaumhundeschleichweg
----
ID: 168
Date: 10.09.2011
Waypoint: GC2C8VH OCB56F
Title: das Goldene Em #BN1
----
ID: 169
Date: 10.09.2011
Waypoint: GC2VTRT OCC5D4
Title: Nächster Halt: Limperich Nord
----
ID: 170
Date: 11.09.2011
Waypoint: GC2VTR6 OCC5D5
Title: Nächster Halt: Küdinghoven
----
ID: 171
Date: 25.10.2011
Waypoint: GC2NVFZ
Title: BHO - Besondere Historische Orte 1
----
ID: 172
Date: 31.10.2011
Waypoint: GC1MDYJ
Title: Freundschaftscache Apfelallee
----
ID: 173
Date: 01.11.2011
Waypoint: GC2VKVZ
Title: MS19 - die älteste Cacherin Deutschlands
----
ID: 174
Date: 06.11.2011
Waypoint: GC1TABR OC9B8A
Title: Schwimmbad Bad Neuenahr
----
ID: 175
Date: 11.11.2011
Waypoint: GC33YM4 OCD217
Title: Kopfüber in die Nacht
Tag: recommended
----
ID: 176
Date: 11.11.2011
Waypoint: GC30F3G OCCE63
Title: Panoramabad Rüngsdorf
----
ID: 177
Date: 12.11.2011
Waypoint: GC244M1
Title: Ein Rundsitz auf der Promenade
----
ID: 178
Date: 13.11.2011
Waypoint: OCD2B7
Title: Sinn oder Sinnlosigkeit
----
ID: 179
Date: 02.02.2012
Waypoint: GC2YG0E
Title: Häuser d. Helfer: Freiwillige Feuerwehr Dottendorf
----
ID: 180
Date: 09.02.2012
Waypoint: GC281TW
Title: Schwimmbad Bonn Frankenbad
----
ID: 181
Date: 20.02.2012
Waypoint: GCK91R
Title: IMC No. 2 P-DE - No Wind over Schwelmer Stadwald?
Tag: recommended
----
ID: 182
Date: 20.02.2012
Waypoint: GC36MM4
Title: Warten auf die Nordbahntrasse
----
ID: 183
Date: 20.02.2012
Waypoint: GC2P5BB
Title: Eine von Zehn
Tag: recommended
----
ID: 184
Date: 20.02.2012
Waypoint: GC285T3 OCA4A3
Title: Top Of Schwelm
----
ID: 185
Date: 22.02.2012
Waypoint: GC34FQV
Title: Sport ist Mord
----
ID: 186
Date: 29.02.2012
Waypoint: GC2PK4T
Title: Punktesammler
----
ID: 187
Date: 29.02.2012
Waypoint: GC1WEJD OC8B7F
Title: Römerbad - der Tradi
----
ID: 188
Date: 29.02.2012
Waypoint: GC313D2
Title: Pentaspastos
----
ID: 189
Date: 29.02.2012
Waypoint: GC371AB
Title: legio XXI rapax
----
ID: 190
Date: 29.02.2012
Waypoint: GC348WY
Title: Bonn
Tag: recommended

dreist
----
ID: 191
Date: 16.03.2012
Waypoint: GC23M4C
Title: Chemnitzer Brückenbauwerke - Bernhardstrasse
----
ID: 192
Date: 16.03.2012
Waypoint: GC36E83
Title: TB-Hotel Kirchheimer Dreieck
----
ID: 193
Date: 17.03.2012
Waypoint: GC248F9
Title: Technische Universität Chemnitz
----
ID: 194
Date: 17.03.2012
Waypoint: GC24582
Title: Chemnitzer Brückenbauwerke-Chemnitztalviadukt B95
----
ID: 195
Date: 17.03.2012
Waypoint: GC37EZ4
Title: BHF Chemnitz Mitte
----
ID: 196
Date: 17.03.2012
Waypoint: GC29AG3
Title: Such mich doch!
----
ID: 197
Date: 18.03.2012
Waypoint: GC2PTJK
Title: Diablos Nightmare - Der Totenbeschwörer
----
ID: 198
Date: 18.03.2012
Waypoint: GC2PTJ2
Title: Diablos Nightmare - Der Barbar
----
ID: 199
Date: 22.03.2012
Waypoint: GC31PGQ
Title: TbSC
----
ID: 200
Date: 24.03.2012
Waypoint: GC2Q86V
Title: crazy pics # 8
----
ID: 201
Date: 24.03.2012
Waypoint: GC2A5XP
Title: Ein einfaches Kreuz
----
ID: 202
Date: 09.04.2012
Waypoint: OCC5A3
Title: Der Wunschbaum
----
ID: 203
Date: 09.04.2012
Waypoint: GC273F3
Title: DENKstein (D1/T1.5/BYOP)
----
ID: 204
Date: 09.04.2012
Waypoint: GC36WAH
Title: Im Gedenken - In Memoriam
----
ID: 205
Date: 09.04.2012
Waypoint: GC2HCDM
Title: Alte Stadt Rheinbach (Öffnungszeiten beachten)
Tag: recommended
----
ID: 206
Date: 09.04.2012
Waypoint: GC2BGHQ
Title: Sankt Martin
----
ID: 207
Date: 09.04.2012
Waypoint: GC3DTG0
Title: Telefonjoker gesucht...
----
ID: 208
Date: 22.04.2012
Waypoint: GC1GEDG OC6885
Title: Hillijehüsje
----
ID: 209
Date: 25.04.2012
Waypoint: GC199YV
Title: Astronomie: Refraktorium
----
ID: 210
Date: 28.04.2012
Waypoint: GC3AV5W
Title: Nenn mich wie du willst
----
ID: 211
Date: 28.04.2012
Waypoint: GC260YR OCA170
Title: Unter Schafen
Tag: recommended
----
ID: 212
Date: 28.04.2012
Waypoint: GC313KA
Title: Lost Place - Das Autohaus
----
ID: 213
Date: 01.05.2012
Waypoint: GC161DG OCCF72
Title: Haus Carstanjen
----
ID: 214
Date: 01.05.2012
Waypoint: GC1TMRM
Title: Quer durch Plittersdorf
----
ID: 215
Date: 01.05.2012
Waypoint: GC28M7J
Title: Die &#34;Grünanlage&#34;
----
ID: 216
Date: 01.05.2012
Waypoint: GC2VPTF
Title: Park Sunday
----
ID: 217
Date: 01.05.2012
Waypoint: GC297FW
Title: Ev. Kliniken Bonn - Waldkrankenhaus
----
ID: 218
Date: 11.05.2012
Waypoint: GC2ZVQ3
Title: Der Medien-Cache - Reloaded
----
ID: 219
Date: 13.05.2012
Waypoint: GC2E86F
Title: Bonner Retter - Löscheinheit 11 -&gt; Bonn Mitte
----
ID: 220
Date: 28.05.2012
Waypoint: GC2YAH0
Title: Geo-Golf # 01
----
ID: 221
Date: 28.05.2012
Waypoint: GC2YAHC
Title: Geo-Golf # 02
----
ID: 222
Date: 28.05.2012
Waypoint: GC2YAHH
Title: Geo-Golf # 03
----
ID: 223
Date: 28.05.2012
Waypoint: GC2YAHQ
Title: Geo-Golf # 04
----
ID: 224
Date: 28.05.2012
Waypoint: GC2YAHX
Title: Geo-Golf # 05
----
ID: 225
Date: 28.05.2012
Waypoint: GC2YAJ0
Title: Geo-Golf # 06
----
ID: 226
Date: 28.05.2012
Waypoint: GC2YAJ3
Title: Geo-Golf # 07
----
ID: 227
Date: 28.05.2012
Waypoint: GC2YAJ8
Title: Geo-Golf # 09
----
ID: 228
Date: 28.05.2012
Waypoint: GC2YAJ9
Title: Geo-Golf # 10
----
ID: 229
Date: 28.05.2012
Waypoint: GC2YAJC
Title: Geo-Golf # 11
----
ID: 230
Date: 28.05.2012
Waypoint: GC2YAJE
Title: Geo-Golf # 12
----
ID: 231
Date: 28.05.2012
Waypoint: GC2YAJF
Title: Geo-Golf # 13
----
ID: 232
Date: 28.05.2012
Waypoint: GC2YAJH
Title: Geo-Golf # 14
----
ID: 233
Date: 28.05.2012
Waypoint: GC2YAJK
Title: Geo-Golf # 15
----
ID: 234
Date: 28.05.2012
Waypoint: GC2YAJQ
Title: Geo-Golf # 16
----
ID: 235
Date: 28.05.2012
Waypoint: GC2YAJT
Title: Geo-Golf # 17
----
ID: 236
Date: 28.05.2012
Waypoint: GC2YAJ4
Title: Geo-Golf # 18
----
ID: 237
Date: 28.05.2012
Waypoint: GC2YANG
Title: Geo-Golf Bonus
----
ID: 238
Date: 28.05.2012
Waypoint: GC24DN9
Title: Rätsel an der Rheinfähre
----
ID: 239
Date: 03.06.2012
Waypoint: GC2R1T3
Title: Drive In mit Aussicht
----
ID: 240
Date: 09.06.2012
Waypoint: GC3G5A2
Title: Bonn Grillt   2 0 1 2
----
ID: 241
Date: 09.06.2012
Waypoint: GC18ARR OC4D41
Title: Malen nach Zahlen II
----
ID: 242
Date: 09.06.2012
Waypoint: GC21K1J
Title: pünkTchen
----
ID: 243
Date: 09.06.2012
Waypoint: GC1M616
Title: The Cachers Home
----
ID: 244
Date: 09.06.2012
Waypoint: GC28VQ6
Title: Bonn - Südbrücke (A 562) - reloaded
----
ID: 245
Date: 10.06.2012
Waypoint: GC2E8G9
Title: Bonner Retter - BF Wache 2 -&gt; Bonn - Beuel
----
ID: 246
Date: 10.06.2012
Waypoint: GC2HPXC OCB9AF
Title: .
----
ID: 247
Date: 10.06.2012
Waypoint: GC3AH33
Title: Pfaffenpfädchenskreuz
----
ID: 248
Date: 10.06.2012
Waypoint: GC2PK16
Title: Ordo ab chao
----
ID: 249
Date: 10.06.2012
Waypoint: GC26QX2
Title: Bonn - Kennedybrücke (B 56)
----
ID: 250
Date: 10.06.2012
Waypoint: GC12B7W OC341E
Title: Augensausen II
----
ID: 251
Date: 24.06.2012
Waypoint: GC1Y54X
Title: Bonn Hbf re-reloaded
----
ID: 252
Date: 30.06.2012
Waypoint: GC2VVJT
Title: Ippendorfer Sportstätten #3
----
ID: 253
Date: 30.06.2012
Waypoint: GC2VVK7
Title: Ippendorfer Sportstätten #4
----
ID: 254
Date: 30.06.2012
Waypoint: GC2VV21
Title: Ippendorfer Sportstätten #2
----
ID: 255
Date: 30.06.2012
Waypoint: GC2VQ7P
Title: Ippendorfer Sportstätten #1
----
ID: 256
Date: 30.06.2012
Waypoint: GC2DCA6
Title: Kreuz am Wegesrand
----
ID: 257
Date: 30.06.2012
Waypoint: GC3MZJ5
Title: Ippendorfer Sportstätten #6
----
ID: 258
Date: 30.06.2012
Waypoint: GC2VTCD
Title: Drive in - Auf dem Weg zum größten Logbuch
----
ID: 259
Date: 30.06.2012
Waypoint: GC2TDN7
Title: Das größte Logbuch der Welt
Tag: recommended exceptional
----
ID: 260
Date: 05.07.2012
Waypoint: GC3KE8V
Title: Minden-/MuggelStation v3
----
ID: 261
Date: 05.07.2012
Waypoint: GC3KEH8
Title: (GC)TB-Lounge
----
ID: 262
Date: 07.07.2012
Waypoint: GC2N499
Title: Braunschweiger Spargel
Tag: recommended
----
ID: 263
Date: 07.07.2012
Waypoint: GC2771B
Title: Graffiti in Braunschweig
----
ID: 264
Date: 07.07.2012
Waypoint: GC3NY78
Title: Unterm Eis
----
ID: 265
Date: 07.07.2012
Waypoint: GC37WGE
Title: Kann schon mal länger dauern!!!
----
ID: 266
Date: 09.07.2012
Waypoint: GC3G0P1
Title: Düsseldorf Hbf - Bertha-von-Suttner-Platz
----
ID: 267
Date: 13.07.2012
Waypoint: GC1X77C OCB481
Title: It's All About the Numbers
----
ID: 268
Date: 14.07.2012
Waypoint: GC3KWY8
Title: Kessenicher Drive-In
----
ID: 269
Date: 11.08.2012
Waypoint: GC22944
Title: Königswinter Wanderparkplatz
----
ID: 270
Date: 11.08.2012
Waypoint: GC11EMP
Title: BAB3: Raststätte Fernthal West --&gt; Frankfurt
----
ID: 271
Date: 11.08.2012
Waypoint: GC174WD OC4790
Title: &#34;Lore ist silber!&#34;
----
ID: 272
Date: 11.08.2012
Waypoint: GC174WC OC476D
Title: &#34;Lore ist groß!&#34;
----
ID: 273
Date: 11.08.2012
Waypoint: GC17038 OC474D
Title: &#34;Lore ist zu dritt!&#34;
----
ID: 274
Date: 11.08.2012
Waypoint: GC16VM0 OC4638
Title: &#34;Lore ist flach!&#34;
----
ID: 275
Date: 18.08.2012
Waypoint: GC3K2JX
Title: Project
----
ID: 276
Date: 06.09.2012
Waypoint: GC2WW2T
Title: Wer lesen kann...
----
ID: 277
Date: 06.09.2012
Waypoint: GC36302
Title: Wildwechsel
----
ID: 278
Date: 06.09.2012
Waypoint: GC2WZDK
Title: Wachtberger Kreuze 9
----
ID: 279
Date: 06.09.2012
Waypoint: GC2XAFT
Title: Wachtberger Kreuze (sind wir bei 11?)
----
ID: 280
Date: 06.09.2012
Waypoint: GC35NXT
Title: Heiligenhäuschen Ließem
----
ID: 281
Date: 06.09.2012
Waypoint: GC2BJ0C
Title: Gotteshäuser – St. Gereon  (Niederbachem)
----
ID: 282
Date: 06.09.2012
Waypoint: GC2BHZK
Title: Häuser der Helfer – Feuerwehr Wachtberg #1
----
ID: 283
Date: 07.09.2012
Waypoint: GC37CWT
Title: &#34;Große Namen&#34; # 1
----
ID: 284
Date: 08.09.2012
Waypoint: GC38MCW
Title: Zum Burzeltag
----
ID: 285
Date: 08.09.2012
Waypoint: GC3N3KM OCE558
Title: In der Nähe meines großen gelben Bruders
----
ID: 286
Date: 09.09.2012
Waypoint: GC3BR42
Title: Kreuz am Wegesrand # 2
----
ID: 287
Date: 10.10.2012
Waypoint: GC1HGEH
Title: Eau de source à PARIS- Spring water in PARIS.
Tag: Earth recommended
----
ID: 288
Date: 25.10.2012
Waypoint: GC2JBGV
Title: Blick auf Gewässer !
----
ID: 289
Date: 26.10.2012
Waypoint: GC3QPW7
Title: Starkes Bündnis
----
ID: 290
Date: 26.10.2012
Waypoint: GC3488X
Title: Eisenquelle Alfhausen / Iron source Alfhausen
Tag: recommended earth
----
ID: 291
Date: 26.10.2012
Waypoint: GC3QJWF
Title: Königswald
----
ID: 292
Date: 27.10.2012
Waypoint: GC2VA18
Title: noch'n apple a day ...
Tag: recommended
----
ID: 293
Date: 09.11.2012
Waypoint: GC2FW17
Title: Für S
----
ID: 294
Date: 24.11.2012
Waypoint: GC2BNY0
Title: Lore ist nicht weit (Tribute to Asbacher Bande)
----
ID: 295
Date: 25.12.2012
Waypoint: GC3CFD4
Title: Auf der Gassirunde...
----
ID: 296
Date: 05.01.2013
Waypoint: GC39NHA
Title: Unter den Linden
----
ID: 297
Date: 05.01.2013
Waypoint: GC3F81P
Title: ++++++++++[&gt;+++++++-]&gt;----.++++.
Tag: recommended tech
----
ID: 298
Date: 05.01.2013
Waypoint: GC32NGB
Title: Knubbelbaum
----
ID: 299
Date: 27.01.2013
Waypoint: GC3CFK2
Title: Burg-Bach-Kreuz-Ung
----
ID: 300
Date: 01.02.2013
Waypoint: GC1MZWP
Title: Expo58 - The Whirling Ear STEALTH
----
ID: 301
Date: 03.02.2013
Waypoint: GCRNQC
Title: Coudenberg
----
ID: 302
Date: 04.02.2013
Waypoint: GCR68J
Title: CINEMATEK
----
ID: 303
Date: 04.02.2013
Waypoint: GC2VH28
Title: Steinkreis
----
ID: 304
Date: 13.02.2013
Waypoint: GC22APZ OC9B37
Title: Heinrichsblick
Tag: recommended
----
ID: 305
Date: 13.02.2013
Waypoint: GC2NDK9
Title: Burgen &amp; Schlösser - Rolandsbogen - dritte Ausgabe
----
ID: 306
Date: 13.02.2013
Waypoint: GC1TKGT OC8744
Title: Rodderberg Vulkan
Tag: recommended earth
----
ID: 307
Date: 02.03.2013
Waypoint: GC3YA6K
Title: Can you do it?
----
ID: 308
Date: 02.03.2013
Waypoint: GC40XBK
Title: Verschlumpft
Tag: recommended exceptional
----
ID: 309
Date: 10.03.2013
Waypoint: GC3NBWF OCE691
Title: The Invisible Bicycle
----
ID: 310
Date: 23.03.2013
Waypoint: GC40BKF
Title: Hagelsiepen
----
ID: 311
Date: 23.03.2013
Waypoint: GC3YJXK OCEDFB
Title: Oberbeck
----
ID: 312
Date: 23.03.2013
Waypoint: GC2NGB5
Title: Die Evangelisch-reformierte Kirche Radevormwald
----
ID: 313
Date: 24.03.2013
Waypoint: OCDF52
Title: Bonn estas bona
----
ID: 314
Date: 24.03.2013
Waypoint: GC1WPCE
Title: &#34;Der Gasometer&#34; vom Venusberg
----
ID: 315
Date: 24.03.2013
Waypoint: GC27TTG
Title: Im Gedenken an Dr. Gerold von Braunmühl
----
ID: 316
Date: 24.03.2013
Waypoint: GC3QRPH
Title: TB Hotel &#34;Fliegerbombe&#34;
----
ID: 317
Date: 24.03.2013
Waypoint: GC2QX6B
Title: Waldhütte
----
ID: 318
Date: 24.03.2013
Waypoint: GC43432
Title: Langweilliger Tradi weil einer keine Geduld hatte!
----
ID: 319
Date: 24.03.2013
Waypoint: GC14BJ8 OC3C6A
Title: Tauschstübchen - Dvd
----
ID: 320
Date: 24.03.2013
Waypoint: GC1W442
Title: Lost Place: Diplomatenschule
----
ID: 321
Date: 24.03.2013
Waypoint: GC3B86C
Title: Wo die Sonne scheint
----
ID: 322
Date: 31.03.2013
Waypoint: GC1WVMW OC8C44
Title: offenes Logbuch
----
ID: 323
Date: 31.03.2013
Waypoint: GC40WGQ
Title: Puddingbrezel und Kaffee
----
ID: 324
Date: 14.04.2013
Waypoint: GC40H1V
Title: Familie Levy
----
ID: 325
Date: 14.04.2013
Waypoint: GC3KZAX
Title: Asphaltcowboys
----
ID: 326
Date: 14.04.2013
Waypoint: GC3VHXY
Title: Willkommen in Mehlem 2.0
----
ID: 327
Date: 19.04.2013
Waypoint: GC1X2MD OCB3FD
Title: Bundesämter BBK und THW
----
ID: 328
Date: 19.04.2013
Waypoint: GC22BXK
Title: So ein Durcheinander
Tag: recommended tech
----
ID: 329
Date: 19.04.2013
Waypoint: GC31RJB OCD37F
Title: Bonn-HiCOG, oder Stuttgart
----
ID: 330
Date: 19.04.2013
Waypoint: GC3DM51 OCEDA7
Title: Muffendorf Bildstock II
----
ID: 331
Date: 19.04.2013
Waypoint: GC1P96M
Title: High Water Weinhaeuschen
----
ID: 332
Date: 20.04.2013
Waypoint: GC2C1QD
Title: Fliegen war ihr Leben
----
ID: 333
Date: 21.04.2013
Waypoint: GC3N21M
Title: ... in die Ferne
----
ID: 334
Date: 21.04.2013
Waypoint: GC3AJCG
Title: Lannesdorfer Pümpchen
----
ID: 335
Date: 21.04.2013
Waypoint: GC2JJ4D
Title: Häuser der Helfer &#34;Feuerwehr Bonn Lannesdorf“
----
ID: 336
Date: 22.04.2013
Waypoint: GC2TXZ3
Title: Gotteshäuser: Jesus-Christus-Kirche
----
ID: 337
Date: 28.04.2013
Waypoint: GC2PMYX
Title: Für Kinofans
----
ID: 338
Date: 06.05.2013
Waypoint: GC4AP8Y
Title: Gestrandet
----
ID: 339
Date: 06.05.2013
Waypoint: GC2NVG1
Title: HDH 1 - Helfer der Haustiere
----
ID: 340
Date: 07.05.2013
Waypoint: GC35YVZ
Title: SPANNEND!
----
ID: 341
Date: 07.05.2013
Waypoint: GC37CYC
Title: “Große Namen“ # 2
----
ID: 342
Date: 07.05.2013
Waypoint: GC2E8DX
Title: Bonner Retter - Löscheinheit 42 -&gt; Lengsdorf
----
ID: 343
Date: 07.05.2013
Waypoint: GC45V16
Title: Der größte TB der Welt
Tag: D15 T25 Micro Mystery recommended
----
ID: 344
Date: 07.05.2013
Waypoint: GC3Y31B
Title: Ring*Con 2012
----
ID: 345
Date: 09.05.2013
Waypoint: GC3HRJQ
Title: Per &#34;Anhalter&#34; durch Buschdorf?
----
ID: 346
Date: 09.05.2013
Waypoint: GC13D9B
Title: Binnendüne Tannenbusch
Tag: earth
----
ID: 347
Date: 10.05.2013
Waypoint: GC3GRNT
Title: Eierkooche-Rötzje
----
ID: 348
Date: 10.05.2013
Waypoint: GC26TEW
Title: Sankt Augustin Mülldorf I
----
ID: 349
Date: 10.05.2013
Waypoint: GC3N0WW
Title: Grottis BK
----
ID: 350
Date: 10.05.2013
Waypoint: GC3YN2N
Title: Stellplatz
----
ID: 351
Date: 10.05.2013
Waypoint: GC2CEK0 OCB570
Title: Häuser der Helfer: Polizeipräsidium Bonn
----
ID: 352
Date: 19.05.2013
Waypoint: GC4BJGJ
Title: Alles Lama oder was ?
----
ID: 353
Date: 20.05.2013
Waypoint: GC4C9HX
Title: In der Fremde Zuhause: Nepalesische Botschaft
----
ID: 354
Date: 20.05.2013
Waypoint: GC4C9RW
Title: PonyFish- Land - Außenstelle Mehlem
----
ID: 355
Date: 27.05.2013
Waypoint: GC30TF6
Title: Ich bin der Wald... (D2/T1.5/BYOP)
----
ID: 356
Date: 27.05.2013
Waypoint: GC210AZ
Title: Alles für den Ball – alles für den Verein…
----
ID: 357
Date: 28.05.2013
Waypoint: GC2E8DN
Title: Bonner Retter - Löscheinheit 41 -&gt; Duisdorf
----
ID: 358
Date: 30.05.2013
Waypoint: GC3D8H9
Title: Der Kolibri
----
ID: 359
Date: 30.05.2013
Waypoint: GC4BFHM
Title: Die Quelle des durstigen Wanderers
----
ID: 360
Date: 30.05.2013
Waypoint: GC43YQF
Title: Rodderberger Erdnuckel
----
ID: 361
Date: 30.05.2013
Waypoint: GCQCF8 OC0915
Title: Auf dem Rodderberg
----
ID: 362
Date: 02.06.2013
Waypoint: GC2HKT7
Title: Projekttage: Lena Meyer-Landrut
----
ID: 363
Date: 02.06.2013
Waypoint: GC3A03V
Title: HERSEL 21
----
ID: 364
Date: 02.06.2013
Waypoint: GC42W4E
Title: Cacher - Rastplatz
----
ID: 365
Date: 02.06.2013
Waypoint: GC449JK
Title: Wider das Vergessen
----
ID: 366
Date: 02.06.2013
Waypoint: GC3JNKF
Title: Linie 16 - Haltepunkt Hersel
----
ID: 367
Date: 04.06.2013
Waypoint: GC2TJKT
Title: Godesberger Schleichwege
----
ID: 368
Date: 06.06.2013
Waypoint: GC4DDVE
Title: Auf den Spuren der Elfen
nTF: 1
----
ID: 369
Date: 06.06.2013
Waypoint: GC27MAQ
Title: Die Brücke
----
ID: 370
Date: 06.06.2013
Waypoint: GC48KGX
Title: Ausgefuchst
----
ID: 371
Date: 06.06.2013
Waypoint: GC1M87F
Title: Vorgartenschätzchen
----
ID: 372
Date: 06.06.2013
Waypoint: GC37WBE
Title: Bonner Katzenloch
----
ID: 373
Date: 06.06.2013
Waypoint: GC3VBVR
Title: Die Kurfürstenquelle
Tag: recommended
----
ID: 374
Date: 06.06.2013
Waypoint: GC35JTV
Title: Am alten Kloster
----
ID: 375
Date: 06.06.2013
Waypoint: GC33BD3
Title: Der Wächter ist ein Esel
----
ID: 376
Date: 08.06.2013
Waypoint: GC3XPT3
Title: TB-Hotel Rheinbach Nord
----
ID: 377
Date: 08.06.2013
Waypoint: GC26VVH
Title: Cache &amp; Rast - West (dt/en)
----
ID: 378
Date: 08.06.2013
Waypoint: GC2N8N8
Title: Cache &amp; Rast Ost - TB Motel

Haha, N-Acht Nacht… toller Waypoint-Code
----
ID: 379
Date: 08.06.2013
Waypoint: GC2P5WP
Title: T-Helferzelle
----
ID: 380
Date: 08.06.2013
Waypoint: GC27X28
Title: Ramershovener Verlies [LP]
Tag: recommended
----
ID: 381
Date: 08.06.2013
Waypoint: GC3CBKZ
Title: Schwarzes Steinkreuz
----
ID: 382
Date: 08.06.2013
Waypoint: GC30N2V
Title: Der Himmel über mir
----
ID: 383
Date: 08.06.2013
Waypoint: GC3CE7W
Title: Kleines Steinkreuz
----
ID: 384
Date: 09.06.2013
Waypoint: GC373EA
Title: Obsession bis zur Session
Tag: recommended tech
----
ID: 385
Date: 09.06.2013
Waypoint: GC3KBN1
Title: Das Planschbecken
----
ID: 386
Date: 09.06.2013
Waypoint: GC3HT0X
Title: Marias Rutsche
----
ID: 387
Date: 11.06.2013
Waypoint: GC2E89G
Title: Bonner Retter - Löscheinheit 14 -&gt; Endenich
----
ID: 388
Date: 17.06.2013
Waypoint: GC4BYEZ
Title: Wasserhäuschen
----
ID: 389
Date: 17.06.2013
Waypoint: GC2QA76
Title: Dorfbrunnen Hilgert

Wenn Du hier bist, bist Du falsch, wenn Du zur A3 Richtung Köln willst.
----
ID: 390
Date: 17.06.2013
Waypoint: GC188KM OC4CF1
Title: Das Goldene Em - Add on SU #1
----
ID: 391
Date: 20.06.2013
Waypoint: GC374F5 OCDEA0
Title: Remember HIH
----
ID: 392
Date: 20.06.2013
Waypoint: GC2VQ5G
Title: Besuch aus der Antarktis ...

Natureshadow ist (multipel indirekt) schuld ☺
----
ID: 393
Date: 22.06.2013
Waypoint: OK00CA
Title: House of Correction
nTF: 2

Okay, I cheated a bit, here. But, pooh.
Whatever method is used to log the cache,
the result matters; it’s the same with
accidentally found Finals for Mystery or
other multi-stage caches.
----
ID: 394
Date: 22.06.2013
Waypoint: CC7TB
Title: Truly Well-Rounded Cacher LC - Level I
Tag: MC3 Locationless Challenge
----
ID: 395
Date: 22.06.2013
Waypoint: CCR2
Title: WCG II - Keep it going
Tag: MC0 Locationless Challenge
----
ID: 396
Date: 23.06.2013
Waypoint: LC7TL
Title: Birthday Coordinates
nTF: 3
Tag: MC0 Safari
----
ID: 397
Date: 24.06.2013
Waypoint: GC357H8
Title: Hintertürchen am Bolzplatz
----
ID: 398
Date: 24.06.2013
Waypoint: GC3DE82
Title: Kunst am Wegesrand
----
ID: 399
Date: 24.06.2013
Waypoint: GC3PZG4 OCEDA8
Title: Muffendorfer Bildstöcke
----
ID: 400
Date: 28.06.2013
Waypoint: GC3VECK
Title: Project Eck 2013 - Meet &amp; Greet am Eck
----
ID: 401
Date: 28.06.2013
Waypoint: GCTJ8X OC183E
Title: ZEICHEN VND SÄTZE (Megaevent Version)
----
ID: 402
Date: 29.06.2013
Waypoint: GC3TECK
Banner: jpg
Title: Project Eck 2013
----
ID: 403
Date: 29.06.2013
Waypoint: GC4D97Q
Title: Weltrekord Lesen
----
ID: 404
Date: 29.06.2013
Waypoint: GC4EGFV
Title: Project Eck - Gabione

„Dosenfischer – Just another Brick in the Gabione“
(sie sind <em>wirklich</em> nicht Pink Floyd…)
----
ID: 405
Date: 29.06.2013
Waypoint: GC4E6VP
Title: Project Eck – Festungspark

Wenigstens den hier mal <em>ganz</em> alleine auf’m
MEGA-Event gefunden. Macht mehr Spaß als nur die
Schlange finden und sich hinten anstellen!
----
ID: 406
Date: 29.06.2013
Waypoint: GC4E6VK
Title: Project Eck – Kletterpark
----
ID: 407
Date: 29.06.2013
Waypoint: GC4E6TF
Title: Project Eck – BUGA2011

Hier mußten wir über die „Nachbarn“ schmunzeln,
fanden die angrenzenden Blumenbeete aber schöner
als den Matschweg.
----
ID: 408
Date: 29.06.2013
Waypoint: GC4E6TA
Title: Project Eck – Seilbahn

Ob Bonn auch so eine bekommt? Ist angenehmer als
die in den Alpen… immer noch suspekt, aber gut.
Wobei es am Venusberg ja nicht wirklich Not tut.
----
ID: 409
Date: 30.06.2013
Waypoint: GCGRNE
Title: Loreley
----
ID: 410
Date: 30.06.2013
Waypoint: GC3WECK
Title: Project Eck 2013 - Eine Schifffahrt die...

(Heißt aber Schiff<b>s</b>fahrt!) Trotzdem Danke
an die Orga, bis auf ein paar Nano-Stolperstellen
war das alles super organisiert und hat Spaß gemacht!
Und Kapitän Brummkreisel war auch gut drauf und wir
hatten definitiv das beste Schiff!
----
ID: 411
Date: 30.06.2013
Waypoint: GC4ACTK
Title: Weltkulturerbe Oberes Mittelrheintal
----
ID: 412
Date: 30.06.2013
Waypoint: GC4AF0X
Title: Wahrschau
----
ID: 413
Date: 30.06.2013
Waypoint: GC2QJVY
Title: Aussicht auf den Rhein
----
ID: 414
Date: 30.06.2013
Waypoint: GC4C4RB
Title: Verlorene Klöster Koblenz: Karmeliterkloster
----
ID: 415
Date: 02.07.2013
Waypoint: GC339M6
Title: 4 Freunde das sind wir
----
ID: 416
Date: 02.07.2013
Waypoint: GC34N3E
Title: Häuser der Beschaffer #00001: Das Beschaffungsamt
----
ID: 417
Date: 02.07.2013
Waypoint: GC2CG7T
Title: Ein Zwilling
----
ID: 418
Date: 07.07.2013
Waypoint: GC1V1EC
Title: Neue Perspektiven
----
ID: 419
Date: 11.07.2013
Waypoint: CC7TX
Title: WCG III - Ruby's Reward
nTF: 2
Tag: MC0 Locationless Challenge
----
ID: 420
Date: 11.07.2013
Waypoint: GC3B0ZM
Title: First Davido
----
ID: 421
Date: 11.07.2013
Waypoint: GC2HJAC
Title: Peerd und Koh
----
ID: 422
Date: 12.07.2013
Waypoint: GC3VKY7
Title: Ich Glaub ich Seh Schwarz - Weiss
Tag: recommended
----
ID: 423
Date: 13.07.2013
Waypoint: GCN5KR
Title: Van Heek fabriek
----
ID: 424
Date: 13.07.2013
Waypoint: GC37CRJ
Title: klik en klaar
----
ID: 425
Date: 14.07.2013
Waypoint: GC2TZN3
Title: Godesberger Scheichwege
----
ID: 426
Date: 22.07.2013
Waypoint: LC7QP
Title: TerraCachin' Fashion
nTF: 2
Tag: MC0 Locationless
----
ID: 427
Date: 27.07.2013
Waypoint: GC21CET
Banner: jpg
Title: Nacht der Vulkane 2013

Uns wurde nicht zuviel versprochen, und die Erde hat tatsächlich gebebt.
Die beiden Führungen in der Vulkan-Brauerei waren auch toll und sind
empfehlenswert… nur eine Marktlücke wäre da noch: Essen im Felsenkeller
(im Sommer schön kühl, im Winter wärmer).
----
ID: 428
Date: 27.07.2013
Waypoint: GC2BETC
Title: A u s l e g e r
----
ID: 429
Date: 27.07.2013
Waypoint: GC4FV10
Title: NdV 2013 - Street End
----
ID: 430
Date: 01.08.2013
Waypoint: GC4GDXD
Banner: jpg CAT-Events im August 2013 – Ich war dabei!
Title: CAT - Eiszeit 1

Tolle Idee; übernehme ich mal, mit Einverständnis…
----
ID: 431
Date: 01.08.2013
Waypoint: GC3AGC4
Title: TBH: Gute Reise
----
ID: 432
Date: 01.08.2013
Waypoint: GC4E2A1
Title: Rosenhof Cache

Massiv off. Bessere Koordinaten in den Logs…
----
ID: 433
Date: 01.08.2013
Waypoint: GC4HHZZ OC3378
Title: Hinterm Busch gleich links
nTF: 4
----
ID: 434
Date: 02.08.2013
Waypoint: GC33PFB
Title: Wachtberger Kreuze # 12
----
ID: 435
Date: 03.08.2013
Waypoint: GC33PFW
Title: Wachtberger Kreuze # 13
----
ID: 436
Date: 04.08.2013
Waypoint: GC306MY
Title: Jagdbomber in Oberholtorf
----
ID: 437
Date: 04.08.2013
Waypoint: GCVNRH OC1CF3 N02049
Title: Gotteshäuser: Zwei Kirchen ohne Namen
Tag: recommended
----
ID: 438
Date: 05.08.2013
Waypoint: GC47F5Q
Title: Hier kämpft der Löwe
----
ID: 439
Date: 06.08.2013
Waypoint: GC48YTE
Title: C-H-B (Coin-Hotel-Bonn)
----
ID: 440
Date: 07.08.2013
Waypoint: GC35BNN
Title: Ankerbach
----
ID: 441
Date: 07.08.2013
Waypoint: GCV21F OC1A07
Title: Burgen &amp; Schlösser #10 - Kommende Ramersdorf
----
ID: 442
Date: 08.08.2013
Waypoint: GC3GX1Y
Title: Planetenrunde-URANUS
----
ID: 443
Date: 09.08.2013
Waypoint: GC486WW
Title: Augustus MMXIII. (3)
----
ID: 444
Date: 10.08.2013
Waypoint: GC3TT0R
Title: Schafwiese
Tag: recommended exceptional

Korrekt müßte es Schaf<b>s</b>wiese heißen.
Geniales Logbuch!
----
ID: 445
Date: 10.08.2013
Waypoint: GC4F9VA
Title: Owerdreeser Ollichsmill
----
ID: 446
Date: 11.08.2013
Waypoint: GC4HMEG
Title: Sam´s Home

Der Owner möchte bitte einen
<a href="http://www.cl.cam.ac.uk/~mgk25/ucs/apostrophe.html">echten
Apostroph</a> verwenden, keinen Akzent Akut.
----
ID: 447
Date: 12.08.2013
Waypoint: GC4BQ6K
Title: Augustus MMXIII. (5)
----
ID: 448
Date: 13.08.2013
Waypoint: GC4B9T2
Title: Oberkasseler Schleichweg
----
ID: 449
Date: 14.08.2013
Waypoint: GC3KHW1
Title: Linie 66
----
ID: 450
Date: 15.08.2013
Waypoint: GC3CTKT
Title: Schieberjagd durch Duisdorf
----
ID: 451
Date: 16.08.2013
Waypoint: GC4644Q
Title: Das grunzende Schwein auf Oberwerth
----
ID: 452
Date: 17.08.2013
Waypoint: GC2WY3D
Title: Volvodidi&#96;s Werkstattcache

Den <a href="http://linuxwiki.de/ApoStrophen">Genitiv mit s</a> lernen wir noch.
----
ID: 453
Date: 18.08.2013
Waypoint: GC33VN3
Title: STOP - in 100 m
----
ID: 454
Date: 18.08.2013
Waypoint: GC2ZQYN
Title: Alfterer Kreuze 02
----
ID: 455
Date: 18.08.2013
Waypoint: GC337BR
Title: Alfterer Kreuze 13
----
ID: 456
Date: 18.08.2013
Waypoint: GC2ZVPG
Title: Alfterer Kreuze 09
----
ID: 457
Date: 19.08.2013
Waypoint: GC354VF
Title: Ruhe in Roisdorf
----
ID: 458
Date: 19.08.2013
Waypoint: GC3DGNB
Title: Der Birnbaum
----
ID: 459
Date: 20.08.2013
Waypoint: GC4G63X
Banner: gif
Title: TB Hotel 24h open
----
ID: 460
Date: 20.08.2013
Waypoint: GC4EDZM
Title: Gemühtliches Plätzchen Drachenfelser Ländchen 1998

Gemütlich!
----
ID: 461
Date: 20.08.2013
Waypoint: GC4H000
Title: Der Apfelpetling
----
ID: 462
Date: 20.08.2013
Waypoint: GC4EP5K
Title: TBHotel am Zaun der Johannisbeeranlage 1998
----
ID: 463
Date: 20.08.2013
Waypoint: GC4ENN9
Title: Die Johannisbeere 1998
----
ID: 464
Date: 20.08.2013
Waypoint: GC4G3CG
Title: XXL Travel Bug House (Ließem)
Tag: recommended
----
ID: 465
Date: 20.08.2013
Waypoint: GC4H15Q
Title: Mathematik im Drachenfälser Ländchen

Der arme Fels… ;-)
----
ID: 466
Date: 20.08.2013
Waypoint: GC4EEFP
Title: TB Hotel an der Kuhweide 1998
----
ID: 467
Date: 20.08.2013
Waypoint: GC4EEGN
Title: Der Drahtspanner an der Schafswiese 1998
----
ID: 468
Date: 21.08.2013
Waypoint: GC4925P
Title: Bernd's Birthday 2
----
ID: 469
Date: 21.08.2013
Waypoint: GC49263
Title: Bernd's Birthday 3
----
ID: 470
Date: 22.08.2013
Waypoint: GC4JMH3
Title: Naturstrom-Bus
Tag: recommended
----
ID: 471
Date: 23.08.2013
Waypoint: GC4E446
Title: Kein Stein
----
ID: 472
Date: 23.08.2013
Waypoint: GC3EA3F
Title: Nepomuks Geheimnis
----
ID: 473
Date: 23.08.2013
Waypoint: GC4G1CG
Title: Bunker Beuel
----
ID: 474
Date: 24.08.2013
Waypoint: GC49258
Title: Bernd's Birthday 1
----
ID: 475
Date: 24.08.2013
Waypoint: GC4926M
Title: Bernd's Birthday 4
----
ID: 476
Date: 24.08.2013
Waypoint: GC49275
Title: Bernd's Birthday 5
Tag: recommended
----
ID: 477
Date: 24.08.2013
Waypoint: GC4926Y
Title: Bernd's Birthday 6
----
ID: 478
Date: 24.08.2013
Waypoint: GC49289
Title: Bernd's Birthday BONUS
----
ID: 479
Date: 25.08.2013
Waypoint: GC49Q9E
Title: Völker und Kulturen
----
ID: 480
Date: 26.08.2013
Waypoint: GC4BNWY
Title: Noch echte Dinos und das mitten in Oberkassel
----
ID: 481
Date: 27.08.2013
Waypoint: GC4G955
Title: Die Heiligen der letzten Tage
----
ID: 482
Date: 28.08.2013
Waypoint: GC1E8G7 OC6104
Title: Unkelbacher Brücke
----
ID: 483
Date: 28.08.2013
Waypoint: GC4KY21
Title: Bandorfer Schutzbrücke
----
ID: 484
Date: 28.08.2013
Waypoint: GC33F6V
Title: Lost in Oedingen - GPS Gerät auf Abwegen
----
ID: 485
Date: 28.08.2013
Waypoint: GC1V5CW
Title: Willkommen in... Oedingen
----
ID: 486
Date: 28.08.2013
Waypoint: GC29GT4
Title: Aschermittwochs Cache
----
ID: 487
Date: 28.08.2013
Waypoint: GC4F9E3
Title: Micro im Dorf 1998
----
ID: 488
Date: 29.08.2013
Waypoint: GC35BNJ
Title: Wachtberger Kreuze # 19
----
ID: 489
Date: 29.08.2013
Waypoint: GC4HNY8
Title: Dűrschhaltevɑmȫjen / Stamina
nTF: 0
Tag: D1 T1 Event
----
ID: 490
Date: 29.08.2013
Waypoint: GC32HCK
Title: Gotteshäuser: Sankt Severin in Mehlem
Tag: D4 T35 Micro Mystery recommended exceptional

Geradezu faszinierend und ein würdiger Nachfolger für
meinen [#46] OC58A9 „Gotteshäuser: Mehlem Kirche St. Severin“!
----
ID: 491
Date: 30.08.2013
Waypoint: GC4H00C
Title: Willkommen auf dem Heiderhof 1998
Tag: D15 T2 Micro Tradi
----
ID: 492
Date: 30.08.2013
Waypoint: GC4H317
Title: Fuderbach/Heiderhof
Tag: D25 T15 Micro Tradi
----
ID: 493
Date: 31.08.2013
Waypoint: GC3WEZW
Title: Der Nachtfalke
Tag: D15 T15 Micro Tradi
----
ID: 494
Date: 20.08.2013
Waypoint: GC4G32E
Title: Nano statt Müll
Tag: D1 T15 Nano Tradi

Naja, bald sind die Sommerferien zum Glück zuende…
----
ID: 495
Date: 31.08.2013
Waypoint: GC4H12G
Title: ist nicht schwer ?! reloaded
Tag: D2 T1 Small Mystery
----
ID: 496
Date: 31.08.2013
Waypoint: GC1Z5AT
Title: Alles in ...
Tag: D3 T1 Micro Tradi
----
ID: 497
Date: 31.08.2013
Waypoint: GC3F6KK
Title: Welche Richtung ?
Tag: D2 T1 Micro Tradi
----
ID: 498
Date: 01.09.2013
Waypoint: GC17RCY OC4AB7
Title: Bonner Meilenstein
Tag: D25 T1 Micro Mystery
----
ID: 499
Date: 02.09.2013
Waypoint: GC36WWX
Title: Die Unvollendete - L471
Tag: D15 T2 Small Tradi
----
ID: 500
Date: 02.09.2013
Waypoint: GC36WQQ
Title: NRW 53 Challenge #Bonn
Tag: D2 T25 Small Mystery

T2½ ist etwas gewagt, wenn #499 nur T2 ist, aber… okay.
Ist jedenfalls nicht T4, auch wenn man’s gefrustet meint.
----
ID: 501
Date: 03.09.2013
Waypoint: GC2HX8V
Title: Spassaufgabe 100 Zellen
Tag: D25 T2 Micro Mystery
----
ID: 502
Date: 04.09.2013
Waypoint: GC44B4Q
Title: Geo-Schach in Unkelbach
Tag: D2 T2 Small Mystery recommended

Der Outdoorteil ist nicht zu unterschätzen und hat m.E. schon
eher D2½ T2½ verdient. Nicht nachts machen. Beim Rätsel auch
mal beim Rechnen nicht zu kompliziert denken.
----
ID: 503
Date: 05.09.2013
Waypoint: GC3FP98 OCF2D5
Title: TB Bunker BONN Duisdorf
Tag: D2 T2 Large Tradi recommended
----
ID: 504
Date: 12.09.2013
Waypoint: GC4FE20
Title: geHÖRT das so?!
Tag: D3 T15 Micro Tradi
----
ID: 505
Date: 12.09.2013
Waypoint: GC4EEAT
Title: An der Kuhweide 1998
Tag: D2 T15 Micro Tradi
----
ID: 506
Date: 13.09.2013
Waypoint: GC40K27
Title: Bonner PETlinge #2
Tag: D1 T15 Micro Tradi
----
ID: 507
Date: 14.09.2013
Waypoint: GC2YAPG
Title: Wachtberger Kreuze # 3
Tag: D2 T1 Micro Tradi
----
ID: 508
Date: 15.09.2013
Waypoint: GC2TXYD
Title: Witterschlicker Grillplatz
Tag: D15 T2 Micro Tradi
----
ID: 509
Date: 16.09.2013
Waypoint: GC492MZ
Title: Planetenrunde-JUPITER
Tag: D15 T15 Small Tradi
----
ID: 510
Date: 17.09.2013
Waypoint: GC3YA55
Title: Königreich Ückesdorf 4
Tag: D1 T2 Micro Tradi
----
ID: 511
Date: 17.09.2013
Waypoint: GC1N76E OC7A88
Title: Gotteshäuser: St. Hubertus (Ückesdorf)
Tag: D1 T1 Micro Tradi
----
ID: 512
Date: 18.09.2013
Waypoint: GC43K9N
Title: Geo-Matt in Niederbachem
Tag: D2 T15 Small Mystery recommended
----
ID: 513
Date: 19.09.2013
Waypoint: GC4305G
Title: Möge die Straße ...
Tag: D1 T1 Micro Tradi
----
ID: 514
Date: 20.09.2013
Waypoint: GC173FT OC471E
Title: Zechers Zuflucht
Tag: D1 T25 Micro Tradi
----
ID: 515
Date: 20.09.2013
Waypoint: GC34CJ9
Title: Rhöndorf grüsst seine Gäste
Tag: D1 T1 Small Tradi
----
ID: 516
Date: 21.09.2013
Waypoint: GC33VKZ
Title: Die Schlaufe
Tag: D1 T1 Micro Tradi
----
ID: 517
Date: 21.09.2013
Waypoint: GC2E4D1
Title: Kreuz an der Mühle
Tag: D2 T15 Small Tradi
----
ID: 518
Date: 22.09.2013
Waypoint: GC3429W OCD380
Title: Wachtberger Kreuze # 14
Tag: D1 T2 Micro Tradi
----
ID: 519
Date: 22.09.2013
Waypoint: GC37RYR
Title: Rettungswache Wachtberg
Tag: D2 T1 Micro Tradi recommended
----
ID: 520
Date: 26.09.2013
Waypoint: GC4918H
Title: Schwarzrheindorf
Tag: D1 T1 Micro Tradi
----
ID: 521
Date: 26.09.2013
Waypoint: GC45KPR
Title: Osterkirmes Beuel
Tag: D15 T15 Small Tradi
----
ID: 522
Date: 27.09.2013
Waypoint: GCVZR8 OC234B
Title: Gotteshäuser Helenenkapelle
Tag: D15 T1 Micro Tradi recommended
----
ID: 523
Date: 28.09.2013
Waypoint: GC2VMD0
Title: Annaberger Bach - Mündung in den Rhein
Tag: D25 T2 Nano Tradi
----
ID: 524
Date: 29.09.2013
Waypoint: GC2E8E4
Title: Bonner Retter - Löscheinheit 43 -&gt; Lessenich
Tag: D15 T15 Micro Tradi
----
ID: 525
Date: 30.09.2013
Waypoint: GC40FG0
Title: Zauberhafter Adventsbazar
Tag: D15 T15 Small Tradi
----
ID: 526
Date: 30.09.2013
Waypoint: GC4J6H4
Title: Bandorfer Runde
Tag: D25 T25 Large Multi
----
ID: 527
Date: 01.10.2013
Waypoint: GC1ZG6N
Title: Keep Toming Back
Tag: D15 T2 Small Tradi
----
ID: 528
Date: 02.10.2013
Waypoint: GC337X6
Title: Alfterer Kreuze 22
Tag: D15 T1 Micro Tradi
----
ID: 529
Date: 02.10.2013
Waypoint: GC2R93G
Title: &#34;Beim Swisttaler GC Stammtisch&#34; - Beifangtradi!
Tag: D15 T15 Micro Tradi
----
ID: 530
Date: 02.10.2013
Waypoint: GC446DR
Title: &#34;O'zapft is&#34;- Tannen&#34;zapfen&#34;edition!
Tag: D15 T15 Micro Tradi
----
ID: 531
Date: 02.10.2013
Waypoint: GC2XHZ0
Title: Chicken Run 4 (Hochwasser)
Tag: D15 T15 Micro Tradi
----
ID: 532
Date: 02.10.2013
Waypoint: GC37W1T
Title: Ollis Monatsdose
Tag: D15 T15 Micro Tradi
----
ID: 533
Date: 02.10.2013
Waypoint: GC41MZK
Title: Der Goldene Saft
Tag: D1 T1 Nano Tradi
----
ID: 534
Date: 02.10.2013
Waypoint: GC315PP
Title: Schäfchenwiese
Tag: D15 T2 Micro Tradi
----
ID: 535
Date: 03.10.2013
Waypoint: GC4HMK8
Title: The Mountain of the Imperium
Tag: D25 T2 Micro Tradi
----
ID: 536
Date: 03.10.2013
Waypoint: GC4HHQH
Title: The Sideview of the Imperium
Tag: D15 T15 Micro Tradi
----
ID: 537
Date: 03.10.2013
Waypoint: GC4H2J0
Title: Der Weg zum Imperium
Tag: D15 T15 Micro Tradi
----
ID: 538
Date: 03.10.2013
Waypoint: GC4MHQ2
Title: Die Bahnstrecke zum Imperium
Tag: D15 T15 Nano Tradi
----
ID: 539
Date: 03.10.2013
Waypoint: GC4H026
Title: Das Imperium wächst...
Tag: D15 T15 Micro Tradi
----
ID: 540
Date: 03.10.2013
Waypoint: GC4H2AA
Title: The Imperium's Background
Tag: D15 T15 Nano Tradi
----
ID: 541
Date: 08.10.2013
Waypoint: GC4H327
Banner: jpg
Title: TB Hotel Fuderbach 1
Tag: D2 T3 Small Tradi
----
ID: 542
Date: 08.10.2013
Waypoint: GCZQQC OC2AE5
Title: Didn't find it - der Cache - Vol. 2 - Heiderhof
Tag: D1 T15 Regular Tradi
----
ID: 543
Date: 09.10.2013
Waypoint: GC2GFB7
Title: Häuser der Helfer: Rettungswache Rheinbach
Tag: D15 T15 Micro Multi
----
ID: 544
Date: 09.10.2013
Waypoint: GC2EXA1
Title: Rheinbach Nord 2
Tag: D15 T15 Regular Tradi
----
ID: 545
Date: 09.10.2013
Waypoint: GC4G7VH
Title: Der kleine See
Tag: D2 T2 Micro Tradi recommended
----
ID: 546
Date: 11.10.2013
Waypoint: GC4KEME
Title: If you go to San Francisco... - Meet &amp; Greet
nTF: 1
Tag: D1 T1 Event
----
ID: 547
Date: 12.10.2013
Waypoint: GC494W0
Title: Die älteste in der Stadt
Tag: D2 T2 Micro Mystery
----
ID: 548
Date: 13.10.2013
Waypoint: GC22ZCX
Title: The Deep Blue
Tag: D15 T3 Earth
----
ID: 549
Date: 13.10.2013
Waypoint: GC1B6J2 OC5C45
Title: P&amp;G #4
Tag: D15 T1 Micro Tradi
----
ID: 550
Date: 13.10.2013
Waypoint: GC2N98P
Title: Hennef: 100 Dörfer #69 Büllesfeld
Tag: D25 T25 Small Tradi
----
ID: 551
Date: 13.10.2013
Waypoint: GC2G85T
Title: Rote Tuer
Tag: D1 T15 Small Tradi
----
ID: 552
Date: 16.10.2013
Waypoint: GC38KAF
Title: Verstecketopf Beschusstest
Tag: D2 T2 Nano Tradi
----
ID: 553
Date: 16.10.2013
Waypoint: GC4F1R3
Title: Verstecketopf Aktennotiz
Tag: D25 T2 Micro Mystery
----
ID: 554
Date: 16.10.2013
Waypoint: GC425DB
Title: &#34;PECH&#34; gehabt
Tag: D15 T35 Micro Mystery
----
ID: 555
Date: 17.10.2013
Waypoint: GC4PH1Z
Title: Bonn - Rathaus
Tag: D15 T15 Micro Tradi
----
ID: 556
Date: 18.10.2013
Waypoint: GC4HHWM
Title: The recovery form the Imperium
Tag: D25 T2 Micro Tradi
----
ID: 557
Date: 19.10.2013
Waypoint: GC4ACQF
Title: Kunst am Wegesrand # 2
Tag: D25 T25 Micro Mystery
----
ID: 558
Date: 20.10.2013
Waypoint: GC4KFQC
Title: Von_Ost_nach_West
Tag: D2 T15 Small Tradi
----
ID: 559
Date: 21.10.2013
Waypoint: GC347VN
Title: Was wird denn hier gebaut?
Tag: D15 T15 Micro Tradi
----
ID: 560
Date: 22.10.2013
Waypoint: GC2XX9W
Title: Schools Out, Parken Verboten
Tag: D2 T1 Micro Tradi
----
ID: 561
Date: 24.10.2013
Waypoint: GC2ZTMX
Title: Alfterer Kreuze 04
Tag: D2 T15 Micro Tradi
----
ID: 562
Date: 25.10.2013
Waypoint: GC4NR65
Title: BDD - Bereitschaftsdienstdose
Tag: D15 T15 Micro Tradi
----
ID: 563
Date: 27.10.2013
Waypoint: GDBW-JUGA
Title: [Game 148 (Oktober 2013)], AW-Weidenbach
nTF: 1
Distance: 17.5
----
ID: 564
Date: 27.10.2013
Waypoint: GC3E7Q4
Title: Gotteshäuser Marien-Walfahrtskapelle Pützfeld
Tag: D15 T15 Micro Tradi recommended
----
ID: 565
Date: 27.10.2013
Waypoint: GC4PJHJ
Title: Ende der Eiszeit ⅯⅯⅩⅢ ☹
nTF: 0
Tag: D1 T1 Event
----
ID: 566
Date: 30.10.2013
Waypoint: GC4KK0H
Title: Faultier Heinz
Tag: D2 T2 Micro Mystery
----
ID: 567
Date: 31.10.2013
Waypoint: GC4FQYA
Title: TUS Germania Hersel - Erwartungen
Tag: D1 T15 Micro Tradi
----
ID: 568
Date: 01.11.2013
Waypoint: GDBX-JOYQ
Title: [Game 149 (November 2013)], SU-Sechtem
nTF: 1
Distance: 3.4
----
ID: 569
Date: 01.11.2013
Waypoint: GC3X4V9
Title: Machmaleibeidiemäh Sechtem 1
Tag: D1 T2 Micro Tradi
----
ID: 570
Date: 02.11.2013
Waypoint: GC4PGAT
Title: BASEBALL TP – No.4 – Erdkunde
Tag: D3 T1 Micro Tradi
----
ID: 571
Date: 03.11.2013
Waypoint: GC4R97Y
Title: Mitten in Bandorf
Tag: D1 T15 Micro Tradi
----
ID: 572
Date: 04.11.2013
Waypoint: GC1Y016
Title: Badminton in Bonn
Tag: D3 T1 Micro Mystery
----
ID: 573
Date: 05.11.2013
Waypoint: GC26VT0
Title: Grete's Memoiren
Tag: D1 T2 Micro Tradi
----
ID: 574
Date: 08.11.2013
Waypoint: GC2QR58
Title: Häuser der Helfer - Freiwillige Feuerwehr Siegburg
Tag: D15 T15 Micro Tradi
----
ID: 575
Date: 09.11.2013
Waypoint: GCP1YA
Title: Oberhausen HBF
Tag: D25 T1 Micro Tradi
----
ID: 576
Date: 10.11.2013
Waypoint: GC4164D
Title: 2. Oberhausener Praxiscache
Tag: D15 T15 Micro Tradi
----
ID: 577
Date: 11.11.2013
Waypoint: GC34FXA
Title: Gotteshäuschen Oberscheid
Tag: D2 T1 Micro Tradi
----
ID: 578
Date: 13.11.2013
Waypoint: GC4FTYV
Title: Der Apfel (2)
Tag: D25 T2 Micro Tradi
----
ID: 579
Date: 14.11.2013
Waypoint: GC4R6KD
Title: Die stinkende Angelegenheit
Tag: D2 T2 Micro Tradi
----
ID: 580
Date: 15.11.2013
Waypoint: GC36WXX
Title: Books-to-go
Tag: D15 T15 Other Tradi recommended
----
ID: 581
Date: 15.11.2013
Waypoint: GC3BAY0
Title: CHALLENGE: SCHNAPSZAHLEN
Tag: D5 T15 Micro Mystery Challenge
----
ID: 582
Date: 15.11.2013
Waypoint: GC4M8XG
Title: Willkommen in Gelsdorf
Tag: D2 T15 Nano Tradi
----
ID: 583
Date: 16.11.2013
Waypoint: GC4Q4N9
Title: Hexenhaus
Tag: D1 T2 Small Tradi recommended
----
ID: 584
Date: 17.11.2013
Waypoint: GC4A6EK
Title: Willkommen in RLP
Tag: D15 T15 Micro Tradi
----
ID: 585
Date: 17.11.2013
Waypoint: GC4R80T
Title: BAGO Kurpark
Tag: D2 T25 Small Tradi
----
ID: 586
Date: 18.11.2013
Waypoint: GC3YA5C
Title: Königreich Ückesdorf 5
Tag: D1 T15 Micro Tradi
----
ID: 587
Date: 19.11.2013
Waypoint: GC2RVGM
Title: Vorher - Nachher ?
Tag: D15 T1 Micro Mystery
----
ID: 588
Date: 20.11.2013
Waypoint: GC4QAAN
Title: A - M - P - E - L 1
Tag: D1 T1 Event
----
ID: 589
Date: 20.11.2013
Waypoint: GC1YN42
Title: Gotteshäuser St. Dionysius Ringen
Tag: D1 T15 Micro Tradi
----
ID: 590
Date: 20.11.2013
Waypoint: GC3772W
Title: Am Regenrückhaltebecken
Tag: D2 T2 Micro Tradi
----
ID: 591
Date: 21.11.2013
Waypoint: GC4HHQZ
Title: Sportplatz Oeverich-Niederich
Tag: D2 T25 Micro Tradi
----
ID: 592
Date: 22.11.2013
Waypoint: GC3AK6K
Title: Die kleine Mystery-Runde#1
Tag: D2 T1 Micro Mystery
----
ID: 593
Date: 23.11.2013
Waypoint: GC2X12X
Title: Am Steinbruch
Tag: D15 T2 Micro Tradi
----
ID: 594
Date: 24.11.2013
Waypoint: GC4RT47
Banner: png
Title: Mitten in Oeverich 1
Tag: D25 T2 Small Tradi
----
ID: 595
Date: 25.11.2013
Waypoint: GC4RT2Y
Title: Willkommen in Oeverich 1
Tag: D2 T2 Small Tradi
----
ID: 596
Date: 26.11.2013
Waypoint: GC1NMFY OC7B83
Title: Bonner Kunstwerke: Aufbr. Samenkorn mit Keimling
Tag: D15 T15 Micro Tradi
----
ID: 597
Date: 27.11.2013
Waypoint: GC383GG
Title: “Große Namen“ # 3
Tag: D3 T15 Micro Mystery
----
ID: 598
Date: 28.11.2013
Waypoint: GC3YA4Z
Title: Königreich Ückesdorf 3
Tag: D1 T15 Micro Tradi
----
ID: 599
Date: 29.11.2013
Waypoint: GC1QNRT OC848C
Title: Willkommen in... Oberwinter
Tag: D1 T1 Small Tradi
----
ID: 600
Date: 30.11.2013
Waypoint: GC4QJJR
Title: Bandorfs XXL TB Hotel (reloaded)
Tag: D1 T15 Large Tradi
----
ID: 601
Date: 01.12.2013
Waypoint: GC4PQVQ
Title: Grotte Römlinghoven
Tag: D15 T15 Micro Tradi recommended

Schönes Gotteshaus!
----
ID: 602
Date: 01.12.2013
Waypoint: GC4RRBV
Title: Willkommen in Ließem
Tag: D15 T25 Regular Tradi
----
ID: 603
Date: 02.12.2013
Waypoint: GC34CEN
Title: Am Lessenicher Bach #1
Tag: D15 T1 Small Tradi
----
ID: 604
Date: 03.12.2013
Waypoint: GC4NTNH
Title: Frankenbad rereloaded
Tag: D15 T15 Nano Tradi
----
ID: 605
Date: 04.12.2013
Waypoint: GC37WBF
Title: Der offene Bücherschrank BN-Duisdorf (reloaded)
Tag: D15 T2 Micro Tradi
----
ID: 606
Date: 05.12.2013
Waypoint: GC3FBHH
Title: Orthographie...
Tag: D15 T1 Nano Tradi
----
ID: 607
Date: 06.12.2013
Waypoint: GC4PGAM
Title: BASEBALL TP – No.1 – Sport und Vergnügen
Tag: D1 T15 Micro Tradi
----
ID: 608
Date: 07.12.2013
Waypoint: GCV20A OC1A06
Title: Dichter &amp; Denker #5 - Leibniz
Tag: D25 T1 Regular Mystery
----
ID: 609
Date: 07.12.2013
Waypoint: GC3WEWZ OCDEA5
Title: Blackbox
Tag: D25 T2 Small Tradi
----
ID: 610
Date: 07.12.2013
Waypoint: GC1AKJ0 OC53F5
Title: Das 13. Grab
Tag: D3 T1 Micro Mystery
----
ID: 611
Date: 07.12.2013
Waypoint: GC1BTE6 OC5962
Title: Gotteshaeuser: St_Elisabeth_Kirche_Bonn
Tag: D2 T1 Micro Multi
----
ID: 612
Date: 08.12.2013
Waypoint: GC1TN4W OC8614
Title: Die Schenkung
Tag: D25 T1 Small Mystery
----
ID: 613
Date: 08.12.2013
Waypoint: GC274QT
Title: Auf den Spuren der Wissenschaft: F. A. Kekulé
Tag: D35 T2 Micro Mystery

<pre>00:42⎜«Natureshadow» &#34;Success! Whoohoo! Yippee!
     ⎜    uh-huh, uh-huh! w00t! Yeah, baby!&#34;
00:42⎜«Natureshadow» Super gemacht, Vutral ;)!</pre>
----
ID: 614
Date: 08.12.2013
Waypoint: GC40M8J
Title: #2 Gewerbepark Remagen Süd ZEPPELIN
Tag: D25 T1 Small Tradi recommended
----
ID: 615
Date: 08.12.2013
Waypoint: GC40M8F
Title: #1 Gewerbepark Remagen Süd INFO
Tag: D2 T15 Micro Multi
----
ID: 616
Date: 08.12.2013
Waypoint: GC4ATMJ
Title: DVD Tausch-Cache reloaded (LP)
Tag: D1 T2 Regular Tradi recommended
----
ID: 617
Date: 08.12.2013
Waypoint: GC41WYK
Title: Die mysteriöse Dose
Tag: D1 T2 Micro Tradi
----
ID: 618
Date: 08.12.2013
Waypoint: GC40M8M
Title: #3 Gewerbepark Remagen Süd RUDI
Tag: D1 T2 Small Tradi
----
ID: 619
Date: 08.12.2013
Waypoint: GC40M8P
Title: #4 Gewerbepark Remagen Süd POLI
Tag: D15 T15 Micro Tradi
----
ID: 620
Date: 08.12.2013
Waypoint: GC40M8Q
Title: #5 Gewerbepark Remagen Süd MANHATTAN
Tag: D2 T2 Other Tradi
----
ID: 621
Date: 08.12.2013
Waypoint: GC40M8R
Title: #6 Gewerbepark Remagen Süd SPORTPLATZ
Tag: D1 T15 Micro Tradi
----
ID: 622
Date: 08.12.2013
Waypoint: GC40M8W
Title: #7 Gewerbepark Remagen Süd BONUS
Tag: D25 T3 Regular Mystery
----
ID: 623
Date: 08.12.2013
Waypoint: GC2H913 OCB4FB
Title: Wo sich Flüsse treffen
Tag: D2 T2 Earth

Tip: den Weg näher am Rhein nehmen, nicht den Trampelpfad…
----
ID: 624
Date: 08.12.2013
Waypoint: GC19GNZ
Title: Gotteshäuser St. Johannes Nepomuk Kripp
Tag: D15 T1 Small Tradi
----
ID: 625
Date: 08.12.2013
Waypoint: GC3XV3P
Title: DER BAHNDAMM
Tag: D2 T15 Micro Tradi
----
ID: 626
Date: 08.12.2013
Waypoint: GC1GJR2
Title: Denkmal Kettenhausen
Tag: D25 T15 Micro Tradi
----
ID: 627
Date: 08.12.2013
Waypoint: GDBY-JUQY
Title: [Game 150 (Dezember 2013)], AK-Busenhausen
nTF: 1
Distance: 2.7
----
ID: 628
Date: 08.12.2013
Waypoint: GC3NHJY
Title: Michelbacher Mühlgraben
Tag: D1 T15 Micro Tradi
----
ID: 629
Date: 09.12.2013
Waypoint: GC31T21
Title: Paulaner meets Humboldt
Tag: D25 T1 Micro Tradi recommended
----
ID: 630
Date: 10.12.2013
Waypoint: GC3Y11Z
Title: Geislarer Schleichwege 5
Tag: D15 T15 Nano Tradi
----
ID: 631
Date: 11.12.2013
Waypoint: GC4T929
Title: 9-10-11-12-13
Tag: D2 T2 Event
----
ID: 632
Date: 12.12.2013
Waypoint: GCVCFN
Title: Rappo, die Welt geht unter!
Tag: D1 T15 Regular Multi

Die armen… Tiere und andere Wesen hier.
----
ID: 633
Date: 12.12.2013
Waypoint: GC2CW3X
Title: A7 Rastplatz Kassel (Norden)
Tag: D1 T1 Micro Tradi
----
ID: 634
Date: 12.12.2013
Waypoint: GC17TK8
Title: A7 - Park &amp; Grab
Tag: D1 T15 Small Tradi
----
ID: 635
Date: 12.12.2013
Waypoint: GC42WZ8
Title: A38 - Galgenberg - gen Osten (MB13)
Tag: D15 T15 Small Tradi recommended
----
ID: 636
Date: 12.12.2013
Waypoint: GCY3VF
Title: A 38 Helmetal (Süd)
Tag: D1 T1 Micro Tradi
----
ID: 637
Date: 12.12.2013
Waypoint: GCMG88 OXMG88 OC62E7
Title: Lame Micro - A38 Fuchsaue Süd
Tag: D15 T2 Small Tradi
----
ID: 638
Date: 12.12.2013
Waypoint: GC40P9J
Title: Der Kannibale vom Sonnenberg
Tag: D2 T15 Other Tradi recommended nsfw

<strong>Warnung</strong>: Das Cachelisting ist nix für schwache Nerven!
Der Container ist allerdings auch so findbar, harmlos und genial.
----
ID: 639
Date: 13.12.2013
Waypoint: GC156F9
Title: Der Versteinerte Wald im Chemnitzer &#34;DAStiez&#34;
Tag: D1 T1 Earth
----
ID: 640
Date: 13.12.2013
Waypoint: GCY3VN
Title: A 38 Helmetal (Nord)
Tag: D15 T1 Micro Tradi
----
ID: 641
Date: 13.12.2013
Waypoint: GDBY-KAUC
Title: [Game 150 (Dezember 2013)], Deuna
nTF: 1
Distance: 24.3
----
ID: 642
Date: 13.12.2013
Waypoint: GC3ACGE
Banner: jpg Der “gehobene” Autobahn-Cache
Title: TB-Hotel &#34;Lüner Grund&#34;
Tag: D1 T1 Small Tradi
----
ID: 643
Date: 13.12.2013
Waypoint: GC1AMVB OC5606
Title: A44 - Pausencache West
Tag: D1 T15 Small Tradi
----
ID: 644
Date: 13.12.2013
Waypoint: GDBY-JUIJ
Title: [Game 150 (Dezember 2013)], K-Mülheim
nTF: 1
Distance: 51.3
----
ID: 645
Date: 14.12.2013
Waypoint: GC2G7YV
Title: sTaTisTik
Tag: D1 T1 Micro Tradi
----
ID: 646
Date: 15.12.2013
Waypoint: GC4DJJV
Title: ducktales
Tag: D3 T2 Regular Mystery
----
ID: 647
Date: 16.12.2013
Waypoint: GC4CHJZ
Title: Willkomen in Bölingen
Tag: D1 T15 Micro Tradi
----
ID: 648
Date: 17.12.2013
Waypoint: GC4PB2K
Title: Witterschlicker Gold
Tag: D15 T2 Earth
----
ID: 649
Date: 18.12.2013
Waypoint: GC315BR
Title: Heiliger Hugo
Tag: D1 T15 Nano Tradi
----
ID: 650
Date: 19.12.2013
Waypoint: GC2BNWR
Title: Häuser der Helfer – Feuerwehr Wachtberg #2
Tag: D2 T2 Micro Tradi
----
ID: 651
Date: 20.12.2013
Waypoint: GC1XD35
Title: Historisches Schmuckstück &#34;Holzlarer Mühle&#34;
Tag: D1 T1 Small Tradi
----
ID: 652
Date: 21.12.2013
Waypoint: GC3DEE8
Title: Holzlarer Eckbank
Tag: D1 T15 Nano Tradi
----
ID: 653
Date: 22.12.2013
Waypoint: GC3393J
Title: Rauschendorf - Kapelle
Tag: D15 T15 Micro Tradi
----
ID: 654
Date: 23.12.2013
Waypoint: GC26CT3
Title: Einsames Heiligenhäuschen
Tag: D1 T15 Micro Tradi
----
ID: 655
Date: 24.12.2013
Waypoint: GC38P26
Title: “Große Namen“ # 4
Tag: D25 T2 Micro Mystery
----
ID: 656
Date: 26.12.2013
Waypoint: GC4PGAX
Title: BASEBALL TP – No.6 – Kunst und Literatur
Tag: D1 T1 Micro Tradi
----
ID: 657
Date: 27.12.2013
Waypoint: GC4VA3H
Title: OpenStreetCache
Tag: D2 T15 Micro Tradi

Kein besonders schöner Cache, dafür auf’m Präsentierteller
und auch kein Bezug zur OSM.
----
ID: 658
Date: 28.12.2013
Waypoint: GC4NCFP
Title: Eichhörnchen gesucht!
Tag: D1 T15 Micro Tradi
----
ID: 659
Date: 28.12.2013
Waypoint: GC4N08J
Title: ClauS FriBe: Flusspferd gesucht!
Tag: D15 T15 Micro Tradi
----
ID: 660
Date: 28.12.2013
Waypoint: GC4H4TF
Title: Igel gesucht!
Tag: D15 T15 Micro Tradi
----
ID: 661
Date: 28.12.2013
Waypoint: GC4HNP4
Title: Elch gesucht!
Tag: D1 T15 Micro Tradi
----
ID: 662
Date: 28.12.2013
Waypoint: GC4K9VR
Title: Biene gesucht!
Tag: D15 T15 Micro Tradi
----
ID: 663
Date: 28.12.2013
Waypoint: GC4HNPZ
Title: Schildkröte gesucht!
Tag: D15 T15 Micro Tradi
----
ID: 664
Date: 28.12.2013
Waypoint: GC4R7XZ
Title: Eule gesucht!
Tag: D2 T2 Micro Tradi recommended
----
ID: 665
Date: 29.12.2013
Waypoint: GC2ZYVM
Title: Wachtberger Kreuze # 2
Tag: D15 T15 Micro Tradi
----
ID: 666
Date: 29.12.2013
Waypoint: GC2X13M
Title: Wiesen, Felder und Plantagen #1
Tag: D25 T15 Micro Tradi
----
ID: 667
Date: 29.12.2013
Waypoint: GC2X13Y
Title: Wiesen, Felder und Plantagen #2
Tag: D2 T15 Micro Tradi recommended
----
ID: 668
Date: 29.12.2013
Waypoint: GC2Z4RN
Title: Wiesen, Felder und Plantagen #3
Tag: D2 T15 Micro Tradi
----
ID: 669
Date: 29.12.2013
Waypoint: GC2X141
Title: Wiesen, Felder und Plantagen #4
Tag: D25 T15 Micro Tradi
----
ID: 670
Date: 29.12.2013
Waypoint: GC2X149
Title: Wiesen, Felder und Plantagen #5
Tag: D25 T3 Micro Tradi
----
ID: 671
Date: 29.12.2013
Waypoint: GC4VR1N
Title: An der Kuhweide (Reloaded)
Tag: D1 T15 Micro Tradi
----
ID: 672
Date: 30.12.2013
Waypoint: GC24VGE OCE644
Title: Berühmte Meteorologen
Tag: D2 T2 Small Mystery
----
ID: 673
Date: 31.12.2013
Waypoint: GC4Q9JY
Title: The Same Procedure As Every Year
Tag: D35 T35 Event
----
ID: 674
Date: 31.12.2013
Waypoint: GC3YMRT
Title: Ungesund
Tag: D1 T1 Micro Tradi
----
ID: 675
Date: 31.12.2013
Waypoint: GC2WKRE OCF72A
Title: Schauspielhalle
Tag: D15 T1 Micro Tradi
----
ID: 676
Date: 01.01.2014
Waypoint: GC45VXE
Title: Villa Camphausen (Nano)
Tag: D15 T2 Nano Tradi
----
ID: 677
Date: 01.01.2014
Waypoint: GC4TCQM
Title: Warten auf die Eiszeit
nTF: 3
Tag: D1 T1 Event
----
ID: 678
Date: 02.01.2014
Waypoint: GC30M8Y
Title: Tradi am Bach (Oberbachem)
Tag: D15 T25 Micro Tradi
----
ID: 679
Date: 02.01.2014
Waypoint: GC2WGB1
Title: Autoschreck
Tag: D2 T25 Micro Tradi
----
ID: 680
Date: 03.01.2014
Waypoint: GC4PGAW
Title: BASEBALL TP – No.5 – Unterhaltung
Tag: D2 T25 Micro Tradi
----
ID: 681
Date: 04.01.2014
Waypoint: GC4R1D2
Title: Einfach mal entspannen
Tag: D2 T1 Nano Tradi
----
ID: 682
Date: 06.01.2014
Waypoint: GC4V90C
Title: Standort506
Tag: D2 T2 Micro Tradi
----
ID: 683
Date: 06.01.2014
Waypoint: GC4F4BB
Title: Heilige drei Könige
Tag: D1 T15 Micro Tradi
----
ID: 684
Date: 07.01.2014
Waypoint: GC4Q39D
Title: Dollendorfer Hardt: Mauer
Tag: D25 T15 Small Tradi
----
ID: 685
Date: 08.01.2014
Waypoint: GC4VYEY
Title: Waiting in Vain
Tag: D15 T3 Small Tradi
----
ID: 686
Date: 09.01.2014
Waypoint: GC476K5
Title: Uni Campus Poppelsdorf in Spe
Tag: D15 T1 Small Tradi
----
ID: 687
Date: 09.01.2014
Waypoint: GC3VAJX
Title: Reutersiedlung
Tag: D15 T15 Micro Tradi
----
ID: 688
Date: 10.01.2014
Waypoint: GC4VTAV
Title: 10 Jahre EarthCache - Flammersfeld feiert (#27)
Tag: D1 T1 Event recommended
----
ID: 689
Date: 10.01.2014
Waypoint: GC4P3FG
Title: Schön durchhalten...#1/6
Tag: D15 T25 Small Tradi
----
ID: 690
Date: 11.01.2014
Waypoint: GC1TYG5 OX1TYG5
Title: Der Balzar von Flammersfeld
Tag: D1 T1 Nano Tradi
----
ID: 691
Date: 12.01.2014
Waypoint: GC3BNT7
Title: Schöne Aussicht
Tag: D15 T1 Micro Tradi
----
ID: 692
Date: 13.01.2014
Waypoint: GC2GEDR
Title: BaGoCity
Tag: D25 T15 Micro Multi
----
ID: 693
Date: 14.01.2014
Waypoint: GC1V5DY
Title: Willkommen in... Pössem ;-))))
Tag: D1 T1 Micro Tradi
----
ID: 694
Date: 15.01.2014
Waypoint: GC44KA8
Title: 365 Tage &#34;O(h) Tannenbaum...&#34;
Tag: D15 T15 Micro Tradi
----
ID: 695
Date: 18.01.2014
Waypoint: GC2B11A
Title: Glockenspiel und Epitaphien
Tag: D2 T15 Regular Mystery
----
ID: 696
Date: 18.01.2014
Waypoint: GC37R1G
Title: Teo Otto Theater
Tag: D15 T1 Micro Tradi
----
ID: 697
Date: 18.01.2014
Waypoint: GC4T7AW
Title: Wermelskirchen - Wappen (1)
Tag: D15 T15 Small Tradi
----
ID: 698
Date: 19.01.2014
Waypoint: GCXCYD OC2251
Title: 5208xxx
Tag: D3 T2 Regular Mystery
----
ID: 699
Date: 20.01.2014
Waypoint: GC48YQF
Title: Petling im Baum
Tag: D25 T15 Micro Tradi
----
ID: 700
Date: 22.01.2014
Waypoint: GC3V40F
Title: Bei Rudolf Herzog
Tag: D1 T15 Micro Tradi
----
ID: 701
Date: 02.01.2014
Waypoint: GC35CB1
Title: Verstecketopf Kreise II
nTF: L
Tag: D35 T25 Micro Multi
----
ID: 702
Date: 23.01.2014
Waypoint: GC4X7R4
Title: Der Cowboy
Tag: D1 T1 Small Tradi

War ja klar, daß gecko2 den doch noch macht… „ich bin müde“ my Foot…
----
ID: 703
Date: 24.01.2014
Waypoint: GC17ZC0 OC5C1B
Title: Hermann Bleibtreu
Tag: D2 T15 Micro Tradi
----
ID: 704
Date: 26.01.2014
Waypoint: GC4W2RP
Title: ⸘Immer noch keine Eiszeit‽
nTF: 0
Tag: D45 T15 Event
----
ID: 705
Date: 26.01.2014
Waypoint: GC4XJMP
Title: Schwimmbad Longenburg
nTF: 0
Tag: D2 T15 Micro Tradi
----
ID: 706
Date: 26.01.2014
Waypoint: GC47WW6
Title: Der Dienstweg
Tag: D15 T15 Micro Tradi
----
ID: 707
Date: 28.01.2014
Waypoint: GC37W20
Title: Alfterer Kreuze 25
Tag: D1 T1 Micro Tradi
----
ID: 708
Date: 29.01.2014
Waypoint: GC4WC0C
Title: FCSB-Schüler-Cache No.1
nTF: 2
Tag: D1 T1 Small Tradi recommended
----
ID: 709
Date: 30.01.2014
Waypoint: GC3BR3Y
Title: Kreuz am Wegesrand # 1
Tag: D2 T2 Micro Tradi
----
ID: 710
Date: 31.01.2014
Waypoint: GC4T5DQ
Title: TB Hotel (halb/halb) &#34;&#34;&#34;&#34;&#34;&#34;&#34;&#34;Alter Reifen&#34;&#34;&#34;&#34;&#34;&#34;&#34;&#34;
Tag: D2 T25 Regular Tradi
----
ID: 711
Date: 01.02.2014
Waypoint: GC4V7ZQ OC10510
Title: FOSDEM 2014 Meetup (aka Where's that ULB cache?)
Tag: D2 T2 Event
----
ID: 712
Date: 01.02.2014
Waypoint: GC1Z4RQ
Title: ULB - Campus du Solbosch
Tag: D2 T2 Regular Multi
----
ID: 713
Date: 01.02.2014
Waypoint: GC3VJ9P
Title: XL Musée des enfants
Tag: D15 T1 Micro Tradi
----
ID: 714
Date: 01.02.2014
Waypoint: GC4T40K
Title: XL Schuiten's Ark
Tag: D2 T15 Nano Tradi recommended
----
ID: 715
Date: 01.02.2014
Waypoint: GC4J0JT
Title: XL - La Trinité
Tag: D1 T15 Small Tradi recommended
----
ID: 716
Date: 02.02.2014
Waypoint: GC2MFNV
Title: Parc l'Abbe Froidure
Tag: D25 T2 Small Tradi recommended
----
ID: 717
Date: 04.02.2014
Waypoint: https://labs.geocaching.com/Adventures/Details/fe30453c-7418-4416-a2fa-c543810ab8f8
Title: Mach mal Mirffee!
nTF: 1
Tag: Lab
----
ID: 718
Date: 04.02.2014
Waypoint: GC1FE4J
Title: Astronomie: Zeitberechnung
Tag: D25 T1 Micro Mystery
----
ID: 719
Date: 05.02.2014
Waypoint: GC1TGX7
Title: Bw&amp;I Kick-Off 2009
Tag: D15 T15 Micro Tradi
----
ID: 720
Date: 07.02.2014
Waypoint: GC4PGAQ
Title: BASEBALL TP – No.2 – Wissenschaft und Technik
Tag: D1 T15 Micro Tradi
----
ID: 721
Date: 08.02.2014
Waypoint: GC27RPP
Title: Bouleplatz
Tag: D15 T15 Small Multi
----
ID: 722
Date: 08.02.2014
Waypoint: GC16M0G OC470B
Title: BonnBeuel Heimatmuseum
Tag: D1 T15 Micro Tradi
----
ID: 723
Date: 10.02.2014
Waypoint: GC4DTTJ
Title: Flitzer_Blitzer
Tag: D15 T25 Micro Tradi
----
ID: 724
Date: 11.02.2014
Waypoint: GC4X6MH
Title: Bonner Kunstwerke: What if?
Tag: D15 T1 Nano Tradi recommended
----
ID: 725
Date: 12.02.2014
Waypoint: GC4YF7K
Title: B257 Blitzgefahr
nTF: 4
Tag: D1 T1 Small Tradi
----
ID: 726
Date: 12.02.2014
Waypoint: GC32NMY
Title: Lourdes / Eifel
Tag: D2 T15 Small Tradi recommended
----
ID: 727
Date: 13.02.2014
Waypoint: GC4WHAK
Title: A - M - P - E - L 2
nTF: 1
Tag: D1 T1 Event
----
ID: 728
Date: 14.02.2014
Waypoint: GC35BNG
Title: Wachtberger Kreuze # 15
Tag: D15 T15 Micro Tradi
----
ID: 729
Date: 14.02.2014
Waypoint: GC3C1DK
Title: Spontanes Kreuz am Feld
Tag: D4 T15 Micro Mystery
----
ID: 730
Date: 15.02.2014
Waypoint: GC3DRGY
Title: Kinderleicht!
Tag: D4 T15 Micro Mystery
----
ID: 731
Date: 16.02.2014
Waypoint: GC187BM
Title: Das Rätsel des Grafen
Tag: D3 T15 Regular Mystery
----
ID: 732
Date: 16.02.2014
Waypoint: GC2DE9V
Title: Über die Insel Grafenwerth
Tag: D2 T2 Micro Mystery
----
ID: 733
Date: 16.02.2014
Waypoint: GC1JTRB OC98BB
Title: Insel Grafenwerth
Tag: D2 T15 Micro Tradi
----
ID: 734
Date: 16.02.2014
Waypoint: GC2DE6R
Title: Rheinfaehre Rolandseck
Tag: D1 T1 Small Tradi recommended
----
ID: 735
Date: 18.02.2014
Waypoint: GC4RR87
Title: Tor zum Ennert
Tag: D15 T1 Small Tradi
----
ID: 736
Date: 19.02.2014
Waypoint: GC2XX34
Title: Häuser der Helfer: GVP Bonn - reloaded
Tag: D15 T1 Micro Tradi
----
ID: 737
Date: 20.02.2014
Waypoint: GC1YQYJ
Title: Der Heilige NanoGral
Tag: D15 T1 Micro Tradi
----
ID: 738
Date: 21.02.2014
Waypoint: GC4PQ3K
Title: Strücher Lore
Tag: D15 T15 Small Tradi
----
ID: 739
Date: 23.02.2014
Waypoint: GC29V1X
Title: Am Brunnen
Tag: D1 T15 Micro Tradi
----
ID: 740
Date: 24.02.2014
Waypoint: GC4YMQ1
Title: Steinklotz
Tag: D15 T15 Micro Tradi
----
ID: 741
Date: 25.02.2014
Waypoint: GC4Z2Q2
Title: Hey, hey Wickie
Tag: D2 T2 Small Tradi
----
ID: 742
Date: 25.02.2014
Waypoint: GC4PGAR
Title: BASEBALL TP – No.3 – Geschichte
Tag: D15 T15 Micro Tradi
----
ID: 743
Date: 26.02.2014
Waypoint: GC4YHX1
Title: Große Namen # 7 (Hotel für Reisende)
Tag: D2 T2 Small Tradi
----
ID: 744
Date: 27.02.2014
Waypoint: GC2PGKF
Title: Sportpark NORD Bonn
Tag: D2 T15 Micro Tradi
----
ID: 745
Date: 25.02.2014
Waypoint: https://labs.geocaching.com/Adventures/Details/b9b2a933-c4fa-4f29-aed4-1d1355318d78
Title: Challenge: Caching
nTF: 0
Tag: Lab Challenge
----
ID: 746
Date: 28.02.2014
Waypoint: GC40W3X
Title: Bonner PETlinge #3
Tag: D15 T2 Micro Tradi
----
ID: 747
Date: 01.03.2014
Waypoint: GC3DVG6
Title: Aussicht auf den Drachen
Tag: D25 T4 Micro Tradi
----
ID: 748
Date: 03.03.2014
Waypoint: GC4X9KD
Title: Leddekopp
Tag: D1 T1 Micro Tradi
----
ID: 749
Date: 04.03.2014
Waypoint: GC4QGFF
Title: Die schnelle Nummer
Tag: D15 T15 Micro Tradi
----
ID: 750
Date: 04.03.2014
Waypoint: GC4CJ3B
Title: Können Birnen glühen?
Tag: D2 T2 Micro Tradi recommended exceptional
----
ID: 751
Date: 05.03.2014
Waypoint: GC1X4KQ
Title: Der verbotene Weg
Tag: D1 T15 Regular Multi
----
ID: 752
Date: 05.03.2014
Waypoint: GC1PHJR
Title: Rundum Fernsicht
Tag: D2 T2 Small Multi
----
ID: 753
Date: 05.03.2014
Waypoint: GC4630F
Title: Herzlichen Glückwunsch!
Tag: D15 T15 Small Tradi
----
ID: 754
Date: 06.03.2014
Waypoint: GC4GF1Q
Title: Die Musikbox
Tag: D15 T25 Large Tradi
----
ID: 755
Date: 06.03.2014
Waypoint: GC3HGG6
Title: Thomas Mulden
Tag: D2 T3 Small Tradi
----
ID: 756
Date: 07.03.2014
Waypoint: GC4R2TY
Title: Beginn der Eiszeit
nTF: 2
Tag: D1 T1 Event
----
ID: 757
Date: 07.03.2014
Waypoint: GC2X14C
Title: Wiesen, Felder und Plantagen #6
Tag: D2 T15 Micro Tradi
----
ID: 758
Date: 07.03.2014
Waypoint: GC2X14Q
Title: Wiesen, Felder und Plantagen - Bonus
Tag: D2 T3 Micro Mystery
----
ID: 759
Date: 08.03.2014
Waypoint: GC2HJ0N
Title: Big brother is watching you...
Tag: D2 T2 Micro Tradi
----
ID: 760
Date: 08.03.2014
Waypoint: GC3Z02Y OX3Z02Y
Title: Der Scheißcache
Tag: D2 T1 Micro Tradi
----
ID: 761
Date: 09.03.2014
Waypoint: GC4WNRJ
Title: Das Herrschaftsgebiet von Röttgen 8
Tag: D15 T15 Small Tradi
----
ID: 762
Date: 10.03.2014
Waypoint: GC4ZXJY
Title: An der Godesburg - Christines Geburtstagscache
nTF: 2
Tag: D15 T2 Small Tradi
----
ID: 763
Date: 10.03.2014
Waypoint: GC4ZXGR
Title: Gotteshäuser: CLW Bonn
nTF: 4
Tag: D15 T15 Nano Tradi
----
ID: 764
Date: 11.03.2014
Waypoint: GC33X0M OCD382
Title: Am Bonner Graben
Tag: D15 T15 Micro Tradi
----
ID: 765
Date: 12.03.2014
Waypoint: GC4YFR2
Title: Lannesdorfer Pömpche
Tag: D15 T15 Small Tradi
----
ID: 766
Date: 12.03.2014
Waypoint: GC3TTG0
Title: Verstecketopf Abschlusstest
Tag: D35 T35 Small Multi
----
ID: 767
Date: 12.03.2014
Waypoint: CC7QX
Title: ScottO's 30 day Challenge!
Tag: MC0 Locationless Challenge
----
ID: 768
Date: 14.03.2014
Waypoint: GC1WJN2
Title: Trasse des Werkzeugs - Güterwagen
Tag: D1 T2 Small Tradi
----
ID: 769
Date: 15.03.2014
Waypoint: GC24A2B
Title: Chemnitzer Brückenbauwerke - Der Pfortensteg
Tag: D25 T25 Micro Tradi
----
ID: 770
Date: 20.03.2014
Waypoint: GC2QFQJ
Title: Sportplatz des FC Rot-Weiss Lessenich
Tag: D15 T15 Micro Multi
----
ID: 771
Date: 21.03.2014
Waypoint: GC4V913
Title: O-rena
Tag: D2 T2 Micro Tradi
----
ID: 772
Date: 22.03.2014
Waypoint: GC21QJF
Title: Gitter 5308 552
Tag: D1 T15 Micro Tradi
----
ID: 773
Date: 22.03.2014
Waypoint: GC28Y9M
Title: goldbroilers MIST
Tag: D15 T2 Small Multi recommended
----
ID: 774
Date: 22.03.2014
Waypoint: GC4BWQT
Title: Vorsicht bissiger Rentner
Tag: D25 T1 Small Tradi recommended exceptional

Aufwendig gemacht und verdammt schön ausgestaltet.
Auf jeden Fall einen Besuch wert – und als Dreingabe
kriegt man, unter Benutzung einer 9V Blockbatterie,
den Code für GC4M90G dazu.
----
ID: 775
Date: 22.03.2014
Waypoint: GC4TVGR
Title: +1#1
Tag: D2 T2 Micro Tradi
----
ID: 776
Date: 22.03.2014
Waypoint: GC4M90G
Banner: jpg
Title: Beach TB Hotel GBH
Tag: D1 T1 Large Tradi recommended exceptional

Die Beschallung war schon etwas übertrieben ☺ aber dieser Cache
ist jeden seiner Favoritenpunkte wert.
----
ID: 777
Date: 22.03.2014
Waypoint: GC4GE2P
Title: &#34;Michaelkapelle&#34;
Tag: D3 T15 Micro Tradi

Und das nennt man hier eine Kapelle? Okay… aber gut.
----
ID: 778
Date: 22.03.2014
Waypoint: GC4D3EX
Title: Im Brooch #3
Tag: D2 T25 Micro Tradi

Recht nahe an der Bahn. Aber wenn die Pänz hier uch spelle…
----
ID: 779
Date: 22.03.2014
Waypoint: GC37W1Z
Title: RSK0004 - Rhein-Sieg-Kreuze
Tag: D1 T1 Micro Tradi

Im zweiten Anlauf endlich, Segamaster sei dank, gefunden.
----
ID: 780
Date: 22.03.2014
Waypoint: GC3NX8H
Title: RSK0003 - Rhein-Sieg-Kreuze reloaded
Tag: D15 T1 Micro Multi

Schneller Fund
----
ID: 781
Date: 23.03.2014
Waypoint: GC21704
Title: Das Schlupfloch der Piraten
Tag: D1 T25 Micro Tradi recommended
----
ID: 782
Date: 25.03.2014
Waypoint: GC4EF6J
Title: Sonnenbank
Tag: D15 T15 Micro Tradi
----
ID: 783
Date: 26.03.2014
Waypoint: GC2X12P
Title: Wachtberger Kreuze # 10
Tag: D15 T3 Micro Tradi
----
ID: 784
Date: 29.03.2014
Waypoint: GC4CXDA
Title: Villa Kunterbunt
Tag: D15 T1 Micro Tradi
----
ID: 785
Date: 29.03.2014
Waypoint: GC3DEF0
Banner: jpg Smørrebrød: Rezept gefunden
Title: „Smørrebrød“ oder „Das Lieblingsrezept“
Tag: D25 T25 Large Multi recommended
----
ID: 786
Date: 30.03.2014
Waypoint: GC18QR6
Title: Im heiligen Stumpf
Tag: D2 T15 Regular Multi
----
ID: 787
Date: 31.03.2014
Waypoint: GC4Z6AK
Title: maker madness (lunchbreak / Mittagspause)
Tag: D2 T1 Event
----
ID: 788
Date: 01.04.2014
Waypoint: GC3R0HE
Title: Verstecketopf Nummer
Tag: D25 T1 Micro Mystery
----
ID: 789
Date: 01.04.2014
Waypoint: GC3TTF4
Title: Verstecketopf lt. Anweisung
Tag: D4 T25 Small Mystery
----
ID: 790
Date: 02.04.2014
Waypoint: GC1XHFY
Title: Der Waldmeister
Tag: D15 T15 Micro Tradi
----
ID: 791
Date: 03.04.2014
Waypoint: GC260J4
Title: Staufrei in 17 Minuten nach Bonn
Tag: D1 T1 Micro Tradi
----
ID: 792
Date: 03.04.2014
Waypoint: GC37W0H
Title: RSK0001 - Rhein-Sieg-Kreuze
Tag: D15 T1 Micro Tradi
----
ID: 793
Date: 04.04.2014
Waypoint: GC48F7C
Title: Essener Bücherschrank
Tag: D15 T1 Large Tradi
----
ID: 794
Date: 04.04.2014
Waypoint: GC3C8Y3
Title: Ruhrbistum
Tag: D2 T1 Micro Tradi
----
ID: 795
Date: 05.04.2014
Waypoint: GC4H3J0
Title: Hauptschlagader
Tag: D25 T1 Small Tradi
----
ID: 796
Date: 05.04.2014
Waypoint: GC42GV3
Title: Wendemöglichkeit
Tag: D15 T2 Micro Tradi
----
ID: 797
Date: 07.04.2014
Waypoint: GC2P3RN
Title: Willkommen in... Bad Neuenahr #2
Tag: D1 T15 Micro Tradi
----
ID: 798
Date: 07.04.2014
Waypoint: GC34H9N
Title: Der Held vom Erdbeerfeld
Tag: D2 T2 Micro Tradi
----
ID: 799
Date: 08.04.2014
Waypoint: GC50XFW
Title: Schleichweg zwischen Baumärkten
Tag: D15 T2 Small Tradi recommended
----
ID: 800
Date: 08.04.2014
Waypoint: GC42KR1
Title: Schleichwege in Oedekoven 1
Tag: D1 T15 Micro Tradi
----
ID: 801
Date: 10.04.2014
Waypoint: GC501AG
Title: Meet Team Ostschweiz
Tag: D1 T15 Event
----
ID: 802
Date: 10.04.2014
Waypoint: GC4WYFD
Title: Bonner Vogelperspektive
Tag: D3 T1 Small Mystery
----
ID: 803
Date: 11.04.2014
Waypoint: GC48NN6
Title: Kirchen &amp; Kapellen - Antoniuskapelle
Tag: D15 T1 Micro Multi
----
ID: 804
Date: 11.04.2014
Waypoint: GC4CKJ7
Title: Kirchen &amp; Kapellen - St.Jakobus
Tag: D2 T15 Micro Multi
----
ID: 805
Date: 13.04.2014
Waypoint: GC4DCXA
Banner: jpg
Title: Mir stinkts...
Tag: D1 T1 Micro Tradi
----
ID: 806
Date: 13.04.2014
Waypoint: GC3088X
Title: Gotteshäuser: St. Sebastianus Bad Bodendorf
Tag: D2 T15 Micro Tradi
----
ID: 807
Date: 13.04.2014
Waypoint: GC1V441 OC86E7
Title: Willkommen in... Bad Bodendorf
Tag: D3 T15 Micro Tradi
----
ID: 808
Date: 13.04.2014
Waypoint: GC14E53 OC3BF6
Title: Gotteshäuser – Ehrendenkmal Bad Bodendorf
Tag: D1 T1 Small Multi
----
ID: 809
Date: 13.04.2014
Waypoint: GC3DRFK
Title: Thermalbad Bodendorf
Tag: D2 T3 Micro Tradi
----
ID: 810
Date: 13.04.2014
Waypoint: GC48Y6N
Banner: jpg
Title: Die Notiz auf dem Küchentisch...
Tag: D2 T15 Small Multi recommended exceptional

Nerviges Final, aber super gemacht und… mitreißend ☺
----
ID: 811
Date: 13.04.2014
Waypoint: GC3CXKH
Title: Willkommen in... Bad Bodendorf II
Tag: D15 T25 Micro Tradi
----
ID: 812
Date: 13.04.2014
Waypoint: GC350YM
Title: Am Deutschem Eck, aber nicht in Koblenz
Tag: D2 T15 Micro Tradi
----
ID: 813
Date: 13.04.2014
Waypoint: GC51709
Title: Rheinhöhenfriedhof Lightversion - Reloaded
Tag: D2 T3 Micro Multi
----
ID: 814
Date: 15.04.2014
Waypoint: GC4ZKGN
Title: Wilkommen in Bandorf
Tag: D1 T15 Micro Tradi
----
ID: 815
Date: 15.04.2014
Waypoint: GC4FWTC
Title: Türme von Hanoi #1
Tag: D2 T2 Small Wherigo_Hybrid
----
ID: 816
Date: 15.04.2014
Waypoint: GC3B64V
Title: Spontan#1
Tag: D2 T35 Micro Tradi
----
ID: 817
Date: 15.04.2014
Waypoint: GC41PF9
Title: Kirchen &amp; Kapellen - St. Scholastika
Tag: D1 T15 Micro Multi
----
ID: 818
Date: 15.04.2014
Waypoint: http://www.wherigo.com/cartridge/details.aspx?CGUID=fea0214b-8c94-4757-ba02-a76b3c66b6a5
Title: Turmbau zu Hanoi
Tag: Wherigo_Cartridge
----
ID: 819
Date: 16.04.2014
Waypoint: GC324G5 OCCF29
Title: Das &#34;Polengrab&#34; - reloaded
Tag: D15 T15 Small Tradi
----
ID: 820
Date: 16.04.2014
Waypoint: GC4FWTE
Title: Türme von Hanoi #2
Tag: D3 T25 Small Wherigo_Hybrid
----
ID: 821
Date: 16.04.2014
Waypoint: GC4FX1R
Title: Türme von Hanoi # Bonus
Tag: D35 T45 Small Mystery
----
ID: 822
Date: 17.04.2014
Waypoint: GC50JNE
Title: Dönerstag 2014 - Bonn
Tag: D15 T15 Event
----
ID: 823
Date: 17.04.2014
Waypoint: GC46TBE
Title: a safe place
Tag: D4 T1 Micro Tradi
----
ID: 824
Date: 19.04.2014
Waypoint: GC4NC2J
Title: Hotte`s kleine Serie Der Petling &#34;O&#34; Meter
Tag: D25 T15 Other Tradi recommended exceptional
----
ID: 825
Date: 19.04.2014
Waypoint: GC4CVC0
Banner: png
Title: Auf der Suche nach dem verlorenen Henkelpott
Tag: D3 T3 Large Multi recommended exceptional
----
ID: 826
Date: 19.04.2014
Waypoint: GC43VM8
Banner: jpg
Title: Der &#34;08/15&#34; Cache
Tag: D35 T2 Large Multi exceptional
----
ID: 827
Date: 19.04.2014
Waypoint: GC3ANNG
Title: Das &#34;blaue&#34; Wunder... der Bonus
Tag: D25 T15 Regular Mystery
----
ID: 828
Date: 23.04.2014
Waypoint: GC18DV3
Title: Wissenschaftsfiguren
Tag: D3 T1 Other Mystery exceptional
----
ID: 829
Date: 27.04.2014
Waypoint: GC4RC2N
Title: Die Weinpresse
Tag: D3 T15 Micro Tradi
----
ID: 830
Date: 27.04.2014
Waypoint: GC37W28
Title: Alfterer Kreuze 28
Tag: D1 T1 Micro Tradi
----
ID: 831
Date: 22.04.2014
Waypoint: GC53J4Q
Title: Kleine Runde durchs Messdorfer Feld 2
nTF: 2
Tag: D15 T15 Small Tradi

vormals: (unpublizierter Cache im Meßdorfer Feld)
----
ID: 832
Date: 28.04.2014
Waypoint: OC10D52
Title: Willkommen in… Duisdorf
nTF: 1
Tag: D1 T2 Micro Tradi

vormals: (unpublizierter Cache von Nik bei tarent)
----
ID: 833
Date: 29.04.2014
Waypoint: GC4XRPD
Title: Da war doch mal was...
Tag: D2 T2 Nano Tradi
----
ID: 834
Date: 29.04.2014
Waypoint: GC4M9NK
Title: Haus der Helfer: Oberdollendorfer Feuerpatschen
Tag: D15 T15 Micro Tradi
----
ID: 835
Date: 30.04.2014
Waypoint: GC4863E
Title: LP - Kappe2
Tag: D15 T2 Micro Multi

Hier wäre eher T3½ angesagt, im Moment…
----
ID: 836
Date: 30.04.2014
Waypoint: GC2CG80
Title: Wachtberger Kreuze 6
Tag: D15 T15 Micro Tradi
----
ID: 837
Date: 01.05.2014
Waypoint: GC52VB7
Title: Der Winter ist vorüber ⅯⅯⅩⅣ
nTF: 0
Tag: D1 T1 Event
----
ID: 838
Date: 01.05.2014
Waypoint: GC37DBD
Title: Röbel Fröbel
Tag: D3 T35 Small Tradi
----
ID: 839
Date: 02.05.2014
Waypoint: GC50XGE
Title: Der kleine Drachenfels
Tag: D1 T15 Small Tradi
----
ID: 840
Date: 02.05.2014
Waypoint: GC50XN8
Title: An der Ovalbahn
Tag: D15 T1 Small Tradi
----
ID: 841
Date: 02.05.2014
Waypoint: GC1WD4P OC8B28
Title: Judas Thaddäus in Alfter
Tag: D1 T15 Micro Tradi
----
ID: 842
Date: 04.05.2014
Waypoint: GC4W612
Title: Neubaugebiet Ließem
Tag: D15 T15 Micro Multi
----
ID: 843
Date: 04.05.2014
Waypoint: GC4R08D
Title: G.G.Hardy's Vergessene Orte - Die Lorenbahn
Tag: D3 T3 Large Multi recommended
----
ID: 844
Date: 04.05.2014
Waypoint: GC3YC3Z
Title: Siebengebirgspanorama
Tag: D2 T3 Small Tradi
----
ID: 845
Date: 05.05.2014
Waypoint: GC53F6K
Title: Der Baum - Noahs Erster
Tag: D15 T2 Small Tradi
----
ID: 846
Date: 05.05.2014
Waypoint: GC52H99
Title: Wiesen, Felder und Plantagen #4 Reloaded
Tag: D15 T15 Micro Tradi
----
ID: 847
Date: 10.05.2014
Waypoint: GC532CV
Title: Schatzsucher sind kreativ und (er-)finderisch
Tag: D1 T15 Event
----
ID: 848
Date: 10.05.2014
Waypoint: GC515YT
Title: Ich trink nur noch schnell meinen Kaffee aus ...
Tag: D1 T1 Small Tradi
----
ID: 849
Date: 14.05.2014
Waypoint: GC29R5W
Title: Heiligenhäuschen Fritzdorf
Tag: D1 T15 Small Tradi
----
ID: 850
Date: 14.05.2014
Waypoint: GC4VN4T
Title: 2014
Tag: D15 T15 Regular Tradi recommended
----
ID: 851
Date: 15.05.2014
Waypoint: GC4WNR1
Title: Das Herrschaftsgebiet von Röttgen 4
Tag: D15 T15 Micro Tradi
----
ID: 852
Date: 15.05.2014
Waypoint: GC4WNR6
Title: Das Herrschaftsgebiet von Röttgen 5
Tag: D15 T15 Micro Tradi
----
ID: 853
Date: 16.05.2014
Waypoint: GC4WNRQ
Title: Das Herrschaftsgebiet von Röttgen 10
Tag: D15 T15 Micro Tradi

Dreist! Zu dreist eigentlich.
----
ID: 854
Date: 16.05.2014
Waypoint: GC4WNQ9
Title: Das Herrschaftsgebiet von Röttgen 1
Tag: D1 T15 Micro Tradi

Eigentlich eher D2½ ob der Schwierigkeit, dies ungesehen zu tun.
----
ID: 855
Date: 17.05.2014
Waypoint: GC4ZQ4V
Title: 10 Jahre Bonn grillt (2014)
Tag: D1 T1 Other Event recommended exceptional
----
ID: 856
Date: 17.05.2014
Waypoint: GC42C73 OCF72B
Title: Nächster Halt: Limperich
Tag: D15 T1 Micro Tradi
----
ID: 857
Date: 18.05.2014
Waypoint: GC3WGCV
Title: Buntes Leben im lichten Wald...(Mini-Multi)
Tag: D15 T25 Micro Multi
----
ID: 858
Date: 18.05.2014
Waypoint: GC37N35
Title: Bullerbü
Tag: D15 T1 Regular Multi
----
ID: 859
Date: 19.05.2014
Waypoint: GC4ACW2
Title: Lehrpfad Obstbau
Tag: D2 T25 Small Multi
With: MM
----
ID: 860
Date: 20.05.2014
Waypoint: GC2NWM6
Title: 7239343
Tag: D35 T4 Nano Mystery
----
ID: 861
Date: 20.05.2014
Waypoint: GC3RV42
Title: HICOG Plittersdorf
Tag: D2 T15 Regular Multi
----
ID: 862
Date: 20.05.2014
Waypoint: GC28Y99
Title: Bonn Cachepitals
Tag: D15 T15 Micro Mystery
----
ID: 863
Date: 20.05.2014
Waypoint: GC37NV3
Title: Lucky &#34;Luke&#34;
Tag: D25 T35 Regular Tradi
----
ID: 864
Date: 21.05.2014
Waypoint: GC1YH9F
Title: Der Blaue Peter und das Einlaufbier
Tag: D15 T15 Micro Multi
----
ID: 865
Date: 22.05.2014
Waypoint: GC3978P
Title: Wachtberger Kreuze # 20
Tag: D25 T25 Micro Mystery
----
ID: 866
Date: 23.05.2014
Waypoint: GC2DR38
Title: crazy pics # 3
Tag: D2 T1 Micro Mystery
----
ID: 867
Date: 24.05.2014
Waypoint: GC2P3Y6
Title: crazy pics # 6
Tag: D2 T15 Micro Mystery
----
ID: 868
Date: 25.05.2014
Waypoint: GC2NPJ6
Title: crazy pics # 5
Tag: D25 T15 Micro Mystery
----
ID: 869
Date: 26.05.2014
Waypoint: GC34902
Title: crazy pics # 13
Tag: D2 T15 Micro Mystery
----
ID: 870
Date: 29.05.2014
Waypoint: GC1WRGQ
Title: Schwimmbad Melbbad
Tag: D1 T15 Micro Tradi
----
ID: 871
Date: 31.05.2014
Waypoint: GC51X5M OC10AF6
Title: Aussicht vom Parkdeck 11
Tag: D1 T1 Small Tradi recommended
----
ID: 872
Date: 01.06.2014
Waypoint: GC4FTGK
Title: Statistik . #36
Tag: D4 T25 Micro Mystery
----
ID: 873
Date: 01.06.2014
Waypoint: GC50483
Title: Wachtberger Kreuze 1 # Reloaded
Tag: D3 T15 Micro Multi
----
ID: 874
Date: 05.06.2014
Waypoint: TCHDU
Title: Cologne Cathedral
nTF: 1
Tag: Virtual Large
----
ID: 875
Date: 05.06.2014
Waypoint: GC16F1M
Title: P6 Cache
Tag: D25 T15 Small Tradi
----
ID: 876
Date: 05.06.2014
Waypoint: LCVE
Title: Traditional Terracache FTF Bonus Points LC
Tag: MC2 Locationless Challenge
----
ID: 877
Date: 05.06.2014
Waypoint: GCZ8H7
Title: The Cologne Cathedral - A Geological Point of View
Tag: D1 T1 Earth
----
ID: 878
Date: 03.06.2014
Waypoint: TCEWS
Title: Dürsch dä Langeberg-Canyon … un'eröm
nTF: 0
Tag: Multi Small
----
ID: 879
Date: 07.06.2014
Waypoint: GC4HMHA
Title: Das Imperium kehrt zurück...
Tag: D35 T25 Micro Tradi
----
ID: 880
Date: 07.06.2014
Waypoint: GC53N9G
Title: CITO Bonn
Tag: D15 T15 CITO
----
ID: 881
Date: 07.06.2014
Waypoint: GC4H98D
Title: Die Macht des Imperiums
Tag: D3 T25 Micro Tradi
----
ID: 882
Date: 07.06.2014
Waypoint: GC53T46
Title: WWFM XI - Bonn ist dabei!
Tag: D1 T1 Event
----
ID: 883
Date: 13.06.2014
Waypoint: GC3WGD9
Banner: jpg
Title: Bonn/Rhein-Sieg 1. offizielle Sissi-T5 Letterbox
Tag: D1 T4 Regular Letterbox_Hybrid
----
ID: 884
Date: 13.06.2014
Waypoint: GC4T3RE
Banner: jpg
Title: Rätseln im Drachenfelser Ländchen
Tag: D25 T25 Small Multi
----
ID: 885
Date: 14.06.2014
Waypoint: GC2XA3Y
Title: RosaStier im FoF
Tag: D2 T1 Micro Tradi recommended
----
ID: 886
Date: 14.06.2014
Waypoint: GC25MTF
Title: GeoTrolle
Tag: D3 T15 Micro Tradi recommended
----
ID: 887
Date: 14.06.2014
Waypoint: GC1N7G0
Title: Feuerhabicht
Tag: D15 T15 Micro Tradi
----
ID: 888
Date: 14.06.2014
Waypoint: GC271T5
Title: Free-Bird
Tag: D25 T25 Regular Tradi
----
ID: 889
Date: 14.06.2014
Waypoint: GC23C6M
Title: FF - Fietsen Freaks
Tag: D15 T15 Micro Tradi
----
ID: 890
Date: 14.06.2014
Waypoint: GC35MWG
Title: Yoda911 im FoF
Tag: D1 T1 Micro Tradi
----
ID: 891
Date: 14.06.2014
Waypoint: GC28G6Q
Title: TEMBO!
Tag: D15 T15 Small Tradi
----
ID: 892
Date: 14.06.2014
Waypoint: GC2PZQH
Title: corsamaus69 im FoF
Tag: D1 T2 Small Tradi
----
ID: 893
Date: 14.06.2014
Waypoint: GC2FHBX
Title: BeanJaro
Tag: D15 T2 Micro Tradi
----
ID: 894
Date: 14.06.2014
Waypoint: GC30BJ8
Title: Gu80 + guvi
Tag: D15 T2 Small Tradi
----
ID: 895
Date: 14.06.2014
Waypoint: GC2FF85
Title: Mediatas
Tag: D15 T2 Small Tradi recommended
----
ID: 896
Date: 14.06.2014
Waypoint: GC31KG5
Title: jps7999
Tag: D15 T3 Small Tradi
----
ID: 897
Date: 14.06.2014
Waypoint: GC2ZDA2
Title: BobbysBandit
Tag: D15 T15 Small Tradi
----
ID: 898
Date: 14.06.2014
Waypoint: GC1PKW9
Title: PeFaJo
Tag: D15 T35 Small Tradi recommended exceptional
----
ID: 899
Date: 14.06.2014
Waypoint: GC2294H
Title: gorgaz
Tag: D2 T2 Small Tradi
----
ID: 900
Date: 14.06.2014
Waypoint: GC1WDMP
Title: stetimm (ET Rhein-Mosel)
Tag: D1 T15 Micro Tradi
----
ID: 901
Date: 14.06.2014
Waypoint: GC21J5K
Title: Norbaer &amp; Norbaerfrau
Tag: D2 T25 Small Tradi
----
ID: 902
Date: 14.06.2014
Waypoint: GC1ZCV2
Title: Frilani
Tag: D25 T15 Small Tradi recommended
----
ID: 903
Date: 14.06.2014
Waypoint: GC23VXF
Title: Schinderhannes
Tag: D1 T25 Large Tradi recommended exceptional
----
ID: 904
Date: 14.06.2014
Waypoint: GC233M8
Title: 4xstone
Tag: D15 T2 Small Tradi
----
ID: 905
Date: 14.06.2014
Waypoint: GC2JNXR
Title: Ju &amp; Ni
Tag: D15 T2 Small Tradi
----
ID: 906
Date: 14.06.2014
Waypoint: GC2NMQT
Title: MaF im FoF
Tag: D25 T15 Regular Tradi
----
ID: 907
Date: 14.06.2014
Waypoint: GC267QK
Title: Lupus54 - FoF
Tag: D15 T15 Small Tradi
----
ID: 908
Date: 14.06.2014
Waypoint: GC2ZEDC
Title: CADS11
Tag: D25 T15 Regular Tradi
----
ID: 909
Date: 14.06.2014
Waypoint: GC2QFG1
Title: StiftLeer
Tag: D2 T2 Small Tradi
----
ID: 910
Date: 14.06.2014
Waypoint: GC29NR5
Title: Heizwert
Tag: D1 T2 Small Tradi
----
ID: 911
Date: 14.06.2014
Waypoint: GC2DZNV
Title: KaelhultFünf
Tag: D15 T2 Small Tradi
----
ID: 912
Date: 14.06.2014
Waypoint: GC30E06
Title: Daisy7861
Tag: D15 T2 Regular Tradi
----
ID: 913
Date: 14.06.2014
Waypoint: GCPTV1
Title: Koblenzer@FoF
Tag: D2 T2 Micro Tradi
----
ID: 914
Date: 14.06.2014
Waypoint: GC1M98T
Title: Pathfinder1980
Tag: D15 T15 Small Tradi
----
ID: 915
Date: 14.06.2014
Waypoint: GC1MX2C
Title: hoerspielnero
Tag: D1 T45 Micro Tradi
----
ID: 916
Date: 14.06.2014
Waypoint: GC1MXRQ
Title: algaert91
Tag: D1 T15 Small Tradi
----
ID: 917
Date: 15.06.2014
Waypoint: GC1EYB0
Title: In the mood
Tag: D2 T5 Regular Multi
----
ID: 918
Date: 15.06.2014
Waypoint: GC4WMM9
Banner: jpg
Title: Das Burggespenst Metternich
Tag: D2 T2 Regular Letterbox_Hybrid recommended
----
ID: 919
Date: 15.06.2014
Waypoint: GC49RWN
Title: Burg Metternich
Tag: D15 T15 Small Tradi
----
ID: 920
Date: 14.06.2014
Waypoint: GC2H7CW
Title: Schieferverwerfung &amp; Fossilien
Tag: D15 T2 Earth
----
ID: 921
Date: 16.06.2014
Waypoint: GC3BAXZ
Title: CHALLENGE: XXXL (15 Dosen der Size LARGE)
Tag: D5 T15 Micro Mystery Challenge
----
ID: 922
Date: 16.06.2014
Waypoint: GC3BAXW
Title: CHALLENGE: DER GIERIGE (30 Caches am Tag)
Tag: D5 T2 Micro Mystery Challenge
----
ID: 923
Date: 18.06.2014
Waypoint: GC496N4
Title: BUNKER (Third Base)
Tag: D2 T2 Small Tradi
----
ID: 924
Date: 18.06.2014
Waypoint: GC3VA8Z
Title: Hardtberg Cache
Tag: D35 T2 Small Multi
----
ID: 925
Date: 19.06.2014
Waypoint: GC4Z0PC
Title: Suchbild : Burgfriedblick II
Tag: D15 T25 Micro Tradi
----
ID: 926
Date: 19.06.2014
Waypoint: TC9BA
Title: Silvio 4x4 (Moving Terracache)
Tag: Small Moving recommended
----
ID: 927
Date: 19.06.2014
Waypoint: GC4YAP0
Title: Suchbild : Burgfriedblick
Tag: D1 T2 Micro Tradi recommended
----
ID: 928
Date: 19.06.2014
Waypoint: GC1JN59
Title: Bleibergwerk Solingen - Reloaded
Tag: D1 T1 Earth
----
ID: 929
Date: 20.06.2014
Waypoint: GC53AAP
Title: Bahnhof Oberwinter
Tag: D15 T15 Micro Tradi
----
ID: 930
Date: 20.06.2014
Waypoint: GC52QNK
Title: Piep Piep Piep
Tag: D1 T2 Regular Tradi
----
ID: 931
Date: 20.06.2014
Waypoint: GC4G2NR
Title: Statistik . #40
Tag: D2 T4 Micro Tradi
----
ID: 932
Date: 20.06.2014
Waypoint: GC4P84B OC10144
Title: Die kleine Wald-Serie &#34;verflixte Runde&#34; #0
Tag: D1 T1 Micro Tradi
----
ID: 933
Date: 20.06.2014
Waypoint: GC53E6D OC10C21
Title: Die kleine Wald-Serie &#34;verflixte Runde&#34; #0,5
Tag: D2 T2 Micro Tradi
----
ID: 934
Date: 20.06.2014
Waypoint: GC54M0J
Title: Entlang der B9 - Wasserwerk Rolandswerth
Tag: D1 T15 Small Tradi
----
ID: 935
Date: 21.06.2014
Waypoint: GC47WR9
Title: Kleingartenkolonie
Tag: D2 T15 Micro Tradi
----
ID: 936
Date: 21.06.2014
Waypoint: GC250WW
Title: LostPlace : Zollfeste der Piraten
Tag: D15 T2 Regular Tradi
----
ID: 937
Date: 21.06.2014
Waypoint: GC25HAB
Title: Denkmal der Petersbergbahn
Tag: D1 T15 Small Tradi
----
ID: 938
Date: 21.06.2014
Waypoint: OCDB3B
Title: Kleiner Trost
Tag: D1 T15 Small Tradi
----
ID: 939
Date: 21.06.2014
Waypoint: GC43GXA
Title: Burgruine Rosenau
Tag: D25 T25 Micro Tradi
----
ID: 940
Date: 21.06.2014
Waypoint: GC56YTJ
Title: Seufzerbrücke
Tag: D15 T15 Micro Tradi
----
ID: 941
Date: 21.06.2014
Waypoint: GCRGR6
Title: little quarry
Tag: D2 T2 Small Tradi
----
ID: 942
Date: 21.06.2014
Waypoint: GC3GGQD
Title: Die Brücke im Nachtigallental oder wo ist sie ?
Tag: D15 T25 Micro Tradi
----
ID: 943
Date: 21.06.2014
Waypoint: GC5932
Title: The Eye of the Dragon
Tag: D1 T3 Virtual
----
ID: 944
Date: 21.06.2014
Waypoint: OC10F2D
Title: Petersberger Bittweg #1
nTF: A
Tag: D15 T3 Virtual
----
ID: 945
Date: 21.06.2014
Waypoint: OC10F2E
Title: Petersberger Bittweg #2
nTF: A
Tag: D15 T3 Virtual
----
ID: 946
Date: 21.06.2014
Waypoint: OC10F2F
Title: Petersberger Bittweg #3
nTF: A
Tag: D15 T3 Virtual
----
ID: 947
Date: 21.06.2014
Waypoint: OC10F30
Title: Petersberger Bittweg #4
nTF: A
Tag: D15 T3 Virtual
----
ID: 948
Date: 21.06.2014
Waypoint: OC10F31
Title: Petersberger Bittweg #5
nTF: A
Tag: D15 T3 Virtual
----
ID: 949
Date: 21.06.2014
Waypoint: OC10F32
Title: Petersberger Bittweg #6
nTF: A
Tag: D15 T3 Virtual
----
ID: 950
Date: 21.06.2014
Waypoint: OC10F33
Title: Petersberger Bittweg #7
nTF: A
Tag: D15 T3 Virtual
----
ID: 951
Date: 21.06.2014
Waypoint: OC10F34
Title: Esel 1,50 DM
nTF: A
Tag: D25 T2 Virtual Mystery
----
ID: 952
Date: 22.06.2014
Waypoint: GC2TKQ3 OX2TKQ3 OCC426
Title: Wupper-Bever-Wander-Cache
Tag: D2 T3 Small Multi
----
ID: 953
Date: 23.06.2014
Waypoint: GC504RE
Title: Old Tree with nice River Rhine View
Tag: D2 T25 Micro Tradi recommended
----
ID: 954
Date: 27.06.2014
Waypoint: GC24WB0
Title: Gotteshäuser: Erlöserkirche
Tag: D15 T15 Micro Tradi
----
ID: 955
Date: 28.06.2014
Waypoint: GC55N3Y
Title: 50 Jahre grillen und kein Ende
Tag: D15 T15 Other Event
----
ID: 956
Date: 28.06.2014
Waypoint: GC29B69
Title: Drachenfels (Earthcache)
Tag: D15 T3 Other Earth
----
ID: 957
Date: 28.06.2014
Waypoint: GC4KT6H
Title: HK5 Nicht verwirklichte Baupläne
Tag: D3 T15 Small Mystery
----
ID: 958
Date: 30.06.2014
Waypoint: GC42XQE
Title: Durch die Felder statt Wälder (6) - Der Wendepunkt
Tag: D15 T15 Micro Tradi
----
ID: 959
Date: 30.06.2014
Waypoint: GC4MWYV
Title: Danke&#34;LEY&#34;be BROILER - (Die Broilerallee)
Tag: D1 T2 Micro Tradi
----
ID: 960
Date: 30.06.2014
Waypoint: GC51QYD
Title: Kleines Biotop
Tag: D15 T15 Small Tradi
----
ID: 961
Date: 30.06.2014
Waypoint: GC51QY2
Title: Räuberleiter
Tag: D15 T3 Micro Tradi
----
ID: 962
Date: 30.06.2014
Waypoint: GC529XV
Title: Schlumpfines Baumplantage
Tag: D1 T25 Micro Tradi
----
ID: 963
Date: 30.06.2014
Waypoint: GC42XRM
Title: Durch die Felder statt Wälder (2)
Tag: D15 T1 Micro Tradi
----
ID: 964
Date: 30.06.2014
Waypoint: GC42XPW
Title: Durch die Felder statt Wälder (3)
Tag: D15 T2 Micro Tradi
----
ID: 965
Date: 30.06.2014
Waypoint: GC4ECKN
Title: Alter Bahnübergang
Tag: D15 T15 Micro Tradi
----
ID: 966
Date: 01.07.2014
Waypoint: GC618 OC0147 N00180
Title: Siebengebirge
Tag: D25 T25 not_chosen Tradi recommended
----
ID: 967
Date: 03.07.2014
Waypoint: GC57QZT
Title: Farbe: Lila
Tag: D1 T15 Micro Tradi recommended
----
ID: 968
Date: 04.07.2014
Waypoint: GC55VT1
Title: Grüner Weg
Tag: D1 T15 Small Tradi
----
ID: 969
Date: 05.07.2014
Waypoint: GC814B N00527
Title: The Bridge at Remagen I
Tag: D15 T15 Micro Tradi recommended
----
ID: 970
Date: 05.07.2014
Waypoint: OC10FC6
Title: Kapelle an der Brücke zu Remagen
nTF: 0
Tag: D1 T1 Virtual
----
ID: 971
Date: 06.07.2014
Waypoint: m/dschuwa/236
Title: Bonner Punktejagd 044
Tag: Munzee

Mal das Munzee-Äpp ausprobieren… echt nicht leicht zu bedienen,
ich habe bestimmt ½h gebraucht, um <em>eine</em> Münze zu loggen.
----
ID: 972
Date: 06.07.2014
Waypoint: GC3RX6V
Title: Lüftet das Geheimnis der Gärten ...
Tag: D2 T2 Small Multi
----
ID: 973
Date: 06.07.2014
Waypoint: GE02FC N02F74 OC10FCE
Title: Godesberger Kreuze #1
nTF: 0
Tag: D1 T1 Virtual
----
ID: 974
Date: 06.07.2014
Waypoint: GE02FD OC10FCF
Title: Godesberger Kreuze #2
nTF: 0
Tag: D15 T1 Virtual
----
ID: 975
Date: 06.07.2014
Waypoint: GE02FE OC10FD0
Title: Godesberger Kreuze #3
nTF: 0
Tag: D1 T15 Virtual
----
ID: 976
Date: 06.07.2014
Waypoint: CC7TG
Title: Truly Well-Rounded Cacher LC - Level II
Tag: MC3 Locationless Challenge
----
ID: 977
Date: 06.07.2014
Waypoint: GE02FF OC10FD8 OXZRN5R
Title: Kapelle zu den „Sieben Schmerzen Mariens“
nTF: 0
Tag: D15 T15 Virtual
----
ID: 978
Date: 08.07.2014
Waypoint: GC2AC80
Title: Streetart: Steckdosen
Tag: D2 T15 Micro Tradi
----
ID: 979
Date: 08.07.2014
Waypoint: TCGQ9
Title: Wald ohne Hüter (Moving TerraCache)
Tag: Regular Moving
----
ID: 980
Date: 10.07.2014
Waypoint: GC21G32 OCB3FE
Title: St. Nikolaus contra Weihnachtsmann
Tag: D25 T15 Small Tradi
----
ID: 981
Date: 11.07.2014
Waypoint: WMM2W4
Title: Open Library in the parc: Bookcrossing Zone Frongasse (Bücherschrank)
nTF: 0
Tag: Virtual
----
ID: 982
Date: 12.07.2014
Waypoint: GC575R4
Title: B-Day Meet&amp;Greet
Tag: D1 T1 Event
----
ID: 983
Date: 12.07.2014
Waypoint: GC547K9 TCEWN
Banner: png
Title: Eis, Eis, Baby... ⅯⅯⅩⅣ
Tag: D1 T1 Event
----
ID: 984
Date: 15.07.2014
Waypoint: GC38YRZ
Title: Wasndasn #04
Tag: D3 T1 Micro Mystery
----
ID: 985
Date: 15.07.2014
Waypoint: GC4YPQZ
Title: Streetart Beethoven
Tag: D2 T15 Micro Multi
----
ID: 986
Date: 15.07.2014
Waypoint: SH02BF
Title: Bergblick
nTF: 0
----
ID: 987
Date: 16.07.2014
Waypoint: GC2Y22K
Title: Quo vadis?
Tag: D25 T25 Nano Mystery
----
ID: 988
Date: 17.07.2014
Waypoint: GC7F6F OC01D8 N009F5
Title: Cologne Clone?
Tag: D1 T1 Virtual
----
ID: 989
Date: 17.07.2014
Waypoint: GC582N7
Title: CAT - Eiszeit 5
Tag: D15 T15 Event
----
ID: 990
Date: 17.07.2014
Waypoint: GC3797R
Title: Römerhof
Tag: D25 T1 Micro Tradi
----
ID: 991
Date: 17.07.2014
Waypoint: GC36QX6
Title: Hl. Drei Könige
Tag: D2 T2 Micro Tradi
----
ID: 992
Date: 17.07.2014
Waypoint: GC4EZKV
Title: Hartplatzhelden
Tag: D15 T15 Small Tradi
----
ID: 993
Date: 17.07.2014
Waypoint: GC2QGGX
Title: Rest in peace
Tag: D15 T15 Small Tradi
----
ID: 994
Date: 17.07.2014
Waypoint: GC2QGJP
Title: Giesdorfer Hof
Tag: D15 T1 Small Tradi
----
ID: 995
Date: 18.07.2014
Waypoint: GC2WP0D
Title: Wachtberger Kreuze 8
Tag: D1 T1 Micro Tradi
----
ID: 996
Date: 15.07.2014
Waypoint: CC7QL
Title: Truly Well-Rounded Cacher Level III Award
Tag: MC5 Locationless Challenge
----
ID: 997
Date: 20.07.2014
Waypoint: LC7LQ
Title: Babewyn
nTF: 1
Tag: Safari
----
ID: 998
Date: 20.07.2014
Waypoint: GC348XJ
Title: Natorampe Oberwinter
Tag: D15 T1 Micro Tradi
----
ID: 999
Date: 20.07.2014
Waypoint: GCWDDD
Title: Gotteshäuser: Apollinariskirche Remagen
Tag: D1 T1 Micro Tradi
----
ID: 1000
Date: 20.07.2014
Waypoint: GC1CPJX
Title: Der Froschkönig am andern Ufer #1
Tag: D1 T1 Micro Tradi
----
ID: 1001
Date: 20.07.2014
Waypoint: GC52B6T
Title: Schweinerei am Paradies
Tag: D15 T15 Micro Tradi
----
ID: 1002
Date: 20.07.2014
Waypoint: GC35B8C
Title: Kreuz in den Feldern mit Sonnenbank
Tag: D1 T15 Micro Tradi
----
ID: 1003
Date: 20.07.2014
Waypoint: GC3BHX7
Title: Spontan#2
Tag: D1 T45 Micro Tradi
----
ID: 1004
Date: 20.07.2014
Waypoint: CCUT
Title: Locationless Cache FTF Bonus Points LC
Tag: Locationless Challenge
----
ID: 1005
Date: 22.07.2014
Waypoint: GC50R22
Title: TB-Hotel im Mini-Wald (FCSB-Schüler-Cache No.2)
Tag: D2 T25 Regular Tradi
----
ID: 1006
Date: 23.07.2014
Waypoint: GC53F4X
Title: a simple cache
Tag: D2 T15 Small Tradi
----
ID: 1007
Date: 24.07.2014
Waypoint: GC3W8D6
Title: Spontan#19
Tag: D1 T3 Micro Mystery
----
ID: 1008
Date: 25.07.2014
Waypoint: GC3WEXV OCC674
Title: Mapa &amp; Co
Tag: D15 T15 Small Tradi
----
ID: 1009
Date: 25.07.2014
Waypoint: GC3WEYG OCC64C
Title: Eine große Schweinerei
Tag: D2 T2 Small Tradi
----
ID: 1010
Date: 26.07.2014
Waypoint: GC3HXYE
Title: GC - Crossgolf #1
Tag: D4 T25 Micro Mystery
----
ID: 1011
Date: 26.07.2014
Waypoint: GC3HXZ1
Title: GC - Crossgolf #2
Tag: D4 T15 Micro Mystery
----
ID: 1012
Date: 26.07.2014
Waypoint: GC3HXZ3
Title: GC - Crossgolf #3
Tag: D45 T2 Micro Mystery
----
ID: 1013
Date: 26.07.2014
Waypoint: GC3HXZ8
Title: GC - Crossgolf #4
Tag: D35 T1 Micro Mystery
----
ID: 1014
Date: 26.07.2014
Waypoint: GC3HXZG
Title: GC - Crossgolf #5
Tag: D35 T15 Micro Mystery
----
ID: 1015
Date: 26.07.2014
Waypoint: GC3HZP1
Title: GC - Crossgolf #6
Tag: D4 T2 Micro Mystery
----
ID: 1016
Date: 26.07.2014
Waypoint: GC3HZP7
Title: GC - Crossgolf #7
Tag: D35 T4 Micro Mystery
----
ID: 1017
Date: 26.07.2014
Waypoint: GC3HZPJ
Title: GC - Crossgolf #9
Tag: D35 T3 Micro Mystery
----
ID: 1018
Date: 26.07.2014
Waypoint: GC3HZPH
Title: GC - Crossgolf #10
Tag: D4 T25 Micro Mystery
----
ID: 1019
Date: 26.07.2014
Waypoint: GC3HZQ2
Title: GC - Crossgolf #11
Tag: D4 T3 Micro Mystery
----
ID: 1020
Date: 26.07.2014
Waypoint: GC3HZQ1
Title: GC - Crossgolf #12
Tag: D45 T4 Micro Mystery
----
ID: 1021
Date: 26.07.2014
Waypoint: GC3NJMF
Title: GC - Crossgolf #13
Tag: D3 T45 Micro Mystery
----
ID: 1022
Date: 26.07.2014
Waypoint: GC3NJMJ
Title: GC - Crossgolf #14
Tag: D45 T35 Micro Mystery
----
ID: 1023
Date: 26.07.2014
Waypoint: GC3NJMM
Title: GC - Crossgolf #15
Tag: D45 T45 Micro Mystery
----
ID: 1024
Date: 26.07.2014
Waypoint: GC26H2A
Title: Himbrich
Tag: D25 T25 Small Tradi
----
ID: 1025
Date: 26.07.2014
Waypoint: GC3NJMX
Title: GC - Crossgolf #17
Tag: D5 T25 Micro Mystery
----
ID: 1026
Date: 26.07.2014
Waypoint: GC3NJN1
Title: GC - Crossgolf #18
Tag: D45 T25 Micro Mystery
----
ID: 1027
Date: 26.07.2014
Waypoint: GC3NJN4
Title: GC - Crossgolf #19
Tag: D4 T2 Micro Mystery
----
ID: 1028
Date: 26.07.2014
Waypoint: GC3NJN6
Title: GC - Crossgolf #20
Tag: D4 T35 Micro Mystery
----
ID: 1029
Date: 26.07.2014
Waypoint: GC3NJN8
Title: GC - Crossgolf #21
Tag: D4 T45 Micro Mystery
----
ID: 1030
Date: 26.07.2014
Waypoint: GC3NJN9
Title: GC - Crossgolf #22
Tag: D4 T15 Micro Mystery
----
ID: 1031
Date: 26.07.2014
Waypoint: GC3NJNB
Title: GC - Crossgolf #23
Tag: D4 T1 Micro Mystery
----
ID: 1032
Date: 26.07.2014
Waypoint: GC3NJMT
Title: GC - Crossgolf #16
Tag: D45 T15 Small Mystery
----
ID: 1033
Date: 26.07.2014
Waypoint: GC3NJNG
Title: GC - Crossgolf #24
Tag: D5 T2 Small Mystery
----
ID: 1034
Date: 26.07.2014
Waypoint: GC3HZP5
Title: GC - Crossgolf # 8
Tag: D45 T15 Small Mystery recommended
----
ID: 1035
Date: 27.07.2014
Waypoint: GC4Y0DZ
Title: “Große Namen“ # 6
Tag: D3 T1 Small Multi
----
ID: 1036
Date: 27.07.2014
Waypoint: GCT355 OC15EA N01E8C
Title: Derletal (Doros Geburtstagscache)
Tag: D15 T15 Regular Multi recommended
----
ID: 1037
Date: 28.07.2014
Waypoint: GC50CQK
Title: Geisterstunde im Spinnenkeller
Tag: D1 T15 Small Tradi recommended
----
ID: 1038
Date: 29.07.2014
Waypoint: GC3W548
Title: Melb-Mikro #2: Die Brücke
Tag: D15 T15 Micro Tradi
----
ID: 1039
Date: 30.07.2014
Waypoint: GC46D19
Title: Die kleine Waldfee
Tag: D2 T25 Regular Multi
----
ID: 1040
Date: 30.07.2014
Waypoint: WMM6HD
Title: Open Library in the parc: Bücherschrank Villip
nTF: 0
Tag: Virtual
----
ID: 1041
Date: 30.07.2014
Waypoint: GC20VXR
Title: Gotteshäuser: St. Simon und Judas Thaddäus
Tag: D2 T15 Small Multi
----
ID: 1042
Date: 31.07.2014
Waypoint: GC57PBM
Title: Kurz Multi mit Aussicht
Tag: D15 T15 Micro Multi
----
ID: 1043
Date: 31.07.2014
Waypoint: GC3NP60
Title: Innovationspark Rheinland
Tag: D15 T3 Micro Tradi
----
ID: 1044
Date: 31.07.2014
Waypoint: GC41FE4
Title: Challenge Cache: 366er Matrix
Tag: D5 T15 Micro Mystery Challenge
----
ID: 1045
Date: 31.07.2014
Waypoint: http://www.wherigo.com/cartridge/details.aspx?CGUID=6779cc32-84be-41e1-8b44-a7fa15bf35c9
Title: Das Haus vom Nikolaus
Tag: Wherigo_Cartridge
----
ID: 1046
Date: 31.07.2014
Waypoint: CC886G
Title: Cheesy Cartridges
nTF: 0
Tag: Locationless
----
ID: 1047
Date: 02.08.2014
Waypoint: http://www.wherigo.com/cartridge/details.aspx?CGUID=4ec786d6-080e-4b29-be31-7d3383102f23
Title: Hilf Bauer Heinrich!!
Tag: Wherigo_Cartridge
----
ID: 1048
Date: 02.08.2014
Waypoint: GC42TQM
Title: Hilf Bauer Heinrich!!
Tag: D2 T15 Small Wherigo_Hybrid
----
ID: 1049
Date: 02.08.2014
Waypoint: GC3JGB6
Title: Area 52 in Rheinbach - Geheimakte Freizeitpark
Tag: D25 T2 Regular Letterbox_Hybrid recommended
----
ID: 1050
Date: 02.08.2014
Waypoint: GC54RXX
Title: Das Revier # 8
Tag: D2 T15 Micro Multi
----
ID: 1051
Date: 02.08.2014
Waypoint: GC2PYA3
Title: Aquäduktenmarmor oder &#34;Travertin selbst gebaut&#34;
Tag: D2 T15 Earth
----
ID: 1052
Date: 02.08.2014
Waypoint: GC4WFME
Title: Römerkanal und Heidentempel V3
Tag: D15 T2 Small Letterbox_Hybrid
----
ID: 1053
Date: 02.08.2014
Waypoint: GC31T3A
Title: Römerbüchse
Tag: D15 T15 Regular Tradi
----
ID: 1054
Date: 02.08.2014
Waypoint: GC3VB8V
Title: Magnetischer Baum
Tag: D25 T15 Micro Tradi recommended
----
ID: 1055
Date: 02.08.2014
Waypoint: GC2JX19
Title: Das Haus vom Nikolaus
Tag: D15 T15 Small Wherigo_Hybrid
----
ID: 1056
Date: 02.08.2014
Waypoint: GC58HPN
Title: Rursee-Event
Tag: D1 T1 Event
----
ID: 1057
Date: 02.08.2014
Waypoint: GC25AT9
Title: Römischer Steinbruch Kall
Tag: D1 T15 Earth
----
ID: 1058
Date: 02.08.2014
Waypoint: GCMX7C OC085C N01D00
Title: Cologne's 14 Traffic Cams
Tag: D15 T1 Webcam
----
ID: 1059
Date: 02.08.2014
Waypoint: GCMYD8 OC026D N017D8
Title: Picture Postcard From Cologne (tiny)
Tag: D1 T1 Webcam
----
ID: 1060
Date: 02.08.2014
Waypoint: GC5B4A
Banner: jpg
Title: Portal to the Past (Köln)
Tag: D1 T1 Virtual
----
ID: 1061
Date: 02.08.2014
Waypoint: GC307NQ
Banner: jpg
Title: Ohm's Law - Ohmsches Gesetz
Tag: D15 T1 Micro Multi
----
ID: 1062
Date: 02.08.2014
Waypoint: GC58K01
Title: Das 2. kleine &#34;Jubi-Event zum 1000.&#34; ;-)
Tag: D3 T1 Event

toller Grillplatz der Forstverwaltung Remscheid
----
ID: 1063
Date: 02.08.2014
Waypoint: GCAE2D OC0931 N0044A
Title: Walzen Cache / Walzing Matilda
Tag: D1 T1 Virtual
----
ID: 1064
Date: 02.08.2014
Waypoint: GC2HNX7
Title: 7 Caches Cologne (Challenge Cache)
Tag: D3 T25 Small Mystery Challenge
----
ID: 1065
Date: 02.08.2014
Waypoint: GC2XT6K OCC8B9
Title: Lore ist ein Challenge (8 Cachetypen)
Tag: D25 T2 Small Mystery Challenge
----
ID: 1066
Date: 02.08.2014
Waypoint: OC2031
Title: R(h)einblick
Tag: D15 T1 Virtual
----
ID: 1067
Date: 11.08.2014
Waypoint: TC1OYX GC59HJ5 OC11141 N02F79 GE0300
Banner: png
Title: August-Eis ⅯⅯⅩⅣ
nTF: 0
Tag: D15 T1 Event
----
ID: 1068
Date: 14.08.2014
Waypoint: GC58BP2
Title: - A - M - P - E - L - 4 -
Tag: D1 T1 Event
----
ID: 1069
Date: 16.08.2014
Waypoint: GC2PA5Y OCBF04
Title: Müllcache
Tag: D25 T15 Micro Mystery
----
ID: 1070
Date: 17.08.2014
Waypoint: GC2JVH7
Title: Strümpfe
Tag: D2 T1 Other Tradi recommended
----
ID: 1071
Date: 17.08.2014
Waypoint: GC200TZ
Title: Rotweintour Teil 1
Tag: D2 T3 Micro Tradi
----
ID: 1072
Date: 17.08.2014
Waypoint: GC1QFZT
Title: Lost Place Das alte Schwimmbad
Tag: D1 T1 Micro Tradi
----
ID: 1073
Date: 17.08.2014
Waypoint: GC1QG0P
Title: Altenahrer Brücken Cache
Tag: D1 T1 Micro Tradi
----
ID: 1074
Date: 17.08.2014
Waypoint: GC1YTV2
Title: Altenahr : Tonsteinklippen / Slate stone cliff
Tag: D2 T25 Earth
----
ID: 1075
Date: 17.08.2014
Waypoint: GC410RQ
Title: AHR Lock
Tag: D3 T15 Small Tradi recommended
----
ID: 1076
Date: 17.08.2014
Waypoint: GC2CCPN
Title: ZWISCHEN KATZ UND KUH (AHRTAL)
Tag: D2 T15 Earth recommended
----
ID: 1077
Date: 19.08.2014
Waypoint: GCTY6M OC1961
Title: Kirchen &amp; Kapellen #3 - Chorruine Heisterbach
Tag: D2 T15 Regular Multi
----
ID: 1078
Date: 19.08.2014
Waypoint: GC218G4
Title: &#34;Basalt und Tuff&#34; am Weilberg
Tag: D3 T15 Earth
----
ID: 1079
Date: 19.08.2014
Waypoint: GC4XRG5
Title: Schloreley
Tag: D15 T15 Micro Multi
----
ID: 1080
Date: 19.08.2014
Waypoint: GCG2JH OC4678
Title: Alter Vulkan
Tag: D2 T15 Regular Multi recommended
----
ID: 1081
Date: 19.08.2014
Waypoint: GC3A4VE
Title: St. Michael - Niederdollendorf
Tag: D1 T15 Micro Tradi
----
ID: 1082
Date: 27.08.2014
Waypoint: GC14Y8P OC3EA7 N0265A
Title: DARE INTO DARKNESS II
Tag: D3 T35 Regular Multi recommended

Vorher GLFAV8M0 lesen. Nix für Weicheier!
----
ID: 1083
Date: 28.08.2014
Waypoint: GC33M48
Title: Alles auf die 20!
Tag: D4 T15 Small Mystery recommended
----
ID: 1084
Date: 30.08.2014
Waypoint: GC4WT0N
Banner: jpg
Title: Wachtberger Sterne
Tag: D25 T25 Regular Multi
----
ID: 1085
Date: 01.09.2014
Waypoint: GC3HY37
Title: BN Challenge Cache: 7 Icons²
Tag: D4 T15 Micro Mystery Challenge
----
ID: 1086
Date: 01.09.2014
Waypoint: GC2NNFG
Title: Projekt CT9 (Challenge Cache)
Tag: D4 T25 Micro Mystery Challenge recommended
----
ID: 1087
Date: 04.09.2014
Waypoint: GC4332X
Title: TUS Germania Hersel
Tag: D15 T15 Micro Tradi
----
ID: 1088
Date: 05.09.2014
Waypoint: GC53E1H
Title: Hotte Hüh
Tag: D1 T15 Micro Tradi
----
ID: 1089
Date: 06.09.2014
Waypoint: OC10C63
Title: Pinkie*5
Tag: D1 T1 Micro Tradi
----
ID: 1090
Date: 06.09.2014
Waypoint: OC10E39
Title: Online-Liebe
Tag: D1 T1 Virtual
----
ID: 1091
Date: 06.09.2014
Waypoint: GC2EJCE
Banner: jpg
Title: Liebesbrücke
Tag: D3 T15 Micro Tradi
----
ID: 1092
Date: 07.09.2014
Waypoint: GC1M1NK
Title: Servatiuskapelle
Tag: D2 T15 Micro Tradi
----
ID: 1093
Date: 07.09.2014
Waypoint: GC4KMK7
Title: Postamt unterm Hasengrill
Tag: D15 T2 Regular Letterbox_Hybrid
----
ID: 1094
Date: 07.09.2014
Waypoint: GC3V1ZM
Title: HÜTTENZAUBER IM SIEBENGEBIRGE-Florianshütte
Tag: D2 T15 Small Tradi
----
ID: 1095
Date: 07.09.2014
Waypoint: GCB88
Title: Himmerich
Tag: D25 T25 Regular Multi recommended exceptional

What can you say. Truly an exceptional old cache.
Do not complain about your back aching, or your
circulation going wild, though ☺
----
ID: 1096
Date: 07.09.2014
Waypoint: GC3NJNN
Banner: jpg
Title: GC - Crossgolf #25
Tag: D5 T5 Small Mystery
----
ID: 1097
Date: 08.09.2014
Waypoint: GC4YVD5
Title: Stairway to Laneway
Tag: D2 T3 Small Tradi
----
ID: 1098
Date: 21.06.2014
Waypoint: TCBDS
Title: Drachenlachen
nTF: L
Tag: Multi Medium exceptional
----
ID: 1099
Date: 09.09.2014
Waypoint: GC3KV89
Title: Linie 16 - Haltepunkt Uedorf
Tag: D15 T15 Small Tradi
----
ID: 1100
Date: 09.09.2014
Waypoint: GC3KV7K
Title: Linie 16 - Haltepunkt Widdig
Tag: D15 T1 Small Tradi
----
ID: 1101
Date: 09.09.2014
Waypoint: GC3KV8V
Title: Linie 16 - Haltepunkt Urfeld
Tag: D15 T15 Micro Tradi
----
ID: 1102
Date: 09.09.2014
Waypoint: GC43QBF OC10096
Title: Rhein-Schifffahrt kurz
Tag: D2 T15 Micro Tradi
----
ID: 1103
Date: 09.09.2014
Waypoint: GC21NE2
Title: Advent Advent: Lichterfest der Luzia
Tag: D15 T15 Micro Tradi
----
ID: 1104
Date: 09.09.2014
Waypoint: GC4F169 OC10092
Title: Rhein-Astschnitt
Tag: D2 T2 Micro Tradi recommended
----
ID: 1105
Date: 09.09.2014
Waypoint: GC33HBD
Title: Mondorfer Bach
Tag: D35 T15 Small Tradi
----
ID: 1106
Date: 11.09.2014
Waypoint: OC11457 GC446WD
Title: Kunst am Wegesrand: Stern des Rheins
nTF: 2
Tag: D25 T15 Small Mystery
----
ID: 1107
Date: 11.09.2014
Waypoint: GC55KJE
Title: Städtekenner gesucht!!!
Tag: D25 T15 Micro Mystery
----
ID: 1108
Date: 13.09.2014
Waypoint: GC3608A
Title: [CHIPS'11] HAUNTED 2
Tag: D25 T25 Small Mystery
----
ID: 1109
Date: 13.09.2014
Waypoint: GCHM04
Title: Alstad #1
Tag: D2 T15 Regular Tradi
----
ID: 1110
Date: 13.09.2014
Waypoint: GC1X8BB
Title: The Luxembourg Plateau – Luxembourg Sandstone
Tag: D15 T15 Earth
----
ID: 1111
Date: 13.09.2014
Waypoint: GC2B1QF
Banner: jpg
Title: Corkscrew Snake
Tag: D2 T1 Small Tradi
----
ID: 1112
Date: 13.09.2014
Waypoint: GC21HTQ
Title: Les vieux z' entrepots
Tag: D3 T25 Small Tradi
----
ID: 1113
Date: 13.09.2014
Waypoint: GC2ATK2 http://www.bessercacher.de/Forum/phpBB3/viewtopic.php?t=1293
Title: Red Land
Tag: D3 T2 Micro Mystery
----
ID: 1114
Date: 13.09.2014
Waypoint: GC4FYTK
Banner: jpg
Title: Forever
Tag: D3 T15 Micro Tradi
----
ID: 1115
Date: 13.09.2014
Waypoint: GC1V6AV
Title: France
Tag: D15 T2 Micro Tradi
----
ID: 1116
Date: 13.09.2014
Waypoint: GC21ZTP
Title: Keiner da? #3
Tag: D25 T3 Small Tradi
----
ID: 1117
Date: 15.09.2014
Waypoint: VX76-DIKA
Title: [Austria], Bad Münstereifel-Wald
Distance: 7
----
ID: 1118
Date: 15.09.2014
Waypoint: VX75-YJYN
Title: [Solomon Islands], Metternich-Weiler am Berge
Distance: 49
----
ID: 1119
Date: 15.09.2014
Waypoint: VX71-UPIK
Title: [Jersey], Zülpich-Ülpenich
Distance: 66
----
ID: 1120
Date: 20.09.2014
Waypoint: GC1G390 OC6ACF
Title: Der Altar der Nibelungen
Tag: D2 T3 Regular Multi recommended
----
ID: 1121
Date: 20.09.2014
Waypoint: GC4Y5HR
Title: Der Ursprung eine Erinnerung an ....
Tag: D3 T25 Small Mystery
----
ID: 1122
Date: 20.09.2014
Waypoint: GC3TE2K
Title: Tell
Tag: D1 T15 Micro Tradi
----
ID: 1123
Date: 20.09.2014
Waypoint: GC4WBBM
Title: Paulownia
Tag: D15 T15 Regular Tradi
----
ID: 1124
Date: 20.09.2014
Waypoint: GC34CMA
Title: TB Hotel - Bad Honnef
Tag: D15 T15 Regular Tradi
----
ID: 1125
Date: 20.09.2014
Waypoint: GC1K547
Title: Villa Raterestohrp
Tag: D15 T15 Micro Tradi
----
ID: 1126
Date: 21.09.2014
Waypoint: GCZZ08
Title: Regenfänger
Tag: D2 T1 Micro Tradi
----
ID: 1127
Date: 21.09.2014
Waypoint: GC4WP72
Title: Entlang der B9 - Schloss Marienfels
Tag: D2 T15 Nano Tradi
----
ID: 1128
Date: 21.09.2014
Waypoint: GC5BW9C
Title: Eis mit Aussicht - Eiszeit MMXIV
Tag: D1 T1 Event
----
ID: 1129
Date: 21.09.2014
Waypoint: GC22DA8 OC9B6B
Title: Das doppelte Drachenfelsmotiv...
Tag: D4 T1 Micro Mystery
----
ID: 1130
Date: 23.09.2014
Waypoint: GC5BFYK
Title: AUENLAND TP – No.3: Erdkunde
Tag: D1 T15 Micro Tradi
----
ID: 1131
Date: 23.09.2014
Waypoint: GC5BFYM
Title: AUENLAND TP – No.4: Unterhaltung
Tag: D1 T15 Micro Tradi
----
ID: 1132
Date: 23.09.2014
Waypoint: GC5BFYN
Title: AUENLAND TP – No.5: Kunst und Literatur
Tag: D15 T15 Micro Tradi
----
ID: 1133
Date: 23.09.2014
Waypoint: GC5BFYJ
Title: AUENLAND TP – No.2: Geschichte
Tag: D1 T15 Micro Tradi
----
ID: 1134
Date: 23.09.2014
Waypoint: GC5BFYH
Title: AUENLAND TP – No.1: Wissenschaft und Technik
Tag: D1 T2 Micro Tradi
----
ID: 1135
Date: 23.09.2014
Waypoint: GC5BFYP
Title: AUENLAND TP – No.6: Sport und Vergnügen
Tag: D1 T15 Micro Tradi
----
ID: 1136
Date: 23.09.2014
Waypoint: GC3ENR0
Title: HONIKMELONE
Tag: D25 T15 Small Mystery recommended
----
ID: 1137
Date: 25.09.2014
Waypoint: GC5CQVC GE0304 N02F7F OC114D3 TC2EEL
Title: AMT Ⅰ (2014 KW39)
nTF: 0
Tag: D1 T1 Event
----
ID: 1138
Date: 25.09.2014
Waypoint: GC2NKTB
Title: Lost Place: Neuer Weg
Tag: D2 T4 Micro Tradi recommended
----
ID: 1139
Date: 26.09.2014
Waypoint: GC5DR15
Title: (unveröffentlichter Cache von Segamaster1998)
nTF: A
Tag: unpublished
----
ID: 1140
Date: 26.09.2014
Waypoint: GC319ZN
Title: Willkommen in... Andernach
Tag: D25 T1 Micro Tradi
----
ID: 1141
Date: 26.09.2014
Waypoint: GC3X6B5
Title: Wer an der Quelle sitzt....
Tag: D45 T15 Micro Tradi
----
ID: 1142
Date: 26.09.2014
Waypoint: GC3KEJW
Title: Anglerparkplatz
Tag: D15 T15 Micro Tradi
----
ID: 1143
Date: 26.09.2014
Waypoint: GC1VCVC
Title: Willkommen in... Remagen
Tag: D1 T15 Micro Tradi
----
ID: 1144
Date: 27.09.2014
Waypoint: GC4XDN8
Title: Von Null auf Heute | From zero hour to the present
Tag: D3 T2 Regular Multi
----
ID: 1145
Date: 27.09.2014
Waypoint: GC2X17V
Title: Karikaturengalerie (Mini-Multi)
Tag: D3 T15 Small Multi
----
ID: 1146
Date: 27.09.2014
Waypoint: GC4XYMK
Title: Bonus: Von Null auf Heute | From &#34;zero hour&#34;...
Tag: D3 T2 Small Mystery
----
ID: 1147
Date: 27.09.2014
Waypoint: GC3MN7C
Banner: jpg
Title: Lost Place - Das Autohaus reloaded
Tag: D2 T5 Small Tradi
----
ID: 1148
Date: 27.09.2014
Waypoint: GC5B9WW
Title: Caching goes Classic!
Tag: D1 T15 Event
----
ID: 1149
Date: 27.09.2014
Waypoint: GC59QR0
Banner: jpg
Title: Marmor, Stein und Eisen bricht....
Tag: D3 T1 Small Mystery
----
ID: 1150
Date: 28.09.2014
Waypoint: GC1PF4T
Title: Remagens weltbester Spanier
Tag: D2 T2 Micro Tradi
----
ID: 1151
Date: 28.09.2014
Waypoint: GC5129X
Title: Zum langen Heinrich
Tag: D1 T15 Micro Tradi
----
ID: 1152
Date: 28.09.2014
Waypoint: GC1R4Z0 OC9B91
Title: Schwimmbad Remagen
Tag: D1 T1 Micro Tradi
----
ID: 1153
Date: 28.09.2014
Waypoint: GC1PYBW
Title: Gotteshäuser: Schwarze Madonna
Tag: D1 T1 Micro Tradi
----
ID: 1154
Date: 02.10.2014
Waypoint: GC34NKX
Title: Verstecketopf NKY
Tag: D45 T25 Micro Mystery
----
ID: 1155
Date: 28.09.2014
Waypoint: OC9E4C
Title: Webcam Fähre Linz
Tag: D2 T1 Webcam
----
ID: 1156
Date: 28.09.2014
Waypoint: GC19HAH
Title: Tilmann Joel Park
Tag: D15 T15 Micro Tradi
----
ID: 1157
Date: 28.09.2014
Waypoint: GC4YZ3D
Title: Reisebüro Glücksreisen
Tag: D15 T15 Micro Tradi
----
ID: 1158
Date: 28.09.2014
Waypoint: GC42QVA
Title: Es war einmal... (Volume1)
Tag: D4 T45 Micro Mystery
----
ID: 1159
Date: 28.09.2014
Waypoint: GC5BQ7A
Title: Skulpturenpark Remagen &#34;Heimat&#34;
Tag: D2 T25 Micro Tradi
----
ID: 1160
Date: 28.09.2014
Waypoint: GC5BPMN
Title: TB Hotel Landesgrenze NRW/RLP reloaded
Tag: D15 T15 Regular Tradi
----
ID: 1161
Date: 02.10.2014
Waypoint: GC34NKY
Title: Verstecketopf NKX
Tag: D45 T25 Micro Mystery
----
ID: 1162
Date: 04.10.2014
Waypoint: GC2T5PN
Title: Der Schatz der wundersamen Bäume
Tag: D25 T2 Small Multi
----
ID: 1163
Date: 04.10.2014
Waypoint: OC1A1E
Title: Rüngsdorf
Tag: D25 T1 Virtual recommended
----
ID: 1164
Date: 05.10.2014
Waypoint: GC2Q842
Title: Ei Ei Ei Sülzer Osterei
Tag: D15 T15 Micro Tradi
----
ID: 1165
Date: 05.10.2014
Waypoint: GCKQFN
Title: Grüngürtel - Cache
Tag: D15 T1 Small Multi
----
ID: 1166
Date: 05.10.2014
Waypoint: GC2HFZY
Title: Biogen
Tag: D25 T1 Other Tradi
----
ID: 1167
Date: 05.10.2014
Waypoint: GC4NWZC
Banner: jpg
Title: Souvenir CHALLENGE - 31-August-Tage
Tag: D5 T15 Micro Mystery Challenge
----
ID: 1168
Date: 05.10.2014
Waypoint: GC5CX5G
Banner: png
Title: Challenge: &#34;Happiest tenth'iest birthday!&#34;
nTF: 3
Tag: D35 T2 Small Mystery Challenge
----
ID: 1169
Date: 05.10.2014
Waypoint: GC531WK
Title: Alles nur geklaut #5: Gehört hier nicht hin #1
Tag: D15 T2 Micro Tradi recommended
----
ID: 1170
Date: 06.10.2014
Waypoint: GC5C0MZ
Title: XLVII. Geocacher Stammtisch BN/SU
Tag: D15 T15 Event
----
ID: 1171
Date: 09.10.2014
Waypoint: GC3YA61
Title: Königreich Ückesdorf 8
Tag: D1 T15 Micro Tradi
----
ID: 1172
Date: 09.10.2014
Waypoint: GC3VX46
Title: Tarnen, Täuschen, Aufklären
Tag: D15 T25 Micro Tradi recommended
----
ID: 1173
Date: 10.10.2014
Waypoint: TC3T8O GC5DJTV OC1152E N02F80 GE0306
Title: ⅯⅯⅩⅣ das Vorletzte
nTF: 0
Tag: D1 T15 Event
----
ID: 1174
Date: 10.10.2014
Waypoint: GC51VZE
Title: Pictogram storys #1
Tag: D35 T2 Small Mystery
----
ID: 1175
Date: 10.10.2014
Waypoint: GC54FX6
Title: Pictogram storys #2
Tag: D4 T2 Micro Mystery
----
ID: 1176
Date: 10.10.2014
Waypoint: GC5DKKJ
Title: stetig an der &#34;Dose&#34;
Tag: D1 T15 Event
----
ID: 1177
Date: 11.10.2014
Waypoint: GC53A9B
Title: Landhuis &amp; LBB cache
Tag: D15 T2 Large Tradi
----
ID: 1178
Date: 11.10.2014
Waypoint: GC4BMP2
Title: #TB-HOTEL# EVENT MANU MENTEQUE
Tag: D15 T25 Regular Tradi
----
ID: 1179
Date: 11.10.2014
Waypoint: GC1TN41
Title: E42 sortie 8 - TB&amp;GC Hotel
Tag: D15 T15 Regular Tradi
----
ID: 1180
Date: 11.10.2014
Waypoint: GC5A4YC
Title: TB Hotel - Sortie 21 (E411) - Pont de Custinne
Tag: D15 T15 Regular Tradi
----
ID: 1181
Date: 11.10.2014
Waypoint: GC4QKBV
Title: La citée du Wandalino
Tag: D15 T15 Nano Tradi
----
ID: 1182
Date: 11.10.2014
Waypoint: GC40 OC14A2
Title: Geocache
Tag: D1 T1 Regular Tradi
----
ID: 1183
Date: 11.10.2014
Waypoint: GC49283
Title: La Harpe
Tag: D15 T15 Micro Tradi
----
ID: 1184
Date: 11.10.2014
Waypoint: GC4XP2B
Title: Aux héros du banel
Tag: D15 T2 Small Tradi
----
ID: 1185
Date: 11.10.2014
Waypoint: GC4Q1YE
Title: La maison forte
Tag: D15 T15 Micro Tradi recommended
----
ID: 1186
Date: 11.10.2014
Waypoint: GC4JV08
Title: RIP Messieurs d'Huard
Tag: D15 T15 Micro Tradi recommended
----
ID: 1187
Date: 11.10.2014
Waypoint: GC4KJP4
Title: Le monument
Tag: D2 T2 Small Tradi
----
ID: 1188
Date: 11.10.2014
Waypoint: GC1K0XP
Title: Pitstop &#34;Hondelange 2&#34;
Tag: D15 T15 Micro Tradi
----
ID: 1189
Date: 11.10.2014
Waypoint: GC1K0XM
Title: Pitstop &#34;Hondelange 1&#34;
Tag: D15 T15 Micro Tradi
----
ID: 1190
Date: 11.10.2014
Waypoint: GC2TP04
Title: Un peu plus près des étoiles - TB/GC Findel Hôtel
Tag: D1 T15 Small Tradi
----
ID: 1191
Date: 11.10.2014
Waypoint: GC4VK7F
Title: MacGyver
Tag: D15 T15 Small Tradi
----
ID: 1192
Date: 11.10.2014
Waypoint: GC1PJ47
Title: Réimerwee - Tumulus
Tag: D15 T3 Small Tradi
----
ID: 1193
Date: 11.10.2014
Waypoint: GC48QWZ
Title: Oratoire
Tag: D1 T2 Micro Tradi
----
ID: 1194
Date: 11.10.2014
Waypoint: GC12QC8
Title: Car Wash
Tag: D1 T1 Micro Tradi
----
ID: 1195
Date: 11.10.2014
Waypoint: GC3V85X
Title: B 51 - Raus auf´s Land
Tag: D1 T15 Micro Tradi
----
ID: 1196
Date: 11.10.2014
Waypoint: GC4MXZT
Title: Jonathan's Kids Cache Sirzenich
Tag: D1 T15 Regular Tradi
----
ID: 1197
Date: 11.10.2014
Waypoint: GC53NWH
Title: Die fünf Länder Challenge
Tag: D5 T3 Micro Mystery Challenge
----
ID: 1198
Date: 12.10.2014
Waypoint: GDCI-JUNU
Title: [Game 160 (Oktober 2014)], BN-Röttgen
nTF: 1
Distance: 92
----
ID: 1199
Date: 12.10.2014
Waypoint: GC4NKYY
Title: Bodenkunde im Kottenforst (rel.) - Kottenforstlehm
Tag: D2 T2 Earth
----
ID: 1200
Date: 14.10.2014
Waypoint: GC1ZJ8V OC5DF3
Title: Hafenblick
Tag: D2 T15 Micro Tradi
----
ID: 1201
Date: 14.10.2014
Waypoint: GC2M8CD
Title: Die Erde bebt - eine Spurensuche
Tag: D1 T15 Earth
----
ID: 1202
Date: 18.10.2014
Waypoint: GDCI-JURE
Title: [Game 160 (Oktober 2014)], Bad Hönningen-Rheinbrohl
nTF: 1
Distance: 17
----
ID: 1203
Date: 18.10.2014
Waypoint: GC2DA0R OCACEF
Title: Kaiserberg
Tag: D15 T1 Micro Tradi
----
ID: 1204
Date: 18.10.2014
Waypoint: VX76-XOCO
Title: [Austria], Linz am Rhein
Distance: 51
----
ID: 1205
Date: 18.10.2014
Waypoint: GC330JB
Title: SCHWARZER PETER
Tag: D3 T1 Small Tradi
----
ID: 1206
Date: 19.10.2014
Waypoint: GC3W54V
Title: Melb-Mikro #3: Das Bad
Tag: D2 T2 Micro Tradi
----
ID: 1207
Date: 19.10.2014
Waypoint: GC377NC
Title: Melbtal ll
Tag: D2 T2 Micro Tradi
----
ID: 1208
Date: 19.10.2014
Waypoint: GC5ECQA
Title: Magicx67's magischer Geburtstags-Cache
nTF: 5
Tag: D2 T15 Nano Tradi
----
ID: 1209
Date: 25.10.2014
Waypoint: GC5DCZH
Banner: jpg
Title: Arrivederci ⅯⅯⅩⅣ
Tag: D15 T2 Event
----
ID: 1210
Date: 25.10.2014
Waypoint: GC5F3HT
Banner: jpg
Title: Cats delight
Tag: D25 T15 Small Multi
----
ID: 1211
Date: 25.10.2014
Waypoint: GC3DRZ7
Title: 2fast4you
Tag: D5 T2 Small Mystery
----
ID: 1212
Date: 25.10.2014
Waypoint: OC116D5
Title: Godesberger Kreuze #5
nTF: 0
Tag: D1 T1 Virtual
----
ID: 1213
Date: 25.10.2014
Waypoint: OC116D6
Title: Godesberger Kreuze #4
nTF: 0
Tag: D2 T1 Virtual Mystery
----
ID: 1214
Date: 26.10.2014
Waypoint: GC5AR2K
Title: Mord in der Südstadt
Tag: D3 T3 Small Multi recommended
----
ID: 1215
Date: 28.10.2014
Waypoint: GC2YPY9
Title: ANTUNNACUM 2 ENDE + ANFANG
Tag: D1 T1 Nano Tradi
----
ID: 1216
Date: 28.10.2014
Waypoint: 2014-10-28_50_7
Title: [Bonn, Germany], Koblenz
----
ID: 1217
Date: 28.10.2014
Waypoint: VX76-WHAT
Title: [Norway], Polch
Distance: 0
----
ID: 1218
Date: 28.10.2014
Waypoint: GC4W7R2
Title: TB-Hotel L 113 / K 27
Tag: D2 T2 Regular Tradi recommended
----
ID: 1219
Date: 28.10.2014
Waypoint: VX77-BENO
Title: [Guernsey], Welling
Distance: 67
----
ID: 1220
Date: 28.10.2014
Waypoint: OC2968 GCFB7E N0059E
Title: Andernacher Standrundgang
Tag: D2 T1 Virtual
----
ID: 1221
Date: 30.10.2014
Waypoint: GDCI-JUIZ
Title: [Game 160 (Oktober 2014)], Weilerswist-Bodenheim
nTF: 1
Distance: 42
----
ID: 1222
Date: 30.10.2014
Waypoint: VX77-BUSI
Title: [Norway], Zülpich-Schwerfen
Distance: 98
----
ID: 1223
Date: 30.10.2014
Waypoint: GC2BGCH
Title: Meckis Spuren-Suche 2010
Tag: D2 T2 Micro Tradi
----
ID: 1224
Date: 02.11.2014
Waypoint: GC4WK01
Title: Das FELD
Tag: D2 T2 Regular Mystery
----
ID: 1225
Date: 02.11.2014
Waypoint: GC37HP1
Title: Halbzeitpause im Chaos-Multi Land
Tag: D2 T2 Micro Tradi
----
ID: 1226
Date: 03.11.2014
Waypoint: CC6NOO
Title: The First NOT To Find Challenge
Tag: Locationless Challenge
----
ID: 1227
Date: 12.11.2011
Waypoint: GC1H7A2
Title: Lore Jacobi
Tag: D1 T15 Small Tradi
----
ID: 1228
Date: 09.11.2014
Waypoint: GC4J6JY
Title: Landschafts_PARKen
Tag: D2 T1 Micro Tradi
----
ID: 1229
Date: 10.11.2014
Waypoint: 2014-11-10_50_7
Title: [Bonn, Germany], Wachtberg-Adendorf/Arzdorf
----
ID: 1230
Date: 10.11.2014
Waypoint: GC5A59J
Title: drei Linden
Tag: D1 T15 Small Tradi
----
ID: 1231
Date: 11.11.2014
Waypoint: VX77-BUSS
Title: [Liechtenstein], Lohmar-Krewelshof
Distance: 4
----
ID: 1232
Date: 11.11.2014
Waypoint: GC1QE7C
Title: Nord-Süd-Verbindung
Tag: D1 T1 Nano Tradi
----
ID: 1233
Date: 11.11.2014
Waypoint: VX77-CIPO
Title: [Israel], K-Bilderstöckchen
Distance: 87
----
ID: 1234
Date: 11.11.2014
Waypoint: 2014-11-11_50_6
Title: [Köln, Germany], Vettweiß-Ginnick
----
ID: 1235
Date: 11.11.2014
Waypoint: VX76-IWUD
Title: [Netherlands], Nideggen-Berg
Distance: 64
----
ID: 1236
Date: 11.11.2014
Waypoint: OCF495
Title: Go Geohashing
Tag: D3 T3 Virtual Safari
----
ID: 1237
Date: 16.11.2014
Waypoint: OCCB62 GC2ZH3E
Title: Schevastesstr.
Tag: D1 T1 Small Tradi
----
ID: 1238
Date: 16.11.2014
Waypoint: VX77-LYYG
Title: [Switzerland], BN-Beuel
Distance: 0
----
ID: 1239
Date: 16.11.2014
Waypoint: OCE5B3
Title: Alte Rathaus Bonn
Tag: D1 T1 Virtual
----
ID: 1240
Date: 16.11.2014
Waypoint: OC1083E
Title: Bonner Rathaustreppe
Tag: D1 T1 Webcam
----
ID: 1241
Date: 17.11.2014
Waypoint: GC4NMDF
Title: Witterschlicker Schleichwege.....#2
Tag: D15 T15 Micro Tradi
----
ID: 1242
Date: 17.11.2014
Waypoint: GC37W06
Title: Alfterer Kreuze 10
Tag: D1 T15 Micro Tradi
----
ID: 1243
Date: 17.11.2014
Waypoint: GC2ZMWK
Title: Lore im R.A.L.F.J.-Land #02
Tag: D2 T15 Small Tradi
----
ID: 1244
Date: 19.11.2014
Waypoint: GC4E22H
Title: Alles nur kein Geld
nTF: 2
Tag: D15 T2 Micro Tradi
----
ID: 1245
Date: 22.11.2014
Waypoint: GCJ270
Title: Schloss Birlinghoven
Tag: D3 T3 Regular Multi
----
ID: 1246
Date: 23.11.2014
Waypoint: GC41AFP
Title: CHALLENGE: DER ROTIERER
Tag: D5 T2 Micro Mystery Challenge
----
ID: 1247
Date: 23.11.2014
Waypoint: GC3YVFP
Title: Kulturdenkmal Siechenhauskapelle
Tag: D15 T15 Micro Tradi
----
ID: 1248
Date: 23.11.2014
Waypoint: GC48VMV
Title: Anti Challenge – Mysterie Cache
Tag: D15 T1 Micro Mystery
----
ID: 1249
Date: 23.11.2014
Waypoint: GC1Z931
Title: CLOOS-FALTE BEI ALTENBURG (AHRTAL)
Tag: D15 T1 Earth
----
ID: 1250
Date: 23.11.2014
Waypoint: GC2AKMB
Title: &#34;Lore ist heiß!&#34;
Tag: D15 T15 Micro Tradi
----
ID: 1251
Date: 23.11.2014
Waypoint: GC5FBFM
Title: Geocacher in der Baracke
Tag: D2 T1 Event
----
ID: 1252
Date: 23.11.2014
Waypoint: GC21XQX
Title: Kunst am Wegesrand - Das Gemälde
Tag: D3 T1 Micro Mystery
----
ID: 1253
Date: 24.11.2014
Waypoint: OCF9DE
Title: Die Wolfsburg
Tag: D1 T1 Virtual
----
ID: 1254
Date: 24.11.2014
Waypoint: 2014-11-24_50_7
Title: [Bonn, Germany], BN-Beuel-Vilich-Rheindorf
----
ID: 1255
Date: 24.11.2014
Waypoint: GC5BJJ5
Title: Clemensstraße Revival in Beuel
Tag: D3 T15 Nano Tradi recommended
----
ID: 1256
Date: 24.11.2014
Waypoint: OCE45C
Title: Schwarzrheindorfer Doppelkirche
Tag: D1 T1 Virtual
----
ID: 1257
Date: 24.11.2014
Waypoint: LC5LT5
Title: Find Your Head
nTF: 1
Tag: Safari
----
ID: 1258
Date: 27.11.2014
Waypoint: GC2340H
Title: Waffenbrüder
Tag: D2 T1 Micro Tradi
----
ID: 1259
Date: 13.09.2014
Waypoint: OC11249
Title: SVC - Kompassrose (Challenge)
Tag: D2 T15 Virtual Safari
----
ID: p1235
Date: 11.11.2014
Waypoint: GDCJ-JUAJ
Title: [Game 161 (November 2014)], EU-Schweinheim
----
ID: p1236
Date: 11.11.2014
Waypoint: GDCJ-JUDI
Title: [Game 161 (November 2014)], Köln-Porz-Wahn
----
ID: p1154
Date: 28.09.2014 17:45
Waypoint: OC1F07 GC8453 N004A9
Title: Beweglicher Cache
Tag: D2 T15 Virtual

Warten auf Logfreigabe
----
# ^K/ mksh -c '. ../../mk/common; xhtml_escape'
# ^K/ datum=dd.mm.yyyy username=tg mksh ../../data/WP2dat
