.\" $MirOS: src/lib/libc/crypt/arc4random.3,v 1.15 2010/09/21 19:38:21 tg Exp $
.\" $OpenBSD: arc4random.3,v 1.27 2008/12/23 18:31:02 deraadt Exp $
.\"
.\" Copyright (c) 2010
.\"	Thorsten Glaser <tg@mirbsd.de>
.\" Copyright 1997 Niels Provos <provos@physnet.uni-hamburg.de>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"      This product includes software developed by Niels Provos.
.\" 4. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd $Mdocdate: September 21 2010 $
.Dt ARC4RANDOM 3
.Os
.Sh NAME
.Nm arc4random ,
.Nm arc4random_buf ,
.Nm arc4random_uniform ,
.Nm arc4random_stir ,
.Nm arc4random_addrandom ,
.Nm arc4random_push ,
.Nm arc4random_pushb ,
.Nm arc4random_pushb_fast ,
.Nm arc4random_pushk
.Nd arcfour based stretching random number generator
.Sh SYNOPSIS
.Fd #include <stdlib.h>
.Ft u_int32_t
.Fn arc4random "void"
.Ft void
.Fn arc4random_buf "void *buf" "size_t nbytes"
.Ft u_int32_t
.Fn arc4random_uniform "u_int32_t upper_bound"
.Ft void
.Fn arc4random_stir "void"
.Ft void
.Fn arc4random_addrandom "u_char *dat" "int datlen"
.Ft void
.Pq deprecated
.Fn arc4random_push "int value"
.Ft uint32_t
.Pq deprecated
.Fn arc4random_pushb "const void *buf" "size_t len"
.Ft uint32_t
.Pq deprecated
.Fn arc4random_pushk "const void *buf" "size_t len"
.Ft void
.Fn arc4random_pushb_fast "const void *buf" "size_t len"
.Sh DESCRIPTION
The
.Fn arc4random
function provides a high quality 32-bit pseudo-random
number very quickly.
.Fn arc4random
seeds itself on a regular basis from the kernel strong random number
subsystem described in
.Xr random 4 .
On each call, an ARC4 generator is used to generate a new result.
The
.Fn arc4random
function uses the ARC4 cipher key stream generator,
which uses 8*8 8-bit S-Boxes.
The S-Boxes can be in about (2**1684) states.
Together with the counters, this amounts to about 212 octets of entropy.
.Pp
.Fn arc4random
fits into a middle ground not covered by other subsystems such as
the strong, slow, and resource expensive random
devices described in
.Xr random 4
versus the fast but poor quality interfaces described in
.Xr rand 3 ,
.Xr random 3 ,
and
.Xr drand48 3 .
.Pp
.Fn arc4random_buf
fills the region
.Fa buf
of length
.Fa nbytes
with ARC4-derived random data.
.Pp
.Fn arc4random_uniform
will return a uniformly distributed random number less than
.Fa upper_bound .
.Fn arc4random_uniform
is recommended over constructions like
.Dq Li arc4random() % upper_bound
as it avoids "modulo bias" when the upper bound is not a power of two.
.Pp
The
.Fn arc4random_stir
function collects data from the user-space SRNG and queued for upload,
sends it to the kernel and receives new entropic data using
.Xr sysctl 3
from
.Va kern.arandom
and uses it to permute the S-Boxes.
There is no need to call
.Fn arc4random_stir
before using
.Fn arc4random ,
since
.Fn arc4random
automatically initialises itself.
Explicit calls will, however, trigger kernel pushing after
.Fn arc4random_pushb_fast
has been used to queue some data for doing so.
.Pp
The
.Fn arc4random_pushb_fast
function will queue the data passed for upload on the
next stir using a (non-cryptographic) hash algorithm, which is only
used for collapsing/compressing the data into the queue buffer.
The deprecated
.Fn arc4random_push
function behaves the same, except instead of being passed a buffer
and its size for pushing, it takes a direct numeric argument.
The deprecated
.Fn arc4random_pushk
and
.Fn arc4random_pushb
functions do exactly the same, namely call
.Fn arc4random_pushb_fast
and then call
.Fn arc4random
and return its return value.
.Pp
The
.Fn arc4random_addrandom
function implements an old, discouraged, API with which the S-Boxes
can be permuted directly from user-specified data.
If merely desiring to add entropy to the pool, use
.Nm arc4random_pushb_fast
instead, which is much faster, unless you really want to do a KSA.
.Sh RETURN VALUES
These functions are always successful, and no return value is
reserved to indicate an error.
.Sh SEE ALSO
.Xr rand 3 ,
.Xr rand48 3 ,
.Xr random 3 ,
.Xr random 9
.Sh HISTORY
An algorithm called
.Pa RC4
was designed by RSA Data Security, Inc.
It was considered a trade secret.
Because it was a trade secret, it obviously could not be patented.
A clone of this was posted anonymously to USENET and confirmed to
be equivalent by several sources who had access to the original cipher.
Because of the trade secret situation, RSA Data Security, Inc. could
do nothing about the release of the
.Ql Alleged RC4
algorithm.
Since
.Pa RC4
was trademarked, the cipher is now referred to as
.Pa ARC4 .
.Pp
These functions first appeared in
.Ox 2.1 .
.Fn arc4random_push
first appeared in
.Mx 8 .
.Fn arc4random_pushb
first appeared in
.Mx 10 .
.Fn arc4random_pushk
and
.Fn arc4random_pushb_fast
first appeared in
.Mx 11 .
All these functions were rewritten for
.Mx 11
and macros for every function are now defined for easy existence checks.
