# $MirOS: ports/infrastructure/pkgtools/lib/Makefile,v 1.6.2.1 2009/12/22 22:26:50 bsiegert Exp $
# $OpenBSD: Makefile,v 1.5 2001/04/08 16:45:47 espie Exp $

LIB=		install
SRCS=		cfgfile.c exec.c file.c global.c mem.c pen.c plist.c proc.c \
		pwarnx.c rcdb.c srclist.c str.c
NOPIC=		yes

install:

.include <bsd.lib.mk>
