#!/bin/sh
# $MirOS: src/share/misc/licence.template,v 1.28 2008/11/14 15:33:44 tg Rel $
#-
# Not complicated enough for copyright.

set -ex
debconf-set-selections <<\EOF
man-db man-db/build-database boolean false
man-db man-db/auto-update boolean false
EOF
