#!/bin/bash
# $MirOS: contrib/hosted/tg/deb/hookdir/D00local,v 1.1 2014/09/24 12:02:25 tg Exp $
#-
# Copyright © 2014
#	Thorsten Glaser <tg@mirbsd.org>
#
# Provided that these terms and disclaimer and all copyright notices
# are retained or reproduced in an accompanying document, permission
# is granted to deal in this work without restriction, including un‐
# limited rights to use, publicly perform, distribute, sell, modify,
# merge, give away, or sublicence.
#
# This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
# the utmost extent permitted by applicable law, neither express nor
# implied; without malicious intent or gross negligence. In no event
# may a licensor, author or contributor be held liable for indirect,
# direct, other damage, loss, or other issues arising in any way out
# of dealing in the work, even if advised of the possibility of such
# damage or existence of a defect, except proven that it results out
# of said person’s immediate fault when using the work as intended.

unset LANGUAGE
LC_ALL=C; export LC_ALL

echo >&2 "I: creating Packages file for local APT cache"
rm -f /var/cache/Packages
#XXX TODO: create only MD5Sum here
(cd /var/cache
dpkg-scanpackages -h md5 -m apt/archives >Packages 2>/dev/null || \
    dpkg-scanpackages -m apt/archives >Packages)
paste -d_ <(sed -n '/^Package: /s///p' /var/cache/Packages) \
    <(sed -n '/^Version: /s///p' /var/cache/Packages) \
    <(sed -n '/^Architecture: /s///p' /var/cache/Packages) | \
    sed 's/^/N: /' >&2
echo >&2 "I: updating APT repository information"
cp /var/cache/Packages /var/lib/apt/lists/_var_cache_._Packages
echo 'deb [trusted=yes] file:///var/cache ./' >/etc/apt/sources.list.d/D00local.list
apt-cache gencaches
echo >&2 I: made $(grep -c '^Package: ' /var/cache/Packages) packages available
exit 0
