#!/bin/sh
# $MirOS$
#-
# Not complicated enough for copyright.
#
# Evil hack, to go with D25backports, when necessary.

unset LANGUAGE
LC_ALL=C; export LC_ALL

d=${DIST%/*}
d=${d%-backports*}

apt-get -y install debhelper/$d-backports
