.\" $MirOS$
.\"-
.\" Copyright (c) 2004
.\"	Benny Siegert <bsiegert@gmx.de>
.\"
.\" Licensee is hereby permitted to deal in this work without restric-
.\" tion, including unlimited rights to use, publically perform, modi-
.\" fy, merge, distribute, sell, give away or sublicence, provided the
.\" above copyright notices, these terms and the disclaimer are retai-
.\" ned in all redistributions, or reproduced in accompanying documen-
.\" tation or other materials provided with binary redistributions.
.\"
.\" Licensor hereby provides this work "AS IS" and WITHOUT WARRANTY of
.\" any kind, expressed or implied, to the maximum extent permitted by
.\" applicable law, but with the warranty of being written without ma-
.\" licious intent or gross negligence; in no event shall an author or
.\" contributor be held liable for any direct, indirect or other dama-
.\" ge, however caused, arising in any way out of the usage of covered
.\" work, even if advised of the possibility of such damage.
.\"-
.Dd September 20, 2004
.Dt SVNUP-CVS 1
.Os
.Sh NAME
.Nm svnup-cvs
.Nd update a Subversion repository from a CVS repository
.Sh SYNOPSIS
.Nm svnup-cvs
.Ar repository path
.Sh DESCRIPTION
The
.Nm
utility synchronizes a
.Xr svn 1
repository with a
.Xr cvs 1
one.
You should use this program if the
.Tn CVS
repository is here to stay (for example, some project on which you work
uses CVS), but you yourself want to use Subversion for your daily tasks.
Or you want to manage your own branch of an upstream CVS repository in 
Subversion.
.Pp
The synchronisation is done differently than in other programs of this
kind, notably
.Xr cvs2svn 1
and
.Xr svn_load_dirs 1 .
Not every single CVS revision is kept; instead, every
.Nm
run imports the current revisions in CVS into Subversion and tags the import
with date and time (see below).
Additionally, all the
.Pa CVS/
directories are preserved. 
.Pp
This has the following advantages:
.Bl -dash
.It
You can commit directly to CVS from inside a Subversion working copy.
Other solutions require you fiddling around with 
.Li svn diff
and manual importing of the diff to CVS.
This is tiresome.
.It
You do not always have to keep a
.Dq pristine
CVS working copy you update from.
Instead, you can delete everything under
.Ar path
to save disk space.
.El
.Pp
However, there are also disadvantages:
.Bl -dash
.It
In the commit messages, the files under
.Pa CVS/
generate some noise, especially during updates.
.It
The Subversion repository grows much larger because of the overhead.
.El
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Ar repository
The Subversion repository URL.
For unattended runs, the repository should be readable and writable without
a password (e.g. using a
.Pa file:///
URL or a ssh key).
.It Ar path
The local path which is used during the update.
This can be a directory under
.Pa /tmp ,
but using a persistent directory saves some time, as the Subversion repository
does not have to be checked out each time
.Nm
is run.
This should really be an absolute path.
.El
.Sh EXAMPLES
To update a local
.Dq ports
repository, one could use the following command line:
.Dl $ svnup-cvs file:///svn/ports $HOME/ports
.Sh SEE ALSO
.Xr svn 1 ,
.Xr cvs 1
.Sh AUTHORS
This program was written for MirPorts by
.An Benny Siegert Aq bsiegert@gmx.de .
.Sh BUGS
Error handling (apart from abort-on-error) and parameter validation are
practically non-existent.
