.\" $MirOS: X11/extras/evilwm/evilwm.1,v 1.7 2006/09/24 17:48:31 tg Exp $
.\"-
.\" Copyright (c) 2004, 2005, 2006
.\"	Thorsten "mirabilos" Glaser <tg@mirbsd.de>
.\"
.\" Licensee is hereby permitted to deal in this work without restric-
.\" tion, including unlimited rights to use, publicly perform, modify,
.\" merge, distribute, sell, give away or sublicence, provided all co-
.\" pyright notices above, these terms and the disclaimer are retained
.\" in all redistributions or reproduced in accompanying documentation
.\" or other materials provided with binary redistributions.
.\"
.\" Advertising materials mentioning features or use of this work must
.\" display the following acknowledgement:
.\"	This product includes material provided by Thorsten Glaser.
.\"
.\" Licensor offers the work "AS IS" and WITHOUT WARRANTY of any kind,
.\" express, or implied, to the maximum extent permitted by applicable
.\" law, without malicious intent or gross negligence; in no event may
.\" licensor, an author or contributor be held liable for any indirect
.\" or other damage, or direct damage except proven a consequence of a
.\" direct error of said person and intended use of this work, loss or
.\" other issues arising in any way out of its use, even if advised of
.\" the possibility of such damage or existence of a defect.
.\"-
.TH evilwm 1 "October 16, 2006"
.SH NAME
evilwm \- Minimalist Window Manager for X
.SH SYNOPSIS
.B evilwm \[ \-display
.I display
.B \] \[\ \-term
.I termprog
.B \] \[\ \-fg
.I foreground
.B \] \[\ \-bg
.I background
.B \] \[\ \-bw
.I borderwidth
.B \] \[\ \-snap
.I num
.B \] \[ \-mask1
.I modifiers
.B \] \[ \-mask2
.I modifiers
.B \] \[ \-app
.I name/class
.B \[ \-g
.I geometry
.B \] \[ \-v
.I vdesk
.B \]
.B \]... \[ \-V \]
.SH DESCRIPTION
.B evilwm
is a minimalist window manager based on aewm, extended to feature
many keyboard controls, and otherwise altered to be more friendly.
.PP
In
.BR evilwm ,
the focus follows the mouse pointer, and focus is not lost if
you stray onto the root window.  The current window border is shaded
gold, with other windows left as a dark grey.
.PP
You can use the mouse to manipulate windows either by click/dragging
the 1 pixel border, or by holding down Alt and doing so anywhere in the
client window. The controls are:
.IP "Button 1"
Move window.
.IP "Button 2"
Resize window.
.IP "Button 3"
Lower window.
.PP
Most keyboard controls are used by holding down Control and Alt, then
pressing a key. Available functions are:
.IP Return
Spawn new terminal.
.IP \`
Spawn a new X11R6 terminal in a sane state, not inheriting
the parent environment, resetting most values to defaults.
.IP Escape
Delete current window.
.IP Insert
Lower current window.
.IP "H, J, K, L"
Move window left, down, up or right (16 pixels).
.IP "Y, U, B, N"
Move window to top-left, top-right, bottom-left or
bottom-right of screen.
.IP "Q, W, E, R"
These have the same meaning as \fBHJKL\fR, but resize the window.
The \fBQ\fR and \fBR\fR keys decrease and increase, respectively,
the width of the window, while \fBW\fR and \fBE\fR increase or
decrease the height.
.PP
The amount the window is resized by can be given by the application
and defaults to one (1) pixel.
In addition, no window is ever resized to less than one (1) pixel
width or height by these keys.
.IP I
Show information about current window.
.IP Equals
Maximise current window vertically (toggle).
.IP X
Maximise current window (toggle).
.PP
If compiled with virtual desktop support, these functions are also available:
.IP F
Fix or unfix current window.
.IP "1\ \-\ 8"
Switch virtual desktop.
.IP Left
Previous virtual desktop.
.IP Right
Next virtual desktop.
.PP
In addition to the above, Alt+Tab can be used to cycle through windows
on screen.
.PP
To make
.B evilwm
exit, you have to kill the process.
.SH OPTIONS
.IP "\-display display"
specifies the X display to run on.
.IP "\-term termprog"
specifies an alternative program to run when spawning a new terminal (defaults
to xterm, or x\-terminal\-emulator in Debian).
.IP "\-fg foreground"
frame colour of currently active window.
.IP "\-bg background"
frame colour of inactive windows.
.IP "\-bw borderwidth"
width of window borders in pixels.
.IP "\-snap num"
enable snap-to-border support.  num gives the proximity in pixels to snap to.
.IP "\-mask1 modifiers"
.IP "\-mask2 modifiers"
override the default keyboard modifiers used to grab keys for window manager
functionality.
.I mask1
is used for most keyboard controls (default: control+alt), and
.I mask2
is used for mousebutton controls and cycling windows (default: alt).  Modifiers
may be separated with + signs.  Valid modifiers are shift, lock, control, alt,
mod1, mod2, mod3, mod4, mod5.
.IP "\-app name/class"
match an application by instance name and class (for help in finding these,
use the
.BR xlsclients
tool with the
.I \-l
option).  Subsequent
.I \-g
and
.I \-v
options will apply to this match.
.IP "\-g geometry"
apply a geometry (using a standard X geometry string) to applications matching
the last
.I \-app.
.IP "\-v vdesk"
specify a default virtual desktop for applications matching the last
.I \-app.
Use 0 for vdesk to set window as sticky.
.IP "\-V"
print version number.
.SH BUGS
The author's idea of friendly may differ to that of many other people.
.SH AUTHOR
Ciaran Anscomb <evilwm@6809.org.uk>.

aewm was written by Decklin Foster <fosterd@hartwick.edu>.

9wm was written by David Hogan <dhog@cs.su.oz.au>.

.BR evilwm
was integrated into MirOS #4 by Thorsten "mirabile"
Glaser <tg@66h.42h.de>, who also wrote several extensions and
re-added the "old move behaviour" for MirOS #8.
Starting with MirOS #10, keyboard resizing behaves the
same as keyboard moving, regarding the mouse cursor.

Some of the MirOS additions have been inspired by work
done by Jonathan "ciruz" Schleifer <js@h3c.de>.
.SH "SEE ALSO"
.BR xterm (1),
.BR xlsclients (1)
