# $OpenBSD: Makefile,v 1.2 2004/05/18 21:00:23 naddy Exp $

COMMENT=			Wake On Lan client

DISTNAME=		wol-0.7.1
CATEGORIES=		net

HOMEPAGE=		http://ahh.sourceforge.net/wol/


# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=ahh/}

MODULES=		devel/gettext

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
