# $MirOS: src/sbin/wicontrol/Makefile,v 1.2 2005/03/06 19:50:40 tg Exp $
# $OpenBSD: Makefile,v 1.9 2004/01/29 03:42:49 deraadt Exp $
# From: Makefile,v 1.1 1999/05/05 07:37:06 wpaul Exp $

PROG=	wicontrol
MAN=	wicontrol.8
CFLAGS+=-Wall

.include <bsd.prog.mk>
